### ISSUE TITLE
advertise virtualenv

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1017]
Hi,

`sudo pip install ...` is discouraged, instead the python community advertises the use of the much cleaner virtualenv's because pip is not a full package manager. Read up on http://opensourcehacker.com/2012/09/16/recommended-way-for-sudo-free-installation-of-python-software-with-virtualenv/ and https://packaging.python.org/en/latest/installing/ for this.

FWIW I want the installation to be as simple as possible, virtualenv is an additional command... maybe we can pack that in a script and serve that statically or so...

Any thoughts?

**Comment by miohtama** [comment]
It's good to copy what other well known packages do.

For example, Flask seems to do pretty decent job:

http://flask.pocoo.org/docs/0.10/installation/

**Comment by sils1297** [comment]
Hm, I'd still like to keep it simpler. One command to install it, one
command to execute it. Everything above that is a complexity for the user
we didn't take away. Maybe we could hack some scripts around virtualenv to
make it possible cleanly. Activate the coala env, execute it, clean up.

**Comment by miohtama** [comment]
I suggest sticking out what Python community does. It's  a problem (difficult package installation) Python developers should be solve on Python core development level.

You can make it to one-liner:

      virtualenv venv && source venv/bin/activate && pip install conda

This, unfortunately being UNIX only. 

Also pip comes with `install --target` option to install it to a local folder. Not many are using this - not sure why.

Furthermore `sudo pip` is no no on OSX: http://stackoverflow.com/a/33004920/315168

**Comment by sils1297** [comment]
I was more thinking about a setup.py-like script that makes your one-liner one beautiful command and makes it work platform independent. It can also install a very small binary globally that executes coala within the virtualenv.

I.e. what we want to have is a global availability of the commands while executing  the real code in the virtual env to get rid of the dependency problem. @miohtama IIUC this suits your (and of course also our) desire for a cleaner installation process while it gets us the one-command-install and one-command-execution usability. (And while we're at it, we're probably not the only one looking for something clean *and* usable we could make a nice pip package out of that.)

**Comment by miohtama** [comment]
For the easiest installation option, wrap the application to the system native distribution format like

- deb (Ubuntu) - https://github.com/spotify/dh-virtualenv

- Windows store installer

- OSX DMG

Thus, there is no need to educate the users and the installer plays well with the system files.

**Comment by sils1297** [comment]
I do see your point of my solution not playing well with the system files
by installing a global command which is not installed via the package
manager. According to virtualenv, "The basic problem being addressed is one
of dependencies and versions, and indirectly permissions.", this approach
solves this problem. It also touches the system only at one very tiny
point, the executable wrapper.

Native packaging is a lot of work for both us and the distributions that
can be avoided by using the virtualenv/global command option IMO. (I do get
the feeling that applications rather tend to use virtual environments
nowadays, also for global installations. virtualenv, xdg-app...) It
combines the needs of users and developers while securing the application
in an environment. dh-virtualenv is just another approach to solve this
(but only for debian packages), a very nice thing btw. Native distribution
also comes with the drawback that some users might wait ages for new
releases that work perfectly fine, assuming the developers did their job
well.

2015-11-02 21:20 GMT+01:00 Mikko Ohtamaa <notifications@github.com>:

**Comment by AbdealiJK** [comment]
I think it depends on whether the person is making something in python or now. For example when I'm coding in coala and I need to install a nodejs package - i dont really care if it's globally installed. If I want a ruby package - same thing - i dont really mind it being global. But when I install a python package, i'd prefer local because I need to manage those packages while testing and debugging.

So, I think both should be mentioned. If a person is using virtualenv - he already knows the extra command, and it's fine. So, just putting a section like "Easy install" and "Installing in virtualenv" seems to be appropriate.

**Comment by sudheesh001** [comment]
> FWIW I want the installation to be as simple as possible, virtualenv is an additional command... maybe we can pack that in a script and serve that statically or so...

I think those working with virtualenv directly startoff creating it and then activating it before the setup.py is run. If we have to package it into a script, we need to do something to the `setup.py` file to create something using `subprocess.call()` before the following code segment.

```py
with open('requirements.txt') as requirements:
    required = requirements.read().splitlines()
```

But we don't want to create a virtualenv for the users, so we need to pass a flag/argument to the setup.py to install it for development purpose, `python3 setup.py install --dev` which will do the following
1. Check if the virtualenv is already there ?
- If it's there then just `source envname/bin/activate`
- If not, then create and activate
2. If the argument `--dev` isn't given, then directly run setup.py without creating or activating venv's

I think it's best to just add documentation for installation about using virtualenv's than making the changes to the setup script.
