### ISSUE TITLE
ConfParser does a bad job when parsing empty items

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1032]
```
[TEST]
a = abc, ,def
b = 123,,456
```
read this via `coalib.parsing.ConfParser`:
```python
>>> from coalib.parsing.ConfParser import ConfParser
>>> c = ConfParser()
>>> A = c.parse("file")
>>> list(A["TEST"]["a"])
['abc', 'def']
>>> list(A['TEST']['b'])
['123', '456']
```
We want to keep empty matches :O

**Comment by sils1297** [comment]
I'm looking at this, not sure we really want to change the behaviour. It makes things incredibly simple.

**Comment by sils1297** [comment]
ok we'll probably go for a parameter when iterating over it.
