### ISSUE TITLE
Look at Kythe for Language Independent Code analysis

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1033]
see http://www.kythe.io/

could somebody check that out?

**Comment by Makman2** [comment]
I roughly read the page and I don't understand what they are doing^^ Something about analysis, that they don't want to do, but they support analysis tools in a way that's not revealing for me :/

**Comment by sils1297** [comment]
looked shortly, we should keep them in mind but shouldn't waste actively time on that further, I see no immediate thing we can do here.
