### ISSUE TITLE
-A/-B only show user relevant bears only

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1035]

**Comment by sils1297** [comment]
at the same time at least in `-B` we'll want to reveal configuration options of dependent bears, so probably we only want to restrict display fo `-A`, see also https://github.com/coala-analyzer/coala/issues/623

**Comment by fneu** [comment]
@sils1297 what exactly do you mean with showing only relevant bears?

**Comment by sils1297** [comment]
@fneu if you have a ClangASTBEar and multiple consumers and the user wants the consumers, not the dependent bear, we might want to think about hiding those "internal" bears

**Comment by AbdealiJK** [comment]
How do we define an "internal" bear ?

**Comment by sils1297** [comment]
@AbdealiJK this all is very confusing, let me close this and https://github.com/coala-analyzer/coala/issues/623 and start a new discussion.
