### ISSUE TITLE
annotation bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1040]
a bear that takes the language definition and annotates each line with simple properties like "from here to there is a comment", "from here to there is a string" and so on. This is intended to be used by other bears for simpler analysis functionality

**Comment by AbdealiJK** [comment]
I think we may want a abstracted AST bear ?
Something that just creates ASTs (using pre existing packages) and let's each bear do things with them.

**Comment by sils1297** [comment]
The idea with this one was more simple, a real universal AST isn't really viable so the idea was that we have some light annotations here and provide some graphs and other language independent representation at other places so some algorithms might use different abstractions. Or we could try making an extensible AST later.

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#37
