### ISSUE TITLE
Error while running ClangASTPrintBear

### ISSUE THREAD

**Issue by shiv12095** [coala-analyzer/coala#1061]
```
shiv@shiv-Inspiron-7520:~/coala/coala-tutorial/src$ coala --files=main.c --bears=ClangASTPrintBear -L DEBUG
[WARNING][02:20:32] The requested coafile '/home/shiv/coala/coala-tutorial/src/.coafile' does not exist.
Executing section Default...
[DEBUG][02:20:32] Running bear ClangASTPrintBear...
[DEBUG][02:20:32] |-stdio.h CursorKind.INCLUSION_DIRECTIVE Lines 1-1 (# include < stdio . h > int)
[DEBUG][02:20:32] `-main() CursorKind.FUNCTION_DECL Lines 3-8 (int main ( void ) { // TODO: Let's print something more original here. printf ( "Hello World!\n" ) ; return 0 ; })
[DEBUG][02:20:32]  `- CursorKind.COMPOUND_STMT Lines 3-8 ({ // TODO: Let's print something more original here. printf ( "Hello World!\n" ) ; return 0 ; })
[DEBUG][02:20:32]   |-printf CursorKind.CALL_EXPR Lines 5-5 (printf ( "Hello World!\n" ) ;)
[DEBUG][02:20:32]   ||-printf CursorKind.UNEXPOSED_EXPR Lines 5-5 (printf ()
[DEBUG][02:20:32]   ||`-printf CursorKind.DECL_REF_EXPR Lines 5-5 (printf ()
[DEBUG][02:20:32]   |`- CursorKind.UNEXPOSED_EXPR Lines 5-5 ("Hello World!\n" ))
[DEBUG][02:20:32]   | `- CursorKind.UNEXPOSED_EXPR Lines 5-5 ("Hello World!\n" ))
[DEBUG][02:20:32]   |  `- CursorKind.STRING_LITERAL Lines 5-5 ("Hello World!\n" ))
[DEBUG][02:20:32]   `- CursorKind.RETURN_STMT Lines 7-7 (return 0 ;)
[DEBUG][02:20:32]    `- CursorKind.INTEGER_LITERAL Lines 7-7 (0 ;)
[WARNING][02:20:32] Bear ClangASTPrintBear failed to run. Take a look at debug messages for further information.
[DEBUG][02:20:32] The bear ClangASTPrintBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/coala-0.3.0.dev0-py3.4.egg/coalib/bears/Bear.py", line 75, in execute
    return list(self.run_bear_from_section(args, kwargs))
TypeError: 'NoneType' object is not iterable
```

**Comment by sils1297** [comment]
@shiv12095 if you need the AST in the meantime, clang can print it to you directly, the ClangASTPrintBear was more of a playground for me to try out what I can do with clang when I wrote the code clone detection and has no real advantage or usecase.

**Comment by shiv12095** [comment]
@sils1297 I was just trying to run some sample bears to get a basic idea of coala. There is no real urgency for me to use this. This was just an issue I saw and thought I should get it your notice. 

The following is the link for the main.c file:
https://gist.github.com/shiv12095/951d5140b27f9dca1bf8

**Comment by sils1297** [comment]
@shiv12095 actually I was just looking at this, behind this is an actual issue: the ClangASTPrintBear returns nothing and right now we don't have handling for None (i.e. no return) returned from a bear which is the underlying issue. Thanks for reporting, I missed that in commit 2a41e630 .

**Comment by sils1297** [comment]
@shiv12095 this bug should be solved by https://github.com/coala-analyzer/coala/pull/1062 . Want to test it out? (It's on the `sils/ast` branch) I'll just wait for a review from somebody before I will merge it into master.

**Comment by shiv12095** [comment]
@sils1297 Checked out the code from your branch and tested it. Works fine now

**Comment by sils1297** [comment]
@shiv12095 would you mind taking a look at https://github.com/coala-analyzer/coala/commit/065c62514b5f8a8d58da5b265c572ed994e89d6f ? If you think it is sane, comment it with "ack". The code has already been automatically verified and tested against windows linux and mac.

**Comment by shiv12095** [comment]
ack

**Comment by sils1297** [comment]
@shiv12095 I meant right on the commit, thanks, I'll put it there for you. (We have a bot that sets the commit status which is required for merging.)

**Comment by sils1297** [comment]
solved, merged, auto-released at https://pypi.python.org/pypi/coala/0.3.0.dev20151118081722

Thanks!
