### ISSUE TITLE
Let an Action define a result message

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1065]
Currently every action returns "The action was executed successfully." I think we could improve this a bit if we want finer graded messages, i.e. for applying diffs the message could be "Diff applied successfully."

**Comment by NalinG** [comment]
Hi, I would like to work in this.
And as far as I understand, we just have to change the messages for each action.

**Comment by AbdealiJK** [comment]
@NalinG Currently there is no "message" saved to each action. We'd also need ConsoleInteraction to get the message from the action and print that.
