### ISSUE TITLE
checkstyle bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1067]
java checkstyle

**Comment by rubdos** [comment]
```bash
wget "http://iweb.dl.sourceforge.net/project/checkstyle/checkstyle/6.15/checkstyle-6.15-all.jar"
wget "https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml"
java -jar checkstyle-6.15-all.jar -c google_checks.xml ClassName.java
```

**Comment by sils1297** [comment]
@rubdos thanks. While thinking about it there's one unsolved issue still - we need to install checkstyle somehow because we don't want the execution to be dependent on where the user runs coala, right?

**Comment by sils1297** [comment]
I think I'll be using something like http://regex-explain.googlecode.com/hg/explain.html#\[%28%3FP%3Cseverity%3EWARN|INFO%29\]\s*%28%3FP%3Cfile_name%3E.+%29%3A%28%3FP%3Cline%3E\d+%29%28%3A%28%3FP%3Ccol%3E\d+%29%29%3F%3A\s*%28%3FP%3Cmessage%3E.*%29 for checkstyle

**Comment by rubdos** [comment]
@sils1297 You probably want to have the user/coala put it in some standard location or something.

**Comment by rubdos** [comment]
I found: https://oss.sonatype.org/content/repositories/snapshots/com/puppycrawl/tools/checkstyle/
which is their official maven snapshot repo
and http://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/
which is their release repo.

Looks like file are persistent there, so this could be something.
