### ISSUE TITLE
mdast/alex integration

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1078]
https://github.com/sindresorhus/SublimeLinter-contrib-alex/blob/master/linter.py

regex will also work for mdast lint

**Comment by wooorm** [comment]
:+1:

**Comment by sils1297** [comment]
This is blocked by https://github.com/wooorm/alex/issues/61 though.

**Comment by sils1297** [comment]
helpful code: https://github.com/sindresorhus/SublimeLinter-contrib-alex/blob/master/linter.py

**Comment by sils1297** [comment]
@wooorm how do I install alex on windows? https://ci.appveyor.com/project/sils1297/coala/build/1.0.2091/job/6v0ejnkfpoahevqe the  `npm install --global alex` doesn't seem to work, see build log.

**Comment by sils1297** [comment]
@wooorm The most difficult thing seems to be installing alex on our CI, can you take a look? AppVeyor is the windows CI, CircleCI is Linux and Travis does Mac.

**Comment by wooorm** [comment]
Hmm, no experience with Windows and node/npm, other than that it *should* work (I’ve heard of people using alex on Windows). Also, the logs don’t show any failures so I couldn’t detect any hints for what might be going wrong.

Maybe it’s a possibility to not instal alex globally, but rather locally?! `npm install alex` would install the alex executable to `node_modules/.bin/alex`.

**Comment by sils1297** [comment]
Our CI systems run on Ubuntu which should have the old node version. I guess upgrading this via custom PPA will solve that.

**Comment by wooorm** [comment]
I’m guessing people using node themselves would upgrade from those low Node version ranges to higher versions (alex is definitely *not* the only module which breaks in 0.10). This of course leaves out people who don’t use Node themselves, but I’m hoping it be marginal :anguished:

**Comment by sils1297** [comment]
We probably want to install alex and mdast on setup time into a local directory and our bear can just use that.

**Comment by sils1297** [comment]
covered in https://github.com/coala-analyzer/coala/issues/897
