### ISSUE TITLE
Use PEP8 conform line lengths

### ISSUE THREAD

**Issue by fneu** [coala-analyzer/coala#1082]
Our docs allow 79 chars excluding newline,

default setting max_line_length is set to 80

running `coala -S PythonCheck.max_line_length=79` gives various errors with 

> |    |    | Line is longer than allowed. (81 > 79)

default gives no errors, so there is also a bug in LineLengthBear showing 81.

ALSO: PEP8 mentions constraining comments and docstrings to to 72 chars, what about that?

**Comment by sils1297** [comment]
> ALSO: PEP8 mentions constraining comments and docstrings to to 72 chars, what about that?

We ignore that for the LineLengthBear at least for now. KISS.

**Comment by fneu** [comment]
@sils1297 still, we wanna go to 79 or keep 80?

**Comment by sils1297** [comment]
@fneu I'd go for 79 plus `\n`, that belongs to the line IMO. We should clarify that in the docs.

**Comment by fneu** [comment]
@sils1297  it's fine in the docs

> Every line of code may hold only up to 79 characters (excluding the newline character \n).

**Comment by sils1297** [comment]
I mean in the documentation comment of the LineLengthBear

**Comment by Makman2** [comment]
In fact we are PEP conform, we keep below 80 chars per line :)
(except for docstrings :P)

**Comment by fneu** [comment]
@sils1297 @Makman2 no, PEP allows 79+1 chars per line and we are not consistently following that. 

see ConsoleInteraction.py line 440:

> def show_enumeration(console_printer, title, items, indentation, no_items_text):

those are 80 +1 chars (80 visible and a new line), which is neither allowed according to PEP8 nor our code style document. I know it's nitpicking, but since Lass helpfully assigned me to it I am fixing it atm.

**Comment by sils1297** [comment]
:D you reported it and helpfully assigned me so I thought I'd return the favour :)

**Comment by fneu** [comment]
@sils1297 tbh. I mostly just wanted you to notice it ;)

**Comment by sils1297** [comment]
@fneu in those cases you usually want to @ people, right?

**Comment by fneu** [comment]
@sils1297 yeah but mentioning you in the initial message would somehow looked improper in front of the others... I could have added a comment but by now I'm pretty used to assigning stuff to you...
