### ISSUE TITLE
Protect file-contents from bear-writers

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1084]
It could accidentally happen that you modify the passed content (especially if you get split-up lines which is a list-instance). Only patch-results should be allowed to write contents of files.

How to solve this problem?
Use a proxy object for the bear-writer, so file contents are read-only.

**Comment by sils1297** [comment]
> Only patch-results should be allowed to write contents of files.

Actually not even that. coala has the file_dict internally and gives proxy objects to the bears. They *never* modify the file. They only provide `Diff` objects. At a later stage the Result Actions can modify the actual file diff, there's no need for a non-read-only proxy for bears.

**Comment by sils1297** [comment]
We should also take binary data (see https://github.com/coala-analyzer/coala/issues/495 ) for this one into consideration.
