### ISSUE TITLE
CorrectionBasedBear: Needs refactor

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1091]
1. The name is imo to general and means in coala's context nearly nothing (the bear is correction based, yeah, nearly everything is correction based in coala...).
2. Using public variables to set external tool and its settings: Even you can modify everything in python, it's still not good since it suggests a "public" variable and encourages changing this value during runtime. Imo better would be an overridable read-only property.
3. Maybe more...

**Comment by sils1297** [comment]
we have https://github.com/coala-analyzer/coala/issues/1115 instead
