### ISSUE TITLE
Tests executing infinite loop still consume CPU after CTRL+C

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1096]
The `multiprocessing.Process` executing the unittest keeps alive. I registered that my fan didn't stop cooling the CPU even after canceling the process. And indeed inside the system monitor the python3 application was still running.

Workstation: Fedora 22, Intel i7 3GHz quad-core CPU

Can somebody confirm this?

**Comment by Makman2** [comment]
On branch https://github.com/coala-analyzer/coala/tree/Makman2/infinite-loop-consumer
just execute
`./run_tests.py -t DocumentationExtractionTest`
cancel it via CTRL+C and look into the system monitor whether the test process is still alive (or listen to your cooler :D)

**Comment by sils1297** [comment]
![we_dont_want_this_fixed](https://imgs.xkcd.com/comics/workflow.png)

**Comment by sils1297** [comment]
@Makman2 seriously, could we maybe just close this? I'm against having bugs filed against WIP states of people, bugs are serious, while your stuff isn't merged you probably have a lot of bugs and this is not the right place to track them.

**Comment by sils1297** [comment]
@Makman2 yes, I can reproduce that on your branch on linux. You should take a close look at that :)

**Comment by sils1297** [comment]
@Makman2 this was only for your WIP branch, right? So closing this as an invalid bug.

**Comment by Makman2** [comment]
We use pytest anyway soon^^ maybe it addresses this issue

**Comment by sils1297** [comment]
@Makman2 does that branch exist still anyway?

**Comment by Makman2** [comment]
@sils1297 yes
