### ISSUE TITLE
tern javascript analysis

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1102]
http://ternjs.net/

@Makman2 this sounds easy and would be *very* attractive, time to look at that?

**Comment by Makman2** [comment]
@sils1297 since it's easy and the linter bear is imo more important since it simplifies external tool usage, keep this open, maybe a newcomer takes this one up :)

**Comment by sils1297** [comment]
covered in https://github.com/coala-analyzer/coala/issues/897
