### ISSUE TITLE
Bears seem to be running multiple times

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1108]
I'm not sure if this is expected or not.
When I run coala on a single file, and show the DEBUG log_level, It says
```
[DEBUG][14:18:34] Running bear PyLintBear...
[DEBUG][14:18:34] Running bear PyLintBear...
```

Why is it running the bear twice ? I gave a print statement in the bear and the bear seems to be running the print statement twice.
```
[DEBUG][14:21:24] Running bear PyLintBear...
[WARNING][14:21:24] a statement
[DEBUG][14:21:24] Running bear PyLintBear...
[WARNING][14:21:24] a statement
```

**Comment by sils1297** [comment]
Hey, print out the filename?

**Comment by AbdealiJK** [comment]
AH. sorry. There was a hidden file which I did not notice in the directory.
Nevermind.
