### ISSUE TITLE
Lazy diff creation

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1110]
I'm wondering if this is feasible - I'd rather that bears don't create diffs when making the result.
This is kind of unusual because the user may not want the diff to be created. Only when he chooses the action to fix itself, should the diff be requested from the bear and that's when the bear should create it.

It would make processing faster.

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/issues/1021 covers lazy diff generation if bears want to use it as such, I think this is a healthy wontfix
