### ISSUE TITLE
Make LocalBearTestHelper robust

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1111]
Currently, `LocalBearTestHelper` simply checks if there are results that are yielded or not.
Would be considerably better is we give it a list of line, cols where the result should yield in a given file.

**Comment by sils1297** [comment]
@AbdealiJK I think we should support both, it's nice to have those simple tests sometimes IMO

**Comment by AbdealiJK** [comment]
Yes, i meant it as an optional thing

**Comment by sils1297** [comment]
The helper should also create the actual files so it can be used well with linters that use file input.

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#36
