### ISSUE TITLE
Merge CorrectionBasedBear into Lint

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1115]
@AbdealiJK I think that would be good. CorrectionBasedBear also has some logging features.

**Comment by sils1297** [comment]
Maybe we can make a function `get_output(cmd_array, stdin: str=None)` which get's us `stdout, stderr` as strings for the command with the args and optionally the std input

**Comment by sils1297** [comment]
@Arcanemagus hey, we're trying to create some generic linter abstraction here just like you did. We already have a `Lint` class which parses lint outputs based on regexes or JSON as well as the weirdly named `CorrectionBasedBear` class which passes a file via stdin and expects a new file via stdout, then creates issues based on Diff hunks. So we want to merge those, ideally uniting all advantages:

1. Both are pretty simple to use of course.
2. `CorrectionBasedBear` works with in memory file contents which is good because it works well if we write plugins for e.g. Atom and Builder that might even check unsaved files. `Lint` does not though it can use temporary files in the future if needed.

There is also the problem that coala provides the user with the ability to use one config for all linters so for some linters we need to generate config files as temporary files or so. The new class should ideally do that too.

@Arcanemagus I'm CCing you in the hope that you have a few hints on how we can properly design such a thing. (Hope it got clear what we want.)

**Comment by Arcanemagus** [comment]
@steelbrain is actually the one that has done most of the work on the base Linter package, I've been doing what I can to maintain the `linter-*` plugins.

**Comment by Arcanemagus** [comment]
Essentially how the `linter` + `linter-*` setup works is that the `linter-*` plugins act as intermediaries between the linter programs (pyflakes`, `eslint`, ...) and `linter`, handling all aspects of running the program and parsing its output into a standard format that `linter` deals exclusively in. It sounds like most of the aspects of the `linter-*` plugins are handled within your `Lint` class, it _sounds_ like getting this functionality merged together will be as "simple" (ha!) as extending `Lint` to handle the `stdin`/`stdout` interaction model.

**Comment by AbdealiJK** [comment]
@sils1297 Ive pushed a prototype
