### ISSUE TITLE
results: show file path related to coafile

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1124]
I think in the output we should show the file path relative to the coafile, i.e. relative to the project root. *Maybe* provide an option to show full paths.

At least gitmate would like this...

**Comment by sils1297** [comment]
@keerthisuresh you're currently working on something related to this issue. (https://github.com/coala-analyzer/coala/pull/1154) so you already know what this is about roughly, are you interested in looking into this after getting your current PRs merged?

**Comment by keerthisuresh** [comment]
sure !

**Comment by sils1297** [comment]
@keerthisuresh hey given that I haven't heard from you for some time I'm unassigning you for the time being. Feel free to reassign if you still want to do that.

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/1154 shows @keerthisuresh attempt
