### ISSUE TITLE
pypy3 support

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#113]
Currently some tests fail when running them with pypy3. (Note that in order to test this you need to adjust the python call in the TestHelper so it calls pypy3 instead of python3.)

Though pypy3 is a valid python implementation we should support it.

**Comment by sils1297** [comment]
if we're droppiong support for python 3.2 (#434) we can't currently support pypy3.

**Comment by AbdealiJK** [comment]
It seems as though the only 2 issues with pypy3 are dbus and clang.

clang  - has errors with ctypes ... I am unsure how those things work

I was unable to compile and install dbus using pypy's compiler - ubuntu doesnt have pypy3 in apt-get and so, I dont have the python headers to use to compile it.

Can we skip these two in pypy ?

**Comment by sils1297** [comment]
For starters it would be cool to be able to announce pypy support. Even if
we skip two things.

2015-06-27 13:19 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
@AbdealiJK maybe we want to use the 4th build on circle for pypy which is more important than test skipping IMO. I'm thinking about contacting circleci if they want to "sponsor" us more containers... it's almost no cost for them.

**Comment by AbdealiJK** [comment]
Blocked by https://github.com/coala-analyzer/coala/issues/708
as Clang's bindings do not work with `pypy`

**Comment by AbdealiJK** [comment]
Although coverage isn't going on in pypy3, pypy3 has been supported.
So, closing this.
