### ISSUE TITLE
JSONFormatBear: Parse exception message

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1130]
Would be a nice feature to show line and column automatically, instead of having it in the message:

`This file does not contain parsable JSON. 'Expecting property name enclosed in double quotes: line 2 column 7 (char 8)'`

**Comment by SanketDG** [comment]
What is the intended behaviour for this?

**Comment by Makman2** [comment]
@SanketDG I think @sils1297 means parsing the message to extract the position where the JSON style error occurred. So you get a result with position values and the message would just be `Expecting property name enclosed in double quotes`. @sils1297 Did I understand that right?

**Comment by sils1297** [comment]
Yes. To express it more complicated but IMO exact, the exception contains
that info in the message as text, we want it as result metadata.

**Comment by sils1297** [comment]
@jjsg hey, need help?

**Comment by sils1297** [comment]
Until further notice I'm assuming you're not interested anymore, simply ping me otherwise.

**Comment by jjsg** [comment]
@sils1297 hey i m little slow, but working on it

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#35
