### ISSUE TITLE
File in SourcePosition should use `abspath`

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1132]
The file in SourcePosition currently doesnt getnormalized using abspath - this is bad because when comparison wouldnt work beterrn two SourceRanges because the path given may not be the same (although the files are same)

Eg:
paths like `/a/b/c` and `/a/d/../b/c` are the same but SourceRange doesn't think they are the same

**Comment by keerthisuresh** [comment]
I'm working on this , could someone assign it to me ?

**Comment by sils1297** [comment]
@keerthisuresh please accept the invitation to our org so I can assign you, thanks for your support! :)

**Comment by SanketDG** [comment]
I opened #1247 to fix this.
