### ISSUE TITLE
DocumentationFormatBear

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1140]
The documentation extraction routines are ready now, what needs to be done next:
1. documentation parsing machinery:
   This should work with regexes or similar. Also this shall be configured for each language inside a coafile!
2. documentation reassembling:
   Shouldn't be problematic using the current `DocumentationComment` class. Just a nice function like `assemble_documentation_comment`/similar.
3. The actual `DocumentationFormatBear`
   - extract documentation from given source code
   - parse it
   - check it against the user defined style/regex
   - for patching: reassemble the wanted documentation comment

See #919.

**Comment by sils1297** [comment]
actually it would be nice to do things like add/remove periods after the end of a parameter description or capitalize/uncapicalize the first char of a description. This way we can get rid of https://github.com/coala-analyzer/coala/issues/173 in the same run.

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#34
