### ISSUE TITLE
cpplint integration

### ISSUE THREAD

**Issue by theandrewdavis** [coala-analyzer/coala#1144]
Hi, I'm maintaining the fork of the Google C++ style guide checker cpplint that's on pypi. @sils1297 got in touch with the former maintainer asking for some help with coala integration ([issue here](https://github.com/tkruse/cpplint/issues/3)). Just wanted to drop a note that if y'all are still looking to pursue it, I'm happy to help.

Cheers!

**Comment by sils1297** [comment]
Hi @theandrewdavis , thanks for getting in touch! This is definitely interesting for us. Would you mind joining https://gitter.im/coala-analyzer/coala for a chat?

**Comment by sils1297** [comment]
@AbdealiJK have you started working on cpplint yet? You want to check up on this or shall I?

I can think about making a collection of bears, each of which holds a routine from cpplint, I.E. a really deep integration, so cpplint can drop the whole issue suppressing, CLI and so on making maintenance easier for them. That is assuming they're interested in that. For that we'd ideally solve #1047 so it can continue to live in an own repository.

Otherwise we can do the usual 5-minute-wrapper.

**Comment by AbdealiJK** [comment]
I've not really worked on cpplint (I've not checked out the linter either)

My opinion: I'd rather that cpplint give something in the form of a json like
```
"file1": [
    {"line": int,
     "column": int,
     "message": str,
     "severity": int or str,
     "diff": A jsonified diff class ? or the Diff file as a string (if applicable)
    },
    { <another result> },
    ...
]
```
And we make linter class read that and make auto correct Diffs for each result.

I think you should do it if you're free - I'm looking at `autopep8` and will continue that for the time being.

**Comment by theandrewdavis** [comment]
@AbdealiJK cpplint has a couple of ways it can output errors already, so it wouldn't be a big deal to add a json output if that's what y'all are looking for. I'm imagining the output being:

```
{
    "failures": {
        "path/to/main.cpp": [
            {"line": 0, "message": "No copyright message found"},
            {"line": 15, "message": "Tab found; better to use spaces"},
        ]
    }
}
```

cpplint doesn't track column information or a diff (not sure what that's referring to), though.

If that's what you're looking for, I'd be happy to add it, just let me know.

**Comment by sils1297** [comment]
@AbdealiJK I don't see any meaning in making them add more outputs to CPP lint, we can easily take whatever they have and from that *we* can provide JSON and so on so they don't need to care.

@theandrewdavis coala allows you to provide a diff so you can get issues fixed automatically. We're trying to get as many fixes as possible so we usually prefer integrating linters that also can fix stuff, e.g. we have Clang.

**Comment by theandrewdavis** [comment]
Gotcha. As it stands now you can run cpplint with --output=junit to get output like this:

```
$ cat main.c
int main() {
	return 1;
}
$ cpplint --output=junit main.c
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite name="cpplint" errors="0" failures="2" tests="2"><testcase name="main.c"><failure>0: No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"
2: Tab found; better to use spaces</failure></testcase></testsuite>
```
Which has all the same information. It's formatted in a way that Jenkins/Bamboo will accept, but it should be parseable by coala as well.

**Comment by sils1297** [comment]
As far as I understand we could also use the default output:

```
lasse@localhost ~/prog % cpplint gitmate-test/test.cpp
gitmate-test/test.cpp:0:  No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
gitmate-test/test.cpp:5:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
gitmate-test/test.cpp:6:  public: should be indented +1 space inside class Obj  [whitespace/indent] [3]
gitmate-test/test.cpp:13:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
gitmate-test/test.cpp:19:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
gitmate-test/test.cpp:19:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
Done processing gitmate-test/test.cpp
Total errors found: 6
```

That'd be very simple output which we can capture with a regex, where we even get more information like the name of the rule and apparently an ID which can be used to disable/enable them. Is there any advantage in the XML output? The default one seems to hold more information.

**Comment by sils1297** [comment]
Oh wait, cpplint is even python, right? So couldn't we import a method from CPPLint, give that one our file content and a config kind of thing, it gets us results as python objects already?

**Comment by sils1297** [comment]
Alright, I brewed together a five-minute thing, works well:

```
lasse@localhost ~/prog % cat main.c
int main() {
    return 0;
}
lasse@localhost ~/prog % coala-json -b CPPLintBear -f main.c
{
  "results": {
    "default": [
      {
        "affected_code": [
          {
            "end": {
              "column": null,
              "file": "/home/lasse/prog/main.c",
              "line": 0
            },
            "file": "/home/lasse/prog/main.c",
            "start": {
              "column": null,
              "file": "/home/lasse/prog/main.c",
              "line": 0
            }
          }
        ],
        "debug_msg": "",
        "diffs": null,
        "id": 146200610722874749131866838596930617275,
        "message": " No copyright message found.  You should have a line: \"Copyright [year] <Copyright Owner>\"  [legal/copyright] [5]",
        "origin": "CPPLintBear",
        "severity": 1
      }
    ]
  }
}
```

(I stripped away log messages.)

**Comment by AbdealiJK** [comment]
That looks good :)
I suggested json because I thought cpplint had fixits and diffs are not easy to parse in regex. As it does not, using simple regex is good.

Also, a design opinion:
I personally think that if regex/json is fine, we shouldn't import linters as a module - because its easier and uniform to use the same method for linters written in python or other languages. If importing gives us some extra abilities, only then it should be done.

-----Original Message-----

**Comment by sils1297** [comment]
Ah, @theandrewdavis the numbers in square brackets are like a severity, right? We can map that into coala too. I guess `5` is something like `informative` while `0` then is a major issue?

**Comment by theandrewdavis** [comment]
That number is actually "confidence" since cpplint sometimes has false positives. Here's a comment from the source about it:

```
confidence: A number from 1-5 representing a confidence score for
      the error, with 5 meaning that we are certain of the problem,
      and 1 meaning that it could be a legitimate construct.
```

**Comment by sils1297** [comment]
@theandrewdavis ah, I think you may want to update your description for the `verbose` parameter and maybe rename it to `confidence`, after all it's the same, right?

coala currently actually has no confidence right now so we'll keep this value in the message, when we solve https://github.com/coala-analyzer/coala/issues/1145 , we can add that value to coala's result so coala can filter results by confidence.

I'll now write a test for the bear and add configuration options, then it should be ready to go with coala initially:

```
lasse@localhost ~/prog % coala-format -b CPPLintBear -f gitmate-test/test.cpp -S format_str={file},{line},{message} cpplint_ignore=whitespace
/home/lasse/prog/gitmate-test/test.cpp,0, No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
1 lasse@localhost ~/prog % coala-format -b CPPLintBear -f gitmate-test/test.cpp -S format_str={file},{line},{message}                              :(
/home/lasse/prog/gitmate-test/test.cpp,0, No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
/home/lasse/prog/gitmate-test/test.cpp,5, { should almost always be at the end of the previous line  [whitespace/braces] [4]
/home/lasse/prog/gitmate-test/test.cpp,6, public: should be indented +1 space inside class Obj  [whitespace/indent] [3]
/home/lasse/prog/gitmate-test/test.cpp,13, { should almost always be at the end of the previous line  [whitespace/braces] [4]
/home/lasse/prog/gitmate-test/test.cpp,19, Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
/home/lasse/prog/gitmate-test/test.cpp,19, { should almost always be at the end of the previous line  [whitespace/braces] [4]
1 lasse@localhost ~/prog %
```

**Comment by theandrewdavis** [comment]
@sils1297 Thanks, good point

**Comment by sils1297** [comment]
@theandrewdavis CPPLint is rather small, what would you think about moving your routines into coala as bears? This would effectively allow you to get rid of the whole user interaction, issue suppression, that's what coala is for, and some things like the copyright check could easily be reused for other languages too.

One way or another, would you mind taking a look at https://github.com/coala-analyzer/coala/commit/15f8883706676a7521a8ccee4ef277502d13536b ? Start your comment with `ack` if you think it's good (`unack` otherwise), then our CI review enforcement system will pick it up accordingly.

**Comment by sils1297** [comment]
FWIW we're looking into building an indentation algorithm that can detect and fix wrong indentation language independently, i.e. you only have to register a few keywords and stuff like that for a new language, see https://github.com/coala-analyzer/coala/issues/225 .

**Comment by theandrewdavis** [comment]
@sils1297 cpplint is open source (Google just requires you include their license in the distribution) so it's checks can definitely be integrated into coala. cpplint itself is a pretty old google tool that I had no hand in writing, so I wouldn't want to do anything to change its direction drastically. But I think it would be awesome to add its checks into coala -- sounds like a great idea. I'll be happy to work on this as time permits.

**Comment by sils1297** [comment]
@theandrewdavis very cool! Would you mind taking a look at #225 , would love to hear your opinion. This'll auto-close when we merge our wrapper.
