### ISSUE TITLE
Add result confidence

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1145]
We probably want the result to have a confidence field and the ability to only show results with a confidence of x or higher.

**Comment by sils1297** [comment]
We probably also want to add a "rule" field so bears can yield subresults with rules and ignores can be set appropriately. Instead of setting origin to `SomeBear (W205)` originwould be SomeBear and the `rule` "W205"

**Comment by AbdealiJK** [comment]
Note: In CSecurityBear we are adding `exclude_likely_false_positives` which should ideally be removed when this is implemented.
Reference: https://github.com/coala-analyzer/coala-bears/pull/434/commits/f87c6808a1d248144bb66a9ba8f554395f18b4d8#diff-5ae4bb763553c1c0ecf08cf8075a9c9aR27

**Comment by Makman2** [comment]
Did you include logic to set some kind of confidence limit for results shown?

**Comment by sils1297** [comment]
not yet, this simply adds the possibility of setting it in the API, not
user facing ATM except JSON etc.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Makman2** [comment]
then this issue is not really closed, is it?

**Comment by Makman2** [comment]
or we just create a new issue^^

**Comment by sils1297** [comment]
Can you create a new please?

**Comment by palash25** [comment]
Should be closed as it is a duplicate of #2455

**Comment by Makman2** [comment]
It is already closed :)
