### ISSUE TITLE
coala Platypus

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1176]
This is the issue from where we'll do the Platypus release :) (I think rultor uses the issue title for the release so I figured rather creating an own one was good.)

**Comment by Makman2** [comment]
@rultor release 0.3.1

**Comment by Makman2** [comment]
@rultor release, tag=`0.3.1`

**Comment by Makman2** [comment]
hello @rultor

**Comment by Makman2** [comment]
@rultor release, tag=0.3.1

**Comment by sils1297** [comment]
@rultor stop

**Comment by sils1297** [comment]
@rultor hello

**Comment by sils1297** [comment]
@rultor stop

**Comment by sils1297** [comment]
release done, after some difficulties...
