### ISSUE TITLE
SpaceConsistencyBear shows "Trailing Whitespace" when newline is missing

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1185]

**Comment by sils1297** [comment]
Steps to reproduce:

Write a file e.g. with pycharm (some editors like gedit, vim won't work since they don't do such stupid stuff) and put no empty line at the end of the file but some content. Then run coala with SpaceConsistencyBear over it and it'll show that there's a missing newline before EOF but it'll also show that there's trailing whitespace which is wrong.

**Comment by kaushikmit** [comment]
I will take this issue..Can you assign this to me?

**Comment by sils1297** [comment]
You have been assigned

**Comment by kaushikmit** [comment]
I don't get why `if replacement != pre_replacement` is true for a line with no trailing spaces and no new line at EOF in SpaceConsistencyBear.py .Is there any other internal modification , that I should make to solve this issue ?

**Comment by Makman2** [comment]
@kaushikmit which line do you mean? This statement appears 3 times in the `SpaceConsistentyBear`^^

**Comment by sils1297** [comment]
@kaushikmit you could try putting a few print statements in there outputting the contents to see what's wrong there.

**Comment by kaushikmit** [comment]
@sils1297 This is the modification I made in SpaceConsistencyBear.py : 
```
if not allow_trailing_whitespace:
    pre_replacement = line + "\n"
    replacement = replacement.rstrip(" \t\n") + "\n"
    if replacement != pre_replacement:
        result_texts.append("Trailing whitespaces.")
        result_texts.append(line)
```

I'm just adding a newline character to pre_replacement , just to fail the if condition for a line which is in the EOF and doesn't contain whitespaces in it.But this is failing some unit tests.Not able to figure out why !

**Comment by sils1297** [comment]
@kaushikmit hi, if you want assistance, please put your test output into some paste service and post a link, also you should push your code to a branch and link to it so we can reproduce it. It's hard to help you with that little information :)

**Comment by kaushikmit** [comment]
This is the error log : http://pastebin.com/EDdQRiN0

Have pushed the changes to my branch:
https://github.com/kaushikmit/coala/blob/mybranch/bears/general/SpaceConsistencyBear.py

**Comment by sils1297** [comment]
why don't you `print(repr(line))` here and there to see what's wrong? Have you already figured out which testcases fail? Apparently it fails in SpaceConsistencyBearTest.py, lines 30 and 40. Should be straightforward to get some debug info from that?

P.S.: The `AssertionError: 1 != 0 : coala-ci must return zero when running over its own code.` is simple to solve, please run `coala` in the coala root directory and it'll show you what you have to fix :) coala checks itself in that test.

**Comment by kaushikmit** [comment]
Sure..will do !

**Comment by kaushikmit** [comment]
The below test fails : 
`self.assertLineValid(self.uut, "    t")` 
Not able to figure out why it does fail .I can actually see why the error "Trailing whitespaces" comes for a line with no new line at EOF and no trailing whitespaces.This is because pre_replacement is the same as replacement in all cases (one with whitespaces and the one without ) .So I added a sentinel character('\n') to the pre_replacement to make it work.

```
if not allow_trailing_whitespace:
                pre_replacement = line + "\n"
                replacement = replacement.rstrip(" \t\n") + "\n"
                if replacement != pre_replacement:
                    result_texts.append("Trailing whitespaces.")
                    result_texts.append(line)
```

**Comment by sils1297** [comment]
@kaushikmit you can't simply add a `\n` to the string because there might already be one. The error in this implementation is that we do `pre_replacement = line` while line might not have a `\n` right? So if we strip all whitespace from `replacement` and add `\n` at the last line it might show the trailing whitespace error because `pre_replacement` has no `\n` but `replacement` has.

Since you alter the `replacement` you could simply do `pre_replacement = line.rstrip("\n") + '\n'` to unify the strings, as an example. Other fixes are also possible but this may be the easiest one.

Understand it?

**Comment by sils1297** [comment]
@kaushikmit probably it's even better to do `pre_replacement = line.rstrip('\n'); replacement = line.rstrip(' \t\n')`, there's no need to reappend the `\n` both times

**Comment by sils1297** [comment]
and while we're at it you could simply replace `pre_replacement` in the condition by the `line.rstrip('\n')` expression and remove the `pre_replacement` assignment, saves a line and the complexity of that variable there.

**Comment by kaushikmit** [comment]
Tried it too.The same error mentioned in the error log occurs.This test fails even now : 
`self.assertLineValid(self.uut, " t") `

**Comment by sils1297** [comment]
Works for me:

```
lasse@lssteady ~/prog/coala (git)-[master] % ./run_tests.py -t SpaceConsistencyBearTest
 1/1 | SpaceConsistencyBearTest

Tests finished: failures in 0 of 1 test modules.
lasse@lssteady ~/prog/coala (git)-[master] % git diff
diff --git a/bears/general/SpaceConsistencyBear.py b/bears/general/SpaceConsistencyBear.py
index 4e7840f..c4930ad 100644
--- a/bears/general/SpaceConsistencyBear.py
+++ b/bears/general/SpaceConsistencyBear.py
@@ -41,9 +41,8 @@ class SpaceConsistencyBear(LocalBear):
                     result_texts.append("No newline at EOF.")
 
             if not allow_trailing_whitespace:
-                pre_replacement = line
-                replacement = replacement.rstrip(" \t\n") + "\n"
-                if replacement != pre_replacement:
+                replacement = replacement.rstrip(" \t\n")
+                if replacement != line.rstrip("\n"):
                     result_texts.append("Trailing whitespaces.")
 
             if use_spaces:
```

**Comment by sils1297** [comment]
This'll be a better fix though, because `\n` will be treated correctly, otherwise it'll remove the `\n` when the patch removing the whitespace is applied...:

```diff
diff --git a/bears/general/SpaceConsistencyBear.py b/bears/general/SpaceConsistencyBear.py
index 4e7840f..a8a5f19 100644
--- a/bears/general/SpaceConsistencyBear.py
+++ b/bears/general/SpaceConsistencyBear.py
@@ -41,9 +41,8 @@ class SpaceConsistencyBear(LocalBear):
                     result_texts.append("No newline at EOF.")
 
             if not allow_trailing_whitespace:
-                pre_replacement = line
                 replacement = replacement.rstrip(" \t\n") + "\n"
-                if replacement != pre_replacement:
+                if replacement != line.rstrip("\n") + "\n":
                     result_texts.append("Trailing whitespaces.")
 
             if use_spaces:
```

**Comment by kaushikmit** [comment]
Yeah...this seems to be a better fix !
