### ISSUE TITLE
Add option to deactivate creation of .orig backup files

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1186]
This happens when applying a patch. Also IMO we shouldn't override the orig files if they're already present, renders them quite useless if multiple patches are applied to the same file...

**Comment by sils1297** [comment]
this would have to be done in the ApplyPatchAction

**Comment by abhsag24** [comment]
decisions:
1> Defualt for coala would be, to create orig files, so that any unintended changes made by coala can easily be got back.
2> if orig files already exist then we shouldn't override them
