### ISSUE TITLE
Refactor _yield_if_right_kind into a condition

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1190]
That is practically a condition @fneu was there any reason why you *looped* over that thing?

**Comment by fneu** [comment]
I guess this was subtly different at one point - not necessary anymore :stuck_out_tongue:

**Comment by sils1297** [comment]
Task here is to take the `_yield_if_right_kind` function in `Collectors.py` and refactor it into a condition like `_right_kind`. This way we don't need a `for` loop and can use a simple condition at invocation side.
