### ISSUE TITLE
Also save configuration after running all sections

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1196]
When actions are executed some ask for parameters, those may get stored too.

That should be an easy feature to hack on too.

**Comment by AbdealiJK** [comment]
When we do this, even `autoapply` would be written back. Is that alright ?
And this would be done only is `-s` is given right ?

**Comment by AbdealiJK** [comment]
We use `autoapply=True` in coala_main. That goes into the default section right ?
When we write back the sections at the end of all `execute_sections` wouldn't this also be written back to the coafile ?

Also, we want to save sections only is the `--save` flag is given - correct ?

**Comment by sils1297** [comment]
This is more about if I use the OpenEditorAction the user will be asked for the editor and that setting should/could be written back in the end.

Though I'm not completely sure if we should do that or just close it as wontfix/not happening.

**Comment by AbdealiJK** [comment]
I'm closing this as wontfix/not happening
Because I don't think the user should be writing these settings manually. For example, I'd probably set the editor config in the user level coarc rather than the project level coafile. Seems unfair to do something like that.
