### ISSUE TITLE
coala git hook

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1204]
It should be fairly simple to write an example Git Hook that executes coala on commit. http://signal0.com/2012/07/20/checking_git_commit_message_format_before_commit_ing.html describes how that could be done.

I think it makes sense to revert ab74ecaa750c5a8faee89a2801c95587f7800f7f since 255c04c3fa93a6d2b4e35d313b790e0df177adfc got done. If that is done we can simply run `coala-ci` in the project root, it may autoapply stuff (e.g. fix codestyle by itself) and if any results beyond that are yielded (i.e. the retval of `coala-ci` isn't zero) we can tell the user that something's wrong and he should run `coala`.

The result of this work would be one little script and a documentation file.

**Comment by sils1297** [comment]
also see https://github.com/phobologic/git-hooks/blob/master/pre-commit/check-flake8.sh

**Comment by sils1297** [comment]
i.e. we'll want it to be a pre commit hook

**Comment by sils1297** [comment]
hm, actually this might get complicated when doing a partial add...

**Comment by AbdealiJK** [comment]
We should also try to do something so that we can specify a commit range and coala checks every commit in the range.

^ As gitmate checks coala's styling on every commit. This would help people check gitmate's result before pushing

**Comment by sils1297** [comment]
FWIW I have a mini gitmate coala script thingy at https://gitlab.com/gitmate/coala-incremental/ that shows how new results can be filtered with the coala result filter routines.

**Comment by AbdealiJK** [comment]
@sils1297 Im not sure what you're expecting here ...
I've made a very obvious script ... Im not sure if thats what you want. Can you take a look : https://github.com/coala-analyzer/coala/commit/d1cf6838c7448b593bebc6ae42845e7fb7cb7a75

**Comment by AbdealiJK** [comment]
Note that we cannot really run coala only on the changed files because GlobalBears won't function correctly like that.

**Comment by sils1297** [comment]
something like that might well do, essential to this issue is that it's properly documented though
