### ISSUE TITLE
filter_results() crashes on certain results

### ISSUE THREAD

**Issue by fneu** [coala-analyzer/coala#1209]
The Problem lies in the `remove_result_ranges_diffs()` function:

```python
for source_range in reversed(original_result.affected_code):
            file_name = source_range.file
            new_file = remove_range(mod_file_dict[file_name],
                                    source_range)
            mod_file_dict[file_name] = new_file
```

Here, the affected code of a result gets removed from a file. The reversed sorting ensures that SourceRanges behind others get removed first so that the indices are not off.

The bane of this implementation are overlaps though: they cause the indices to be off, resulting in the wrong code being removed. This might even throw an `IndexError` if the deviation is too high:

example: removing char 2-4 and 3-6 from the string `"123456"` should result in  `1` as the chars 2-6 should be removed.

instead:
- chars 3-6 are removed, resulting in: `"12"`
- chars 2-4 from `"12"` are removed, resulting in `IndexError`.

**Comment by sils1297** [comment]
@fneu this is scheduled for the next release in a week or so, can you please give this a priority over the other bugs?

**Comment by fneu** [comment]
@sils1297 sure, it's just that I have some problems with my cousins hard-bricked phone right now so I will be busy today with that I guess.
