### ISSUE TITLE
Add guide on how to ask questions

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1212]
Would be good to have a guide for newcomers on how to properly ask about help for a problem, that includes pointing out what one did which is sometimes nontrivial. Still it's needed because otherwise it's close to impossible to help.

**Comment by yash14123** [comment]
I would like to work on this. Please assign me this task.

**Comment by sils1297** [comment]
@yash14123 hi, cool. Please approve the invitation to our org at https://github.com/orgs/coala-analyzer so we can assign you. Let us know if you need any help, we're also usually available on the gitter channel.

**Comment by yash14123** [comment]
Accepted the invitation. Sent a PR for issue #1317.

**Comment by AbdealiJK** [comment]
@sils1297 It would be better if we just linked - http://stackoverflow.com/help/how-to-ask Much easier and probably everything we need.

**Comment by yash14123** [comment]
Agreed. @AbdealiJK

**Comment by sils1297** [comment]
@yash14123 you already have three fixes, right? Can I unassign you? You're working on something way nicer anyway right?

**Comment by yash14123** [comment]
There were no further comments on the last one made by AbdealiJK. Give me
just time for today. I will fix them both. :) Got busy with some proposals
to the Capital's government.

**Comment by AbdealiJK** [comment]
Closing this as it's done in CONTRIBUTING.rst now.
