### ISSUE TITLE
ImportError when running ./run_tests.py with virtualenv

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1217]
After creating new virtualenv and installing requirements `./run_tests.py` raises the following error.
```
Traceback (most recent call last):
  File "./run_tests.py", line 5, in <module>
    from site import getsitepackages
ImportError: cannot import name 'getsitepackages'
```

**Comment by sils1297** [comment]
Ah this affects only the tests, right? So https://github.com/coala-analyzer/coala/issues/875 might actually solve this along the way.

**Comment by Uran198** [comment]
@sils1297 yes, it seems this affects only tests. I had no issues with other parts.
