### ISSUE TITLE
Lint: Implement `check_prerequisites` from `CorrectionBasedBear`

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1225]
The `Lint` class does not have a check if the binary exists.

This task involves:
1. Port the function `check_prerequisites` of `CorrectionBasedBear` (lying in `coalib/bearlib/abstractions/CorrectionBasedBear.py`) to the `Lint` class (lying in `coalib/bearlib/abstractions/Lint.py`).
2. Testing that
3. Implement that for all other bear tests for bears inheritting `Lint`, using `generate_skip_test` (residing in `bears/tests/BearTestHelper.py`)

**Comment by sils1297** [comment]
Prototypish implementation and discussion available on https://github.com/coala-analyzer/coala/pull/1135
