### ISSUE TITLE
Applied patch info message shows multiple paths

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1233]
I'm getting here:

```
Executing section autofixotherpython...
[INFO][17:53:22] Applied 'ApplyPatchAction' from '/home/lasse/prog/gitmate-generic/server/views/auth/addrepo.py', '/home/lasse/prog/gitmate-generic/server/views/auth/addrepo.py', '/home/lasse/prog/gitmate-generic/server/views/auth/addrepo.py' for 'PyImportSortBear'.
```

It shouldn't show me the same path thrice. Also I think it would be nice to shorten the paths down to maybe only the filename so they're readable very quickly.

@abhsag24 can you try to reproduce this locally with an own example of yours?

**Comment by abhsag24** [comment]
how about relpath?

**Comment by sils1297** [comment]
@abhsag24 do you understand that this issue is about one bug and one "feature request" you could say?

1. It shows me multiple times the *same* path! That shouldn't happen! Bug.
2. Path's need to be shortened. Relpath would be possible but I think it'd be still very long, especially when having multiple paths. So I think we may want to go for splitting off the whole path and showing filename only.

Your take on this?

**Comment by abhsag24** [comment]
1. Yes need to fix this, will get to it soon.
2. Its a matter of choice, ideally i won't want long messages , but if a user has multiple paths they might be confused as to which file the patch was applied to(2 files with the same name.)

**Comment by sils1297** [comment]
@abhsag24 about 2. you prefer relpath? Then let's go for that. Do you want to open a new issue to track that? Do you want to do that?

**Comment by abhsag24** [comment]
@sils1297 i'll do both at once, they change the same file so need for a new issue

**Comment by sils1297** [comment]
@abhsag24 please do them in an own commit each though, thanks.

**Comment by abhsag24** [comment]
@sils1297  okay :P
