### ISSUE TITLE
ConflictError: Cannot add lines after given line since there are already lines.

### ISSUE THREAD

**Issue by TimSo94** [coala-analyzer/coala#1235]
![pasted image at 2016_01_21 11_22 pm](https://cloud.githubusercontent.com/assets/15891199/12522408/c36cb5f8-c150-11e5-83a1-9dca14885844.png)

There is the error message. If you have more questions, ask me.

**Comment by sils1297** [comment]
@Makman2 I think this is a usability issue, probably relevant for 0.5... ish?

Could you tell us what you were expecting coala to do in this case? Print the same patch again? Are you aware that the patch would be no longer valid because the files on your FS have changed?

**Comment by Makman2** [comment]
@sils1297 wouldn't that also happen on Linux systems?
But yeah that's a bit difficult now what to expect. First the "apply the patch"-action should be removed after applying the patch. Second for the print-patch-action there are two possibilities:
1. Remove it also from the choice list after applying the patch 
2. Display the old patch (which would be the better option imo)

   I'm not sure when coala does write back stuffs, it was immediately, wasn't it? Depending on how this is handled it gets more or less difficult to regain the old file content. Maybe we keep two versions in memory, the old one and a working copy that gets written back to files after each apply or so^^

**Comment by sils1297** [comment]
@Makman2 we have the new version in the memory always and also on the filesystem. Would be hard to print the patch after it's applied. I'd rather remove that action after the patch was applied together with the apply action. That would be done by https://github.com/coala-analyzer/coala/issues/1064 then.

**Comment by Makman2** [comment]
@sils1297 yes that's why we need to keep the old version if we want to print the patch and refer to that. I would like to be able to print the patch still, sometimes it's like "oh coala found something, just apply... oh wait damn, that was from SpecialSuperBear, omg need to check that again what I did..."
Even though git tracks changes and you could see them, this would only work when you work with git :)

**Comment by sils1297** [comment]
@Makman2 I don't see any way to do this cleanly from a technical POV. I.e. we can't provide an action with the means to do that kind of thing without doing something completely weird, complicated that would work just for this one usecase which isn't that important anyway. I would rather think about executing applypatchaction automatically before applying the patch or so.

**Comment by Makman2** [comment]
Alright then let's remove the choice for displaying the patch when a user already applied it.
