### ISSUE TITLE
Shell: Detect current shell instead of platform

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1236]
The function `escape_path_argument` inside `coalib/misc/Shell.py` (and also the coming `prepare_string_argument` function) use the operating system to chose which shell is used (chosing the default shell). Would be way better to depend on the actual shell, more bullet-proof across platforms and then we can support multiple shells on the same OS.

So in fact we change the parameter default of `os` to something that gets the shell name and adjust the conditions inside the function accordingly.

Problem: After googling a bit I couldn't find anything on how to retrieve the current shell...

**Comment by Makman2** [comment]
A solution would be anyway to run shell commands that determine the current shell and put that inside a function that can be easily used. Though someone needs to collect all commands for all different shells and implement that :)

**Comment by sils1297** [comment]
@Makman2 sorry but I'm strongly pledging for a wontfix if there isn't a library out there that does that. You can write one if you want and then reopen :P don't think this belopngs in coala.

**Comment by Makman2** [comment]
@sils1297 this could prevent run and test errors that use shell stuff. The current usage of the OS is not clean^^ Since the main OSes do work I've set importance to low^^

**Comment by sils1297** [comment]
Still this is not code that should reside in coala. I'd advise you to put
that into a library.

2016-01-22 22:45 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
why that? that's what the `Shell` module is for. It would be anyway a single function, imo that's a bit sparse for creating a library , which would involve a test framework, installing and publishing to pip. I would use the shell functions also from this module, porting them makes also no sense, they are more for convenience and clean handling.

**Comment by sudheesh001** [comment]
Would the value in `echo $SHELL` be useful for this ?

**Comment by Makman2** [comment]
Does this work for all shells? Thats the question for this issue :)
And if not we need more such shell commands that specify the shell and pack them together inside a function.

**Comment by sudheesh001** [comment]
I think that command should work on all Linux and Mac.

**Comment by sils1297** [comment]
So the biggest problem here is windows with the powershell and cmd.

2016-02-07 18:15 GMT+01:00 Sudheesh Singanamalla <notifications@github.com>:

**Comment by AbdealiJK** [comment]
I do not think this is possible.
I think the best way is to check `$SHELL`. Because the only shell you'd see in Windows where we shouldnt do windows like escaping in GitBash and cygwin. Both have a `$SHELL`.

If `$SHELL` is not available - use OS

**Comment by AbdealiJK** [comment]
Sorry - in fact `$SHELL` gives you the login shell. not the current shell (Just tried it out)
```
ajk@ajk-Precision-T1700:~/Documents/coala/coala$ echo $SHELL
/bin/bash
ajk@ajk-Precision-T1700:~/Documents/coala/coala$ sh
$ echo $SHELL
/bin/bash
```

I vote to close this issue as wontfix (patches accepted) as there doesn't seem any way to do it. And we **could** do it in some highly complicated way but it's just not worth the effort

**Comment by Makman2** [comment]
@AbdealiJK is `sh` not `bash`? In windows powershell and cmd quite differ, especially escaping. And that's the problem with just feeding in the OS^^

**Comment by sils1297** [comment]
sh sometimes actually is bash but sometimes isn't.

**Comment by AbdealiJK** [comment]
@Makman2 `sh` isnt `bash`. its renamed sometimes to just be linked to bash (for me it isn't).

**Comment by SanketDG** [comment]
```shell
echo $0
```

Returns whatever shell I am working from. But just the name. Something like:

```shell
which `echo $0`
```

could be useful.

**Comment by AbdealiJK** [comment]
@SanketDG that doesnt work on cmd and Powershell
Ive done some reading and have come to the conclusion:

 - If `echo $host.name` gives `ConsoleHost` it is Powershell
 - If `echo $host.name` gives `$host.name` it is cmd
 - If `echo $host.name` gives `.name` it is unix based shell

 - If `echo $0` gives out `$0` => cmd
 - If `echo $0` gives nothing, it is powershell
 - If `echo $0` gives out a linux path use `basename` to get shell

Note that this is from other people's blogs - and I haven't tested it out myself.
I do not know of any shell except `cmd` and `powershell` which do not work with `echo $0` (I only know sh, zsh, bash (and derivatives), cmd, powershell, cygwin-bash)

**Comment by Makman2** [comment]
@AbdealiJK it is ar least linux, so that works at least ^^

**Comment by AbdealiJK** [comment]
@Makman2 sorry ? didn't understand

**Comment by Makman2** [comment]
Nvm havent read everything properly^^

**Comment by AbdealiJK** [comment]
All 6 of those cases mentioned work (just tested it)
@Makman2 are those conditions fine ?

**Comment by AbdealiJK** [comment]
So, I pushed a code which uses shell_type instead of OS.
But I do not know what escape characters to use for `powershell`.
@Makman2 could you add that part when you can ?

**Comment by Makman2** [comment]
Sure, but I remember backslashes shall work...

**Comment by Makman2** [comment]
I think this is solved :)

**Comment by sils1297** [comment]
you think?

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-04-13 4:42 GMT+02:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
We only need it inside `Shell.escape_path_argument` currently, and there it's implemented^^
