### ISSUE TITLE
find config doesn't search the current directory actually

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1246]
```
lasse@localhost ~/prog/coala (git)-[master] % coala --find-config
[INFO][10:54:57] FOUND CONFIG /home/lasse/prog/.coafile
Executing section Default...
lasse@localhost ~/prog/coala (git)-[master] % cd coalib 
lasse@localhost ~/prog/coala/coalib (git)-[master] % coala --find-config
[INFO][10:55:12] FOUND CONFIG /home/lasse/prog/coala/.coafile
Executing section Default...
Executing section autopep8...
...
```

CC @AbdealiJK

**Comment by AbdealiJK** [comment]
@sils1297 I think I had mentioned this on gitter, but I don't seem to be able recreate this bug.

```
ajk@ajk-ThinkPad-R60:~/Documents/coala$ ls
coala  coala-atom  coala-gedit  coala-sublime  pyprint  test.coffee  test.py  website

ajk@ajk-ThinkPad-R60:~/Documents/coala$ cat test.py 
import s

def a(): ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        pass

ajk@ajk-ThinkPad-R60:~/Documents/coala$ cat .coafile 
[PythonFiles]
files = test.py
bears = SpaceConsistencyBear, LineLengthBear, PEP8Bear
use_spaces = True
max_line_length = 80

ajk@ajk-ThinkPad-R60:~/Documents/coala$ coala-format --settings format_str="{line}:{message}"3:Line is longer than allowed. (94 > 80)
2:The code does not comply to PEP8.
4:The code does not comply to PEP8.

ajk@ajk-ThinkPad-R60:~/Documents/coala$ coala-format --find-config --settings format_str="{line}:{message}"
3:Line is longer than allowed. (94 > 80)
2:The code does not comply to PEP8.
4:The code does not comply to PEP8.

ajk@ajk-ThinkPad-R60:~/Documents/coala$ mkdir abc
ajk@ajk-ThinkPad-R60:~/Documents/coala$ cd abc/

ajk@ajk-ThinkPad-R60:~/Documents/coala/abc$ coala-format --find-config --settings format_str="{line}:{message}"
3:Line is longer than allowed. (94 > 80)
2:The code does not comply to PEP8.
4:The code does not comply to PEP8.

ajk@ajk-ThinkPad-R60:~/Documents/coala/abc$ coala-format --settings format_str="{line}:{message}"
[WARNING][14:46:00] The default coafile '.coafile' was not found. Ignoring it.
```
So, as you see if the test.py was in the same directory as coafile - When i run it from that directory with or without `--find-config` it worked. And when I created a folder `abc` and ran it from there it only worked with `--find-config`  as the coafile was one layer down.

I even did a whole system search on `.coafile` and all of thema re inside /home/ajk/Documents/coala` folder. So it never found anything below this folder.

**Comment by sils1297** [comment]
I think this bug occurs if you e.g. do `-c path/to/directory` as the `dirname` will cut away `directory`

**Comment by AbdealiJK** [comment]
Why would you do -c and --find-config ?

**Comment by sils1297** [comment]
good point... still I think the commit we hav ewould be useful

**Comment by AbdealiJK** [comment]
Figured out how to reproduce this. It seems if I have a `.coafile` one directory above where I run it from, it prefers that one. If I don't have a coafile one directory above, it uses the one in the current directory.

**Comment by AbdealiJK** [comment]
@hypothesist still working on this ? This affects all the editor plugins and would be nice to be able to solve it soon

**Comment by AbdealiJK** [comment]
@sils1297 we shouldn't do a release without this bug solved (as it affects all the plugins too)

**Comment by sils1297** [comment]
@AbdealiJK can you cherry pick in @hypothesist s commit maybe? It was almost ready IIRC.
