### ISSUE TITLE
Find a way to delete .orig files created by ApplyPatchAction 

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#1253]
right now orig files once created never get modified or deleted, until the user them-self deletes them, coala should provide a way to delete these files, either on start up or through a command line argument or maybe provide some other way to handle these files.

**Comment by abhsag24** [comment]
decisions: 
1> to create a subroutine which would do all the work 
2> run this subroutine before `run_coala` on all other subroutines 
3>add option(maybe?) to keep the .orig files

**Comment by sils1297** [comment]
Don't run it before `run_coala` but *in* it, otherwise you have to put it there multiple times
