### ISSUE TITLE
Allow ignoring ranges via coafile

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1258]

**Comment by Makman2** [comment]
You think that makes sense? If you would delete a single line before such an ignoring range, you need to adapt the coafile too^^

**Comment by sils1297** [comment]
I had an explicit request to do so and it is a usecase that wyou want to
ignore stuff in a range without changing your code

2016-01-30 16:54 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by sils1297** [comment]
Would be nice to have a command line option for line ranges , too. Of course also in the coafile

**Comment by sils1297** [comment]
> If you would delete a single line before such an ignoring range, you need to adapt the coafile too^^

yeah that's quite an issue indeed...

**Comment by Makman2** [comment]
honestly I'm not in for that feature, it's more maintenance for the user. Even if he/she thinks on first sight to be able to separate codestyle-checks and code, this isn't worth when you change your code again (which you likely do, I mean you develop a project more or less consistently).
Even automated generation (maybe via a build tool like CMake) of such a coafile that would do skipping stuff is more pain than gain^^

**Comment by sils1297** [comment]
alright, this is a wontfix. We should be aware of the reasons though this feature does not make sense indeed because users would have to alter the config always which is impractical.
