### ISSUE TITLE
Use arrays instead of strings to execute new programs

### ISSUE THREAD

**Issue by setharnold** [coala-analyzer/coala#1264]
At least the LInt abstraction (probably others, I haven't looked) is building a string to pass to the shell to execute; this is dangerous, especially when some inputs may come from untrusted sources (presumably the software being reviewed) and some inputs may come from trusted sources. This then requires properly quoting inputs, which is entirely too easy to overlook. (See the huge number of SQL injection and command injection faults already assigned CVEs. Every one of those devs thought they'd always remember to quote what they needed to quote but they all forgot.)

It'd be far safer to switch to passing shell=false to the subprocess module and building arguments using lists instead of strings. This is a simple change from args += foo + bar to args.extend([foo,bar]) or args.append(foo) as needed.

Not only is this safer but it's also faster -- building strings by iterative concatenation is slow, executing the shell is slow, and the shell must break apart the string into an array internally anyway.

https://github.com/coala-analyzer/coala/blob/master/coalib/bearlib/abstractions/Lint.py#L48

Thanks

**Comment by sils1297** [comment]
@setharnold thanks for this report! We'll look into that as soon as possible.

**Comment by sils1297** [comment]
@abhsag24 would you any of you be interested in doing this?

**Comment by sils1297** [comment]
@setharnold please note that coala allows you to execute any custom code anyway. You can specify `bear_dirs` and thus provide custom analysis routines written in python through the `.coafile`. coala is not intended to be run with a configuration that has possibly malicious intent. (That is no reason to not clean up our code like you suggested, just noting.) If coala is run with a *trusted configuration* on *untrusted code that is to be reviewed* there's no problem either way as long as no bears execute the code.

**Comment by Makman2** [comment]
It's anyway a good idea to be safe as possible, maybe we can just deactive the `shell=True` argument in most places?

**Comment by sils1297** [comment]
We could also use a well defined regex in a bear to ensure such things
don't occur in the future, should be rather easy to do only for python with
a low false positive rate since this case is rather special.

**Comment by abhsag24** [comment]
@sils1297 sure :)

**Comment by sils1297** [comment]
@abhsag24 you seem to be busy with a lot of other stuff so I guess it's bad to push you to do this ;) However @AbdealiJK is just working on some refactorings related to this and he should at least be aware of it. @AbdealiJK would be nice if you could include a fix in https://github.com/coala-analyzer/coala/pull/1404 .

**Comment by AbdealiJK** [comment]
@setharnold  @sils1297 Python docs https://docs.python.org/3/library/subprocess.html#subprocess.Popen say that when `shell=True` is given its preferred to send a string instead of an array

> The shell argument (which defaults to False) specifies whether to use the shell as the program to execute. If shell is True, it is recommended to pass args as a string rather than as a sequence

We use `shell=True`. If I set `shell=False`, then the linters are not found (probably `PATH` is not set if `shell=True`)

**Comment by Makman2** [comment]
@AbdealiJK the environment should be inherited from the calling process as stated from the documentation. Maybe you forgot to change the string to binary/argument lists? Anyway I'll look into it^^

**Comment by AbdealiJK** [comment]
Commit reverted in https://github.com/coala-analyzer/coala/pull/1670
