### ISSUE TITLE
Deeper Go support

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1267]
http://dominik.honnef.co/posts/2014/12/an_incomplete_list_of_go_tools/ lists a few tools. https://github.com/coala-analyzer/coala/pull/1266 implements some basic support for Go, I'd like to see

- [ ] errcheck
- [ ] goreturns
- [ ] goimports
- [ ] golint

Take inspiration from the GoVetBear and the GofmtBear

**Comment by sudheesh001** [comment]
@sils1297 Please rename this issue to `errcheck` bear , I've opened up the other issues for the other gotools, That way this issue also gets closed without explicitly mentioning this to close after fixing all the other issues

**Comment by Makman2** [comment]
@sudheesh001 I think you can open another issue just for `errcheck`, then we just close this issue, so we have a new and clean one :)

**Comment by sudheesh001** [comment]
@Makman2 good to close ! :smile:
