### ISSUE TITLE
Installing coala from source in Windows using virtual env in conda

### ISSUE THREAD

**Issue by abit2** [coala-analyzer/coala#1268]
Steps to reproduce the problem
Create a virtual environment with conda.
Clone repo in your Desktop.
Activate env and try to install using python setup.py install
Getting this error: "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid
start byte".

**Comment by sils1297** [comment]
@abit2 can you give us the exact commands to reproduce to make sure they don't differ? Usually it's good to open a new terminal session, recreate the issue with commands and put the whole thing into pastebin, possibly stripping away unrelated output like the one from the venv creation.

**Comment by abit2** [comment]
@sils1297 http://pastebin.com/yainhCUf

**Comment by sils1297** [comment]
interesting, the exception happens in setuptools, can you just retry the installation? I recall sometimes it just worked the second time in such cases...

**Comment by abit2** [comment]
tried a few times, getting the same error.

**Comment by Makman2** [comment]
your python version is somehow interesting (`Python 3.5.1 :: Anaconda 2.4.1 (64-bit)`), maybe that's the problem?

**Comment by Makman2** [comment]
But I'll try it soon on my windows machine with `python setup.py install`^^

**Comment by Makman2** [comment]
Can't reproduce, deleted setuptools, installed it again, installed coala befor and after, everything succeeds^^

**Comment by Makman2** [comment]
Btw the problem seems to be inside coverage, there the traceback shows up^^

**Comment by Makman2** [comment]
@abit2 could you maybe provide all commands that lead to this error? Also how you create the venv, cloning etc.

**Comment by abit2** [comment]
@Makman2 
created conda create --name coala python=3
cloned from forked repository 
python setup.py install 
it gives me  this error

**Comment by Makman2** [comment]
@abit2 please the concrete commandos, not a description :) I can't reproduce it then

**Comment by abit2** [comment]
http://pastebin.com/sh7znSXQ

**Comment by Makman2** [comment]
@abit2 you use a package manager called "conda", tbh I've never worked with it. The default way what I tried and what others use by default is `venv` (I think we support that by now). What I know from there is that you need to activate a created environment, maybe that's missing in your setup? I don't know if you skipped something, seems you stripped off the install logs :/ even if they are long please just keep them, better having them than not. And please make sure that you clone and setup everything inside a clean and new environment, otherwise this isn't really reliable since you could maybe changed something inside the local clone (maybe on purpose or even not).

On my windows machine I don't use virtual environments, I have a global python 3.4 installation and pip modules are also globally installed.

You could try if installation via pip works, `pip3 install coala --pre`, this is anyway the preferred way^^

**Comment by sils1297** [comment]
@Makman2 we should not advise people against using a virtual env, using that is actually the cleaner and generally better thing because dependencies don't conflict with otherwise installed packages.

**Comment by sudheesh001** [comment]
Did you try using `export LC_ALL=en_US.UTF-8` before running the `setup.py`. Specifically C_TYPE should fix this `export LC_CTYPE=en_US.UTF-8`, I could reproduce this problem on a friends windows PC and fix it using the export.

**Comment by sils1297** [comment]
@sudheesh001 any hint on how this could be fixed?

**Comment by sudheesh001** [comment]
```py
import locale
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
```
Putting this as a part before the setup process starts should be fixing this I guess.

**Comment by sils1297** [comment]
Apparently this is not resolved

**Comment by abit2** [comment]
http://pastebin.com/HhyLSErM

**Comment by Makman2** [comment]
@abit2 could you try to install inside your `te` environment `coverage` directly using `pip install coverage`? If that works could you then try to install coala again like you do via `python setup.py install`?
Looks more like an issue in pip (on first sight), already found bug reports where unicode stuff can't be decoded correctly.
@sils1297 btw I'm a bit irritated why coala tries to install `coverage`, I mean it's only needed for testing, isn't it? The `setup.py` should be deployment-only.

**Comment by sils1297** [comment]
We may have stuff for testing in the requirements.txt which is picked up by
setup.py. Yes, it's actually in there.

2016-02-06 22:12 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by abit2** [comment]
@Makman2 pip install coverage tells it is already up-to-date.Still the same error.

**Comment by abit2** [comment]
http://pastebin.com/NX2Mr479

**Comment by sils1297** [comment]
@abit2 can you try it outside conda? To see if it's conda related?

**Comment by abit2** [comment]
@sils1297 http://pastebin.com/Gnh6NCwz
getting the same errror.

**Comment by Makman2** [comment]
@abit2 did you deactivate the conda environment? The anaconda3 path does still show up^^

**Comment by abit2** [comment]
@Makman2 Sorry my bad.

**Comment by abit2** [comment]
@Makman2 http://pastebin.com/v6jFWvLw 
same problem.

**Comment by Makman2** [comment]
I think I need to get python 3.5 on windows. I have 3.4 and coverage installs for me the `coverage-3.4` script instead of `coverage-3.5`, maybe that makes a difference.

**Comment by sils1297** [comment]
@sudheesh001 any news on this?

**Comment by AbdealiJK** [comment]
Notice that this is actually an issue others face too http://stackoverflow.com/questions/34551625/pgmpy-build-error-anaconda-windows .

I am thinking that conda doesnt seem to be sourcing the virtualenv correctly. Possibly a conda bug ?

@abit2 dont you ahve to activate the new conda env you create ? you dont seem to be doing it at http://pastebin.com/sh7znSXQ

**Comment by abit2** [comment]
notice the [conda] in brackets @AbdealiJK

**Comment by AbdealiJK** [comment]
@abit2 - I'm guessing you mean [coala] ?

But yeah, it's there. Sorry, I got confused between `lenovo@admin MINGW64 ~` and `C:\Users\lenovo\Desktop>`.
Shouldnt this be [coala1] as thats what you named the virtualenv in `conda create --name coala1 python=3` ?

Secondly - so it seems conda auto enables the virtualenv. Is this right ?
If yes, could you try to activate it yourself using `activate <venv name>` ? as http://stackoverflow.com/questions/34551625/pgmpy-build-error-anaconda-windows says ?
This would confirm whether this is a conda bug or coala bug

**Comment by abit2** [comment]
Hmmm.....Sorry but i have shifted completely to ubuntu, don't have windows os now.
Cannot reproduce this issue,anyways it runs smoothly in ubuntu (using conda env).

**Comment by AbdealiJK** [comment]
@Makman2 can you try this out ?

**Comment by Makman2** [comment]
Can't reproduce still on my machine^^

**Comment by AbdealiJK** [comment]
Then im not sure what we can do about this for now :/

**Comment by Makman2** [comment]
@abit2 I'm not able to reproduce, you have no windows machine, so practically the issue is gone :3
If it happens again, feel free to reopen the issue/ping us^^
