### ISSUE TITLE
Explicitly mention usage of pip3 for users while installing requirements

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1270]
Installing using `pip` instead of `pip3` causes errors as follows
```log
  File "/Users/sudheeshsinganamalla/Documents/coalaenv/build/language-check/setup.py", line 586, in language_tool_hook

    download_lt()

  File "download_lt.py", line 148, in download_lt

    with closing(ZipFile(t)) as z:

  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 770, in __init__

    self._RealGetContents()

  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 811, in _RealGetContents

    raise BadZipfile, "File is not a zip file"

zipfile.BadZipfile: File is not a zip file
```
As noted on [Gitter](https://gitter.im/coala-analyzer/coala?at=56b1be19c54bc2bf180db15a) using pip3 should fix this problem.

**Comment by sils1297** [comment]
At least on the install docs we should have a note about this, where did you get the info from? README?

**Comment by sudheesh001** [comment]
I couldn't really find out where the install docs were, i noticed a requirements file and just like every other project (I generally work with Django / Flask, So I did `pip install -r requirements.txt` more instinctively than via any docs) Could you point me to the install docs please @sils1297

**Comment by sils1297** [comment]
http://coala.readthedocs.org/en/latest/Users/Install/

**Comment by sils1297** [comment]
@sudheesh001 do you think we could improve something or can we close this?

**Comment by sudheesh001** [comment]
@sils1297 Maybe we could create a `..note` telling contributors to use only `python 3`, but how do we exactly put the wording for it ?
```
.. note::

   To setup and use coala you will need to have python3
```

**Comment by sils1297** [comment]
@sudheesh001 feel free to do a PR, note that we use markdown, we usually do notes with a quote, you won't have a hard time finding an esxample somewhere I guess
