### ISSUE TITLE
CircularDependencyError in Dependencies.py: Code can be simplified

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1281]
```python
        bear_names = []

        for bear in bears:
            bear_names.append(bear.__name__)
```

that can be easily written as a generator expression shortening the code

**Comment by shubhamrajput** [comment]
how about this...
bear_names=[bear.__name__ for bear in bears]

**Comment by sils1297** [comment]
yes :)

**Comment by sils1297** [comment]
@shubhamrajput interested in doing this one?

**Comment by shubhamrajput** [comment]
yes i am...

**Comment by sils1297** [comment]
@shubhamrajput any progress? Should I unassign you?

**Comment by sils1297** [comment]
unassigning because of lack of response

**Comment by lonewolf07** [comment]
I would like to try this one!

**Comment by SanketDG** [comment]
@lonewolf07 make us proud!
