### ISSUE TITLE
Move dependency `coverage` from `requirements.txt` to `test-requirements.txt`

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1293]
`coverage` is for measuring coverage inside tests. No need to have this package for deployment.

**Comment by sils1297** [comment]
yeah, there'll be a lot of movement around this soon with the pytest switch, this has other effects and is not a task that can be carried out that easily. I think this bug report is not really useful right now.

**Comment by sils1297** [comment]
seems this'll be part of the pytest switch
