### ISSUE TITLE
git commit bear doesn't work if coala isn't run in the same directory

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1294]
it should also work if I provide a coafile with `-c`, @Makman2 can you fix that soonish? This is kind of the reason why this breaks everywhere for my gitmate experiments.

**Comment by Makman2** [comment]
@sils1297 you know how to retrieve the filename of the coafile being used? Then I can just passing this as a working directory to git.

**Comment by sils1297** [comment]
@Makman2 so the `section` might have a `config` setting that points to the coafile. Actually @abhsag24 has a function in one of his PRs that retrieves that location for you, we just need to move it out later.
