### ISSUE TITLE
change verify_local_bear so it (optionally) writes file contents to actual files

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1299]
Pass the parameters as
- filename1 (good file) : Valid
- filename2 (bad file) : Invalid

The bear tests fail in scrutinizer because of duplication, there should be a way around that problem by writing a function as above which generates the test instead of explicitly maintaining the test.

**Comment by Makman2** [comment]
Don't we have that already in `LocalBearTestHelper.verify_local_bear()`?
https://github.com/coala-analyzer/coala/blob/master/bears/tests/LocalBearTestHelper.py#L256

**Comment by sils1297** [comment]
yeah we should rather change that one
