### ISSUE TITLE
setup.py: classifiers: Set development status to beta

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1303]
we're not alpha. We're not production yt but we're close so let's say beta.

**Comment by CruiseDevice** [comment]
What exactly to do here? Is there a typo in title?

**Comment by sils1297** [comment]
the classifiers in setup.py need to be edited - just look into the file, there should be a comment explaining what they are.

Yes there was a typo ;)

**Comment by CruiseDevice** [comment]
Only change this line `'Development Status :: 3 - Alpha'` right?

**Comment by sils1297** [comment]
yes

2016-02-07 22:27 GMT+01:00 Bruce Wayne <notifications@github.com>:
