### ISSUE TITLE
getting `setup.py test` to work

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1305]
As pytest support is complete now we can use https://pypi.python.org/pypi/pytest-runner to integrate pytest with setup.py. With this we can simply run `python3 setup.py test` and run all our tests.

Gives us more flexibility because we can add hooks for before and after too (inside setup.py) !

**Comment by sils1297** [comment]
pytest support is possible but we didn't do the switch yet fwiw

**Comment by sils1297** [comment]
blocked by https://github.com/coala-analyzer/coala/issues/1305

**Comment by AbdealiJK** [comment]
Er, @sils1297 you just wrote that this test is blocked by itself ?

**Comment by sils1297** [comment]
sorry I meant https://github.com/coala-analyzer/coala/issues/875

**Comment by sils1297** [comment]
Doesn't seem too easy...

**Comment by sils1297** [comment]
http://pastebin.com/VxCWj3p4

**Comment by AbdealiJK** [comment]
So, i checked out the pytest thing. its not very nice :/
Apparently with `python setup.py test`  you'd need to pass arguments using something like `pytest_args="..."` which i find irritating.
Also, `python setup.py test` will install pytest on its own locally to a .egg file which i again don't like because it is confusing.
