### ISSUE TITLE
XML Bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1309]
apparently I did https://github.com/coala-analyzer/coala/commit/20fdbd88f3d638365776e75f7af9f01e6d18af29 not sure how good this is reusable

**Comment by yash14123** [comment]
Can you explain this a little bit more?

**Comment by Makman2** [comment]
This issue is about implementing a new bear that scans through XML files. For this purpose @sils1297 used the python built-in `xml` module inside his commit.
What actual analyze routines this bear shall implement is up to its writer :)

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#32
