### ISSUE TITLE
coala-format new string option : severity_str

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1313]
Currently, severity gives the formatted output as a integer.
`severity_str` can be used to give it as a string (Info, Normal, Major).

So, then people can use which ever they prefer.

**Comment by iamshubh22** [comment]
@AbdealiJK I am a newcomer to coala and it would be helpful if you elaborate this.

**Comment by AbdealiJK** [comment]
@iamshubh22 hey there !
We have a file named `RESULT_SEVEIRTY.py` which contains an Enum (enumeration) for all the severities we have in coala. As you may know, enums are essentially ints which have a string associated to it.

Currently we have 3 severities: Info (0), Normal (1), and Major (2)

Now, in `coala-format`, we can specify how we want coala's results to be formatted using the `format_str` setting (try: `coala-format -S --format_str="{line} - {severity} - {file} - {message}"`)

Example output:
`3 - 1 - /home/ajk/Documents/coala/test.py - The code does not comply to PEP8.`

And if you notice the output of `coala-format`, the output for the "severity" is an integer (which is the integer part of the Enum). I propose that we add a "severity_str" which would allow me to get something like this:
`3 - Normal - /home/ajk/Documents/coala/test.py - The code does not comply to PEP8.`

**Comment by iamshubh22** [comment]
@AbdealiJK Got it.

**Comment by sils1297** [comment]
@yash14123 ping us if you need assistance :)

**Comment by yash14123** [comment]
I do. :(

**Comment by sils1297** [comment]
@yash14123 we're around at https://gitter.im/coala-analyzer/coala to help you :)

**Comment by yash14123** [comment]
Will catch up with you in an hour.

**Comment by sils1297** [comment]
I'll be away then, others will be around for sure. Try pinging @AbdealiJK

2016-02-14 14:53 GMT+01:00 yash14123 <notifications@github.com>:

**Comment by sils1297** [comment]
@yash14123 please ping back todayish, otherwise we may reassign this issue.

**Comment by sils1297** [comment]
Just a ping is sufficient to know you still intend to work on it, you don't need to actually do it today.

**Comment by yash14123** [comment]
I am consumed with the mid-semesters. I really apologize for not being
active . They end in about 4 days. If someone else is willing to work on
it, please reassign.
Sorry for the delay. Real tough exams in India u know :(

On Wed, Feb 24, 2016 at 11:16 PM, Lasse Schuirmann <notifications@github.com

**Comment by sils1297** [comment]
@yash14123 ok I'm freeing this bug then, feel free to approach us whenever you like though ;)

**Comment by sils1297** [comment]
@SanketDG you've asked about this, if you have some kind of interest on it, feel free to look into it.

**Comment by SanketDG** [comment]
@sils1297 yes assign this to me.
