### ISSUE TITLE
Add contextmanager for os.chdir()

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#1314]
The context manager, should change the directory and then revert back after all the work is done(as with all context managers)
UPDATE: Would be useful in testing, when tests need to check in different directories

**Comment by sils1297** [comment]
@abhsag24 please add at least one case where this should be used

**Comment by Makman2** [comment]
Found it only here:
https://github.com/coala-analyzer/coala/blob/b5c49a77f7f8d11cf9d2101ffd665205c35fb307/bears/tests/vcs/git/GitCommitBearTest.py#L51
In this case I wouldn't use this context manager, I've written the tests and I wanted to get the test cases in some "environment" so one can execute git without bothering about the working directory.
Would be a nice context manager though^^

I would say we implement that on demand^^

**Comment by AbdealiJK** [comment]
@abhsag24 Was this ever added ?
If not - why not ?

We need it for:
 - https://github.com/coala-analyzer/coala/blob/master/tests/settings/ConfigurationGatheringTest.py#L244
 - https://github.com/hypothesist/coala/commit/cbbb91b777628a1a24f71e7583af85b380147f5b#diff-47b0faa7cf6a1e9bf67b19d5d1746de3R260
 - https://github.com/coala-analyzer/coala-bears/blob/master/tests/vcs/git/GitCommitBearTest.py#L53
 - https://github.com/coala-analyzer/coala-bears/blob/master/tests/vcs/git/GitCommitBearTest.py#L64
 - https://github.com/coala-analyzer/coala-bears/blob/master/tests/vcs/git/GitCommitBearTest.py#L157
 - https://github.com/coala-analyzer/coala-bears/blob/master/bears/vcs/git/GitCommitBear.py#L43

**Comment by abhsag24** [comment]
@abhsag24it wasn't since it was in my PR for improving tests, which eventually you had to do since we moved to pytest and had the whole issue regarding the coverage

**Comment by AbdealiJK** [comment]
@abhsag24 Aha. I see, cool.
It'd be a nice thing to have.

**Comment by Makman2** [comment]
Not for the GitCommitBear test, since the working dir is changed in `setUp` and `tearDown` to execute the complete test case inside a different working directory^^

**Comment by AbdealiJK** [comment]
@Makman2 the GitCommitBearTest has 1-2 places where it wants to change to a temp directory (even after the setUp thing)

**Comment by Makman2** [comment]
@AbdealiJK ah okay, though there's no context manager needed anyway since `tearDown()` changes to the last working dir :dancer:
