### ISSUE TITLE
Running coala on a specific glob only

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1315]
There are a few issues that came up when looking at the editor plugins.

### What we want
We want to be able to run all sections in a coafile. But we do not want to run everything - we only want to run on a specific glob of files (or a single file).
For example:
If I have 3 sections `[JSON]`, `[Python]`, `[Coffee]` - and I want coala to only give me results for a `test.py`

### Current solutions
 - If I do `--files=test.py` - this only replaces the `files` value in `[Default]` and this still gives results from `test.coffee` and `test.json`
 - if I do `-S files=test.py` again only does it for the default section. i could do `-S Python.files=test.py` and repeat for all sections, but this not nice.

Possible solutions:
 - make a `--limit-files` which will limit the files in *every* section

**Comment by AbdealiJK** [comment]
@sils1297 What do you think about adding wild cards in the Section names ?

Like : `-S *.files=test.py` ?

This would be good because if you want you can modify a bunch of sections with similar names you can do it. Like if you have a `[PythonLinting]` `[PythonAutofix]` `[PythonCodeClone]` and you want to change the `files` for all Python related section you could do `-S Python*.files=test.py`

**Comment by sils1297** [comment]
that wouldn't cover the usecase as it'd override the file setting also for
sections that don't even contain the file, we really want an intersection ;)

2016-02-08 11:25 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
True.
