### ISSUE TITLE
Remove docs/requirements.txt

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1317]
We have a `./docs-requirements.txt` and also a `docs/requirements.txt`

I had created the `docs/requirements.txt` about half a yr ago. https://github.com/coala-analyzer/coala/commit/f14b734fbdfd330d18c4c09de05cd9593d6dea4c

I notice we're not using mkdocs anymore ? Maybe this should be removed ?

**Comment by sils1297** [comment]
oh yeah, sorry

**Comment by AbdealiJK** [comment]
Also, `.misc/deps.linux.sh` needs to be removed. It just says "No dependencies to install for linux" and is not used anywhere

**Comment by sils1297** [comment]
@AbdealiJK can you file another bug for this? I'm doing a workshop in a month or so and need 15 newcomer suitable bugs for that :P

**Comment by AbdealiJK** [comment]
sure

**Comment by yash14123** [comment]
PR sent for this. ! :)

**Comment by yash14123** [comment]
@AbdealiJK the second point made : removing .misc/deps.linux.sh . By that you mean .misc/deps.sh?

**Comment by AbdealiJK** [comment]
@yash14123 - No, I did not mean deps.sh
Please ignore the comment aboud `.mics/deps.linux.sh`. It is invalid (check here for more details https://github.com/coala-analyzer/coala/issues/1318)

**Comment by yash14123** [comment]
Can you help me @AbdealiJK ? I am stuck >.< . 
What should I do with the PR now. I committed two changes and both of them are vaguely written. Just guide me in this please.

**Comment by AbdealiJK** [comment]
@yash14123 sure ! Why dont you come on to https://gitter.im/coala-analyzer/coala so its easier to chat ?

**Comment by AbdealiJK** [comment]
Closed with https://github.com/coala-analyzer/coala/commit/11cdb46e3b4c267f061763bb12c8ceb7c6e21a4d
