### ISSUE TITLE
Remove .misc/deps.linux.sh

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1318]
`.misc/deps.linux.sh` needs to be removed. It just says "No dependencies to install for linux" and is not used anywhere.

its a file which was useful a while back when we planned on using travis for linux.

**Comment by sudheesh001** [comment]
I think this isn't a bug, The file is no more there and there are no traces of any `deps.linux.sh` in the code anywhere ?

**Comment by sils1297** [comment]
indeed

**Comment by AbdealiJK** [comment]
I must have been looking at an older version of the code by mistake

-----Original Message-----
