### ISSUE TITLE
setup.py : Ignore comments from requirements.txt

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1319]
In setup.py we are reading `requirements.txt` to get the list of requirements for coala. This doesnt consider comments. This is not good.

`# Do *not* use 0.3 which is not backwards compatible to common clang versions` is a comment which we have right now which is getting added to setup.py. Seems like setup.py is able to handle this without crashing, but it should be removed.

**Comment by sils1297** [comment]
well we know it doesn't make any difference as setup.py handles it the same as any line directly from the requirements so why put special handling in there?

**Comment by Makman2** [comment]
@sils1297 and me did this on purpose, since like said `setup()` handles that right.

**Comment by sils1297** [comment]
@AbdealiJK reopen if you disagree with this resolution
