### ISSUE TITLE
Add rust-clippy bear for rust support

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1324]
Rust clippy is one of the linters for `rustc` the Rust programming language.
https://github.com/Manishearth/rust-clippy#usage

It gives the linter warning in the following format
```rust
src/main.rs:8:5: 11:6 warning: you seem to be trying to use match for destructuring a single type. Consider using `if let`, #[warn(single_match)] on by default
src/main.rs:8     match x {
src/main.rs:9         Some(y) => println!("{:?}", y),
src/main.rs:10         _ => ()
src/main.rs:11     }
src/main.rs:8:5: 11:6 help: Try
if let Some(y) = x { println!("{:?}", y) }
```

**Comment by sils1297** [comment]
@sudheesh001 does it support another output

**Comment by AbdealiJK** [comment]
You may want to try `rustc` and `cargo` as Atom and Sublime already made that plugin and it'd be much easier to implement (as we have the regex) - https://github.com/AtomLinter/linter-rust and https://github.com/oschwald/SublimeLinter-contrib-rustc

http://atomlinter.github.io/ is a list of all available atom linters

**Comment by sudheesh001** [comment]
I think this can be parked for some time, `rust-clippy` works only on the nightly builds of `rustc`, Do we really want to download the binaries / compile rustc as a part of our build procedure to run this ? I've asked Manish, the repo owner for `rust-clippy` for a workaround to this.

**Comment by sils1297** [comment]
@sudheesh001 can you give a link to the upstream bug?

**Comment by sudheesh001** [comment]
@sils1297 Its not a bug, its in their documentation itself https://github.com/Manishearth/rust-clippy#usage for the nightly only support

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#50
