### ISSUE TITLE
Adding a package.json file to coala

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1328]
I think, like we have a requirements.txt file for `pip` we should have a `package.json` for `npm` also

`package.json` are easy to make and will make installing all out nodejs dependencies easy - just a `npm install` or `npm install -g`

This will make it easy for people to setup coala for development in their local computer also. It'd just be:
 - `pip install -r requirements.txt`
 - `npm install -g`
to get majority of bears working.

We can also make a `bundle` file later (but right now we do not have any ruby dependencies)

**Comment by yash14123** [comment]
So npm init , generate package.json and then add that to the code right?

**Comment by AbdealiJK** [comment]
@yash14123 - Once again, i suggest letting @sils1297 triaging these bugs and making sure its a feature we want.

You could check out the newcomer bugs on the issues page - https://github.com/coala-analyzer/coala/issues
[Here](https://github.com/coala-analyzer/coala/issues?q=is%3Aissue+is%3Aopen+label%3Adifficulty%2Fnewcomer) is a list of issues filtered by `difficulty/newcomer` label

In general, it's better to attempt solving bugs with a few labels as the ones without labels are still being considered - i.e. we're unsure whether that is something we want in coala or not.

You can also chat with us at https://gitter.im/coala-analyzer/coala

**Comment by Makman2** [comment]
I would go for it, so we easily integrate our npm dependencies. Not sure how far #1304 gets affected though...
