### ISSUE TITLE
GoVetBear - skip condition invalid

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1329]
I have ubuntu 14.04 and was trying to get all the tests in coala to work for me.
I noticed that GoVetBearTest kept failing and found out that in GoVet the skip condition is set to `go`.
This is not right because that isn't the correct thing to check. I had `go` installed but not `go vet`.

I had to install `golang-go.tools` to get the `vet` package in `go`.

**Comment by AbdealiJK** [comment]
The skip condition to be to check if `go help vet` returns 0 or not

**Comment by NalinG** [comment]
Hi, I would like to work on this issue.
I checked the GoVetBear.py file but is just called the self.lint method.
Do we have to change the lint method or I am missing something.

Thank You

**Comment by AbdealiJK** [comment]
The ship condition is in GoVetBearTest
The @SkipIf checks for go, not for go vet 

-----Original Message-----

**Comment by sils1297** [comment]
@NalinG please work only on one newcomer issue, we don't have a lot of them because they take a lot of work to create.

**Comment by NalinG** [comment]
Sorry for the trouble.
I will take care in the future.

**Comment by sils1297** [comment]
no problem

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#49
