### ISSUE TITLE
Typo in "invalid settings" error message

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1333]
In Interactions.py there is an error message like 
```
msg = ("During execution, we found that some required"
               "settings were not provided. They are:\n")
```

There is no space between "required" and "settings"

**Comment by yash14123** [comment]
@Makman2 if you feel this is important , assign me this too. :) 
Thanks.

**Comment by AbdealiJK** [comment]
Closed with https://github.com/coala-analyzer/coala/commit/e421d45f133f962a53998163418f998da6f3d75a
