### ISSUE TITLE
circleci: Install docs-requirements instead of sphinx

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1338]
In `deps.sh` we run `pip install -q sphinx`. This should be replaced with `pip install -q -r docs-requirements.txt`.

Right now, it doesn't matter much but later we may want to add more dependencies

**Comment by yash14123** [comment]
Fixing it . :)

**Comment by yash14123** [comment]
So I fixed #1338 and #1333 but they are added to the previous pull request only. 
I guess then the name of the PR would be same Remove docs/requirements.txt #1317 but will fix 3 issues. 
Is this the right way ?

**Comment by AbdealiJK** [comment]
You can fix multiple issues in the same PR - thats not a problem
Normally if you want to make multiple PRs separately you use different branches and make pull requests from these different branches

**Comment by yash14123** [comment]
Ok I will try that. 
Thanks. :)

**Comment by AbdealiJK** [comment]
Closed in https://github.com/coala-analyzer/coala/commit/47e0da8fd139bbcc8ff040e260a66bc25aeface7
