### ISSUE TITLE
PyTest cache results

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1339]
We may want to use https://pypi.python.org/pypi/pytest-cov-exclude/0.0.6 when pytest is implemented

Seems like it would allow us to run tests locally much faster.
But I do not know if it works if I just switch my git branch ?

Also, right now I get a ImportError when trying to install it and haven't tried to debug it yet. Keeping it here so that if someone is interested in making tests faster later can check it out.

PS : Pytest takes about 80 sec to run all our tests right now (on my laptop)

**Comment by sils1297** [comment]
@AbdealiJK wouldn't it be better to actually have a make like testing system that only execute tests if they have changed since last time? This seems to be only for the coverage?

**Comment by AbdealiJK** [comment]
@sils1297 I am not sure, but from what I read it isnt only for coverage.
It uses the coverage information to check which lines have already been tested and doesnt test them again until they've changed

Note: I may be mistaken, documentation is sparse

**Comment by sils1297** [comment]
Installed it. No further changes seem to be needed though we should activate coverage by default for this to work. We could even cache the cache in the CI and save time :P

Anyway when I use it I get a crash, bug is filed upstream at https://github.com/mhallin/cov-exclude-py/issues/1

**Comment by sils1297** [comment]
I have had this installed for a day now and its really annoying because it slows down the collection phase a lot. If you ust want to execute one test it'll be slower and currently I'm usually just using pytest with `-k WhateverIsInteresting` which is way faster

**Comment by sils1297** [comment]
so I'm not sure about this one

**Comment by AbdealiJK** [comment]
Just a note here - https://pytest.org/latest/cache.html is still possible

You can tel pytest to only run all your failed tests from the last run

**Comment by AbdealiJK** [comment]
https://pypi.python.org/pypi/pytest-testmon may be a solution too

**Comment by AbdealiJK** [comment]
Im closing this for now.
testmon can be used to cache tests (it just doesnt run tests it thinks shouldnt be run)

But I think that cacheing is not a good idea to keep as a default. Because new comers will get super confused.

Also, circleci cannot do this because the coverage for the skipped tests isnt calculated.

Hence, devs can use this locally if they like.
