### ISSUE TITLE
Change coafile to run coala on docs (rst files)

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1341]
We were using `.md` files for docs earlier, but now we use `.rst`

The coafile has not been changed to reflect this.

```
[DOCS]
bears = SpaceConsistencyBear

files = docs/**/*.md
default_actions = SpaceConsistencyBear: ApplyPatchAction
```

The `files` needs to be changed to `docs/**/*.rst`

**Comment by yash14123** [comment]
Please assign me this @AbdealiJK . I will be doing proper commits now.

**Comment by AbdealiJK** [comment]
@yash14123 I think you should be able to assign yourself to issues. There is an `Assignee` section on the right of this page.
