### ISSUE TITLE
README.rst: invalid rtfd urls

### ISSUE THREAD

**Issue by tushar-rishav** [coala-analyzer/coala#1350]
`Getting Involved Information` link under `Getting Involved` section of `README.rst` is pointing to invalid url. We should change the url to [http://coala.readthedocs.org/en/latest/](http://coala.readthedocs.org/en/latest/)

**Comment by WJCode** [comment]
Hi @tushar-rishav @scriptnull I think this link should actually be `http://coala.readthedocs.org/en/latest/Getting_Involved/README.html` as that is the Introduction page for Getting Involved.

Also, I noticed that the other links pointing to coala.rtfd.org in README.rst need this change. i.e in the link, simply replace the ending `/` with `.html`

**Comment by sils1297** [comment]
@WJCode I guess you're the best to review #1374 then :)

**Comment by WJCode** [comment]
@sils1297 :) I will do that

**Comment by AbdealiJK** [comment]
Note that even Installation, Tutorial, etc are all broken.
All the rtfd links seem broken
