### ISSUE TITLE
ConfigurationGathering: Uses mutable arg

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1352]
In `ConfigurationGathering` we have a mutable argument `sys.argv` for `gather_configuration()`

**Comment by sils1297** [comment]
@AbdealiJK proposed fix?

**Comment by AbdealiJK** [comment]
We put a `None` in the function header and do an If condition inside the function to replace it with the mutable value

```
def gather_configuration(acquire_settings, log_printer, arg_list=None):
    arg_list = sys.argv[1:] if arg_list == None else arg_list
```

**Comment by sils1297** [comment]
@AbdealiJK in that case rather do `arg_list = arg_list or sys.argv[1:]` as it's shorter

**Comment by AbdealiJK** [comment]
That is shorter, but it will use sys.argv for `[]`
Which is bad. because we pass "empty" args many times in tests
