### ISSUE TITLE
Use Tox

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1358]
@sils1297 You had mentioned this earlier. Do we want it ?

The only downside I can see is that if we use tox we will be constrained by the pyenv in circleci. i.e. we wont be able to run with betas and so on. I dont think tox accepts betas quickly either.

If we do not mind that, then we can use tox

**Comment by sils1297** [comment]
think it'd be good

**Comment by AbdealiJK** [comment]
Tox seems to be complicating the current CI scripts more than needed.
Setting as wontfix for now.

If you can find a good way to use tox - then patches accepted
