### ISSUE TITLE
coala_delete_orig : Typo, no space

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1359]
In coalib/coala_delete_orig.py, We are giving a INFO message about deleting files using the log_printer.
After "Deleting file ..." there is not space.

We need to add the space for better formatting

**Comment by iamshubh22** [comment]
@AbdealiJK I would fix this.

**Comment by sils1297** [comment]
@iamshubh22 you've got mail! : ) please accept that so we can assignyou

**Comment by sils1297** [comment]
@iamshubh22 also consider joining our channel at https://gitter.im/coala-analyzer/coala

**Comment by iamshubh22** [comment]
@sils1297 Done :smile:
