### ISSUE TITLE
InferBear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1364]
http://fbinfer.com/ - works on Objective-C, Java, or C code and seems to do quite some cool stuff. I'm not sure where we want to put it as it doesn't really belong in one of the language folders, maybe in the c_languages...

This is a simple wrapper if infer is done properly it should be simple to do.

**Comment by NalinG** [comment]
Hi, so we need to make a bear using infer to do stuff that infer does.
Please correct me if I am wrong

**Comment by AbdealiJK** [comment]
Nalin, thats exactly what needs to be done

**Comment by NalinG** [comment]
I would like to work on this bug, can you assign it to me.

**Comment by NalinG** [comment]
Is it better to discuss here or on the gitter channel ?

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#30
