### ISSUE TITLE
Tests: Do we need __main__

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1369]
In tests, we normally add 
```
if __name__ == '__main__':
    unittest.main(verbosity=2)
```

So we need this anymore ? Pytest doesnt need it ... and I rarely if ever run a test using `python3 path/to/test/_Test.py`.
Shall we remove it ?

**Comment by Makman2** [comment]
Yes these statements shall be removed, they where only needed from `unittest`.

**Comment by AbdealiJK** [comment]
Ok, then Ill make a `sed` patch to remove them
