### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#137]
Hi everyone,

this is about licensing, I know nobody likes that but it's a nice thing to have a say in how the program is used.

# What I want from you

@smfn3321 In order to change the license I legally need your and my permission to do that.
@smfn3321 , @cw1 I'd be very interested in what license you think is the best for our project and why. I wrote this whole text just for you :)
Anyones opinion is valued.

# Short Introduction to Free Licenses

If you consider free licenses, there are usually three main licenses to choose from:

* MIT License
* BSD License(s)
* GNU General Public License(s)

The main difference between the GPL(s) and the other two is the *copyleft*. They are two fundamentally different views on how to achieve the most free license.

## MIT-/X-Window-System-License

If one wants his code to reach the largest number of developers and derivates and one is not bothered by the use of his code in proprietary applications, this license might be the one. The basic message is along the lines of: "You can do with this code as you please". The License is GPL compatible, short, and easy to understand.

License: http://opensource.org/licenses/MIT

## BSD License family

See http://www.wikiwand.com/en/BSD_licenses

The BSD guys wrote a pretty small license because their goal is to not impose restrictions, which is an intuitive view on freedom. It is merely a no-warranty clause plus copyright-note-enforcement.
The BSD licenses suffer a bit from a naming confusion since an original 4-clause license existet that never got approved by the open source iniative board (osi-board). It got essentially deprecated because it forced to mention each and every organization or author that worked on a project which proved to be quite a hassle in bigger projects.

### 3-clause BSD

After dropping the problematic 4. clause, the 3-clause license offers only one real point of differentiation from the MIT License which is the (3rd) endorsement clause:

> Neither the name of the copyright holder nor the names of its contributors may be used to
> endorse or promote products derived from this software without specific prior written permission.

Without this clause, it is not clear whether or not somebody that receives the software has the right to use the Name and/or trademark of the license distributor. This clause removes any doubt.

License: http://opensource.org/licenses/BSD-3-Clause

### 2-clause BSD

This License got osi-approved in 2008 and is basically the 3-clause BSD license without the endorsement clause. It is roughly equivalent to the MIT License 

License: http://opensource.org/licenses/BSD-2-Clause

## GNU General Public License family

See http://www.wikiwand.com/en/GNU_General_Public_License

The big goal of the GPL license is to ensure at all cost that the user gets the four aspects of freedom with any GPLd program. These are:

* The freedom to run the program as you wish, for any purpose (freedom 0).
* The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). Access to the source code is a precondition for this.
* The freedom to redistribute copies so you can help your neighbor (freedom 2).
* The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

GPL is designed in a way that gives any user of a GPLd program these freedom. Furthermore it ensures that *any derivative work* also offers this freedom to the user. So basically in order to ensure freedom to the users, they impose restrictions on the developers. Note that a software under the GPL license is not necessarily free of charge! (RHEL is an example for that. If you buy RHEL binaries you can demand the source code for it *and* redistribute it for free if you want. Still the concept works because RHEL usually is much more than just the binaries.)

### GPLv2

The GPL v2, like nearly any licence, grants rights under certain provisos. These are briefly listed here. A licensee of GPL v2-licensed software can:
* copy and distribute the program’s unmodified source code (Section 1)
* modify the program’s source code and distribute the modified source (Section 2)
* distribute compiled versions of the program, both modified and unmodified (Section 3) provided that:
    * all distributed copies (modified or not) carry a copyright notice and exclusion of warranty (Section 1 and 2)
    * all modified copies are distributed under the GPL v2 (Section 2)
    * all compiled versions of the program are accompanied by the relevant source code, or a viable offer to make the relevant source code available (Section 3)

The aims of the FSF can be seen clearly in these grants and provisos. They allow anyone to use, copy, distribute, and modify the software under certain conditions. The intent of the provisos is perhaps less obvious. They are intended to protect the software’s author from various potential problems. For example, someone could use the software for some critical purpose, and then try to sue the author if it failed; for this reason the insistence on exclusion of warranties is essential. Someone could pretend the software was their own work if the licence did not insist upon a full inclusion of the original copyright information. Someone could take the program, modify it (or not) then purport to relicense it in a way that made it non-free; for this reason the licence insists that the program itself and all programs based on it must be made available under the GPL v2 if they are made available at all. The source to the program, and all modified versions, must also be made available; if not, the granted right to modify is impossible to exercise.

See http://oss-watch.ac.uk/resources/gpl

### GPLv3

The GPL v3 was finalised and published in 2007 and it is the Version the FSF recommends

Firstly, GPL v2 software had started to be distributed in encrypted forms, perhaps as the operating software of a hardware device. By doing this, the device manufacturers hoped to prevent end users from modifying that software and perhaps breaking the device. The GPL v2 did not seek to restrain this kind of distribution; provided the source code to the encrypted software was made available you were in compliance. However this could be seen as inhibiting the ability of the software’s recipients to modify and use the GPL v2 code they were receiving. Therefore the GPL v3 made it obligatory for anyone distributing software it covered to also distribute any additional information or keys necessary to modify it and run the modified copies.

Secondly, as a result of the growing use of the internet, many countries had introduced tougher laws to deal more stringently with the modification of software or data. Such modifications were often undertaken in order to copy the material in question, ‘cracking’ digital protection schemes. The new laws made circumventing such schemes an offence in itself, even if it did not also include an act of copying. For many in the free and open source software community this legislating against modification seemed a retrograde step. While the GPL v3 authors could not directly affect the enforcement of these laws, they could change their licence so that no such scheme implemented using GPL v3 software would be protected by it.

Thirdly, an important protection against software patent litigation had been partially circumvented in the GPL v2. Under GPL v2, if a distributor is made to pay a licence fee to distribute the GPL v2 code - for example because it has been found to embody someone else’s patent - then they must cease distributing altogether. This provision made suing over software patent infringement in GPL v2 software less appealing; you could stop its distribution, but not gain any ongoing fees through some kind of licensing deal with the distibutor. However this provision in the GPL v2 only covered the direct relationship between patent owner and distributor. Less direct deals - for example agreeing not to sue each other’s customers - were not prevented. Using deals like this, companies could create ‘favoured’ versions of GPL v2 software which effectively had lower risks of patent litigation for their customers. GPL v3 stipulates that any such ‘favours’ must be extended to the entire community, undermining their effectiveness as a tool to realise business advantage through threat of litigation.

Finally various small issues were fixed, including unintended incompatibilities with some other free and open source software licences, ambiguous legal language and clarification of responsibilities around source code distribution.

Of course, updating such a popular licence is not without problems. Simply because the new licence exists, it does not mean it will be used. For software that already declared itself to be under ‘GPL v2 or later’ (a form of words that the Free Software Foundation had been recommending for some time) a user could automatically choose to take the software under the new licence. For other software that was declared to be solely under the GPL v2, the licensors would have to explicitly distribute their code under the new licence for it to take effect. Many projects have converted in this way, but there have been some notable refusals. The Linux kernel, for example, the core element of the GNU/Linux operating system, remains under GPL v2 only. 

See: http://oss-watch.ac.uk/resources/gplv3

### LGPL

One should be aware of another GNU license: the Lesser General Public Licence (LGPL). It grants fewer rights to a work than the standard GPL. Generally, the LGPL is appropriate for libraries that want to allow linking from non-GPL and non-open-source software. Because the GPL requires that other software with parts of licensed code to also be licensed under the GPL, developers cannot use GPL-licensed code for paid and proprietary software. The LGPL negates this by not requiring other projects with parts of the code to be similarly licensed

### AGPL

The AGPL license differs from the other GNU licenses in that it was built for network software. You can distribute modified versions if you keep track of the changes and the date you made them. As per usual with GNU licenses, you must license derivatives under AGPL. It provides the same restrictions and freedoms as the GPLv3 but with an additional clause which makes it so that source code must be distributed along with web publication. Since web sites and services are never distributed in the traditional sense, the AGPL is the GPL of the web.

# Short summaries for all mentioned License:
MIT: https://tldrlegal.com/license/mit-license
3-clause BSD: https://tldrlegal.com/license/bsd-3-clause-license-%28revised%29
2-clause BSD: https://tldrlegal.com/license/bsd-2-clause-license-%28freebsd%29
GPLv2: https://tldrlegal.com/license/gnu-general-public-license-v2
GPLv3: https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29
LGPL: https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-%28lgpl-2.1%29
AGPL: https://tldrlegal.com/license/gnu-affero-general-public-license-v3-%28agpl-3.0%29

# Licensing in coala

coala currently runs under the GPLv3 license. I'm a fan of having it GPLd instead of BSDed because it prevents companies from using and extending the software without contributing their work back. (And IMO the world would be much better if companies would start to share code. Big companies slowly get that this is very efficient, from red hat via google to facebook)

## ASP hole in GPL
However GPLv3 has the so called ASP-hole (ASP=Application Service Provider). This means that someone could grab coala, modify it and provide it as a *SaaS*. This way the company doesn't have to share the used source code because no binary is distributed. In order to prevent this there is a GPL sublicense named Affero General Public License (AGPL, See http://www.wikiwand.com/en/Affero_General_Public_License). There is only one additional clause (no. 13) to enfoce suppliers of SaaS products to make their source code available to their users.

## My Proposal
Since coala is likely to be distributed as a Service I'm in favor of switching to the AGPLv3 version.

**Comment by sils1297** [comment]
Decision: we'll change to AGPL.

**Comment by smfn3321** [comment]
Ok, I officially agree;)

**Comment by sils1297** [comment]
thanks, me too, changing now.

**Comment by sils1297** [comment]
solved on #150
