### ISSUE TITLE
PyImportSortBear: Add max_line_length arg

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1380]
isort has a arg named `line_length` which is uses internally. We need to give it that.

**Comment by AbdealiJK** [comment]
Also, make the bear into a correctionbased bear
And add tab/use_spaces also.

**Comment by sils1297** [comment]
also adding lots of others

**Comment by AbdealiJK** [comment]
@sils1297 you can close https://github.com/coala-analyzer/coala/issues/1403 too

**Comment by sils1297** [comment]
No I'm leaving that open for now out of laziness.
