### ISSUE TITLE
RELEASE_NOTES.rst: fix incorrect links

### ISSUE THREAD

**Issue by WJCode** [coala-analyzer/coala#1383]
Some links were not converted correctly during our move to sphinx/RST documentation. These two links in `RELEASE_NOTES.rst` need to be updated as follows:

Current | Change to
--------------------------------------------------------------------------|----------------------------------------------------------
http://coala.readthedocs.org/en/latest/Users/Exit\_Codes/ | http://coala.readthedocs.org/en/latest/Users/Exit_Codes.html
http://coala.readthedocs.org/en/latest/Users/Glob\_Patterns/ | http://coala.readthedocs.org/en/latest/Users/Glob_Patterns.html

**Comment by sils1297** [comment]
@srisankethu is working on this

**Comment by sils1297** [comment]
Ok apparently @srisankethu is not longer working on this.

**Comment by srisankethu** [comment]
@sils1297 I am...I will do it right away

**Comment by sils1297** [comment]
@srisankethu please note that you can't work on more than two newcomer issues since we have a limited amount of them and a lot of people want to solve them.

**Comment by sils1297** [comment]
(i.e. working on two is fine but we won't give you a third one :))
