### ISSUE TITLE
docs: Mention `develop` command

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1390]
Mention the `python3 setup.py develop` command in our docs.

it essentially links your repository into the site-packages and so, if you make a change in the code, it is immesiately affected in site-packages. Making it look like it got immediately installed into the system

**Comment by srisankethu** [comment]
@AbdealiJK Where exactly do you want to add this?

**Comment by AbdealiJK** [comment]
@hypothesist is working on this - https://github.com/coala-analyzer/coala/pull/1392

@hypothesist any updates ?
