### ISSUE TITLE
ConfWriter ConfParser: Check delimiters better

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1393]
The ConfParser and ConfWriter doesnt check the delimiter properly.

We want to make sure that:
 
 - The delimiters are all strings
 - No 2 things have the same delimiter
 - No delimiter is a substring of another delimiter
 - Make sure that some delimiters are not absurd ... like `section_name_surroundings` being spaces
 - Make sure that none of the delimiters are backslashes.

**Comment by sils1297** [comment]
I think we could trust the user here to use the parser/writer responsibly

**Comment by AbdealiJK** [comment]
If so, then we can close it. I'm making these assumptions while fixing another bug - hence brought it up.
