### ISSUE TITLE
Links in Readme lead to non existing pages

### ISSUE THREAD

**Issue by sims1253** [coala-analyzer/coala#1395]
http://coala.readthedocs.org/en/latest/Users/Install/
Does not exist.

**Comment by AbdealiJK** [comment]
@sims1253 Hi !

Could you help me out with where you got that link from ?

The correct link is http://coala.readthedocs.org/en/latest/Users/Install.html

**Comment by sims1253** [comment]
https://github.com/coala-analyzer/coala
Under the Readme section.

**Comment by AbdealiJK** [comment]
Ah, you're right.
Even http://coala.readthedocs.org/en/latest/Users/Tutorial/ is a broken link in README. It sees as though all our rtfd links in README is broken

**Comment by AbdealiJK** [comment]
@sims1253 closing this as I just found https://github.com/coala-analyzer/coala/issues/1350 which already reports it. Hence closing as a duplicate.
