### ISSUE TITLE
Bear: Check for broken links

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1396]
Owing to the numerous broken links we have https://github.com/coala-analyzer/coala/issues/1383 https://github.com/coala-analyzer/coala/issues/1350 it would be really awesome if we could make a bear which tests whether a markdown or rst file has any broken links

We could simply use the URL regex which will be able to give us a lost of links. After which we simply test that each link gives a 200 HTTP code ?
We can skip this test if the bear is unable to find google (or some well known site) because they test runner may not have internet connection.

**Comment by sils1297** [comment]
heh, that's neat :) really neat!

**Comment by SanketDG** [comment]
Regarding sending the requests, will we stick to `urllib2` or use `requests`?

**Comment by AbdealiJK** [comment]
@SanketDG either would be fine IMO
As long as it works

**Comment by SanketDG** [comment]
I am planning to do the following:

First of all I am checking every line against a regex pattern to filter out the urls, along with the line numbers.

I am checking if the status code is not `20x`, then:

- If code is `40x` or `50x`, display the `The link is invalid. Returns <code>`
- If code is `30x`, display the diff with the updated redirect url.

Non-existent domain names (http://www.coalaisthebest.com) throw a `socket.gaierror` exception. How should I handle this? 

Right now the first thing that comes to my mind is to display the `e.reason` (where e is the exception) that has a good message on why the error was thrown.

**Comment by sils1297** [comment]
That sounds sane and awesome!

2016-02-13 8:32 GMT+01:00 Sanket Dasgupta <notifications@github.com>:

**Comment by AbdealiJK** [comment]
e.reason sounds good to me

-----Original Message-----

**Comment by AbdealiJK** [comment]
@Redridge mentioned on gitter -

> Guys, the link here https://github.com/coala-analyzer/coala/wiki/Getting-Started-to-Contribute is broken. It should be http://coala.readthedocs.org/en/latest/Users/Tutorial.html (with .html at the end)

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#29
