### ISSUE TITLE
StringProcessing.Core.escape: Use yield_once on escape_chars param in for loop

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1397]
Otherwise if there are double elements in escape_chars they'll get doubly escaped.

**Comment by Makman2** [comment]
Imo that's intended behaviour, if you provide a char twice, you get it escaped twice^^

**Comment by Makman2** [comment]
It's even (more or less) documented: `Duplicate chars are allowed.`

**Comment by sils1297** [comment]
ah ok
