### ISSUE TITLE
CSSCombBear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1398]
http://csscomb.com

**Comment by AbdealiJK** [comment]
We *could* write it to a temporary file, let csscomb fix that and read it back - but that's really really ugly.
i suggest we wait until https://github.com/csscomb/csscomb.js/issues/451 is done.

Blocked by https://github.com/csscomb/csscomb.js/issues/451

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#28
