### ISSUE TITLE
LocalBearTestHelper - better debug info

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1405]
If a test using the helper fails, we do not have proper debugging output. Very difficult to understand what caused the issue and even which test case caused the issue.

Needs work

**Comment by AbdealiJK** [comment]
Also, if a bear raised an Exception that comes out as an assertion error because the `local_bear` is None. That shouldnt happen, it should tell the error the Bear gave

**Comment by sils1297** [comment]
@AbdealiJK I'm assuming you're doing this as part of your work on that part of the code?

**Comment by AbdealiJK** [comment]
@sils1297 Ill assign myself when I begin working on the branch. Until then anyone else can build upon the branch if they wanna.

(I'm solving many issues parallelly, dont wanna block others from solving it if they want to)
