### ISSUE TITLE
PyTest use multile cores

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1407]
Use xdist with pytest to increase speed by using multiple cores.

http://pytest.org/latest/xdist.html

@sils1297 says it has bugs. Let fix them or find another plugin
The error he got was http://pastebin.com/pMKzDkTd

**Comment by sils1297** [comment]
this is what it does for me: http://pastebin.com/pMKzDkTd

**Comment by sils1297** [comment]
related upstream bug: https://github.com/pytest-dev/pytest/issues/1075
