### ISSUE TITLE
LanguageToolBear: skip test when java not found

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1409]
LanguageToolBear assumes java is installed. SKip test if not found

**Comment by sils1297** [comment]
@AbdealiJK the bear also needs `check_prerequisites` method, then the test skipping is merely a matter of using the skip test decorator for bears.

**Comment by AbdealiJK** [comment]
@iamshubh22 I am doing something in `LanguageToolBear` which is very similar - so, I'm taking over this issue. is that alright ? Or have you begun working on it ?

**Comment by iamshubh22** [comment]
@AbdealiJK Busy with exams these days. You can proceed :smile:
