### ISSUE TITLE
Remove checkstyle.jar

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1412]
We have a binary bears/java/checkstyle.jar that needs to be removed, we also want `.jar` in the gitignore.

**Comment by nishant-mor** [comment]
so we have to just delete this file and add *.jar to .gitignore ?

**Comment by sils1297** [comment]
@nishant-mor we'd appreciate it if you go on to solve difficulty/low issues as you're already on your third IIRC. Newcomer issues are more to show you the workflow and we don't have enough of them sadly.

But yes, this is just about deleting that file.

**Comment by nishant-mor** [comment]
ok lets leave it for the newcomer :smile:

**Comment by Makman2** [comment]
blocked by https://github.com/coala-analyzer/coala/issues/1465
