### ISSUE TITLE
Merge `coalib/tests/MakeTempTest.py` into `coalib/tests/misc/ContextManagersTest.py`

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1416]
There's already a test for the argument forwarding. The already existing `MakeTempTest.py` testcase shall be merged into it.

**Comment by souravsingh** [comment]
I would like to work on this issue

**Comment by sils1297** [comment]
@souravsingh cool, go ahead! :)

**Comment by Makman2** [comment]
@souravsingh still on it?

**Comment by souravsingh** [comment]
@Makman2 I am still on the issue.

**Comment by Makman2** [comment]
@souravsingh nice just wanted to check this one doesn't get stale :+1:

**Comment by souravsingh** [comment]
@Makman2 I have a doubt. Do we simply move the tests to ``ContextManagersTest.py`` or we have to add something else?

**Comment by Makman2** [comment]
just moving them :+1:

**Comment by srisankethu** [comment]
@souravsingh are u still on this ?

**Comment by souravsingh** [comment]
@srisankethu I am working on this. Will make a PR soonish

**Comment by Adrianzatreanu** [comment]
You still working on that PR? @souravsingh
