### ISSUE TITLE
patch: support explicit file renaming

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1419]

**Comment by AbdealiJK** [comment]
Could you elaborate?

**Comment by sils1297** [comment]
@AbdealiJK so right now people could make two diffs, one emptying the file, the other one filling the file - and I bet coala would crash or do it wrong because you can't apply a diff to no file.

We want users to be able to create/rename/delete files with our Diff class or rather the diff dict appended to the result

**Comment by sils1297** [comment]
maybe we could give the `Diff` class some flags

**Comment by arush0311** [comment]
Can I work on this?

**Comment by AbdealiJK** [comment]
@arush0311 assigned you

**Comment by arush0311** [comment]
> aa

**Comment by arush0311** [comment]
> We want users to be able to create/rename/delete files with our Diff class or rather the diff dict appended to the result

Can you explain?

**Comment by Makman2** [comment]
Currently the only way we support renaming (and deleting etc) is via having a diff that deletes all lines in file A and append them again in file B. We want to have a simple flag or else that contains information like `renamed A to B`, so the user doesn't get the whole diff displayed which can be sometimes very huge.

**Comment by arush0311** [comment]
Can you tell me where these renaming (and deleting) functionalities are incorporated?

**Comment by Makman2** [comment]
That's it, there aren't any. That's what this issue is about: creating those :3

**Comment by arush0311** [comment]
There can be line changes accompanying the rename also ?

**Comment by arush0311** [comment]
And right now the modified and original properties return a list of lines. Should it be changed to a tuple containing (<rename string>,<deleted flag>,<list of lines>)?

**Comment by arush0311** [comment]
And right now the modified and original properties return a list of lines. Should it be changed to a tuple containing (<rename string>,<deleted flag>,<list of lines>).

**Comment by arush0311** [comment]
And right now the modified and original properties return a list of lines. Should it be changed to a tuple containing ([rename string],[deleted flag],[list of lines]).

**Comment by Makman2** [comment]
I don't know maybe create a new property like `renamed`. This issue is at least `difficulty/medium`, so you have to come up with something :)

**Comment by AbdealiJK** [comment]
Wasnt this nearly done ?
@arush0311 still working on this ? Need any help ?

**Comment by Makman2** [comment]
@arush0311 ping

**Comment by sils1297** [comment]
Maybe somebody can pick this up so the code doesn't get out of date?
