### ISSUE TITLE
Auto-apply message should be slightly modified

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1425]
`[INFO][22:04:26] Applied 'ApplyPatchAction' from 'bears/c_languages/codeclone_detection/CloneDetectionRoutines.py' for 'PyImportSortBear'.`

"to apply sth. on sth.", so it should be

`[INFO][22:04:26] Applied 'ApplyPatchAction' on 'bears/c_languages/codeclone_detection/CloneDetectionRoutines.py' from 'PyImportSortBear'.`

**Comment by nishant-mor** [comment]
https://github.com/coala-analyzer/coala/blob/15d3707beb37271de9728b4deadc4ad6094706c5/coalib/processes/Processing.py#L146

So we need to change :   log_printer.info("Applied {} from {} for {}.".format
to    log_printer.info("Applied {} on {} from {}.".format
?

**Comment by sils1297** [comment]
yeah sounds sane

**Comment by nishant-mor** [comment]
So can i work on it ?

**Comment by sils1297** [comment]
@nishant-mor you have been invited to the team, when you accept I can assign you :)

**Comment by nishant-mor** [comment]
from where to accept the invitation?

**Comment by sils1297** [comment]
You should have an email, otherwise github.com/coala-analyzer I think

**Comment by nishant-mor** [comment]
got it
