### ISSUE TITLE
Lint.py: Use Shell-module functions instead of Popen

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1428]
`coalib/bearlib/abstractions/Lint.py` contains code that can be replaced with an already implemented function inside `Lint.lint()`.
Replace the `Popen` and stdin stuff with `coalib.misc.Shell.run_shell_command`, since the functionality is more or less duplicated here. Also `run_shell_command` takes care of buffer-flushing-deadlocks.

**Comment by sils1297** [comment]
@Makman2 I don't see how we can get stdout and stderr separately with this one.

**Comment by AbdealiJK** [comment]
@Makman2 also that uses PIPEs. I'd rather not use PIPE incase we have to parse large files (Pipes hang if they get too much information - We ad an old `run_tests` bug about this.

^ For example if we parse .sql files or log files

**Comment by sils1297** [comment]
ideally that function should handle the pipe problem

2016-02-12 3:21 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by Makman2** [comment]
@AbdealiJK that's what `run_shell_command` is for, it uses `communicate()` on the underlying stream that doesn't hang on large data.
@sils1297 this function returns a tuple, `(stdoutstring, stderrstring)` :)

**Comment by Makman2** [comment]
@AbdealiJK nvm, I think I've misread something inside the module^^

**Comment by Makman2** [comment]
alright then maybe add some parameters to `run_interactive_shell_command` that also let's you specify output streams.

**Comment by AbdealiJK** [comment]
@Makman2 are you sue `.communicate()` won't hang ?

**Comment by AbdealiJK** [comment]
Well, either way - Im using it.
The docs cays it buffers all the streams in memory - so it should be limited by memory size, not the pipe.
If it hangs we'll open an issue on `run_interactive_shell_command` later.
