### ISSUE TITLE
Bear to check for merge conflicts

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1432]
Currently when I have an unresolved merge conflict, AutoPep8 tries to format it.

We should ideally be searching for `<<<<< HEAD` followed by `>>>> sha` or so to show an issue like

"Merge conflict found"

**Comment by Makman2** [comment]
You sure? If you have a merge conflict git is responsible for this and normally displays it for you quite clearly. It's more of a workflow problem, not a "static" code problem. Imo this is not in our scope^^

**Comment by sils1297** [comment]
Agree with mischa
