### ISSUE TITLE
python setup.py test throws VersionConflict(dist, req) errors

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1436]
If there are already packages installed in the virtualenv or the system requirements, any changes in the version stop the test run and raise a VersionConflict error.

Expected behaviour: it runs pip upgrade of that particular requirement.

**Comment by sils1297** [comment]
Any idea on how that can be fixed?

**Comment by Makman2** [comment]
problem is what when it automatically downgrades? At least it should ask the user^^

**Comment by AbdealiJK** [comment]
This should be fixed by the better requirements managing right ?
The reason the VersionConflict happens is because setuptools checks the dependencies in `setup.py test`

**Comment by sils1297** [comment]
so is this fixed? Requirements management is better now after all

**Comment by AbdealiJK** [comment]
If the virtualenv has let's sat setuptools v18.0 and we need >=19.0 I think the error will still be there.
But overall it should occur less frequently and only if we *cannot* use that version.

**Comment by sils1297** [comment]
and we have a way better error message now, can we close?

**Comment by AbdealiJK** [comment]
Closing this.
If others have a different opinion, please reopen
