### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1442]
It'd be nice to have a contributing.md which educates the people about:

1. Our commit message style.
2. Maybe how they can later rebase stuff?
3. Everything else you need to know to get your PR approved.

**Comment by srisankethu** [comment]
@sils1297 Can you assign me to this because it would be a challenge to me (I haven't got any  of my PR accepted yet"

**Comment by sils1297** [comment]
@srisankethu lets first get your other PR merged. In order to get your PR accepted you can't just keep working on new issues and give up on old ones, you need to listen to what we propose to you and how you can fix things. No PR will be accepted at the first submission. Not yours not mine, not the ones of other contributors. Otherwise coala would be reaaaaally buggy.
