### ISSUE TITLE
Full coverage for all main routines

### ISSUE THREAD

**Issue by tushar-rishav** [coala-analyzer/coala#1444]
Let's have maximum coverage for  `coala_format.py` ,  `coala.py`, `coala_delete_orig.py` and  `coala_main.py`.

**Comment by sils1297** [comment]
@tushar-rishav three points for indiahacks assuming you fix it for all of them

**Comment by tushar-rishav** [comment]
@sils1297  Yeah? I never expected for that. Thanks :stuck_out_tongue:
