### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1449]
What about some linters that work on `LaTeX`? :D

(on first googling I've found `ChkTeX` and `lacheck`)

**Comment by sils1297** [comment]
yes please! Can look up if something is simpler than the other and file a bug for that with difficulty low? That's usually a good task for arising newcomers.

**Comment by AbdealiJK** [comment]
`chktex` seems to be the easier one - https://github.com/nscaife/linter-chktex/blob/master/lib/linter-chktex.coffee

**Comment by sils1297** [comment]
Yeah that coffee file also already contains a regex so this can easily be turned into a bear.

**Comment by nishant-mor** [comment]
rawRegex ?

**Comment by sils1297** [comment]
Yes. Just look at CSSLintBear how it's done in coala.

**Comment by nishant-mor** [comment]
ok
