### ISSUE TITLE
checkstyle.jar: Download it as requirement-install-step

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1465]
I would propose for a clean requirement-install-handling to populate `./setup.py` with two new commands, e.g. `install-test-requirements` and `install-requirements`. These two commands shall do the pip install via `pip3 install -r requirements.txt` (or `test-requirements.txt`) and also allows to handle custom install steps like the checkstyle.jar download.

This also needs adaption inside the docs and CI-scripts!

**Comment by AbdealiJK** [comment]
I think the better way to do it would be to add a install-requirements form each bear and let each bear handle it individually

Something like `check_prerequisites` we add a `install_prerequisites`.
Here the bear can do whatever it wants.
We can also add helper functions to run `pip`, `npm`, `gem` commands to make it easier.

This would also help in https://github.com/coala-analyzer/coala/issues/1304

**Comment by Makman2** [comment]
Not a bad idea^^

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#47
