### ISSUE TITLE
case insensitive bear glob matching

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1477]
area/CLI
difficulty/medium

**Comment by Makman2** [comment]
do we want that?

**Comment by sils1297** [comment]
I think we did but I still want it :P

**Comment by Makman2** [comment]
I'm against case insensitivity, less work for us and being strict with name case is programming-language like^^

**Comment by sils1297** [comment]
@fneu says it's not hard to make a case insensitive matching with globbing... though with the new warnings things aren't as bad indeed. Okokok...
