### ISSUE TITLE
HTML Bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1478]
We desperately need a bear to lint HTML code since coala is especially interesting for web based projects. Anybody any idea on what HTML linters are out there and easy to integrate? If that's there then this should be difficulty/low .

**Comment by sudheesh001** [comment]
There's one linter
- https://www.npmjs.com/package/htmllint
- https://github.com/mozilla/html5-lint
- https://github.com/deezer/html-linter

**Comment by sils1297** [comment]
The mozilla one uses a webservice, I'm against that but the others look fine.

**Comment by Redridge** [comment]
Is anyone working on this? Could I get assigned?

**Comment by sils1297** [comment]
@Redridge I'd recommend using the deezer html linter as it seems to have python bindings/be written in pythin.
