### ISSUE TITLE
Puppet Bear for linting puppet files

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1480]
bears/configfiles
difficulty/low

https://github.com/rodjek/puppet-lint

**Comment by sudheesh001** [comment]
@gitmate-bot assign @sudheesh001

**Comment by sils1297** [comment]
nope, doesn't work that, though in the future gitmate will analyse statistics and auto assign people if they worked a lot on issues with similar labels :)

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#46
