### ISSUE TITLE
Julia bear integration

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1482]
Julia is a high-level, high-performance dynamic programming language for technical computing, with syntax that is familiar to users of other technical computing environments.

It looks like there's a linter available here https://github.com/tonyhffong/Lint.jl

**Comment by AbdealiJK** [comment]
@niraj8 are you still working on this ?

**Comment by niraj8** [comment]
@AbdealiJK I have read the docs for writing a Bear and gone through other Bears in the repo, but I haven't written any code yet. I'll work on it today.

**Comment by nishant-mor** [comment]
@niraj8 are you working on this , if not can i ?

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#23
