### ISSUE TITLE
Linter: Strip whitespace from values

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1485]
Lint should strip whitespace away when creating the results in line 191 ff.

difficulty/newcomer

**Comment by kpraveenkumar** [comment]
Could you please suggest, how to recreate the scenario..

**Comment by sils1297** [comment]
I'm not fully sure, I think CPPLintBear sometimes yields results with trailing spaces in the message. Anyway this is more a general thing not addressing this particular bug but just simplifying bear development as the writers of regexes for lint bears don't have to care about trailing/leading whitespaces.

**Comment by Makman2** [comment]
`Lint` is deprecated, hereby maintenance of it is stopped :)

**Comment by Makman2** [comment]
But Linter doesn't have it currently
