### ISSUE TITLE
rultor: rebase

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1486]
It'd be nice if we had a command for rultor to rebase.

`@rultor rebase` maybe which just runs a `git rebase mater` and pushes it to github.
It doesn't do anything else. 
 - If the rebase fails, rultor says it failed
 - If the rebase was successful, tests will run on it again and if they pass `@rultor merge` can be done

^ Would be helpful with the numerous newcomer issues which do not normally get merge conflicts

**Comment by sils1297** [comment]
Rultor maintainers aren't willing to add that.

**Comment by AbdealiJK** [comment]
cant we do it ourselves ?

**Comment by sils1297** [comment]
not in rultor, I want it in gitmate though. If you want it there's some
issues on IGitt to be resolved first (GitHub api paging :/), then I can
include it and then we could have it in one or two weeks?

2016-02-15 10:24 GMT+01:00 AbdealiJK <notifications@github.com>:
