### ISSUE TITLE
Change `not a is None` to `a is not None`

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1494]
Needs to be done throughout the code
There exist a few of these in `Tagging.py`

**Comment by madminions** [comment]
I want to work on this issue. Please accept merge request.

**Comment by sils1297** [comment]
Hi, apparently @707 is working on this issue (though he hasn't accepted the invitation to our org yet...)

@madminions could you work on another issue for the time being? I've sent you an invitation so we can assign you, if you express interest in some issue you'll get assigned so it's guaranteed that nobody else works on the same.

**Comment by madminions** [comment]
Ok. Thanks.

**Comment by Makman2** [comment]
Be careful, in fact `not a is None` is not the same as `a is not None`, but I think too this should work in all our cases since we don't override `__neg__` anywhere (or use classes that provide special negation behaviour).
