### ISSUE TITLE
Collectors function needs return annotation

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1495]
collect_all_bears_from_sections() needs a return annotation

**Comment by arush0311** [comment]
Can I work on this?

**Comment by sils1297** [comment]
@arush0311 please understand that our newcomer bugs are limited so please don't solve more than two!

**Comment by arush0311** [comment]
No Problem. Just wanted to dive into codebase

**Comment by arush0311** [comment]
Can you tell me where I can find this?

**Comment by Makman2** [comment]
`coalib/collecting/Collectors.py`
You can use `git grep` or the search inside GitHub if you want to find stuff.
