### ISSUE TITLE
docs: use doctests

### ISSUE THREAD

**Issue by Redridge** [coala-analyzer/coala#1498]
In order for the docs to be correct, the code that the docs contain must be correct.
For that matter the docs should be all doctest stable. [doctest](https://pytest.org/latest/doctest.html)
Rewrite/Imporve the docs such that they use doctest

difficulty/low

**Comment by AbdealiJK** [comment]
I just went through the documentation. I'm unable to find any specific place where we can use doctests where it's not being used.
Could you give examples ? We mainly have shell commands in the doctests which `py.test` cannot run.

Our docs majorly talk about creating bears or Linters and stuff - and we cannot exactly run these without running a shell command like `coala ...`. Importing stull and running it using `coala_main` would just make things more complicated for the person reading the tutorial.

**Comment by Redridge** [comment]
If there is no place to run doctest then I think we can close this. I originally wrote it guided by @sils1297

**Comment by sils1297** [comment]
I'm not sure what I was thinking but *I think* that I was thinking that we could migrate some existing tests into neat documentation examples which would do our docs good.

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#57
