### ISSUE TITLE
Use golang dependency manager to go get the dependencies

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1501]
Similar to how we have `requirements.txt` for `pip` and `package.json` for `npm` we can also have a file holding the dependencies for golang

**Comment by sils1297** [comment]
Thought about that too, is there already a file format designed for that?

**Comment by sudheesh001** [comment]
I think `godep` takes a `json` in a specified format, i'll fix this once #1499 lands into master

**Comment by sils1297** [comment]
#1499 has landed :)

**Comment by AbdealiJK** [comment]
not fixed yet :( Goopfile didnt work as expected in circleci

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#43
