### ISSUE TITLE
coala_delete_orig: Modify message

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1514]
Modify message about `Couldn't delete... <filename>`

@sils1297 please suggest a better message.

**Comment by sils1297** [comment]
remove the `...` for a start...

**Comment by Makman2** [comment]
why the current message is bad? It says file `<filename>` couldn't be deleted :O

**Comment by sils1297** [comment]
the ellipsis is there for no reason at all

**Comment by Makman2** [comment]
ah I thought that's where the filename comes :O
Yeah just deleting the `...` suffices

**Comment by yland** [comment]
Please, I would like to work on  this issue. I guess this would also include changes to the coalaDeleteOrigTest.py, which also contains the following lines

self.assertIn("Couldn't delete... file1", output)
self.assertIn("Couldn't delete... file2", output)

**Comment by sils1297** [comment]
Hey @yland  I've invited you into our org, accept at github.com/coala-analyzer please so we can assign you.

**Comment by sils1297** [comment]
Yes, test changes should be included in the very same commit.

**Comment by sils1297** [comment]
Cool, seeing forward to a PR, ping us at https://gitter.im/coala-analyzer/coala if you need anyu assistance.
