### ISSUE TITLE
Cleanup GoReturnsBearTest by removing unnecessary information

### ISSUE THREAD

**Issue by sudheesh001** [coala-analyzer/coala#1516]
the GoReturnsBearTest contains the following which needs to be removed
```python
a = ['import "errors"', '',
     'func F() (*MyType, int, error) { return nil, 0, errors.New("foo") }']
b = ['package main', '', 'import "os"', '',
     'func main() {', '\tf, _ := os.Open("foo")', '}']
```
Put the good_files in the same line like the bad_files
```py
(good_file1,
     good_file2,),
    (bad_file1, bad_file2,))
```

Also correct GoReturnsBear's `run()` documentation to show `using goreturns` instead of `using gofmt`

difficulty/newcomer

**Comment by satyamamrev** [comment]
I want to contribute to this

**Comment by sudheesh001** [comment]
@satyamamrev You could get started with http://coala.readthedocs.org/en/latest/Users/Install.html#installing-coala-from-source

Here are the contribution guidelines http://coala.readthedocs.org/en/latest/Getting_Involved/README.html

**Comment by AbdealiJK** [comment]
@satyamamrev is doing this in https://github.com/coala-analyzer/coala/pull/1533

@sils1297 he needs to be added to the org

**Comment by sils1297** [comment]
Invitation pending to satyamamrev and hypothesist

2016-02-21 12:22 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#44
