### ISSUE TITLE
Usability: Throw error/warning if file globbing doesn't match

### ISSUE THREAD

**Issue by Redridge** [coala-analyzer/coala#1520]
Right now if you pass a wrong path to a file with --files, it won't work but you will not know it.
coala should throw some kind of error/warning when this happens

**Comment by sils1297** [comment]
@AbdealiJK did the same for the bear globs, he'll probably be the right one for this one too.

**Comment by AbdealiJK** [comment]
Question here - do we check which paths gave no files after doing `remove`, and `limit_paths` or before ?

**Comment by sils1297** [comment]
I think we should do it after applying the ignore stuff but before limit paths.
