### ISSUE TITLE
Choose bear kinds to run

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1523]
It would be good if we had a cmdline arg to run coala only in global or only in local mode.

This would be helpful for example if I want to just run coala on a few files that have changed (in Makefile or in a git pre-commit).

Here, we can tell coala to run LocalBears only on the modified files (using `--limit-files`) and GlobalBears on everything.

**Comment by sils1297** [comment]
I'm not fully bought on this, can't we just keep it like this? Run all bears on the limited files will probably give a decent set of results?

**Comment by AbdealiJK** [comment]
Yes ... but that's not the right results.
Could either support it OR not support it and just run coala on everything too.
Im against running global bears on limited paths

**Comment by Makman2** [comment]
Thats more a caching Problem, isnt it? Since global and local bears are more or less thrading models that shall squeeze out performance it doesnt make sense letting the user control such core behaviour.
Btw i dont know what you mean with limited paths^^

**Comment by AbdealiJK** [comment]
So, when Im making a git pre-commit - I can find all the files that have changed in the last commit.

Here, I'd ideally want to run Local Bears only on these files and Global Bears on all files.

The limited paths are the paths to the files that got changed (from git).

**Comment by sils1297** [comment]
fwiw the new bear design will make this more complicated since we'll remove the local/global bear distinction

**Comment by AbdealiJK** [comment]
I know ... the ideal method of doing this is implementing good cache in coala itself

**Comment by Makman2** [comment]
@sils1297 I don't think it would be too complicated in the new-bear design. In fact you just pass the bears less files to process :)

**Comment by sils1297** [comment]
no he wants to exclude those bears that work globally. I'm not bought on
that.

2016-02-16 18:32 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
that doesn't make sense :O if you have a bear set in the coafile you want to get it executed. If you don't want global bears just create a new section without :O

**Comment by AbdealiJK** [comment]
Closing this, I think that a better cache system would be a better solution myself.
Also, the git hook isnt being used atm. So, if in future someone wants it - this can be reopened

**Comment by Makman2** [comment]
Since I still dont understand what you actually wanted, can I mark this issue  with wontfix/not happening? If someone thinks the same like you imo we should open a new issue where we clearly define whats wanted :)

**Comment by sils1297** [comment]
Just mark it as such
