### ISSUE TITLE
Bear for R

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1534]
We can use lintr - https://github.com/jimhester/lintr

**Comment by nishant-mor** [comment]
But it is not available on apt-get or npm.

**Comment by AbdealiJK** [comment]
Where is it available then ?

**Comment by AbdealiJK** [comment]
lintr seems to be in cran - https://cran.r-project.org/web/packages/lintr/README.html

**Comment by nishant-mor** [comment]
@AbdealiJK 
It is written in R and needs to be installed inside R as a package. there is no executable which can be put into bear.
Any other method to execute this ?

**Comment by AbdealiJK** [comment]
@nishant-mor Im nor sure.

 - you can run the R terminal and run it maybe ?
 - or you could find another linter (I couldnt find any other surprisingly)

You may want to check `SublimeLinter-contrib-R` and see what theyve done

**Comment by nishant-mor** [comment]
https://github.com/AtomLinter/linter-lintr   => Atom package , can this be used ?

**Comment by AbdealiJK** [comment]
@nishant-mor thats a plugin for an editor - it uses `lintr` internally.
It won't be of much use

Although, you could read and check how they use `lintr` to get results (to display in atom)

**Comment by AbdealiJK** [comment]
Hey, that PR has been pushed now.
You can do ` -e 'library("lintr")' -e 'lint("{filename}")'` as arguments now

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#41
