### ISSUE TITLE
Fix typos in docs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1535]
In the docs `THis` is written instead of `This` in Git_Hooks.rst

Should be changed

**Comment by madminions** [comment]
Assign me this issue.

**Comment by sils1297** [comment]
Hi, FYI after this we'd love you to go on to difficulty/low issues as we only have a limited number of newcomer issues.

**Comment by madminions** [comment]
Sure.

**Comment by madminions** [comment]
There is no file named Git_Hooks.rst in docs.

**Comment by sils1297** [comment]
oh it will be there soon... when we merge a PR from @AbdealiJK , we sometimes file bugs ahead of time. Sorry for this. :/ If you want you can take another bug in the meantime?

**Comment by gmdsam** [comment]
Can I do this?

**Comment by sils1297** [comment]
@gmdsam @madminions is assigned to this issue. @madminions this is not longer blocked by the way. Sorry, forgot to notify.

**Comment by sils1297** [comment]
@gmdsam we made plenty of other newcomer issues :)
