### ISSUE TITLE
bug: coala random crash

### ISSUE THREAD

**Issue by Redridge** [coala-analyzer/coala#1540]
Steps to reproduce

1. Use the file I provide below
2. Run coala on it with SpaceConsistencyBear and PEP8Bear like so

```
coala --files=src/test.py --bears=SpaceConsistencyBear,PEP8Bear
```

Here is the file

```
from bears.tests.LocalBearTestHelper import verify_local_bear
from bears.go.GoReturnsBear import GoReturnsBear

good_file1 = """import "errors"

func F() (*MyType, int, error) { return nil, 0, errors.New("foo") }"""\
.split('\n')

good_file2 = """package main

import "os"

func main() {
\tf, _ := os.Open("foo")
}""".split('\n')

bad_file1 = """
func F() (*MyType, int, error) { return errors.New("foo") }
""".split('\n')

bad_file2 = """
package main

func main() {
    f, _ := os.Open("foo")
    return nil, 0, errors.New("foo")
}

""".split('\n')



GoReturnsBearTest = verify_local_bear(
    GoReturnsBear,
    (good_file1,good_file2,),
    (bad_file1, bad_file2,))
```

**Comment by sils1297** [comment]
@Redridge uhm when I run that in a tmp folder I get asked for `use_spaces` and either way (true or false) it doesn't fail. I suppose you have a coafile there?

**Comment by sils1297** [comment]
@Redridge so it would be important if you could come up with a *minimal* reproducable example. I.e. you give us one command and one file and if we run that in a clean dir it should reproduce your problem.

**Comment by sils1297** [comment]
Assigning you as we need info from you.

**Comment by Redridge** [comment]
I cannot reproduce the bug anymore ?! Maybe it was something system specific to me I guess. 
Yesterday I reproduced it a couple of times but now I can't. There is nothing a restart can't fix ;)

Closing this
