### ISSUE TITLE
Replace `x or default` with a function doing this properly

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1544]
Last time I recognized that statements like `x or default` could fail when the object `x` overrides `__neg__()`. We should use a function, like
```python
def default_if_none(obj, default):
    return default if obj is None else obj
```

**Comment by sudoankit** [comment]
Can I work on it? 
Guide me into the codebase, I'm new here.

**Comment by sils1297** [comment]
you have to accept the org invitation

**Comment by Makman2** [comment]
@/all though I would clarify beforehand if we want this, i've just seen that the short `x or y` version is in fact not the cleanest way, I should've added the tag "needs-info". Maybe we don't want a function but we just write/inline everywhere `default if x is None else x`?

**Comment by SanketDG** [comment]
yes using a function for this seems overkill. We should just use inline statements.

**Comment by sils1297** [comment]
I'm totally against this! The or/and syntax is native and works well we don't want to import a function for something as simple as that.

**Comment by Makman2** [comment]
@sils1297 in fact the `or` syntax we use is wrong in most places, since we want to check for `None`. Using `x or default` is not the same as `default if x is None else x`.

**Comment by sils1297** [comment]
Then we should use the latter expression

**Comment by Makman2** [comment]
okay so we want to inline `default if x is None else x` everywhere :+1:

**Comment by NalinG** [comment]
Hi, I would like to work on this issue , please assign it to me

**Comment by NalinG** [comment]
Can you kind of give me a starting point because I dont think I will have to skim through the whole code to find these instances to replace..

**Comment by sils1297** [comment]
use `git grep`

**Comment by Makman2** [comment]
Just for interest, performed a benchmark:
```
>>> def oring(a):
...  return [x or 55 for x in a]
...
>>> def ifing(a):
...  return [55 if x is None else x for x in a]
... 
>>> from functools import partial
>>> tor=Timer(partial(oring, range(1000)))
>>> tif=Timer(partial(ifing, range(1000)))
>>> tor.timeit(100000)
5.12427900900002
>>> tif.timeit(100000)
5.831657146999532
>>> tor.timeit(100000)
5.060573998999644
>>> tif.timeit(100000)
5.857475004999287
>>> tor.timeit(100000)
5.056929654999294
>>> tif.timeit(100000)
5.8778584510000655
```
`x or default` vs. `default if x is None else x`
`5.06s` vs. `5.83s`
slight performance impact (about 15-20%), but I assume this is due to the fact that the written out if-form runs in python byte-code, while short-circuitance is a core-feature implemented in C^^

**Comment by abhiroyg** [comment]
Hi, Can I work on this ?

**Comment by sils1297** [comment]
@Makman2 is this well specified enough so @abhiroyg can work on it?

**Comment by Makman2** [comment]
I think it is :+1:
