### ISSUE TITLE
Change from dummy -> _

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1548]
We have a few variables named as `dummy`. Find them all in the project and use `_` instead

**Comment by pavithirakc** [comment]
I would like to work upon this issue.

**Comment by sils1297** [comment]
@pavithirakc I've invited you to our org so we can assign you to bugs!

**Comment by sils1297** [comment]
@pavithirakc please accept that invitation

**Comment by sils1297** [comment]
Assigning @ravinimmi since he's already started working on this, feel free to ping me about another issue
