### ISSUE TITLE
Convert CONTRIBUTING.md to a rst file

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1549]
https://github.com/evonove/django-oauth-toolkit/blob/master/CONTRIBUTING.rst - contributing.rst is an accepted file in github

Need to convert our current markdown file to rst.

Also, when this is done - `coafile` 's [DOCS] section needs to be modified to reflect the new filename

**Comment by arush0311** [comment]
Can I take it if its still open?

**Comment by sils1297** [comment]
@arush0311 @pavithirakc seems to be actively working on this, rather take up something else please!

**Comment by AbdealiJK** [comment]
@pavithirakc Are you still working on this ? It's been nearly 2 weeks. Do you need help with something ?

**Comment by Adrianzatreanu** [comment]
unassigned due to inactivity.

**Comment by msfernandes** [comment]
I'm interested to do this issue :)

**Comment by sils1297** [comment]
@msfernandes you might wanna use pandoc
