### ISSUE TITLE
Lint documentation comment: Link to lint bear tutorial

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1551]
you can find the tutorial on docs.coala-analyzer.org

difficulty/newcomer

**Comment by aayn** [comment]
@sils1297  What exactly is this?

**Comment by sils1297** [comment]
there's a class in Lint.py and it's related to http://coala.readthedocs.org/en/latest/Users/Tutorials/Linter_Bears.html so we want to have a link to that tutorial in a documentation comment there

**Comment by aayn** [comment]
Okay. I'll do this. Assign it to me please.
