### ISSUE TITLE
Lint - arguments

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1553]
Lint has `arguments` which is a class variable. This needs to be removed and made into an arg for `lint()` as otherwise the values in this variables are reused next time.

**Comment by AbdealiJK** [comment]
Blocking this until https://github.com/coala-analyzer/coala/pull/1609 gets merged as we may have to revamp how it works based on that

**Comment by AbdealiJK** [comment]
@Makman2 I notice the bash injection is done. You use `shlex.split` ... so, can we continue using the `.format()` function in Lint ?

**Comment by Makman2** [comment]
Superseded by #1928 and #1990 .
