### ISSUE TITLE
LineLengthBear - Search anywhere in the line

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1554]
Currently if I give "https" as a ignore regex, it works only if "https" is in the beginning of the line.
This shouldn't happen.

ALSO - It would be good to have a list of regexes it can match, rather than only one.

**Comment by SanketDG** [comment]
How is it related to `LineLengthBear`?

**Comment by AbdealiJK** [comment]
LineLengthBear has an argument `ignore_length_regex` which takes a regex. If a line has this regex, it ignored this line's length when giving results. This is to make sure things like links dont throw an error.

For example, setting the regex to `http` basically makes it ignore all lines with links.

Now, currently if I use `http` in the bear, it only ignores links like:
```
https://blablabla .....
```
and doesnt ignore:
```
some words i front. http://blablabla ...
```

We want it to ignore both cases.

ALSO (the second part)
Is to allow the LineLengthBear to take in a list of regexes to ignore (right now it takes in only one)
