### ISSUE TITLE
Linter Bear Tutorial needs an update

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1557]
Update should cover:

- use of `{filename}` in the arguments string
- use of config file generation
- use of `gives_correction`

**Comment by aayn** [comment]
@sils1297 In the the tutorial, `{filename}` would correspond to `html_lint.py`, correct? If yes, then, what exactly should I cover about it?

And, could you please show/point me to an example of the use of the three. I didn't exactly understand what is it that you want me to cover.

**Comment by AbdealiJK** [comment]
@aayn 
 - `{filename}` - used in every bear. Examples: `AlexBear` and `ProseLintBear`. The documentation doesn't mention `{filename}` it was written before that existed
 - config file generation - we're not using this yet. It's meant to be like if a linter needs a config file, we generate it for them using out `.coafile`'s settings and pass it to the linter. (You can take a look at LintTest` to see how it works maybe ?)
 - `gives_correction` - GoImportsBear, GoReturnsBear

FYI:
Next time you want to find all bears using something, just do something like `git grep "gives_corrected"` and it will show you every place where `gives_corrected` is being used.

**Comment by aayn** [comment]
@AbdealiJK  So, I went through a few bears, and here are my next set of questions:

1. I saw that `arguments = "{filename}"` is used in 4 bears(not all). What exactly is this class variable achieving? Does the `{}` around `filename` have some significance or just for formatting?

2. From what I read through in `Lint.py`, if a bear, not just finds issues, but also can suggest corrections , then `gives_corrected` is set to true. But, where does it find such corrections?

**Comment by AbdealiJK** [comment]
@aayn 
 1. You may want to do a broader search for `{filename}` as its frequently used as `+= " {filename}" and so on. The `{filename}` is used by python's `str.format()` function and replaced by the appropriate filename - `{}` is requires as `.format()` only touches these parts of the string and replaces (Sort of like `%s` in C/C++ ?)
 2. Some linters provide a fixed version of the file. We take that, find "diffs" (like `git diff`does) and find out which parts of the file are changed. We use these changed blobs to suggest corrections.

**Comment by aayn** [comment]
@AbdealiJK 
For the first bullet(i.e. `{filename}`), here's the summary of what I've understood:

`{filename}` and some other things are passed into the `arguments` class variable(which is a string). Then, this along with the `executable` class variable, is formatted into a command(in `Lint`) which is then run using `Shell.run_shell_command`.

This^ brings me to my next question: Why does "`{filename}`" have to be added as a class variable of every subclass(of `Lint`)? Won't it be better if we do it in the `Lint` class itself?

**Comment by AbdealiJK** [comment]
@aayn we used to do it in `Lint` - We used to just append it to the command. but the problem is thats not always correct.

`lintr` (the RLintBear) needs the filename in a specific place. - `RScript "library(lintr); lintr(\"{filename}\");"` or something. In such cases we do not know where to put the filename. hence it's better to let the LinterBear using Lint do it (its not much work)

**Comment by aayn** [comment]
@AbdealiJK Oh OK. Thanks :). Is it okay if I do the first bullet in one PR and the rest in another? I've never done documentation before.

**Comment by AbdealiJK** [comment]
Why not juut make the first one in a commit and add more commits to the PR after that ?

**Comment by aayn** [comment]
@AbdealiJK Oh. I didn't think of that. Okay

**Comment by Adrianzatreanu** [comment]
@aayn  still working on this? :)

**Comment by aayn** [comment]
@Adrianzatreanu I really want to, I do. But right now, I have truckloads of work :(.
I've completed the first and the third bullet. For the second one, are we using config files for linters yet?

**Comment by AbdealiJK** [comment]
@aayn we do use it in JSHintBear now :)

**Comment by aayn** [comment]
If we are in a hurry for the config file tutorial, then it would be better if someone else was assigned. If not, I can do it as soon as my assignments/projects are completed.

**Comment by Adrianzatreanu** [comment]
i was just checking if you're still around, it's been a while :) good luck on it!

**Comment by Makman2** [comment]
@aayn ping

**Comment by Adrianzatreanu** [comment]
"testing out the new cool reply template"
Hi,

do you need help figuring this out? We're all happy to help you on [our gitter channel](https://gitter.im/coala-analyzer/coala), just drop by and ask us anything :)

**Comment by Adrianzatreanu** [comment]
lack of reponse => unassigning for now, message us if you would like to work on this when you're coming back :)

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#56
