### ISSUE TITLE
Fix grammatic mistake in the Linter Bears docs

### ISSUE THREAD

**Issue by Redridge** [coala-analyzer/coala#1562]
Under the "Writing the bear" header add a full stop to this sentence
" so it can be used by the Lint class to yield Results. (more on communicating with the user Writing Bears)"

difficulty/newcomer

**Comment by lonewolf07** [comment]
I want to solve this bug.

**Comment by sils1297** [comment]
Hey @lonewolf07 I've invited you into our org, accept at github.com/coala-analyzer please so we can assign you.
