### ISSUE TITLE
Use ConsolePrinter instead of NullPrinter in all tests

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1572]
The null printer is irritating because we have no debug output.

`pytest` automatically shows stdout and stderr when a test fails - if the `log_printer` uses `ConsolePrinter` we can actually see the output which makes it easier to debug.

Just have to go through all tests which use `NullPrinter` - `git grep "import NullPrinter" coalib/tests`
And change them from `NullPrinter` to `ConsolePrinter`

**Comment by Makman2** [comment]
Dont know if thats that useful since often you have so much printed to it you cant read anything valuable out of it. I wouldnt change to ConsolePrinter -> more work
