### ISSUE TITLE
Our development release seems to be a problem for someone

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1575]
I've got https://twitter.com/sfermigier/status/700298827350282240?cn=bWVudGlvbg%3D%3D&refsrc=email . I hope we can get more info on why this is a problem and how we can avoid it.

Having an automated development release is good for the stability of the project (devs are forced to merge releasable quality only, users can test early) and ease dependency management with multiple libraries like PyPrint.

**Comment by sils1297** [comment]
So there are definitely other projects doing this too and services like travis offer it as a service: https://docs.travis-ci.com/user/deployment/pypi/

I don't see how this should be a problem.

**Comment by AbdealiJK** [comment]
Neither do I.
Maybe we can ask pip to not show dev releases in the search page ?

**Comment by sils1297** [comment]
Yeah that I'm indeed annoyed with, if users go to the coala package they should get the non development release shown by default - which already is the default behaviour for pip install.

**Comment by sfermigier** [comment]
There is an option "hide from the front page" when you upload a package.
<img width="651" alt="screen shot 2016-02-18 at 15 20 50" src="https://cloud.githubusercontent.com/assets/271079/13145854/42c31e02-d653-11e5-8077-71f855ccb694.png">

**Comment by sils1297** [comment]
That option is only available via the UI, right? We (and lots of other projects) want a fully automated solution, any manual effort is not feasible.

**Comment by sfermigier** [comment]
This is the only project I see on PyPI that publishes development versions
regularly. And I check PyPI three times a day.

If there is no way to exclude dev packages from the home (I have no idea if
it is or not) then maybe a solution would be to set up your own private
devpi server (http://doc.devpi.net/).



On Thu, Feb 18, 2016 at 3:23 PM, Lasse Schuirmann <notifications@github.com>
wrote:

> That option is only available via the UI, right? We (and lots of other
> projects) want a fully automated solution, any manual effort is not
> feasible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coala-analyzer/coala/issues/1575#issuecomment-185743774>
> .
>



-- 
Stefane Fermigier - http://fermigier.com/ - http://twitter.com/sfermigier -
http://linkedin.com/in/sfermigier
Founder & CEO, Abilian - Enterprise Social Software -
http://www.abilian.com/
Founder, Nuxeo - Enterprise Content Management Platform -
http://www.nuxeo.com/
Chairman, Free&OSS Group / Systematic Cluster -
http://www.gt-logiciel-libre.org/
Co-President, National Council for Free & Open Source Software (CNLL) -
http://cnll.fr/
Founder & Organiser, PyData Paris - http://pydataparis.joinux.org/
---
"Le vrai courage c'est de faire ce qui est juste" - Docteur Benjamin Justice

**Comment by AbdealiJK** [comment]
Out of curiosity - why isn't a project supposed to publish nightly builds to pypi ?

**Comment by sils1297** [comment]
> This is the only project I see on PyPI that publishes development versions regularly.

Some projects do, though we usually have one or several releases every day which might be the difference. The Babel devs want it too, it's just a great deal for everyone. Now that travis supports doing that automatically for you even more projects will come and do this.

I still do not understand what your actual problem is. This is what development versions are for, to give cutting edge stuff to the users in a timely manner, like nightly builds. If you're annoyed by seeing our project in the logs you might rather want to speak with the people from PyPI to exclude development versions in that view. I am not implying that you have no reasons to complain but rather that either I don't understand them well yet or they can't be addressed by us since you'd have to make all projects quit this kind of thing.

**Comment by sils1297** [comment]
We don't have the resources, nor the manpower to set up and maintain an own PyPI server. Also that affects the usability of the development version installation.

**Comment by sfermigier** [comment]
Imagine that every python project set up their CI server to push
development versions to PyPI on every successful commit as you seem to do
(and want to do).

1. I don't believe the PyPI architecture is designed to sustained this.

2. This would make looking at the PyPI timeline to discover new &
interesting packages even more challenging as it is today.


On Thu, Feb 18, 2016 at 4:24 PM, Lasse Schuirmann <notifications@github.com>
wrote:

> We don't have the resources, nor the manpower to set up and maintain an
> own PyPI server. Also that affects the usability of the development version
> installation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coala-analyzer/coala/issues/1575#issuecomment-185773358>
> .
>



-- 
Stefane Fermigier - http://fermigier.com/ - http://twitter.com/sfermigier -
http://linkedin.com/in/sfermigier
Founder & CEO, Abilian - Enterprise Social Software -
http://www.abilian.com/
Founder, Nuxeo - Enterprise Content Management Platform -
http://www.nuxeo.com/
Chairman, Free&OSS Group / Systematic Cluster -
http://www.gt-logiciel-libre.org/
Co-President, National Council for Free & Open Source Software (CNLL) -
http://cnll.fr/
Founder & Organiser, PyData Paris - http://pydataparis.joinux.org/
---
"Le vrai courage c'est de faire ce qui est juste" - Docteur Benjamin Justice

**Comment by sils1297** [comment]
> Imagine that every python project set up their CI server to push development versions to PyPI

A world where projects would actually guarantee the qualiity that the master branch is always releasable and tested immediately by users who want to try out cutting edge stuff.

/me keeps dreaming of that.

> 1. I don't believe the PyPI architecture is designed to sustained this.

This particular question is a theoretical debate that probably won't lead to anything right now, practically we can see that PyPI obviously can handle whatever we and others throw at it.

Our little freetime occupation won't take PyPI down...

> 2. This would make looking at the PyPI timeline to discover new & interesting packages even more challenging as it is today.

The usecase you describe is obviously not the usecase this timeline is designed to suit. If you think this is a bad thing (you seem to do) then you will want to speak with the PyPI maintainers as the development versions shouldn't be shown there at all in that case. If you want to be kept updated about actually new projects I'm sure PyPI has an API that can be served to some application that crunches that data.

https://www.python.org/dev/peps/pep-0386/ was made so projects could do development releases. They exist and they work totally well, they have amazing benefits for the projects that use it. PyPI supports that. If we shouldn't use it why would it be there and be so helpful?

**Comment by sfermigier** [comment]
> "The usecase you describe is obviously not the usecase this timeline is
designed to suit."

-> What makes you think that ?

> "https://www.python.org/dev/peps/pep-0386/ was made so projects could do
development releases"

-> Just because you *can* make dev releases (thanks to PEP 0386) doesn't
mean you should upload them to PyPI."

On Thu, Feb 18, 2016 at 4:55 PM, Lasse Schuirmann <notifications@github.com>
wrote:

> Imagine that every python project set up their CI server to push
> development versions to PyPI
>
> A world where projects would actually guarantee the qualiity that the
> master branch is always releasable and tested immediately by users who want
> to try out cutting edge stuff.
>
> /me keeps dreaming of that.
>
>
>    1. I don't believe the PyPI architecture is designed to sustained this.
>
> This particular question is a theoretical debate that probably won't lead
> to anything right now, practically we can see that PyPI obviously can
> handle whatever we and others throw at it.
>
> Our little freetime occupation won't take PyPI down...
>
>
>    1. This would make looking at the PyPI timeline to discover new &
>    interesting packages even more challenging as it is today.
>
> The usecase you describe is obviously not the usecase this timeline is
> designed to suit. If you think this is a bad thing (you seem to do) then
> you will want to speak with the PyPI maintainers as the development
> versions shouldn't be shown there at all in that case. If you want to be
> kept updated about actually new projects I'm sure PyPI has an API that can
> be served to some application that crunches that data.
>
> https://www.python.org/dev/peps/pep-0386/ was made so projects could do
> development releases. They exist and they work totally well, they have
> amazing benefits for the projects that use it. PyPI supports that. If we
> shouldn't use it why would it be there and be so helpful?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coala-analyzer/coala/issues/1575#issuecomment-185787794>
> .
>



-- 
Stefane Fermigier - http://fermigier.com/ - http://twitter.com/sfermigier -
http://linkedin.com/in/sfermigier
Founder & CEO, Abilian - Enterprise Social Software -
http://www.abilian.com/
Founder, Nuxeo - Enterprise Content Management Platform -
http://www.nuxeo.com/
Chairman, Free&OSS Group / Systematic Cluster -
http://www.gt-logiciel-libre.org/
Co-President, National Council for Free & Open Source Software (CNLL) -
http://cnll.fr/
Founder & Organiser, PyData Paris - http://pydataparis.joinux.org/
---
"Le vrai courage c'est de faire ce qui est juste" - Docteur Benjamin Justice

**Comment by sils1297** [comment]
> -> What makes you think that ?

Simply the fact that they show development releases. If it were made for that usecase they'd only show new packages.

**Comment by sfermigier** [comment]
I think you got it backwards. They didn't anticipate people would post dev
releases to PyPI.

On Thu, Feb 18, 2016 at 5:14 PM, Lasse Schuirmann <notifications@github.com>
wrote:

> -> What makes you think that ?
>
> Simply the fact that they show development releases. If it were made for
> that usecase they'd only show new packages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coala-analyzer/coala/issues/1575#issuecomment-185796190>
> .
>



-- 
Stefane Fermigier - http://fermigier.com/ - http://twitter.com/sfermigier -
http://linkedin.com/in/sfermigier
Founder & CEO, Abilian - Enterprise Social Software -
http://www.abilian.com/
Founder, Nuxeo - Enterprise Content Management Platform -
http://www.nuxeo.com/
Chairman, Free&OSS Group / Systematic Cluster -
http://www.gt-logiciel-libre.org/
Co-President, National Council for Free & Open Source Software (CNLL) -
http://cnll.fr/
Founder & Organiser, PyData Paris - http://pydataparis.joinux.org/
---
"Le vrai courage c'est de faire ce qui est juste" - Docteur Benjamin Justice

**Comment by sils1297** [comment]
Why not, people obviously do that. Us stopping development releases hurts the project as it would any other project doing that right now. There's no real pain at any side from having the dev releases. If you are annoyed by dev releases then the solution is not to go to every project but to speak with PyPI developers; they offer the feature, we use it. That is our right.

I'm voting for a wontfix here, the discussion won't lead to anything productive and we're all unpaid and don't have time for this. If you want, go ahead and discuss with other, possibly more reasonable people, than me.

CC @Makman2 @AbdealiJK @fneu

**Comment by sfermigier** [comment]
OK

On Thu, Feb 18, 2016 at 5:21 PM, Lasse Schuirmann <notifications@github.com>
wrote:

> Why not, people obviously do that. Us stopping development releases hurts
> the project as it would any other project doing that right now. There's no
> real pain at any side from having the dev releases. If you are annoyed by
> dev releases then the solution is not to go to every project but to speak
> with PyPI developers; they offer the feature, we use it. That is our right.
>
> I'm voting for a wontfix here, the discussion won't lead to anything
> productive and we're all unpaid and don't have time for this. If you want,
> go ahead and discuss with other, possibly more reasonable people, than me.
>
> CC @Makman2 <https://github.com/Makman2> @AbdealiJK
> <https://github.com/AbdealiJK> @fneu <https://github.com/fneu>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coala-analyzer/coala/issues/1575#issuecomment-185799982>
> .
>



-- 
Stefane Fermigier - http://fermigier.com/ - http://twitter.com/sfermigier -
http://linkedin.com/in/sfermigier
Founder & CEO, Abilian - Enterprise Social Software -
http://www.abilian.com/
Founder, Nuxeo - Enterprise Content Management Platform -
http://www.nuxeo.com/
Chairman, Free&OSS Group / Systematic Cluster -
http://www.gt-logiciel-libre.org/
Co-President, National Council for Free & Open Source Software (CNLL) -
http://cnll.fr/
Founder & Organiser, PyData Paris - http://pydataparis.joinux.org/
---
"Le vrai courage c'est de faire ce qui est juste" - Docteur Benjamin Justice

**Comment by Makman2** [comment]
Agreeing with @sils1297, @sfermigier I don't see a problem but that you have a view that is full with our dev releases which is more an issue of PyPi arranging a better view onto packages.
A development version is as it says for the newest development stuff, and imo that's what the dev-versions on PyPi are for also. Our current system works very nicely, being able to fetch the newest commits as a developer from PyPi is a really big help.
