### ISSUE TITLE
bug: alert user about wrong alex package

### ISSUE THREAD

**Issue by Redridge** [coala-analyzer/coala#1582]
Apparently there are 2 alex packages
It would be nice to find a way to alert the user that he has the wrong alex package in his PATH so tests might fail

**Comment by sils1297** [comment]
same is true for the remark package btw. don't know what the other one is. FFor alex it's the lexer for haskel (alex of course)

**Comment by AbdealiJK** [comment]
Doesn't the linter give a bunch of warnings as that would give a error in stderr ?
I don't think we should be doing custom checking for package clashes like this ...

**Comment by sils1297** [comment]
Apparently it just gives no results because the regex doesn't match.

**Comment by AbdealiJK** [comment]
I've asked the `alex` devs if they could make an alias `alexjs` so that this clash wouldnt be troublesome.
https://github.com/wooorm/alex/issues/83

**Comment by AbdealiJK** [comment]
Seems like that's not going to happen.

**Comment by AbdealiJK** [comment]
This issue was moved to coala-analyzer/coala-bears#776
