### ISSUE TITLE
Use `shlex.quote` inside `Shell.escape_path_argument` for Unix systems

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1588]
`shlex.quote()` is introduced since Python 3.3, so we should use that instead of our self-written version.

**Comment by Makman2** [comment]
So what to do:
- Replace `Shell.escape_path_argument()` (from file *coalib/misc/Shell.py*) with built-in `shlex.quote()`
- Test if everything works properly
- Remove `Shell.escape_path_argument()`

**Comment by aayn** [comment]
Hey. Being a newcomer, I'd like to do this please.

**Comment by Makman2** [comment]
hi @aayn, you need an invitation to our org so we can assign you.
@sils1297 could you do that please?
Btw did you read our contributing guide? There's many useful information how to get started etc.

**Comment by aayn** [comment]
@Makman2 Yep. I'm going through that right now. Almost finished.

**Comment by sils1297** [comment]
@aayn invitation is out, accept at github.com/coala-analyzer . If you need help, drop by at https://gitter.im/coala-analyzer/coala at all times. Welcome! :)

**Comment by aayn** [comment]
@sils1297 Thanks :). Accepted the inv.

**Comment by aayn** [comment]
According to a script I wrote, these files need the change(`Shell.escape_path_argument()` --> `shlex.quote()`):

```
coala/bears/perl/PerlCriticBear.py
coala/bears/python/PyLintBear.py
coala/bears/js/JSHintBear.py
coala/coalib/misc/Shell.py
coala/coalib/tests/misc/ShellTest.py
coala/coalib/tests/bearlib/abstractions/LintTest.py
coala/coalib/bearlib/abstractions/Lint.py
```

Have I missed any out? @Makman2

**Comment by sils1297** [comment]
you should be able to just `git grep escape_path_argument` for occurrences
in git

2016-02-19 15:14 GMT+01:00 Aayush Naik <notifications@github.com>:

**Comment by aayn** [comment]
@sils1297 Oh. I didn't know about this. This is so easy. I feel like a fool now :P.

**Comment by sils1297** [comment]
I used `git format-patch` for months for reworking commits because nobody
told me about `git rebase --interactive` - that was so complicated :D

2016-02-19 15:24 GMT+01:00 Aayush Naik <notifications@github.com>:

**Comment by aayn** [comment]
OK. So, I've made changes in all the required files and things seem to be running fine. I'll submit a PR now?

**Comment by sils1297** [comment]
sure!

2016-02-19 15:46 GMT+01:00 Aayush Naik <notifications@github.com>:

**Comment by Makman2** [comment]
Since `shlex.quote` is not windows compatible this doesn't work like that any more. `shlex.quote` shall be used inside `escape_path_argument` now to simplify unix behaviour.

**Comment by sils1297** [comment]
@aayn please confirm if you still want to do this issue as it's objective has changed.

**Comment by aayn** [comment]
@sils1297 Yes. Most certainly. But, what exactly would this mean now? As in, how do I make changes just for Unix systems?

**Comment by sils1297** [comment]
@aayn just look into the function, it already does this distinction. Or ask @Makman2 :)

**Comment by aayn** [comment]
Yeah. So, under `elif shell == "sh":`, I'll just change `escape` to `shlex.quote()`. When I do that, I will have to change/remove [this](https://github.com/coala-analyzer/coala/blob/master/coalib/tests/misc/ShellTest.py#L12) test as well. So, what do you suggest I do? @sils1297 @Makman2

**Comment by Makman2** [comment]
@aayn you can keep the test imo, in fact the behaviour shouldn't change for paths.

**Comment by aayn** [comment]
@Makman2 It does. The test fails as soon as I make the change. The way `shlex.quote()` and the custom `escape()` do escaping seems different, at least according to this:
![shlextest](https://cloud.githubusercontent.com/assets/9693267/13195913/962c1a8e-d7e4-11e5-8277-9ca8e36b8ce0.png)

**Comment by Makman2** [comment]
@aayn ahh yeah alright sorry. That's right, quote tries to enclose the path inside quotes instead of escaping special characters like spaces. You can adjust the tests according to output of `shlex.quote` :)

**Comment by aayn** [comment]
@Makman2 No problem :). Will do.

**Comment by Adrianzatreanu** [comment]
@aayn Hey, it seems that you havent been active on this issue for the past 10 days. Are you still working on this, do you need some help :) ? Ping us if you do, would love to help you !

**Comment by Makman2** [comment]
@Adrianzatreanu this issue is blocked together with #1614, I need to fix the shell stuff I introduced that got reverted again^^ Though this requires Lint refactors, that's why I'm completely refactoring the Linter class according to #1703.

**Comment by Makman2** [comment]
takes still a bit of time

**Comment by Makman2** [comment]
@aayn are you willing to revive this PR again? :)
