### ISSUE TITLE
assert_supported_version: Remove pypy support

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1590]
There's a check for PYPY, we don't want that anymore. This is in `coalib/__init__.py`

difficulty/newcomer

**Comment by vidhan13j07** [comment]
I would to work on this bug .

**Comment by sils1297** [comment]
@vidhan13j07 I've invited you to our org, accept at github.com/coala-analyzer please

**Comment by sils1297** [comment]
alright seeing forward to a PR :) At any time you can get help at https://gitter.im/coala-analyzer/coala
