### ISSUE TITLE
bug: PHPLintBearTest.test_run fails on test

### ISSUE THREAD

**Issue by aayn** [coala-analyzer/coala#1592]
All other tests pass. Only this one fails.

# Steps to reproduce
1. Run `py.test`.

# Actual results

![phpbear](https://cloud.githubusercontent.com/assets/9693267/13177206/a1782c90-d73d-11e5-8358-a14509127b3f.png)

# Expected results
Test should pass.

# Additional info

Output to some commands:
![phpv](https://cloud.githubusercontent.com/assets/9693267/13177329/72c12d06-d73e-11e5-81a4-255c41b87914.png)

![phpvl](https://cloud.githubusercontent.com/assets/9693267/13177335/80a1287c-d73e-11e5-8361-c44e7f7f2d88.png)

/cc @AbdealiJK

**Comment by sils1297** [comment]
@aayn can you try running `./coala -c /dev/null -b PHPLintBear -f bears/tests/php/**/phplint_test1.php -L DEBUG` from coala root?

**Comment by aayn** [comment]
Here you go:
![sdb](https://cloud.githubusercontent.com/assets/9693267/13194853/db8ab438-d7c5-11e5-97cc-f444bb09d8f5.png)

**Comment by sils1297** [comment]
what does `php -l bears/tests/php/test_files/phplint_test1.php` give?

**Comment by aayn** [comment]
This:
![phpl](https://cloud.githubusercontent.com/assets/9693267/13196529/285aa734-d7f6-11e5-94da-0349805af79f.png)

**Comment by sils1297** [comment]
interesting, I get

```
lasse@localhost ~/prog/coala (git)-[master] % php -l bears/tests/php/test_files/phplint_test1.php
PHP Parse error:  syntax error, unexpected '?>' in bears/tests/php/test_files/phplint_test1.php on line 3
Errors parsing bears/tests/php/test_files/phplint_test1.php
```

with PHP 5.6.17

**Comment by AbdealiJK** [comment]
I get:
```
ajk@ajk-ThinkPad-R60:~/Documents/coala/coala-bears$ php -l bears/tests/php/test_files/phplint_test1.php
PHP Parse error:  syntax error, unexpected '?>' in bears/tests/php/test_files/phplint_test1.php on line 3
Errors parsing bears/tests/php/test_files/phplint_test1.php
```

with `5.5.9-1` ... which means that only his specific version has this issue ?

@aayn This is a fedora if I remember correct ? Have you changed your php configs anywhere ?

**Comment by AbdealiJK** [comment]
This issue was moved to coala-analyzer/coala-bears#21
