### ISSUE TITLE
coala-json should give relpaths of files

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1593]
IMO we should output relative paths in all scenarios. (This is needed for coala-html to work based on coala-json.)

**Comment by sils1297** [comment]
commit was reverted @tushar-rishav you're still assigned

**Comment by AbdealiJK** [comment]
Why was the commit reverted ?
And also, I dislike relative paths. Because when I run coala on something like `/tmp/abcde` it gives a lot of `../../../../../`. Although this is a rare case, it was a little irritating when i saw this somewhere.

Wouldn't it be possible to track whether the user gave a relative path for the file glob and decide on abs or rel based on that ?
OR - would it be possible for `coala-html` to simple remove the extra part for its current path ?

**Comment by sils1297** [comment]
it broke because the file_dict still used absolute paths so coala couldn't
get the file contents anymore

2016-02-22 13:03 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
we already use relative paths for the output of filenames in
consoleinteraction, my thought was to switch to relative paths overall
possibly. Maybe provide a setting for it? :/

2016-02-22 13:05 GMT+01:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

**Comment by AbdealiJK** [comment]
Ah, ^ @sils1297 I disliked the ConsoleInteraction using relpaths then - as it gave me the `../../../` etc at some point of time.
But again, thats a rare case.

Why exactly does `coala-html` need this ? If it's using json, can't we simply show the path in json ouput ?

**Comment by sils1297** [comment]
so if you do the json dump the html/js page uses paths to get file
contents, if you then zip it and upload it somewhere to be served
statically it won't work if you use abspaths in the json dump

2016-02-22 13:09 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Maybe have a `--relpath` in coala-json ?

**Comment by tushar-rishav** [comment]
Yes. It's possible to convert abspath in json_dump file from `coala-json`
to relpath. In that case we will have to iterate through all the file paths
in `affected_code`  and change it to relative paths and finally save the
changes to json_dump

**Comment by AbdealiJK** [comment]
@tushar-rishav it's quite a bit simpler - We just add an `if` in `coalib.output.JSONEncoder` to catch `Result` classes and special handle them

**Comment by tushar-rishav** [comment]
Makes sense. Let me try.
