### ISSUE TITLE
Investigate `shlex.quote()` on Windows for replacing `Shell.escape_path_argument()`

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1598]
`shlex.quote()` is stated inside the docs as only Unix compliant^^

**Comment by sils1297** [comment]
I thought we know that it's unusable?

**Comment by Makman2** [comment]
@sils1297 maybe it's depending on the shell somehow and shlex doesn't recognize it that nicely. I want to see if it's still possible to use that for Windows too, because I hate doing such stuff for windows, I want python to do that for me :(

**Comment by Makman2** [comment]
hmm it should work, command-paths enclosed in parantheses work at least ...

**Comment by Makman2** [comment]
`escape_path_argument` is deprecated and only used inside `Lint`.
