### ISSUE TITLE
Bear Dependencies

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#161]
Okay, thats the master plan:

 * A bear can add another bear as a dependency
 * We then assure that the other bear is executed before this one
 * aaand we pass the results of the other bear to our bear. (We need to check for recursive deps though.)
 * Multiple bears can have one bear as a dependency, this is an n to n relation.

This way a bear writer can break up his bear into steps and he an reuse the preprocessed results in another bear, thus saving huge amounts of work and performance.

**Comment by cw1** [comment]
Sounds good, but what if:
- A bear have multiple dependencies, but the bear wants to define the ordner of execution of the (possibly independent of each other) dependency bears (for reasons i can't imagine ;-) )
  - Should we define an interface for order management or
  - should we work sequential through the dependency list?
- What (generic) datatype would you use for the forwarding (simple the manipulated input text stream doesn't work for a complex bear which builds a language independend code tree, for example)?

**Comment by sils1297** [comment]
> - A bear have multiple dependencies, but the bear wants to define the ordner of execution of the (possibly independent of each other) dependency bears (for reasons i can't imagine ;-) )

I do not see any usecase for that kind of scenario. Bears are by their very nature a very observant thing. They cannot change any file since they don't get the filehandle but the filecontents. If they modify these filecontents the copy on write mechanism guards other bears from their fault. Thus the order of execution is basically irrelevant. These dependencies are rather about reusing some results from one bear for another.

>  - should we work sequential through the dependency list?

So you're asking about the technical implementation? Not sure how to do that. But thats not important at this time. We should first think about whats best for the user. Usually there is a way. Looking at things from the technical standpoint first results in programs that are unusable.

Naive implementation would be: when choosing the next bear, ask first if all deps are met. If not take one of the deps and repeat the same with the dep. We need to keep track of the recursion to recognize a recursive dependency and abort at that point.

> - What (generic) datatype would you use for the forwarding (simple the manipulated input text stream doesn't work for a complex bear which builds a language independend code tree, for example)?

Although this is a technical idea: I would write another subclass of our Result class. The outputter will filter out this result so they don't get shown to the user. However coala will pass the contents of this class to the bear.

A technical note: the objects which can be passed from one bear to another need to be picklable (see python doc) but that is true for the most objects. (You don't wanna pass filehandles or other non-duplicateable stuff.)

**Comment by sils1297** [comment]
Oh I forgot to mention that we need to collect dependencies too even if they are not specified.

**Comment by sils1297** [comment]
Oh by the way when implementing this the generic get_needed_settings method will also need adjustment to consider needed settings of dependencies too. See #111 .

**Comment by sils1297** [comment]
Began thinking about technical implementation.

1. After collecting our bears we need to collect dependency bears that are not yet included.
2. We need to check for recursions!
3. We need to introduce a DependencyResult that probably has an origin and a content member that could be everything. This will be ignored by the outputters.
4. We need some shared memory where we can put the pickled DependencyResults so every process can use them. I'd rather not do this via queues. This is the difficult part and I don't really know how to do this right now. @smfn3321 @cw1 I'd appreciate help, ideas!
5. We'll probably also want some checks in place so if not all dependencies for a bear are not met yet we push it back on the queue and take the next one. If we do it this way we may even avoid step 1 and 2.

**Comment by sils1297** [comment]
I think if we're using a multiprocessing.Manager.dict for storing the results of everything. This object allows proxy based access to those object, meaning they are stored in our main process and when we access them from another process there'll be a lock and we'll get a pickled version. This is much easier than a version with queues but we'll still need an extra transfer from one process to another (means pickling, some IPC, unpickling) for each dependency result and each bear that is using it.

**Comment by sils1297** [comment]
First step is done: SectionExecutor and BearRunner are using the dict proxies now on #150.

**Comment by sils1297** [comment]
TODO: BearRunner needs a list that is sorted so every _local_ bear with a dependency is after its dependencies.

Global bears need only to be checked for recursivity, BearRunner can put 'em on the queue again if deps are not met yet.

**Comment by sils1297** [comment]
Work in progress on https://github.com/coala-analyzer/coala/tree/wip/sils/deps

**Comment by sils1297** [comment]
dependency resolving algorithm implemented on #253

**Comment by sils1297** [comment]
Do we want global bears to be able to list local bears as dependency? For now I'm not doing this because this would need additional conversions for results and an own specification for some result dict.

**Comment by sils1297** [comment]
implemented dependencies for local bears in #253

**Comment by sils1297** [comment]
Done on #290
