### ISSUE TITLE
Use better name for coala_bears_test_module

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1616]
We have a module named `coala_bears_test_module` in `coalib.tests` we should have a better name for it.

Something like `test_bears` would be good.

**Comment by aayn** [comment]
I would like to this please. Want to get used to the git workflow asap.

**Comment by AbdealiJK** [comment]
Hi @aayn I notice (https://github.com/coala-analyzer/coala/issues/assigned/aayn) that youve already closed 1 issue and are working on 2 others
Could you complete that first ? (I realize that the shell issue is blocked for now, but the other one is pending)

**Comment by aayn** [comment]
@AbdealiJK  It's just that I'm extremely free for the next 2-3 days so I thought I could do it. But, okay. I'll complete that one first.

**Comment by AbdealiJK** [comment]
@aayn we recommend you do `difficulty/low` issues after your first two `newcomer` issues (We're running out of newcomer issues ! :worried: )
From the initiative you've shown in the Shell issue I believe you're already ready for them :+1: 
If you need help, we're always there on https://gitter.im/coala-analyzer/coala

**Comment by aayn** [comment]
@AbdealiJK Aye Aye cap'n!

**Comment by ravinimmi** [comment]
I would like to do this.

**Comment by sudheesh001** [comment]
Assigned it to you @ravinimmi Please go ahead :smile:
