### ISSUE TITLE
CommunicationBear from 'Writing Bears' tutorial throws exception

### ISSUE THREAD

**Issue by aayn** [coala-analyzer/coala#1618]
### Steps to reproduce

1. Copy the `CommunicationBear` code from [here](http://coala.readthedocs.org/en/latest/Users/Tutorials/Writing_Bears.html) to a bear .py file.
2. Run the bear using coala.

### Actual Results

```
Executing section Default...
[DEBUG][20:59:22] Running bear CommunicationBear...
[DEBUG][20:59:22] Got 'sdfs' as user input of type <class 'str'>.
[WARNING][20:59:22] Bear CommunicationBear failed to run. Take a look at debug messages for further information.
[DEBUG][20:59:22] The bear CommunicationBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/coalib/bears/Bear.py", line 95, in execute
    return list(self.run_bear_from_section(args, kwargs) or [])
  File "/home/wysiwys/Development/GitHub/coala-tutorial/bears/CommunicationBear.py", line 21, in run
    file=filename)
  File "/usr/lib/python3.4/site-packages/coalib/misc/Decorators.py", line 298, in decorated
    return function(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'file'
```

### Expected Results

Bear should just run 'normally'.

### Reproducibility

Yes.

**Comment by aayn** [comment]
Also, I'd like to point out that the code from the demo repo (https://github.com/coala-analyzer/coala-tutorial) doesn't match with the tutorial code. (I could do this part)

**Comment by AbdealiJK** [comment]
It seems as though our tutorial is a bit outdated. We're using `SourceRanges` to create results now, but this has not been changed in the tutorial.
We need to update the documentation (http://coala.readthedocs.org/en/latest/Users/Tutorials/Writing_Bears.html) and update the tutorial repo (https://github.com/coala-analyzer/coala-tutorial).
