### ISSUE TITLE
Automatically check if every requirement is installed on running tests.

### ISSUE THREAD

**Issue by ravinimmi** [coala-analyzer/coala#1620]
While I was running tests, some of the them failed because up to date requirements were not installed. It would be great if it could check automatically before running tests.

**Comment by sils1297** [comment]
Maybe @AbdealiJK knows a smart pytest hook we can override

**Comment by ravinimmi** [comment]
@sils1297 Maybe we could use [pytest_runtest_setup](http://pytest.org/latest/writing_plugins.html#_pytest.hookspec.pytest_runtest_setup) hook and pkg_resources API for checking package versions.

**Comment by AbdealiJK** [comment]
I think this is bad.
If you want to install and run tests - do  python setup.py test

Pytest gives you more flexibility and is slow - I'm against getting asking it to check all requirements. Plus many times I've had to check if something works with an older version or check if the test is skipping correctly. This would be irritating to do if we let pytest auto install things.

I think the correct thing to do is ask pytest to show reasons why the test got skipped - we have a bug for this somewhere

-----Original Message-----

**Comment by AbdealiJK** [comment]
Also, FYI - `pytest_load_initial_conftests` would probably be better as `pytest_runtest_setup` is run for every test item (which is not needed)
