### ISSUE TITLE
docs: Explain bear kinds

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#1630]
There is very little information currently on what they are.

**Comment by AbdealiJK** [comment]
We currently have 2 types of bears, this can be seen in `coalib.bears.BEAR_KIND` - Global and local

We have 2 major python files which talk about them and define them - `coalib.bears.LocalBear` and `coalib.bears.GlobalBear`.

What we need to do is add more information about global and local bears in the documentation.
This can be done in the following locations:
 - docs/Users/Tutorials/Tutorial.rst - We never mention that there are two types here. We should atleast mention them and give a 1 line description about them
 - docs/Users/Tutorials/Writing_bears.rst - We use localBear without telling what it is. We don't even mention that a global bears exist. We should add an example with a Global bear here.

**Comment by souravsingh** [comment]
I would like to work on the issue.

**Comment by AbdealiJK** [comment]
Awesome, @sils1297 can you add @souravsingh to the org so we can assign this issue appropriately ?

**Comment by sils1297** [comment]
Invitation is out, accept at github.com/coala-analyzer

2016-02-23 10:56 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by souravsingh** [comment]
I have accepted the invite

**Comment by sils1297** [comment]
@souravsingh awesome! If you need help you can approach us on https://gitter.im/coala-analyzer/coala or ask concrete questions here :)

**Comment by Adrianzatreanu** [comment]
Hey @souravsingh . It seems its been a few days since you have last answered our reviews. Do you need some help? Please feel free to ping us on https://gitter.im/coala-analyzer/coala, as @sils1297 said, or ask here! Id love to help.

**Comment by Adrianzatreanu** [comment]
unassigned due to inactivity.

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#59
