### ISSUE TITLE
Bear descriptions

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#164]
Would be nice if we have metadata for bears. Bug #111 is important for this one because we will have the FunctionMetadata object which is able to extract documentation comments and parse them. Thus we will be able to retrieve the documentation description for the bear.

coala should support commands for investigating what bears are available, what parameters do they need or take and descriptions for everything. The https://github.com/sils1297/coala/blob/wip/extract_needed_params/coalib/parsing/DocumentationCommentParser.py is an important step in that direction.

**Comment by sils1297** [comment]
it works:
```python
>>> from coalib.settings.FunctionMetadata import FunctionMetadata
>>> def test(p1, p2="test", p3=5):
...   """
...   tests something
... 
...   :param p2: its a test value
...   :return nothing.
...   """
...   pass
... 
>>> fm=FunctionMetadata.from_function(
... test)
>>> fm.name
'test'
>>> fm.desc
'tests something'
>>> fm.retval_desc
'nothing.'
>>> fm.non_optional_params
{'p1': 'No description given.'}
>>> fm.optional_params
{'p2': "its a test value (Optional, defaults to 'test'.)", 'p3': "No description given. (Optional, defaults to '5'.)"}

```

**Comment by sils1297** [comment]
needs cli arg design

**Comment by sils1297** [comment]
I wonder if the cleanest solution could be to do a BearDescriptionBear that searches all bear_dirs it gets for bears and lists it to the user via an informational result? It's a bit weird but it would be very consistent in the way that currently everything entered via CLI can also be saved to a coafile.

Alternative would be to provide an independent binary for this. bear_inspector or so?

**Comment by sils1297** [comment]
@Makman2 any ideas?

**Comment by Makman2** [comment]
Isn't the bear collector an option?

**Comment by sils1297** [comment]
what bear collector?

**Comment by Makman2** [comment]
Don't you have a bear collector class that collects each bear specified in the .coafile?

**Comment by sils1297** [comment]
Yeah, but the question here is not *how* we realize that within coala but how we *expose* that feature to the user.

**Comment by Makman2** [comment]
Then I wouldn't use a bear, a bear is for checking your code. I also don't think someone would use this bear in his coafile since it displays information about each available bear. A new command line argument should do the trick in my opinion^^
A new binary is not practiable, the available bears are dependent on the configuration of coala (paths etc.). Also the user doesn't need to explore a new tool, coala would do this already.

**Comment by sils1297** [comment]
The problem is currently coala's command line is just an interface for a Section, just as the coafile is. So either we add some command-line only options, thus break consistency, or we add some settings to show that info instead.

**Comment by Makman2** [comment]
Even if coala is just a section interface, it's the representable binary of your project, so every user will do everything over `./coala`. I would break consistency and make some not-section-interface-like command line switches^^

**Comment by sils1297** [comment]
So you'd really go for inconsistency?

How about `--show-bears` which sets `show_bears` to true and if this is set for a section one gets information about all the selected bears in this section or so?

**Comment by Makman2** [comment]
Cool, nice switch. Would do that! :)

**Comment by sils1297** [comment]
but thats a setting internally then and can also be set from coafile to be consistent.

**Comment by Makman2** [comment]
Is every variable in a bear automatically accessible from the .coafile?

**Comment by sils1297** [comment]
yes, you can even set save from coafile. Thats the beauty of this fully consistent thing IMO. (And I don't see drawbacks)

**Comment by Makman2** [comment]
Then why not, then even `show_bears` is consistent in this case :)
