### ISSUE TITLE
stuff to do

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1647]
@AbdealiJK I think we should make the coala run in the coala CI independent from the master version of the coala core repository
we kind of use it as an integration test
but it is rather a tool to check our code
so we should stop the version number mess
and just install coala-bears

**Comment by sils1297** [comment]
@AbdealiJK what do you think? Code doesn't need to be changed, it'll do it on it's own once we change the coala version number in the requirements for bears.

**Comment by AbdealiJK** [comment]
@sils1297 I agree that it should be done
