### ISSUE TITLE
Use generators to improve performance

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#165]
Generators are better in some cases than usual methods. I didn't know them until shortly and they are not used at all in coala. We may take a performance advantage out of them.

**Comment by sils1297** [comment]
So this is to investigate. Any help is appreciated.

**Comment by Makman2** [comment]
What are generators?

**Comment by sils1297** [comment]
You see? :)
https://wiki.python.org/moin/Generators

**Comment by Makman2** [comment]
Ah that's a python thing, thought it was a project specific feature^^

**Comment by sils1297** [comment]
we're using generators at several points now and it's getting better. I think it's ok to close this now.
