### ISSUE TITLE
coaladocs.readthedocs.org

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1652]
coaladocs.readthedocs.org comes up higher than coala.readthedocs.org in google when searching for "coala docs".

Either we need to remove it completely (from google also) or redirect it to coala.readthedocs.org

**Comment by sils1297** [comment]
From gitter:

> Hi @AbdealiJK wrt #1652 seems readthedocs does have issues removing old/test docu links even when the docs are deleted. I will try adding a redirect to the correct link

**Comment by WJCode** [comment]
It seems it is not possible to entirely remove old/obsolete documentation links from readthedocs. :worried: See [here](https://github.com/rtfd/readthedocs.org/issues/1408)
It also looks like readthedocs does not support redirecting to another domain even though I was the "owner" of *coaladocs*. The option I used was Exact Redirect found under Admin -> Redirects in readthedocs. Also, I had deleted those docs at the time we moved to sphinx hoping to avoid this kind of mix up.

BUT, it looks like google has picked up on recently added meta tags and I now see https://coala.readthedocs.org/ at the top of the results when searching for "coala docs" :smile: 
@AbdealiJK Can you try the search on google again?

**Comment by AbdealiJK** [comment]
Yes, it does look like coaladocs.readthedocs has gone. Closing this
