### ISSUE TITLE
Writing_Good_Commits.rst : Mention that first person shall not be used inside commit body

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1684]
I'm in favor of objective commit message writing :)

**Comment by AbdealiJK** [comment]
I think this seems unnecessary ...
We have enough commit guidelines and not using first person in essays/reports is a very very old English rule which most people do not follow anymore in modern literature.

Also, we have enough commit rules. Let's not add more :(

**Comment by sils1297** [comment]
Yeah, I think we're pretty clear on imperative tense

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-24 4:22 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by Makman2** [comment]
We write it explicitly for the shortlog and not the body, either I would put the present-tense stuff before everything or add it to the **Long Description**.

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#53
