### ISSUE TITLE
Docs: Reference Lint api module in docs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1686]
I notice that there are a few small things not there in `Linter_Bears.rst` like `use_stderr` ( @SanketDG didnt know about it :( )

Can we link the module documentation directly in RST files ? So they'd see the docstrings ?

Or do we again rewrite these types of documentations in Linter_bears.rst ? (I prefer just linking the API - it's really well documented ! ... although I wrote it, so i could be biased)

**Comment by sils1297** [comment]
sure, why not

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-24 3:39 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
So, what needs to be done is add a link to the Lint.py file in Linter_Bear.rst and Self_Correcting_Bear.rst

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#55
