### ISSUE TITLE
install.rst: Fix typo - vertualenv

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1691]
In install.rst we have a typo: vertualenv needs to be changed to virtualenv

**Comment by sam09** [comment]
Is anyone working on it?

**Comment by AbdealiJK** [comment]
@AdeshAtole are you working on this ? I notice a commit in your fork but you arent assigned to it.

**Comment by sils1297** [comment]
@sam09 I've invited you to our org, can you approve at github.com/coala-analyzer ?

**Comment by sam09** [comment]
@sils1297  Thanks!! I accepted it

**Comment by sils1297** [comment]
@sam09 assigned you, at any point feel free to ask any (stupid or nonstupid) questions at https://gitter.im/coala-analyzer/coala

**Comment by sils1297** [comment]
theres https://github.com/coala-analyzer/coala/wiki/Getting-Started-to-Contribute and http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html which is readworthy
