### ISSUE TITLE
Don't use `Lint` when not using an external tool

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1702]
Imo it's a bit unclean if you use `Lint` when you have python modules that do corrections. Like the `JSONFormatBear`. Either inline relevant stuff (since results of different modules could quite differ, that's why I'm in for this one :+1:) or provide a base class that provides this behaviour in the most simple manner.

**Comment by AbdealiJK** [comment]
Blocked as it needs https://github.com/coala-analyzer/coala/issues/1703

**Comment by Makman2** [comment]
Solved with #1990 and https://github.com/coala-analyzer/coala-bears/pull/313

**Comment by sils1297** [comment]
Can this be closed?
