### ISSUE TITLE
Refactor `Lint` to a bunch of functions

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1703]
I see the potential of making the `Lint` class to a module providing the functions to invoke external linter tools. `Lint.lint()` would get all arguments that are currently defined as class-members as parameters. Also `process_output()` could be moved out, since this function is used by some bears directly bypassing actually `lint()` (see #1702).

Opinions?

**Comment by sils1297** [comment]
CC @AbdealiJK

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-24 22:07 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by AbdealiJK** [comment]
I agree - this is a good idea - as currently lint is stateless anyway.

**Comment by AbdealiJK** [comment]
@Makman2 arent you working on this ? (Could you assign yourself?)

**Comment by Makman2** [comment]
Okay this is more problematic than thought. One thing that annoys me most is `check_prerequisites`. We don't want the user to input this `check_prerequisites = is_binary_present(executable)` boilerplate everytime. Since `executable` needs also be available since instantation and setting this variables in constructor is performance-waste, I suggest of using a class-constructing-function, -->
```
def Lint(executable, other_params, ...):
    class LintClass(LocalBear):
        check_prerequisites = is_binary_present(executable)
        # etc etc
    return LintClass
```
Also like seen I want `LintClass` to derive directly from `LocalBear`, since as @AbdealiJK pointed me out multi-file-input for linters is not really supported yet. But there's the option to test via if-statements via a parameter whether GlobalBear features need to be activated or LocalBear features.

I hope I clarified my ideas enough...

Opinions again? :)

**Comment by sils1297** [comment]
Something like

```
CheckstyleBear = linter("java", "--jar", "checkstyle.java", regex="abcd")
```

?

**Comment by Makman2** [comment]
for example, but I thought more of using it like this:
```
class CheckstyleBear(Linter(executable, other_params, ...)):
    def on_run(self, filename, file, other_settings):
        # here one would create the arguments to invoke the linter with
        return ["--lint", filename]

**Comment by Makman2** [comment]
So we keep the ability to dynamically generate our command line (which we need to do anyway) or other stuff^^

**Comment by sils1297** [comment]
why not a decorator then?

**Comment by Makman2** [comment]
would do the same, and inheritting looks a bit clearer for me, that means e.g. `on_run` would actually override the stuff in `Linter`. But yeah in fact a decorator would also be possible^^

**Comment by Makman2** [comment]
Maybe superseded by https://github.com/coala-analyzer/coala/issues/1928 ?

**Comment by sils1297** [comment]
yeah thik so
