### ISSUE TITLE
Constants: Add newlines to crash message

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#1708]
as of now the crash message is just one single line without any newlines,  we should add newlines to this message, the file can be found at coala/coalib/misc/Constants.py
difficulty/newcomer

**Comment by analyticalmonk** [comment]
Simple enough, I will make a PR.

**Comment by sils1297** [comment]
@analyticalmonk hey and welcome! I've sent you an invitation to our org so we can assign you. (We fail to manage all the stuff without assignments, sorry.) Accept at github.com/coala-analyzer. Happy to have you :)

**Comment by analyticalmonk** [comment]
Oh sure! Thanks. :)

**Comment by sils1297** [comment]
@analyticalmonk awesome, seeing forward to your PR. You might want to join our channel at https://gitter.im/coala-analyzer/coala or #coala on freenode or https://telegram.me/joinchat/AuL-lwKZ8JLFZiI6SbtQVw on telegram, whatever suits you they're linked, so we can help you. Our workflow is nontrivial which is why we do those newcomer bugs and give you heavy guidance at every step :) Don't be afraid to ask!

**Comment by sils1297** [comment]
need info from @abhsag24 , see https://github.com/coala-analyzer/coala/pull/1721#issuecomment-189640488

**Comment by AbdealiJK** [comment]
I agree that the terminal should do this if necessary.
That's because I normally keep my terminal on full screen which gives it nearly 100+ chars - It looks weird and irritating to read if you do this in such cases

**Comment by sils1297** [comment]
still in those cases we should rather do a generic solution in PyPrint and
make some auto breaking instead of inserting random newlines in random
messages, that will never solve all cases

**Comment by abhsag24** [comment]
@sils1297 wouldn't auto breaking in pyprint cause problems in a lot of the test cases as well?

**Comment by laxmena** [comment]
I Would like to work on this

**Comment by sils1297** [comment]
@abhsag24 we would fix the version before (== instead of >=) and then change the tests on upgrade

**Comment by AbdealiJK** [comment]
Moved to https://github.com/coala-analyzer/PyPrint/issues/31
