### ISSUE TITLE
docs/install.rst: proxy installation

### ISSUE THREAD

**Issue by srisankethu** [coala-analyzer/coala#1715]
I have faced a difficulity installing coala under proxy.Changes made in install.rst!

**Comment by AbdealiJK** [comment]
This is not specific to coala and is rather a `pip` thing. Should be in `pip` documentation.

**Comment by srisankethu** [comment]
@AbdealiJK yes,you're right but how can one understand that it's a pip thing just by looking at this error message?
![screenshot from 2016-02-17 16 56 04](https://cloud.githubusercontent.com/assets/12644108/13370797/52e32506-dd39-11e5-8663-b3cc9b9332f1.png)
If one wants to install coala successfully the only source available is coala's documentation(for now) and I feel a small note would be good for zero confusion

**Comment by aayn** [comment]
@srisankethu Using pip under proxy isn't that hard. I do it all the time. Just do this:
1. Set your proxy up.
2. Use `sudo -EH pip install <package-name>`.

**Comment by srisankethu** [comment]
@aayn Thanks!
