### ISSUE TITLE
Grammatical errors in git Introduction doc

### ISSUE THREAD

**Issue by erilyth** [coala-analyzer/coala#1725]
These need to be addressed.

1)understanding **about** what one can do with git and thus  ->  understanding **of** what one can do with git and thus
2)``git commit`` which allow us  ->  ``git commit`` which allow**s** us
3)into a so called  ->  into a so**-**called
4) getting current status  -> getting **the** current status

**Comment by sils1297** [comment]
Hey, I've invited you into our org, accept at github.com/coala-analyzer please so we can assign you.

You can always get some help on freenode #coala or https://gitter.im/coala-analyzer/coala

**Comment by Makman2** [comment]
@erilyth Edited your message, highlighted the specific changes^^

**Comment by sils1297** [comment]
@Makman2 please do not edit other peoples messages
