### ISSUE TITLE
Grammatical errors involving Testing and Writing_Good_Commits documents

### ISSUE THREAD

**Issue by erilyth** [coala-analyzer/coala#1730]
1)html  -> HTML
2)tag and and a  ->  tag and-and a
3)that are not self explanatory  ->  that are not self-explanatory

**Comment by sils1297** [comment]
hey could you please stop fixing all our typos? I know it's well meant, I'll explain in the next comment.

**Comment by sils1297** [comment]
We do appreciate your contribution, so do we do the contributions of others. To introduce people to the community we file issues about typos and stuff so if you fix all the typos we can't introduce our newcomers properly anymore.

**Comment by sils1297** [comment]
(E.g. we use LanguageTool basically as a newcomer issue generator, when we need new newcomer issues we can just file them.)

**Comment by erilyth** [comment]
I can understand, thanks for letting me know :)
