### ISSUE TITLE
coala html binary

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1733]
So, as I see it the coala html binary needs to do three things:

 - Make coala-json run and get output from it or just use a predefined location if the file already exists ?
 - Check if `coala-html` bower dependency is installed. (I remember someone saying setup.py has some bower plugin ?)
 - Create a `files.json` for the Files tab to work in coala-html
 - Run a web server so the angular stuff works. And also use webbrowser to open the file automatically (probably with a cli arg)

We probably want an arg to just create the server / open the last result too.

**Comment by tushar-rishav** [comment]
@AbdealiJK 

-  We might want to add an option that allows users to switch between the output from predefined location or run `coala-json` and update the output. 

-  Yes we should create a `file.json` the first time we run coala-json.

-  [Webbrowser](https://docs.python.org/3.1/library/webbrowser.html) is what we might need.

**Comment by tushar-rishav** [comment]
This issue was moved to coala-analyzer/coala-html#31
