### ISSUE TITLE
setup.py on python2 doesnt work again

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1738]
```
ajk@ajk-ThinkPad-R60:~/Documents/coala/coala$ python2 setup.py 
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from coalib import assert_supported_version
  File "/home/ajk/Documents/coala/coala/coalib/__init__.py", line 2, in <module>
    from coalib.misc import Constants
  File "/home/ajk/Documents/coala/coala/coalib/misc/Constants.py", line 37
SyntaxError: Non-ASCII character '\xc3' in file /home/ajk/Documents/coala/coala/coalib/misc/Constants.py on line 37, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
ajk@ajk-ThinkPad-R60:~/Documents/coala/coala$ 
```
It seems when we added `__version__` it broke.
We should maybe call  `assert_supported_version()` in `coalib/__init__` before importing anything else?

**Comment by SanketDG** [comment]
Adding a simple encoding `# -*- coding: utf-8 -*-` at the top of `/home/sanket/coala/coalib/misc/Constants.py` fixes this. Is that the right way?

**Comment by sils1297** [comment]
as long as it fixes it sounds good

**Comment by sudoankit** [comment]
Can I will work on this?

**Comment by Makman2** [comment]
@sudoankit you should've got an invitation, ping again here if you want the issue^^

**Comment by sudoankit** [comment]
I will try doing this. Assign me, please.

**Comment by AbdealiJK** [comment]
Done

**Comment by sils1297** [comment]
@AbdealiJK why is it still open then? What happened?

**Comment by AbdealiJK** [comment]
What I meant by "Done" was that it was assigned to @sudoankit

**Comment by sudoankit** [comment]
Adding the `UTF-8` encoding gives me -
```
caffeinated:coala sudoankit$ python setup.py
coala supports only python 3.3 or later.
```

So, yep, done.

**Comment by AbdealiJK** [comment]
@sudoankit can you make a PR so we can fix it ?
