### ISSUE TITLE
get_public_members documentation comment is wrong

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1739]
in coalib/misc/Decorators.py

difficulty/newcomer

**Comment by sam09** [comment]
Hey.. I would like to work on it..

**Comment by sils1297** [comment]
you already had a newcomer issue and know the workflow, feel free to take the challenge of something cool like a new bear in coala-bears or something :)

**Comment by sam09** [comment]
Okay.

**Comment by tushar-rishav** [comment]
@sam09 Look for [https://github.com/coala-analyzer/coala/issues?q=is%3Aopen+is%3Aissue+label%3Adifficulty%2Flow](Difficulty/low) or [medium](https://github.com/coala-analyzer/coala/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Adifficulty%2Fmedium+) maybe? :D

**Comment by sam09** [comment]
@tushar-rishav Thanks :+1:

**Comment by laxmena** [comment]
I would like to work on this

**Comment by AbdealiJK** [comment]
@laxmena I've invited you to the coala organization. please accept the invitation so we can assign this to you

**Comment by laxmena** [comment]
Thankyou

**Comment by AbdealiJK** [comment]
@laxmena Ive assigned this to you.
We recently made a new newcomer doc (its not yet there on the website). Could you follow it [link](https://github.com/Adrianzatreanu/coala/commit/631a3f903cc704c79488f58310d80380bd79e2c6?short_path=2549fa2#diff-2549fa2ef2c64aed6e741e2f60b45e84) and let us know your opinon and whether any part of it is confusing to you ?
CC @Adrianzatreanu - as he's writing the docs in that link.

**Comment by Adrianzatreanu** [comment]
Sure, im on gitter today, feel free to message us there.
