### ISSUE TITLE
Creating a new git tutorial for newcomers

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#1741]
Since we are leaving the wiki page behind, i am also willing to create a small git tutorial that can at least
help newcomers get their first patch and contribution done. i will try to explain the commands briefly so that they at least understand what they are doing.

**Comment by laxmena** [comment]
I would also like to contribute to this.

**Comment by AbdealiJK** [comment]
This is already assigned to someone. Also, its recommended you solve 1 issue first :)
