### ISSUE TITLE
Using $ for all shell commands in docs

### ISSUE THREAD

**Issue by prodicus** [coala-analyzer/coala#1747]
@AbdealiJK suggests using `$` for all shell commands in docs. 

More specifically implemented in this PR #1746

**Comment by AbdealiJK** [comment]
@prodicus Assigning this to you as you're already working on it ^_^
Welcome to coala btw !

**Comment by Adrianzatreanu** [comment]
Hey @prodicus , are you still working on this :) ? Im asking since it's been a few days since you last worked on your PR, please ping us if you're still here :) !

**Comment by prodicus** [comment]
@Adrianzatreanu Sorry for the delay. Got hung up on some errands. Sending a PR soon :smile:

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity.

**Comment by svsn2117** [comment]
HI i will try working on that...
