### ISSUE TITLE
Catch pkg_resources' exceptions

### ISSUE THREAD

**Issue by rubik** [coala-analyzer/coala#1748]
I ran `coala` and got:
```
An unknown error occurred. This is a bug. We are sorry for the inconvenience.
Please contact the developers for assistance. During execution of coala an exception was raised.
```

Adding a `raise exception` right here:
https://github.com/coala-analyzer/coala/blob/16fdb2eaeb55160eace5724f00e757d305f7b0dc/coalib/misc/Exceptions.py#L19

I discovered that the original exception was this:
```
Traceback (most recent call last):
  [...]
  File /home/user/lib/python3.5/site-packages/pkg_resources/__init__.py, line 835, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (libclang-py3 0.3 (/home/user/lib/python3.5/site-packages), Requirement.parse('libclang-py3==0.2'), {'coala'})
```

So I think that `pkg_resources` exceptions should be handled separately since they're easy to fix.

**Comment by sils1297** [comment]
Thanks, deserves custom handling indeed.

**Comment by aayn** [comment]
I'd like to do this please.

**Comment by AbdealiJK** [comment]
@aayn Ive assigned you

**Comment by aayn** [comment]
@rubik How do I reproduce this?

**Comment by sils1297** [comment]
@aayn do a `pip3 install libclang-py3==0.3 --upgrade` and then run coala

**Comment by aayn** [comment]
@sils1297 And what exception should I raise to catch VersionConflict?

**Comment by sils1297** [comment]
`pkg_resources.ContextualVersionConflict` apparently

**Comment by aayn** [comment]
> do a pip3 install libclang-py3==0.3 --upgrade and then run coala

@sils1297 Even after I do that I get no conflict issue. Anything else?

**Comment by aayn** [comment]
@sils1297  I don't get any conflicts. It just overwrites the other installation. So, is it possible that I send a PR/gist and you just verify if it works?

**Comment by aayn** [comment]
@sils1297 Can you please elaborate on how to reproduce this? I must be missing something.

**Comment by sils1297** [comment]
I don't know it.

**Comment by rubik** [comment]
@aayn Yes, the new package overrides the old one. Then if you run coala you get the error message.

**Comment by aayn** [comment]
@AbdealiJK Can you please 'deassign' me from this? I suddenly have 5 assignments, and exams after that. I'll be a bit inactive for a few days.

**Comment by srisankethu** [comment]
Is this open?

**Comment by srisankethu** [comment]
I followed the earlier conversation and run `coala`. I got no exceptions!

**Comment by Makman2** [comment]
It's more about handling the exceptions received on `VersionConflict`. Now if something like this happens (this depends on your machine what deps you have installed) coala crashes completely, handling this cleanly with a message without crashing would be better :+1:

**Comment by Makman2** [comment]
If you want to reproduce such an exception, you can e.g. install the clang binding v0.3
--> `pip3 install libclang-py3==0.3`

**Comment by srisankethu** [comment]
@Makman2 Yes I have tried that( I followed the earlier conversation). It simply check for libclang-py3.Since it was already present and no file for its uninstallation was found, it simply did an overide.
![screenshot from 2016-03-12 02 53 20](https://cloud.githubusercontent.com/assets/12644108/13715924/c8e58d92-e7fd-11e5-8093-482465e88183.png)

**Comment by srisankethu** [comment]
@Makman2 If this isn't urgent can I do this after a week (on 25th,26th March) ?

**Comment by sils1297** [comment]
I'd love this for the release...

**Comment by sils1297** [comment]
You can do it when you want, if we feel we need it nowish we'll just do it, is that ok?

**Comment by srisankethu** [comment]
@sils1297 ok!

**Comment by Makman2** [comment]
@sils1297 is this really so important for 0.5?

**Comment by sils1297** [comment]
It's a bug, we should strive for cleaning bugs for releases if possible.
