### ISSUE TITLE
A simple typo in the Install.rst file

### ISSUE THREAD

**Issue by prodicus** [coala-analyzer/coala#1749]
The file `/docs/Users/Install.rst` has a typo in it.

Namely the occurence of `Max` instead of `Mac`

**Comment by AbdealiJK** [comment]
@prodicus Thanks for the bug report.
Im not assigning this to you as youre already solving 2 other newcomer issues. We recommend you solve a `difficulty/low` issue after 2 newcomer issues, as you're completely ready for them by then !

Leaving this open for other newcomers to solve

**Comment by prodicus** [comment]
:+1: no problem

**Comment by priests** [comment]
Can i take this up?
I've already made a commit but I've not been assigned.

**Comment by SanketDG** [comment]
@priests You have been invited to the coala organization. please accept the invitation so we can assign this to you.

**Comment by priests** [comment]
@SanketDG Thanks ! :) I've been added to the org.

**Comment by SanketDG** [comment]
@priests Make us proud! If you get stuck, join us at https://gitter.im/coala-analyzer/coala :)

**Comment by sils1297** [comment]
or if you don't get stuck join anyway because we love to get to know new contributors :P

**Comment by priests** [comment]
@SanketDG  Will give my best !! 
@sils1297 I'm in. :) :+1:

**Comment by prodicus** [comment]
@priests Welcome to coala! :smile:

**Comment by priests** [comment]
@prodicus  Thanks !  :)

**Comment by sudoankit** [comment]
I have edited the install.rst file to and changed "max" to "Mac".
Should I give a PR?

**Comment by Adrianzatreanu** [comment]
Sudoankit, this issue seems to be assigned already to someone else. Can you pick another one please?

**Comment by sudoankit** [comment]
Okay, but the issue is fixed.
