### ISSUE TITLE
Provide coala support for setuptools

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1754]
Integrate a setup command so people can import and use it as an install/build step with setuptools.

**Comment by Makman2** [comment]
Shall we open a new repository for it then @sils1297 ?

**Comment by AbdealiJK** [comment]
Well, isn't this pretty easy right now ? just make a build command, import coala and do `main()`
Pytest does the same FYI
I am wondering if there's a better method of doing this

**Comment by sils1297** [comment]
the best way of doing this is with a doc page IMO

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-01 4:28 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by theaverageguy** [comment]
Is it open? Please assign me this. :)

**Comment by SanketDG** [comment]
@theaverageguy are you still working on this? Just let us know.

**Comment by theaverageguy** [comment]
PR today.

**Comment by Makman2** [comment]
@theaverageguy ping

**Comment by Adrianzatreanu** [comment]
unassigning due to lack of response within 4 days.

**Comment by NalinG** [comment]
Hi, I would like to work on it , can you assign me this issue.

**Comment by sils1297** [comment]
Hey welcome back @NalinG ! Ping us on gitter if you need anything :)

**Comment by NalinG** [comment]
What we have to do is to create a setup file using setuptools library and create a coala egg??
That means we have to create a setup.py file and a doc page explaining all the details

**Comment by Makman2** [comment]
Don't know what I wanted exactly, seems this one doesn't really apply^^
