### ISSUE TITLE
Mention commit style guide in newcomer

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1757]
Mention the commit style guide in the Newcomer page in docs

I think we should add an example commit message about typos (As it's the most popular newcomer issue)

```
.travis.yml: Fix typo xontainer -> container

Fix a minor typo in the file for better readability.

Fixes #xxx
```
would be nice

@Adrianzatreanu can you do this ?

**Comment by manojpandey** [comment]
Hook me to this task, will do this :)

**Comment by Adrianzatreanu** [comment]
all yours.

**Comment by manojpandey** [comment]
@Adrianzatreanu: Where should it go?
Does it look fine after [this example](http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html#example) along with the example provided ?

**Comment by Adrianzatreanu** [comment]
I think its okay :)
