### ISSUE TITLE
Inclusion of venv in .gitignore

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala#1761]
Most of us work on `virtualenv` in Python but `.gitignore` has no `venv/` listed. Is there any particular reason for it ? 

I know `venv` name is not compulsory to use but since Node, Bower etc have their packages listed under a fixed directory name so just a suggestion, if making `venv` a standard name for virtual environments in our project makes it easier for other people as well we can maybe add it to .gitignore.

**Comment by AbdealiJK** [comment]
Nope, it should be added

**Comment by mr-karan** [comment]
Can I submit a PR for this then ?

**Comment by AbdealiJK** [comment]
@mr-karan You have already submitted 2 PRs for newcomer issues. I suggest you go on to `difficulty/low` and above from now on. ( Let newcomers solve newcomer issues :) )

**Comment by mr-karan** [comment]
Sure.

**Comment by laxmena** [comment]
Can I submit a PR for this?

**Comment by AbdealiJK** [comment]
Assigned you @laxmena

**Comment by mr-karan** [comment]
While @laxmena is at this, it would be great if you could also do this in all Python dependent repos under `coala` organization.

**Comment by AbdealiJK** [comment]
Can you make appropriate bugs in the appropriate repos ? (only coala-bears
i think)

The more newcomer issues we have the better !

**Comment by mr-karan** [comment]
@AbdealiJK done. https://github.com/coala-analyzer/coala-bears/issues/135

**Comment by Adrianzatreanu** [comment]
deassigning to lack of response multiple days.

**Comment by mr-karan** [comment]
It's done already by me https://github.com/coala-analyzer/coala-bears/pull/185

**Comment by AbdealiJK** [comment]
@mr-karan that was coala-bears.
This is coala

**Comment by mr-karan** [comment]
Ah my bad sorry

**Comment by sapo1438** [comment]
I'll do it
