### ISSUE TITLE
Typo in from_clang_fixit method annotation in Diff class

### ISSUE THREAD

**Issue by arush0311** [coala-analyzer/coala#1765]
obejct is written instead of object

**Comment by saurabhiiit** [comment]
Can I submit a PR for this?

**Comment by AbdealiJK** [comment]
@saurabhiiit Assigning this to you.
I also notice you already have an open PR. I'd suggest you fix that first.

**Comment by saurabhiiit** [comment]
@AbdealiJK  Thanks ... Sure I will fix the previous one first
