### ISSUE TITLE
Typo in Install.rst

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala#1767]
In `docs/Users/Install.rst`
> If a bear still doesn’t work for you, please make sure that you have a decent version of npm installed. Many linux distributions ship a very old one.

I think you mean _recent_ and not _decent_

**Comment by sudoankit** [comment]
Should I look into this?

**Comment by Makman2** [comment]
This time I'll assign you again for another newcome issue since you already made a commit. Though please don't take up issues next time you aren't assigned to, especially no newcomer issues since this one is your third^^

**Comment by Makman2** [comment]
So wait for a response from our side next time, okay? :)

**Comment by sils1297** [comment]
actually I meant decent...

**Comment by Makman2** [comment]
what does "decent" mean in that case? :O

**Comment by mr-karan** [comment]
Oh. My bad. `D` and `R` being close together and also the context somehow made me believe it's a typo. You can close this.

**Comment by sils1297** [comment]
@Makman2 look it up in the dict. But apparently the wording is a bit weird so we can take the fix

**Comment by Makman2** [comment]
I know what "decent" is, I just don't understand the context here...

**Comment by sils1297** [comment]
well the versions before just aren't decent :P

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-01 19:08 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
yeah just, decent is not the best word in this case :3

**Comment by sils1297** [comment]
then take the fix

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-01 19:14 GMT+01:00 Mischa Krüger <notifications@github.com>:
