### ISSUE TITLE
Outdated section in Install.rst

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala#1768]
[This](http://coala.readthedocs.org/en/latest/Users/Install.html#generating-documentation) section assumes there's a file `docs-requirements.txt` but there's no such file in the latest version.
I think we should replicate / remove this section as it's already mentioned [here](http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Documentation.html)

**Comment by Makman2** [comment]
https://github.com/coala-analyzer/coala/blob/master/docs-requirements.txt
Seems everything is valid, imo there's no need to change something. It makes sense that the installation is described shortly in both pages, **Writing Documentation** and **coala Installation**.

**Comment by mr-karan** [comment]
You linked to coala-analyzer/coala. But you're supposed to use `coala-bears` repo.

> git clone https://github.com/coala-analyzer/coala-bears/
[source](http://coala.readthedocs.org/en/latest/Users/Install.html#installing-coala-from-source)

**Comment by Makman2** [comment]
Why coala-bears? The header says **coala Installation**.
Maybe we need also `docs-requirements` inside the coala-bears repo^^

**Comment by mr-karan** [comment]
Yeah either that. Because otherwise you would get an error like this:

![screenshot from 2016-03-01 20-50-05](https://cloud.githubusercontent.com/assets/5689132/13431446/6fb5f3c6-dfef-11e5-9ac6-28a87fb04cbf.png)

**Comment by Makman2** [comment]
@sils1297 we use sphinx already to generate documentation out of docstrings, right?

**Comment by Makman2** [comment]
If so we migrate this issue to coala-bears^^

**Comment by AbdealiJK** [comment]
So, the thing is in bears we do not generate API yet.
Maybe we should ? If we do, then it needs to be done in `coala` or else we'll have 2 sets of documentation for coala and coala-bears
Which gets confusing.

This brings me back to having a new repo for docs of all the repos in the org `coala-docs` to clean things up

**Comment by Makman2** [comment]
I'm against outlining docstrings, that makes maintenance by far worse.

**Comment by Makman2** [comment]
Okay since we don't generate them yet there's no need to add it as docs-prerequisites there.
@mr-karan since your pages mention coala installation and not coala-bears installation I would pledge for closing this issue as `invalid`.

**Comment by mr-karan** [comment]
`invalid`
