### ISSUE TITLE
add neat little gif to readme

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1771]
yeah!

**Comment by AbdealiJK** [comment]
@aachiritoaei still on this ?

**Comment by sils1297** [comment]
this one's important though might class with the PRs from @cw1

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-22 5:44 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by Adrianzatreanu** [comment]
Unassigning as per gitter discussion

**Comment by AbdealiJK** [comment]
Nobody doing this :( ?
Would be really cool to have
