### ISSUE TITLE
StringProcessing: Documentation typo

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1772]
https://github.com/coala-analyzer/coala/blob/master/coalib/parsing/StringProcessing/Core.py#L240

Change `escaped` to `escape`, since `\\` is the escape character, not an escaped one :)

**Comment by yufw** [comment]
Hi,

I am a newcomer and I have created a pull request fixing this typo.

**Comment by sils1297** [comment]
Hi, I've invited you to our org. http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html might guide you the way towards getting your first contribution accepted.
