### ISSUE TITLE
Add a syncing section in git help

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#1774]
Lots of newcomers have been asking on how to keep their fork/branch/PR in sync with upstream.
Might be helpful to add some info on how to do that.

difficulty/low

**Comment by mr-karan** [comment]
This might help : https://help.github.com/articles/syncing-a-fork/

**Comment by SanketDG** [comment]
Also, this should be linked to, https://asciinema.org/a/11269

**Comment by arafsheikh** [comment]
@SanketDG I don't think that fits in this issue. I'll open a different issue for adding a commit squashing section.
