### ISSUE TITLE
We need to improve our getting started docs

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1776]
Many many people have problems with rebasing. We just need a little (not too explaining section, if someone wants explanation refer to our other guides) section with

```
Rebasing for dummies - GitHub

If you don't have setup upstream -> look here

Rebasing onto the newest changes

git fetch upstream
# on your branch
get rebase upstream/master
# repush changes with forces since rebase overwrites history
git push --force
```

**Comment by srisankethu** [comment]
@Makman2 Can I take this up?

**Comment by sils1297** [comment]
isn't this issue clashing with https://github.com/coala-analyzer/coala/issues/1774 ? I'd categorize it as a duplicate which is a little unfortunate since work on both issues has started already.

**Comment by sils1297** [comment]
@srisankethu sorry for wasting your time, this should have been detected earlier :/

**Comment by Makman2** [comment]
@sils1297 #1174 refers to git help, not to the newcomer guide^^
