### ISSUE TITLE
Move link to another line

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#1780]
Right now, we have a link in the "meet the community" paragraph that overcomes the line length limit. We would like it on the next line, as this wont remove the aspect of the page.

**Comment by Makman2** [comment]
Which file?

**Comment by AbdealiJK** [comment]
Well, he's mentioned a "meet the community" para ... but not which file the
paragraph exists in.

**Comment by Adrianzatreanu** [comment]
@ the newcomer page, my bad :)

**Comment by swatilodha** [comment]
I would like to fix this issue.

**Comment by Adrianzatreanu** [comment]
@swatilodha hey. it seems you have already closed 2 PRs. Are you still working on it? do you need some help? feel free to message us on https://gitter.im/coala-analyzer/coala

**Comment by sils1297** [comment]
or #coala on freenode if that's better for you

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-06 14:15 GMT+01:00 Zatreanu Adrian-Gabriel <notifications@github.com

**Comment by Adrianzatreanu** [comment]
unassigning due to long inactivity.

**Comment by sophiavanvalkenburg** [comment]
I'll do this!
