### ISSUE TITLE
Globbed in-line bear ignores

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#1781]
Currently when the user gives `# Ignore SpaceConsistencyBear`, that bear does not execute on the line below. I think it would be an useful feature to allow the user to mention globs such as
`# Ignore (Py*Bear | Space*)` which will ignore all the python bears and the space consistency bear.

**Comment by hypothesist** [comment]
@sils1297 should we consider renaming `ignore` for ignoring inline? It is an awfully common word in comments in a code and it is matching way too many unnecessary lines, slowing it down (it would match quite a lot if you run it on a huge code base). `start ignoring` and `stop ignoring` are good, but how about `ignore` -> `ignore_bears` or something like that?

**Comment by sils1297** [comment]
the reason we have this so it reads natural, let's not destroy it. Come up with a concrete example where it'd slow it down?

**Comment by hypothesist** [comment]
Even in coalib, it comes up over 10 times (I know it's not much, but it could potentially be) when there isn't a legitimate use. But yeah, I agree it's natural.

**Comment by hypothesist** [comment]
@sils1297 Another decision to make: let it be `# Ignore Line*,Space*` or make that glob-format (i.e. `# Ignore (Line*|Space*)`). The first option is natural and simple while the second is more standardardized.

**Comment by sils1297** [comment]
both will be possible right now because before the globbing is applied at least currently the comma splitting should be done
