### ISSUE TITLE
Replace old link

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#1782]
Right now we are using in the Newcomers document page an outdated link. We would like to replace it with this one : http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html , as this is newly written.
The link to be replaced is in Start working section, at the end.

**Comment by priests** [comment]
Can I take this up?
It's the git link in Start Working section that comes later in the page. Right?

**Comment by sils1297** [comment]
@priests you've already contributed haven't you? Don't strive to do something cool?

**Comment by priests** [comment]
@sils1297   I've done one newcomer issue. Should move up the difficulty level ?

**Comment by sils1297** [comment]
sure take difficulty/low, also look at the coala-bears repo, over there
there are lots of cool things that are post-newcomer friendly :)

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-02 21:22 GMT+01:00 priests <notifications@github.com>:

**Comment by priests** [comment]
:smile: :+1:

**Comment by Adrianzatreanu** [comment]
labeling this high as we really need to do this asap, since we are planning to remove the other link. *in case its not removed already*

**Comment by aachiritoaei** [comment]
@Adrianzatreanu Can I take this one? As far as I can see, the old link is already broken.

**Comment by AbdealiJK** [comment]
@aachiritoaei ive sent you an invitation to the coala organization on github so we can assign this to you

**Comment by Adrianzatreanu** [comment]
Assigned you! welcome to our org :) feel free to contact us on gitter if you encounter any issues, people will be glad to help

**Comment by sils1297** [comment]
https://gitter.im/coala-analyzer/coala

**Comment by Adrianzatreanu** [comment]
he already said Hello World to our gitter a few days ago, i remember him, so i supposed he knew the link :p
