### ISSUE TITLE
Double backticks missing

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#1783]
I think that in our Newcomers document page, the ``Pull Request`` syntax should be more important . We should caption it using double backticks, so it gets shown as code. Prefferably, this should be done all over the document.

**Comment by manojpandey** [comment]
Sure, I want to get assigned ! :)

**Comment by Makman2** [comment]
Oh sorry, I haven't seen that you've already taken up 2 newcomer issues. We usually keep them open for other newcomers as well so they get familiar with our merge-process like you currently :)

**Comment by justuswilhelm** [comment]
I want to get assigned :)
