### ISSUE TITLE
Frequent Errors in CI regarding CoalaDbus

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#1788]
https://circleci.com/gh/coala-analyzer/coala/5227

CC @AbdealiJK

**Comment by Makman2** [comment]
Are they still present? Haven't seen this error for a while...

**Comment by SanketDG** [comment]
Yep this was fixed in https://github.com/coala-analyzer/coala/commit/e06484638cbfcd5b47f889a2eb6bd82cb238f1c1
