### ISSUE TITLE
Git_Help.rst: Add a section explaining commit squashing

### ISSUE THREAD

**Issue by arafsheikh** [coala-analyzer/coala#1789]
As @SanketDG pointed out this can be used: https://asciinema.org/a/11269

`difficulty/low`

**Comment by theaverageguy** [comment]
Working on it.

**Comment by arafsheikh** [comment]
@theaverageguy I think this is already being done here #1791

**Comment by AbdealiJK** [comment]
No, that PR has been canceled. 
@theaverageguy assigning you

**Comment by sils1297** [comment]
@theaverageguy stop working on this for now please. I think this should be done after or as part of https://github.com/coala-analyzer/coala/pull/1775.

**Comment by AbdealiJK** [comment]
@theaverageguy unassigning you because @sils1297 says so + youre working on way too many issues at the same time

**Comment by saurabhiiit** [comment]
Can I submit PR for this ?
