### ISSUE TITLE
Add docs to norecursedirs in pytest config

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#1790]
Lots of RST files are being taken in as tests, they should be ignored.
See here, https://circleci.com/gh/coala-analyzer/coala/5242

As for the doctests in `docs/Users/Glob_Patterns.rst`, they should be moved to the actual python function's docstring instead.

**Comment by AbdealiJK** [comment]
RST files are added on purpose because they contain doctests.

**Comment by AbdealiJK** [comment]
I'm closing this, as I'm fairly sure we want that (Im the one who added it)
Reopen if you think something's still wrong

FWIW Theres currently 1 .rst file which has doctests - Globbing i think

**Comment by SanketDG** [comment]
@AbdealiJK Oh. This is why only one passed. :smile: 

Can we not put those doctests in the `fnmatch()` function itself?
Having tests in docs is okay, but we do have a better option.
Besides, its general practice to put in doctests in docstrings.

**Comment by AbdealiJK** [comment]
@sils1297 comments on that ?
Now that we have api docs it does make sense to remove the globbing tutorial and just like the Globbing module's api doc

**Comment by sils1297** [comment]
Yeah we should deduplicate

**Comment by SanketDG** [comment]
Reopening based on the above info

**Comment by sils1297** [comment]
Wait I disagree, we should encourage people to use doctests in regular documentation, I'm against closing this. This can be used to autovalidated docs.

**Comment by SanketDG** [comment]
Closing this as per discussion with @sils1297 and @AbdealiJK 

From @AbdealiJK:
> Having an extra test (And ensuring our documentation has a correct example) is worth having a few extra lines of noise (me thinks)

:+1:
