### ISSUE TITLE
replace spaces with '_' in coalang files

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#1797]
so our ConfParser treats keys with spaces as two different keys, so we should replace the spaces in our coalang keys with an underscore

**Comment by abhsag24** [comment]
as @AbdealiJK  suggested on gitter we could also just escape the spaces so `key1\  key2` is named `key1 key2`

**Comment by AbdealiJK** [comment]
Just a note: We finally went with underscores as it was easier to read rather than escaping. Also, as no bears use coalangs yet, it doesnt break coala-bears

The related PR is https://github.com/coala-analyzer/coala/pull/1815
