### ISSUE TITLE
cache checked files

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#18]
Auto-cache:
 * caches which file is checked by which filter
   * attention: how is this affected by version control systems?
Filter cache:
 * via fillib

**Comment by sils1297** [comment]
from gitter:

so if only one file is changed local bears are only rerun for this file as well as global bears
if configuration gets changed only the changed sections get rerun

**Comment by hypothesist** [comment]
@sils1297 close this?

**Comment by sils1297** [comment]
yes
