### ISSUE TITLE
Dirs for cache and configs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1805]
I think we should use https://pypi.python.org/pypi/appdirs/1.4.0 instead of defining our own stuff for config dirs and storage of things like tags.
Looks useful and easier to work with

**Comment by sils1297** [comment]
yes! Sounds good.

**Comment by Makman2** [comment]
Something else except for tags we need to consider?

**Comment by arush0311** [comment]
Can I work on this?

**Comment by AbdealiJK** [comment]
@Makman2 this would only affect tags right now
@arush0311 Ive assigned you

**Comment by sils1297** [comment]
@arush0311 still active on this? Please respond ASAP.

**Comment by arush0311** [comment]
@sils1297 actually my exams have started. Can you assign it to someone else?

**Comment by sils1297** [comment]
Cool no problem, we'd appreciate a heads up next time :)
