### ISSUE TITLE
Use pip's parser for requirements

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1806]
Pip apparently has a parser to parse requirements.txt and to be used in setup.py

http://stackoverflow.com/questions/14399534/how-can-i-reference-requirements-txt-for-the-install-requires-kwarg-in-setuptool

We should use that.

**Comment by sils1297** [comment]
what's the advantage?

**Comment by AbdealiJK** [comment]
It's standardized.
Although it's a very simple function - always good to use a standard method available from the package manager itself :)

**Comment by AbdealiJK** [comment]
Not sure if this complicated things though.
Does `pip` become a "requirement" ? Is pip already a requirement ? Can we use easy_install for installing coala right now ?
I've never used python without pip - so, not sure.

**Comment by tushar-rishav** [comment]
@AbdealiJK Following our discussion on last PR, should we close this issue too?

**Comment by AbdealiJK** [comment]
@tushar-rishav yes.
closing it
