### ISSUE TITLE
Using JSON for configuration files

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#1817]
Would it be better to use JSON for configuration files instead of a text file that needs to be parsed?

**Comment by AbdealiJK** [comment]
just a note that there's also an earlier issue for yaml https://github.com/coala-analyzer/coala/issues/795

Also, more python folk prefer ini I guess. Tox uses ini based, setup.cfg uses ini based. Python has a module named configparser which is also ini based.

BUT: As coala is language agnostic I see no reason to cater specifically to pythonistas :)

I guess json is JS ... but it's popular enough to be called generic ?


NOTE: This would solve a lot of problems with escaping stuff and also with writing back the stuff.
Would fix https://github.com/coala-analyzer/coala/issues/922 too ?

**Comment by sils1297** [comment]
We could add support for JSON easily I guess, I think we still should support INI like files, they're less verbose in general, less stuff to type

**Comment by Makman2** [comment]
That's why I also favor our current config format, JSON is much more verbose. Also we don't need nested constructs like JSON offers^^
But yeah JSON support should be possible anyway :+1:

**Comment by AbdealiJK** [comment]
Closing as `wontfix/accepting patches` :)
Not important, as ini files work fine for now.
