### ISSUE TITLE
remove bears/test in Writing_Tests.rst

### ISSUE THREAD

**Issue by srisankethu** [coala-analyzer/coala#1821]
`bears/tests` does not exist->https://github.com/coala-analyzer/coala/blob/master/docs/Getting_Involved/Writing_Tests.rst

difficulty/newcomer

**Comment by AbdealiJK** [comment]
We need to mention it's in `tests` folder in coala-bears repo and also in `tests` folder in coala repo.
They were moved recently and the docs have not been changed to reflect this move

**Comment by iamgroot42** [comment]
Created a PR to fix this issue : https://github.com/coala-analyzer/coala/pull/1867

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity.

**Comment by Adrianzatreanu** [comment]
oh, you weren't even assigned, nevermind.

**Comment by BigDproject** [comment]
i will try to work on this
