### ISSUE TITLE
Do not display 'Open in editor' after 'Apply the patch automatically' option, if patch application suceeds

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#1822]
Example: SpaceConsistencyBear

**Comment by sils1297** [comment]
you mean *after* patch application succeeds? Don't we do it already? I think we don''t show it if there's a conflict.

**Comment by AbdealiJK** [comment]
he meant:

Do not display 'Open in editor' adfter 'Apply the patch automatically' option, if patch application suceeds

**Comment by hypothesist** [comment]
http://asciinema.org/a/bxxeml0m1d48cfy2czswmatm9

Example

**Comment by AbdealiJK** [comment]
Basically, if a patch has successfully been applied, he does not want to again press 0 to move on to the next result.
he things that if the patch applied successfully coala should ask the user to do anything else.

**Comment by sils1297** [comment]
So our action design is quite generic, I guess we'll want to give actions the possibility to return something that tells us "the user is unlikely to want to do another thing with this result" and in that case we should auto-end the interactive session for this result.

**Comment by AbdealiJK** [comment]
I think we should close this as `wontfix/accepting patches` it's quite complicated and not worth the effort honestly.
What are your opinions ?
