### ISSUE TITLE
Add descriptions to coalang keys

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#1824]
https://github.com/coala-analyzer/coala/blob/master/coalib/bearlib/languages/definitions/__init__.py is currently undocumented.

**Comment by Makman2** [comment]
What keys are missing?

**Comment by hypothesist** [comment]
The _descriptions_ of the keys is missing, not the key itself.

**Comment by hypothesist** [comment]
Something like what `names` is, `extensions` is, ... (it's a new-comer issue I think)

**Comment by Makman2** [comment]
Ah sorry, yeah that's good :+1:

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#50
