### ISSUE TITLE
coala shouldn't store previous input values in case of failed execution

### ISSUE THREAD

**Issue by srisankethu** [coala-analyzer/coala#1825]
Noticed case:

I tried opening affected files in an editor.I gave an invalid editor name and the execution failed.But when I tried to open the editor again, i get an error because coala takes in the 'number of action' and applies it to check the editor name.

**Comment by Makman2** [comment]
so for clarification:
After a failed OpenEditorAction, the editor-name is saved for the next try. So i if the user retries now, he isn't asked for the editor again and coala tries to reopen the invalid editor again, which immediately leads to failing again.

**Comment by srisankethu** [comment]
Yes!...Can you assign this to me?
