### ISSUE TITLE
Follow up section of Git Help in docs needs to be reworded.

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#1827]
http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html#follow-up

Instead of PR rejection, the point of having commit reviews and re-iterations of the PR should be mentioned.

**Comment by AbdealiJK** [comment]
I agree. We should mention "improvements to your PR will be suggested" as its more positive.

**Comment by vinc456** [comment]
I'll work on this.
