### ISSUE TITLE
Docs do not build

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1830]
The badge is displayed in red which signals an error for me, but the latest docs means everythings alright. We should change color^^

**Comment by AbdealiJK** [comment]
How do we do this though ?

**Comment by niraj8** [comment]
@sils1297 can change preferences on readthedocs.

**Comment by sils1297** [comment]
wow actually it's red because it fails! https://readthedocs.org/projects/coala/builds/

**Comment by sils1297** [comment]
if somebody has time to look at this (@WJCode?) please step up ASAP, we should fix that for the release

**Comment by WJCode** [comment]
It seems that this is has been happening recently with readthedocs. See [here](https://github.com/rtfd/readthedocs.org/issues/2002). I triggered a build manually and it [passed](https://readthedocs.org/projects/coala/builds/3793570/).

Apart from the recent 6 failures in the list of builds, there was just a single build that had the same error almost [2 weeks back](https://readthedocs.org/projects/coala/builds/3752048/).

**Comment by AbdealiJK** [comment]
This seems to be a bug on their side because the API is giving a 500 error ?

**Comment by WJCode** [comment]
Yes, our docs seem to be fine

**Comment by sils1297** [comment]
so we should keep watching https://github.com/rtfd/readthedocs.org/issues/2002 and our build status, manually retrigger if needed

**Comment by WJCode** [comment]
Yes, I agree. I hope they are able to find and fix the issue soon.

**Comment by WJCode** [comment]
Seems this issue has re-occurred. I triggered a build 3 times but all failed with the same error(server error 500).
Please note the docs currently hosted on readthedocs are from commit `8de8b62f`. @AbdealiJK @sils1297

**Comment by AbdealiJK** [comment]
Have we told them of this bug ? If yes, can you put the link to the issue here ?

**Comment by WJCode** [comment]
Ok. I triggered another build and we succeeded this time. The docs now show the latest commit. :smile:
Also, I commented on the readthedocs bug so hopefully they'll let us know if there's anything we can do.

**Comment by sils1297** [comment]
clearing the milestone but keeping open since we need to keep an eye on this

**Comment by Makman2** [comment]
Did we have problems since last time? If not I think we can close it and reopen/recreate an issue on demand^^

**Comment by sils1297** [comment]
most certainly :/ somebody should really look into this and report it upstream

**Comment by AbdealiJK** [comment]
It's back !
Failed 10+ times and passed 4 times in the past 11 days http://readthedocs.org/projects/coala/builds/

**Comment by sils1297** [comment]
retriggered build FWIW

**Comment by Adrianzatreanu** [comment]
they build now
