### ISSUE TITLE
Windows: cannot run bears in the tutorial

### ISSUE THREAD

**Issue by niraj8** [coala-analyzer/coala#1832]
I tried initialising the .coafile using the command
```coala --files=src/\*.c --bears=SpaceConsistencyBear --save```

here's the output after running the above command.
```src\main.c
|   1| #include[ERROR][05:18:00] An unknown error occurred. This is a bug. 
We are sorry for the inconvenience. Please contact the developers for assistance. 
During execution of coala an exception was raised. This should never happen. 
When asked for, the following information may help investigating:
```

Here's the output from ```coala -L DEBUG``` command - 
[Debug Output](https://nirajftw.cozycloud.cc/public/hastebin/BtnSytDe)

**Comment by Makman2** [comment]
Confirmed

We need to settle this before the next release.

**Comment by AbdealiJK** [comment]
I think this is again a problem that we do not open the file in utf8.

Would adding that `*~ utf-8 ~*` thing on top fix this ? (Its meant for source code, not other files i guess ?)
If not, We need to add encoding="utf-8" for all places we use `open()`.

**Comment by AbdealiJK** [comment]
Just saw the traceback and realized this is a pyprint issue because we added the dot character for spaces
