### ISSUE TITLE
Logo in wiki seems wrong

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1835]
Logo in wiki

https://github.com/coala-analyzer/coala/wiki
is not the same as 
https://github.com/coala-analyzer/coala-artwork/blob/master/artwork/logo/logo.txt

A fair number of lines are different (i.e. slightly differently aligned)
I do not know which is correct :/

Can someone correct this ?

**Comment by sils1297** [comment]
fixes

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/wiki/Home/_compare/9f654f0cfc724c0292cea8b6cdc14e67480da4bc...f1e518251ec398651211e5846624ce45fa425946?diff=unified
