### ISSUE TITLE
MentionBot

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1842]
There's a nice bot which CCs the potential reviewers for a PR
https://github.com/facebook/mention-bot

Maybe we want to use that now that we have many reviewers ?

**Comment by sils1297** [comment]
we actually want something like that in gitmate

**Comment by AbdealiJK** [comment]
Why make something when it already exists ?

**Comment by sils1297** [comment]
For starters I didn't know this existed, basically we had the same idea of using git blame. Second, we want it all integrated in GitMate anyway to build an all in one solution.

**Comment by sils1297** [comment]
Hm, I find the mention bot pretty useless for coala-bears, it's active since a few days there

**Comment by AbdealiJK** [comment]
Out of curiosity: What more were you expecting?
Maybe a feature request on their repo?

-----Original Message-----

**Comment by sils1297** [comment]
Well at least what I had in mind for GitMate would assign people

**Comment by AbdealiJK** [comment]
Btw, I just realized.
Git blame data for coala bears is bad right now. Nearly everything would blame me as I moved the bears folder :p

-----Original Message-----
From: "Abdeali JK" <abdealikothari@gmail.com>
Sent: ‎10-‎03-‎2016 21:09
To: "coala-analyzer/coala" <reply@reply.github.com>; "coala-analyzer/coala" <coala@noreply.github.com>
Subject: RE: [coala] MentionBot (#1842)

Out of curiosity: What more were you expecting?
Maybe a feature request on their repo?

-----Original Message-----

**Comment by sils1297** [comment]
yeah and the blame data seems not very good, not convinced of the algorithm. I want it in gitmate so gitmate has it integrated because it's neat and then you can configure it also and autoassign people instead of doing comments which trigger lots of emails to watching people

**Comment by sils1297** [comment]
FWIW for coala we should decide what's best for coala, I still want to have this feature in GitMate because I think it's a good thing to have.

**Comment by sils1297** [comment]
mention bot is active for coala also now

**Comment by sils1297** [comment]
tried it out, apparently people found it annoying and asked me to remove it. Closing it with that?
