### ISSUE TITLE
Pypi page description

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1843]
This is what I've understood about the pypi package stuff.
If we have a long description, it shows that.
If we do not have a long description, it shows the file README, if its not there, then README.rst

So, I think we should remove the long description and the pypi package description will be much richer and nicer.

Should be done before 0.5.0

**Comment by sils1297** [comment]
fwiw I've seen projects reading their readme in setup.py and giving that variable to the long description just like we do it with the requirements.txt
