### ISSUE TITLE
pyprint and coalib.output.printer

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1844]
I just noticed that pyprint and coaal ahve some duplicated code:

 - String printer: in [coala](https://github.com/coala-analyzer/coala/blob/master/coalib/output/printers/StringPrinter.py) and [pyprint](https://github.com/coala-analyzer/PyPrint/blob/master/pyprint/StringPrinter.py). We should delete the coala copy
 - ESpeakPrinter - Should move it to pyprint
 - HTMLWriter - Should be deleted (I see no use for it)
 - LogPrinter - Should move it to pyprint
 - ListLogPrinter - I think this can be deleted by simply adding a `save_history` arg to the normal LogPrinter

**Comment by Makman2** [comment]
The `LogPrinter`s are not that easy, since it's in fact no functionality pyprint shall provide. We want to use the builtin logging module anyway: #975 
I would say we delete `LogPrinter` and `ListLogPrinter` when #975 is accomplished^^

**Comment by sils1297** [comment]
yes we should remove that stuff, keep logging for now and remoe it when we switch to python builtin logging

**Comment by Makman2** [comment]
* StringPrinter: https://github.com/coala-analyzer/coala/issues/1938
* HTMLWriter: https://github.com/coala-analyzer/coala/issues/1940
* EspeakPrinter: https://github.com/coala-analyzer/coala/issues/1939 and https://github.com/coala-analyzer/PyPrint/issues/36

Can we close this issue then?
