### ISSUE TITLE
Annotations are used inconsistently

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1848]
Only in some files there is use of [function annotations](https://www.python.org/dev/peps/pep-3107/).
It would be good to either use annotations everywhere or don't use them at all.

**Comment by sils1297** [comment]
I think we should define some guidelines about when and when not to use
them.

We need them for enforce signature and the bears, otherwise they're mostly
useless except if the type isn't obvious from the name, not sure what's the
best way to guide this

**Comment by Makman2** [comment]
That's the problem, if you don't do anything with them they are quite useless. Only `@enforce_signature` accesses them and `Bear.get_metadata()` to pass coafile settings down to the custom defined `run()` with you own signature.
like @sils1297 says, we need to discuss what's best^^

**Comment by sils1297** [comment]
Alright, we probably want some docs about annotations and the enforce_signature stuff, @Uran198 would that help you?

**Comment by Uran198** [comment]
Yes, I think guidelines in docs and consistency of code with those guidelines would be enough.

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#49
