### ISSUE TITLE
Add a list of Coala advantages

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1851]
When someone not familiar with coala stumbles upon it, the first thing that goes through his head is: "is it worth the trouble?". Because of this, I think it would be useful to add somewhere at the top of README a list of coala advantages.
Some of them, pointed out by @sils1297 and @Makman2 are listed below.

1. The user can apply easily self written results i. e. if we don't have the right tool, he can quickly write it himself (how quickly depends on the actual analysis he/she wants to perform :grinning:)
2. We have some own checking stuff, like `SpaceConsistencyBear`
3. On long term we want to write more stuff ourselves
4. You have a unified interface you don't need to learn 5 tools but one
5. We provide json, formatted and interactive output for each analysis we have
6. We have an underlying threading model to execute our stuff in parallel, the user doesn't need to care but gets optimal performance

**Comment by AbdealiJK** [comment]
+1 for this. Should be mentioned in the GitHub wiki and docs though.
Readme is already pretty big

-----Original Message-----

**Comment by saurabhiiit** [comment]
Can I submit PR for this?

**Comment by sils1297** [comment]
Imo we should shorten the readme and make sure it contains the important
information

**Comment by tushar-rishav** [comment]
+1 for Readme. Because, Readme is the *first* thing that a guy would see. Maybe we can move the list of advantages into `About` section?

**Comment by Makman2** [comment]
Imo this should belong to the readme. If I search for a codechecking solution, coming directly to the points - why I need it actually - is exactly what someone wants to read.

**Comment by priests** [comment]
Can I take this up?
