### ISSUE TITLE
Use `:type param_name:` for documentation about wanted type

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1854]
Instead of annotating functions with a type (except when used inside `@enforce_signature`, but maybe we can even change that :D), rst offers
```
:type some_number: int
```
We should use that more consistently to document types.

Question is how do we use them inside docstrings?
A.
```
:param x: Description of x
:type x:  int
:param y: Description of y
:type y:  str
```
B.
```
:param x: Description of x
:param y: Description of y
:type x:  int
:type y:  str
```

A or B? :)

**Comment by sils1297** [comment]
I'm against us doing that! sphinx should rather learn annotations!

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-09 0:51 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
Can't sphinx already read annotations? Though I like having types inside the docs since annotations are reflected inside code, this is maybe sometimes not wanted. That's why I suggested this `:type:`^^

**Comment by sils1297** [comment]
if sphinx does it why should we annotate type manually?

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-09 17:59 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
https://pypi.python.org/pypi/sphinx-autodoc-annotation
It's not only about sphinx though, do we want actually annotate every function with types?

**Comment by sils1297** [comment]
rather annotate it that put explicit ":type" thingies into the oc comment that's s verbose and useless!

**Comment by sils1297** [comment]
at least you can use the annotations for stuff

**Comment by Makman2** [comment]
alright :+1:
