### ISSUE TITLE
Constraints on args in bears

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1855]
This is an interesting one.
@sam09 mentioned that some args should always be greater than 0 or False (https://github.com/sam09/coala-bears/commit/e9d42721e2f4c9d369a772a01bfa863d813d5149#commitcomment-16579300)

First question: are multiple data types possible in our FunctionMetadata ? I.e. can I do `typing.Union[int, bool]`
Second question: Can I add constraints on the argument ? something like `int(min=1, max=inf)` or something ? Or in general: `int(lambda x: x > 0)` for positive ints or even `int(lambda x: x%2 == 0)` for only even numbers.

Do we want such features ?
Maybe we can use the method existing pkgs like sqlalchemy use for dbfields which already have such validations ?

**Comment by sils1297** [comment]
If the user lists multiple data types how should coala know in which data type to convert the value into? We could try the first and if we get an exception take the next... could work. Constraints are a bit not easy for that I'd rather start a library that does this :P

**Comment by Makman2** [comment]
Constraints can be just implemented inside `run()`. Doing this inside annotations makes it imo way too complicated and unflexible.

**Comment by Makman2** [comment]
Or the other possibility is defining a custom type with custom wrapper function (which is definitely not easier, but reusable) registered for the settings parser.

Conclusion:
I'm not in for that^^ too complicated and the same can be achieved inside `run()` which in fact offers maximum flexibility.

**Comment by sils1297** [comment]
well hey actually you can do that! Just write a function:

def bool_or_int(value):
    if value == "False":
        return False
    val = int(value)
    if val == 0:
        raise ValueError
    return val

def run(value: bool_or_int):
    pass

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-09 18:29 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
perfect, so in fact we have such a feature :+1:
for a more built-in way and less writing for multi-type support I filed a new issue: https://github.com/coala-analyzer/coala/issues/1859
More complicated constraints can be achieved like @sils1297 suggested manually.

**Comment by AbdealiJK** [comment]
Hey, just saw this discussion.
Reopening for now as I have a few concerns

The bear writer could write their own code ... but isn't it better if we provide this ?
This would make lots of bears repeat that function.
They can make errors in their type casting and so on For example [this](https://github.com/sam09/coala-bears/commit/a41c15d02dc0c93d4e22e5d1fe033c81868ceb08#diff-732cf5cf5f77985606c5e89def5320bfR10) is not the right method of doing it.

Also, python has a standardized way of doing this using `typing.Union` ... why make weird custom methods of doing it ?

@sils1297 regarding which type to use (?) we should make a function to figure that out and [cast](https://www.python.org/dev/peps/pep-0484/#casts) it to the type based on our analysis.

Possible methods:
 - Use a priority of types : If possible to convert to int, do that else do Bool
 - Or just do from left to right ?
I guess this is the part that needs design

**Comment by Makman2** [comment]
That's what #1859 is for. And if python has a way of doing this, when you could write that into #1859.

**Comment by AbdealiJK** [comment]
I didnt see the other issue :/
Nevermind.
