### ISSUE TITLE
Built-in function for chaining types to provide inside Bear.run() as annotation

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1859]
Originated from https://github.com/coala-analyzer/coala/issues/1855, where multiple-types shall be supported. coala already has a way to define your own parsing function:
```python
def bool_or_int(value):
    if value == "False":
        return False
    val = int(value)
    if val == 0:
        raise ValueError
    return val

def run(value: bool_or_int):
    pass
```

The task of this issue to implement a generic function that works like this:
```python
def run(value: typechain(bool, int))
    pass
```
So it takes a sequence of types and tries to parse them in order. If nothing works, raise a `ValueError`.

**Comment by hypothesist** [comment]
Would it be enough to have a helper function that does this job *inside* the function instead of verifying at the function prototype definition?

Example:
```
def run(val_1, val_2): # unrestricted
    types.validate(val_1, [bool, int])
    types.validate(val_2, [string])
```
And `types.validate` raises `ValueError` if it doesn't match. I have no knowledge on how to validate types directly at the argument definition line.

**Comment by sils1297** [comment]
the thing is if we have it as the annotation then coala will auto convert
it and the user doesn't have to care any further, this way he'd have to
manually error out if something's inconveertible and stuff

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-13 13:28 GMT+01:00 Adhityaa Chandrasekar <notifications@github.com>:

**Comment by hypothesist** [comment]
No, we can let the function raise an error if the variable doesn't match the type. The user doesn't need to do anything IMO.

**Comment by Makman2** [comment]
Having this inside the signature is way better since coala is then able to provide more help for that bear. Inside the body coala can't influence/see anything. Also your `validation` function would do pretty much the same, so having the extra signature advantage is good keep^^

**Comment by hypothesist** [comment]
Is a function prototype like

```
@enforce(int, float)
def run(arg1, arg2):
    ...
```

make the enforced variable types available to bear help?

**Comment by sils1297** [comment]
right now it's more:

```
def run(arg1: int, arg2: float):
    ...
```

and coala will always give the bear an int and a float, if conversion is not possible the bear won't be executed

**Comment by Uran198** [comment]
Where does this function have to live?

**Comment by sils1297** [comment]
I think StringConverter would be the right place

**Comment by Makman2** [comment]
@sils1297 what about directly inside Bear? since it's general purpose type-chaining^^

**Comment by sils1297** [comment]
it's general purpose, it's not at all tied to bears

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-20 16:23 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Uran198** [comment]
I want to get assigned :)
