### ISSUE TITLE
Changing invalid links in documents

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#1860]
It seems we have a small number of invalid links that need to be changed a little. You can see those when running ``coala invalidlinks`` in the coala repository; you simply need to open the required file and change it, or let coala handle it :)

P.S. : https://github.com/coala-analyzer/coala/issues?q=is%3Aissue+is%3Aopen+label%3Adifficulty%2Fnewcomer this link doesnt need to be replaced, even though it says its invalid, its because the bear cant authenticate, the link works.

**Comment by sils1297** [comment]
There should be an ignore comment it the bear should be fixed

**Comment by Adrianzatreanu** [comment]
Sorry, i dont understand your comment.

**Comment by sils1297** [comment]
Either the bear doesn't work correctly or an `ignore InvalidLinkBear` comment should be placed so the issue isn't shown anymore

**Comment by Makman2** [comment]
but that is rendered inside the docs^^

**Comment by sils1297** [comment]
No sphinx has comments we already use that

**Comment by Makman2** [comment]
ah alright then this is good :+1:

**Comment by AbdealiJK** [comment]
What do you mean by "the bear cannot authenticate"
The link doesnt need any authentication to open (I don't need to sign into github to see it)

**Comment by sils1297** [comment]
removing newcomer label until https://github.com/coala-analyzer/coala/issues/1860#issuecomment-195266071 is resolved

**Comment by Adrianzatreanu** [comment]
i havent found any invalid links yet while reworking docs, clsoing issue

**Comment by AbdealiJK** [comment]
Also, don't we run InvalidLinkBear on the docs now ?
