### ISSUE TITLE
ResultFilter should manage if files are not in the dicts

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1866]
e.g. for renamings/deletions and so on

```
Traceback (most recent call last):
  File "/usr/src/app/run_coala.py", line 171, in <module>
    main()
  File "/usr/src/app/run_coala.py", line 165, in main
    analyse_commits(git_repo, tempdir, pr)
  File "/usr/src/app/run_coala.py", line 124, in analyse_commits
    results)
  File "/usr/src/app/run_coala.py", line 93, in get_new_results
    old_results[section_name], results[section_name])
  File "/usr/lib/python3.5/site-packages/coalib/results/ResultFilter.py", line 26, in filter_results
    modified_file_dict[file])
KeyError: '/tmp/tmp6l7uhhgp/tests/ruby/RubyLintBearTest.py'
```

**Comment by sils1297** [comment]
argh, this sucks, prototype available on https://github.com/coala-analyzer/coala/compare/sils/resf

**Comment by sils1297** [comment]
but it doesn't work

**Comment by sils1297** [comment]
@fneu I did this workaround in `coala-incremental` and it seems to work:

```python
        # Workaround for https://github.com/coala-analyzer/coala/issues/1866
        affected_files = set(old_file_dicts[section_name].keys())
        affected_files |= set(file_dicts[section_name].keys())
        for file in affected_files:
            if file not in old_file_dicts[section_name]:
                old_file_dicts[section_name][file] = []
            if file not in file_dicts[section_name]:
                file_dicts[section_name][file] = []
```

possibly you can do that kind of small preprocessing and that's it? We should definitely have tests for this!

**Comment by rresol** [comment]
@sils1297  coalib.results.ResultFilter.remove_result_ranges_diffs(result_list, file_dict).
The result list parameter according to the docs contain list of results . I am not able to get this completely.
Will you please explain it ?

**Comment by fneu** [comment]
@rresol We have a result class in `coalib/results/Result.py`. So for this parameter a list of instances of this result class or a subclass should be passed.

**Comment by fneu** [comment]
@rresol by the way since I see now that you are assigned for this issue:

In `coalib/results/ResultFilter.py` put:

```
def ensure_files_present(original_file_dict, modified_file_dict):
    """
    Ensures that all files are available as keys in both dicts.

    :param original_file_dict: Dict of lists of file contents before  changes
    :param modified_file_dict: Dict of lists of file contents after changes
    """
    affected_files = set(original_file_dict.keys())
    affected_files |= set(modified_file_dict.keys())
    for file in affected_files:
        if file not in original_file_dict:
            original_file_dict[file] = []
        if file not in modified_file_dict:
            modified_file_dict[file] = []
```

and put this as the first line of `filter_results()`:
`ensure_files_present(original_file_dict, modified_file_dict)`

A least that's what I came up with so far and I think it's pretty much what @sils1297 expects here. It also seems to work well although I could not yet find the time to write any tests for it. Hope this helps :)
