### ISSUE TITLE
nocheck for Interactor

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#187]
Check if the line of the result contains a "nocheck" or "nocheck: bear_name" which matches origin of the result, if thats the case dont use it!

We'll need a concept first especially for results that affect multiple lines.

**Comment by sils1297** [comment]
So I'm in favor of filtering the results in Processing.py (ex SectionExecutor) and in that filter function we give it the file dict and we do the following: (concept - yeah!)

Before processing results search all files for `disable: any_python_identifier,any_python_identifier...` and the same for enable, thus collecting exclude ranges for all bears. We only want to do that once as it costs.

1. We exclude HiddenResult
2. We look if the Result is within an exclude range.

**Comment by Makman2** [comment]
Don't we refactored the Interactor class?

**Comment by sils1297** [comment]
Yeah, we probably want some general utilities for that.

**Comment by Makman2** [comment]
@sils1297 Would you mind moving this to 0.4?

**Comment by sils1297** [comment]
If I self assign an issue and set its milestone, why do you have anything against me doing it?

**Comment by Makman2** [comment]
I think it's just out of scope for 0.3, I don't have anything against you doing this issue :)

**Comment by sils1297** [comment]
and here comes the fix, pending review :)
