### ISSUE TITLE
Document coala's dependancy management 

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#1871]
So coala has cool way in which bears can depend on other bears, but it's undocumented right now, it'd be nice to have documentation regarding how this works :)

**Comment by AbdealiJK** [comment]
Currently I think Clang bears are the only ones that uses this feature. So
first step for anyone solving this would be to read that and understand how
it uses dependency with bears

**Comment by sils1297** [comment]
@abhsag24 do you mind? :P If you can't make it it's ok, just unassign when you know.
