### ISSUE TITLE
Cleaning issues a little.

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1875]
Currently issues are used both for discussions and actually for issues i. e. things that should be done. I think it would be good to either use a mailing list for discussions entirely or to use some issues for discussions and some for stating very clearly what has to be done. In this way when someone new wants to contribute he will not have to read through all of the comments(and ideally he should read no comment at all) and right away can start working on a task.
So, the labels can be used to mark issues which are discussed and which are ready to be worked on. It's somewhat implicit right now. I think it would be helpful to add information to wiki or `CONTRIBUTING.md` that `needs-design` is for discussion and when difficulty is set it's ready to be worked on and a task is stated clearly. And after the discussion a new issue should be opened with instructions on what should be done.
Also, to clean things a little we can have an agreement to ask for assignment not in comments, but on gitter instead. Here may rise a problem when no one is around.
What are your thoughts on this?

**Comment by Makman2** [comment]
Sounds good, though I think often issues are some kind of "investigation process" that doesn't reveal completely itself until the very last end (that especially applies for `difficulty/hard` and `difficulty/very hard`). I'm in for that, but I think after we try for a few weeks/months we will fall back to our old behaviour because it's easier and more comfortable :P

**Comment by AbdealiJK** [comment]
Why do you want to ask to be assigned on gitter ? It make sense to be on an issue I think
Ideally the original comment (The description of the issue) should be edited if the task changes, We're probably just too lazy to do it ^_^ ... we should though.

**Comment by Uran198** [comment]
@AbdealiJK Sometimes issues bounce from one person to another and comments become filled with unrelated stuff. So, one should go through it, while with asking assignments on gitter, one shouldn't.

**Comment by Makman2** [comment]
some people don't read the assigment entry on the github page. Doesn't harm to have this inside the issue imo^^ And often the issues aren't that problematic that the discussion blasts everything.
I really like the idea behind this issue, but I don't see why we should clean up everything now, it's work and imo it's working quite good currently. If someone wants to take an issue, he/she should read it through, also if there's sometime not-really-helpful information. It's not that much that it costs you an hour to read everything. In this case you discuss stuff anyway on the gitter channel^^

**Comment by sils1297** [comment]
alright @Makman2 @Uran198 @AbdealiJK I think we can agree that it's good especially for longer discussions to open up new issues for clearly defined tasks. Also we want to have documentation for the labels and how to interpret them *or* better label names. Suggestion: somebody starts discussing this on gitter, you come to a conclusion and file one or two issues so we can close this one?

**Comment by sils1297** [comment]
Assigning @Uran198 since he seems to have the biggest interest. If that's not ok just ping me and I'll unassign you of course.

**Comment by Uran198** [comment]
Evolved into #2009 and #2010
