### ISSUE TITLE
Rename `_check_command` in Lint class 

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#1887]
The function `_check_command()` also tests for the executable, so this is a confusing name. The name should be changed to something more appropriate.

**Comment by manojpandey** [comment]
I want to work on this issue :)

**Comment by AbdealiJK** [comment]
@manojpandey please do mention what you're going to set the name to here so that @SanketDG can confirm it's alright.

**Comment by manojpandey** [comment]
@AbdealiJK @SanketDG :
How about `_check_executable_command()` or `_check_exec_command` or `_check_exec_run` ?

**Comment by SanketDG** [comment]
@manojpandey `_check_executable_command()` sounds good to me.

How about `_check_executable_and_command()`? Both are okay to me, feel free to go with your own choice.
