### ISSUE TITLE
Suppress output in Lint class during subprocess call

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#1888]
By redirecting the `stdout` and `stderr` to `/dev/null`
difficulty/newcomer

**Comment by Makman2** [comment]
the built-in values `subprocess.DEVNULL` can be used for that purpose.

**Comment by AbdealiJK** [comment]
The better way would be to use the `supress_stdout` decorator ?
And possible add a `supress_stderr` decorator.

**Comment by Makman2** [comment]
`subprocess.call` has `stdout` and `stderr` arguments, just using `subprocess.DEVNULL` is easier and more performant :)

**Comment by AbdealiJK** [comment]
AH, cool.
Much better - yeah.

**Comment by sils1297** [comment]
neat sounds like a quick fix, can we have it for the release?

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-15 3:24 GMT+01:00 AbdealiJK <notifications@github.com>:
