### ISSUE TITLE
DocStyleDefinition: fails to parse marker sets if there are other fields

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#1892]
If I have `default.coalang` as:

```
[PYTHON]
doc-marker = """, , """

[PYTHON3]
doc-marker = """, , """
keywords = def, if, else
```

And I do :
```python
from coalib.bearlib.languages.documentation.DocstyleDefinition import DocstyleDefinition
result = DocstyleDefinition.load("PYTHON3", "default")
```
I get:
```python
<DocstyleDefinition object(docstyle='default', language='python3', markers=(('"""', '', '"""'), ('def', 'if', 'hello'))) at 0x7fae0f961dd8>
```

Only fields starting with `doc-marker` should be parsed. Right now everything that is **not** starting with `comment` is parsed. Am I missing something?

**Comment by AbdealiJK** [comment]
It seems this is a feature. I have no clue why...

From the DocstyleDefinition.load() function:
```
        Loads a ``DocstyleDefinition`` from the coala docstyle definition files.

        This function considers all settings inside the according coalang-files
        as markers.
```

and

```
        marker_sets = (tuple(value)
                       for key, value in
                       filter(lambda kv: not kv[0].startswith("comment"),
                              docstyle_settings.contents.items()))
```

**Comment by AbdealiJK** [comment]
git blame shows @Makman2 wrote that ...

**Comment by sils1297** [comment]
Well the whole file is for dicstyle only, it's separated from the language
definition which is why we just took everything

**Comment by SanketDG** [comment]
Yes but a proper coalang file, what would that consist of? Not only documentation I hope. Also, I hope I don't have to create two separate files for docstyle and language definition.

**Comment by Makman2** [comment]
These coafiles are written for only documentation purposes in mind. I discussed that with @sils1297 during my PR (since in early versions I required to prefix with `doc-marker`).
Do you have a need to put other settings into such a coafile @SanketDG ?

**Comment by Makman2** [comment]
If you want to have a single coafile for single language (or similar), we need to discuss https://github.com/coala-analyzer/coala/issues/1818 again since then our coalang format does not suffice for that purpose^^

**Comment by SanketDG** [comment]
I think we should have a single coafile for a single language, and it doesn't even come down to this, because its pretty obvious that only `doc-marker` prefixes should be taken for a usecase that involves documentation strings, irrespective of what other stuff the coafile may contain.

**Comment by Makman2** [comment]
@SanketDG would you mind renaming this issue to "One language - one coalang file"? This needs to be designed well^^

**Comment by SanketDG** [comment]
No this issue is about taking in `doc-marker` prefixed fields from the coalang file. I'll open a new one.

**Comment by AbdealiJK** [comment]
Closing in favour of https://github.com/coala-analyzer/coala/issues/1898

**Comment by AbdealiJK** [comment]
So maybe we want to add a new arg `from_fields` or so which only limits it
to specific fields or something ?

**Comment by SanketDG** [comment]
Reopening.

It doesn't matter what kind of fields my coafile has, but a single standard prefix or a set of prefixes should be decided to be read from the coafile when dealing with docstyle definition. For example, my coafile could have:

```
[PYTHON3]
doc-marker = """, , """
contributors = abdealijk, makman2
bdfl = sils1297
```
Not a strong example, but only the first field should be read. It doesn't matter whether we have a single unified coafile or not, the right field should be parsed IMHO.

**Comment by Makman2** [comment]
since they are currently designed to do this, I would close this as `wontfix/not-happening`. This fits more into the redesign in #1898 , as this is a question of concept.

**Comment by AbdealiJK** [comment]
@SanketDG please confirm if you agree/disagree with @Makman2 and comment/close as appropriate ?

**Comment by SanketDG** [comment]
@AbdealiJK closing this because of the broad concept of #1898
