### ISSUE TITLE
Bear: Add helper function name()

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1893]
Frequently, we need to use the name of the bear inside the bear.
Example: https://github.com/coala-analyzer/coala-bears/pull/242/files/32dea21eebf3df34dabd2333b84e148a4eb01f28#r56285822

We should add the `name()` function which allows users to just do `self.name()` easily.
Or even a property `self.name`

**Comment by djkonro** [comment]
Please assign me to this task.

**Comment by Makman2** [comment]
A "read-only" property is good :+1:

**Comment by sils1297** [comment]
this should also use it in various places, git grep for `__name__` in coala and coala-bears

**Comment by BigDproject** [comment]
this issue seems to be fixed.
So you can close it.

**Comment by SanketDG** [comment]
@BigDproject No, this is being worked on by @djkonro at https://github.com/coala-analyzer/coala/pull/1936

**Comment by djkonro** [comment]
@BigDproject, I am presently working on BearRunningTest which needs to be updated.

**Comment by sils1297** [comment]
@BigDproject ah, this commit is on *his* master but not on ours and thus still open. Thanks for the consideration anyway!
