### ISSUE TITLE
Alias for rebase

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#1895]
I am adding an alias for rebase, as @AbdealiJK requested, in the documents in the git tutorial and probably to the newcomers too, as its something many newcomers encounter; in a section as ``Git rebase: this is something you most probably encountered already, here's how to fix it `` or something like it.

**Comment by AbdealiJK** [comment]
@sils1297 @Makman2 any objections ?
Or maybe ideas to make this even easier ?

**Comment by sils1297** [comment]
An alias? Most people won't use that,can't you point to proper documentation in a note or something?

**Comment by AbdealiJK** [comment]
Proper documentation to ?

**Comment by sils1297** [comment]
To git aliases

**Comment by AbdealiJK** [comment]
I didnt understand what you're saying.
Are you saying tell them to make an alias on their own ?
I'd suggest we give them the alias to make also

I think i'd use aliases

**Comment by sils1297** [comment]
We're talking about a git alias to shorten commands, do we?

**Comment by AbdealiJK** [comment]
Im talking about a git alias to "pull coala master > rebase with coala master > push to the branch required"

**Comment by sils1297** [comment]
ok you want to recommend contributors the use of a customly baked alias that'll fetch upstream and rebase on upstream I guess?

**Comment by AbdealiJK** [comment]
(and then push) yes

On Thu, Mar 17, 2016 at 12:34 PM, Lasse Schuirmann <notifications@github.com

**Comment by sils1297** [comment]
@AbdealiJK @Adrianzatreanu there seems to be a lot of confusion around this. Can you please come to an agreement and solve this soon or close this as wontfix as it's really a minor thing and we shouldn't waste so much time on it.

**Comment by AbdealiJK** [comment]
Closing as wont fix
