### ISSUE TITLE
Bear.py: Invalid RST

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1897]
In bear.py we have 
```
Section value requirements shall be checked inside the `run` method.
```
In `check_prerequisites()`

We need to change the single backtick to double backtick.

**Comment by MayankVachher** [comment]
@AbdealiJK can you assign this task to me?

**Comment by abhsag24** [comment]
@MayankVachher  you have already solved 2 newcomer bugs, do you mind moving on to bug with a higher difficulty? )

**Comment by sils1297** [comment]
He doesn't, we just talked on gitter :) Should've mentioned that...

**Comment by whonut** [comment]
Just went to fix this and it seems to have been done already, just FYI.

**Comment by sils1297** [comment]
Oh great! @whonut you just fixed an issue then :) Sorry for the circumstance, those issues get fixed as a side effect sometimes and it's hard to regularly check all of them so it rarely happens :/
