### ISSUE TITLE
version of Docs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1900]
Now that we use dev99999..
the docs versions shows this. Not nice

@sils1297 add what you want it to show later

**Comment by sils1297** [comment]
we can just generate a development version with a date I guess

**Comment by AbdealiJK** [comment]
@sils1297 can you give more info here ?
I tried:
```
    current_version = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    call(['python3', '.misc/adjust_version_number.py', 'coalib/VERSION',
          '-b {}'.format(current_version)])
```
but the problem is that if we don't have a dev version (I.e. if we release a new version) then it will still be called a dev version. Shall we just do `if "dev" in Constants.VERSION` and do this only in that case ?
