### ISSUE TITLE
Install dependencies in rultor and not in the docker image

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1904]
In this way they are synced with `requirements.txt`

**Comment by sils1297** [comment]
this is related to https://github.com/coala-analyzer/rultor-python/ and needs changes there too

**Comment by AbdealiJK** [comment]
Do we even need that docker container ?
Seems redundant ...
 - We already get-pip in the rultor.yml
 - We don't need zanata anymore
 - Locales - not really needed i think ?

What we do need:
 - apt-get update
 - apt-get install
 - pip3 install

And this issue wants to move deps into rultor.yml ... so, essentially the rultor-python container will be useless now.

**Comment by sils1297** [comment]
well the rultor-python container still can help us having lower rultor
execution times

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-22 7:28 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
We could use yegor's container for that

**Comment by Nosferatul** [comment]
Hi, I wanna work on this! I believe that I should change .rultor.yml, right?
