### ISSUE TITLE
coala should catch pkg_resource.VersionConflict for bears

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1909]
when collecting bears we don't catch that exception and coala crashes completely which sucks! Just show a warning man! CC @fneu

**Comment by AbdealiJK** [comment]
We should do this in our `_import_module()` ideally so that we don't forget it again later

**Comment by sils1297** [comment]
As per discussion on gitter we're not sure where the catch should happen, probably not in `_import_module` but at the place where we also catch the import error so you'll have to search a bit on your own here.

**Comment by jarifibrahim** [comment]
@AbdealiJK
Seems like its used only in _iimport_objects
Which has the documentation:
```
    :raises Exception: Any exception that is thrown in module code or an
                       ImportError if paths are erroneous.
````
@sils1297 do you want all of Importers.py generic ?
If so, then we should do this show an error at _import_bears
in Collectors.py

**Comment by jarifibrahim** [comment]
@sils1297 We do not catch the `ImportError` anywhere. This is what I got on `git grep ImportError`
```
coala:# importing things that could cause an ImportError
coalib/collecting/Importers.py:        raise ImportError
coalib/collecting/Importers.py:                       ImportError if paths are erroneous.
coalib/collecting/Importers.py:                       ImportError if paths are erroneous.
coalib/collecting/Importers.py:                       ImportError if paths are erroneous.
coalib/output/ConsoleInteraction.py:except ImportError:  # pragma: no cover
tests/coalaDbusTest.py:except ImportError:
tests/collecting/ImportersTest.py:        with self.assertRaises(ImportError):
tests/collecting/ImportersTest.py:        with self.assertRaises(ImportError):
tests/output/dbus/DbusAppTest.py:except ImportError as err:
tests/output/dbus/DbusDocumentTest.py:except ImportError as err:
tests/output/dbus/DbusServerTest.py:except ImportError as err:
tests/output/dbus/DbusTest.py:except ImportError as err:
tests/results/DiffTest.py:        except ImportError as err:
```

**Comment by sils1297** [comment]
@fneu where do we catch that?

**Comment by Makman2** [comment]
Isn't that already implemented?

**Comment by sils1297** [comment]
@Makman2 we catch ImportError but not the version conflict

**Comment by sils1297** [comment]
@jarifibrahim still working on this?

**Comment by jarifibrahim** [comment]
@sils1297 @Makman2 I'm waiting for @fneu's reply. 

I've been told to handle the `VersionConflict` error where the `ImportError` is handled. But I can't find where the `ImportError` is handled.

**Comment by Makman2** [comment]
@sils1297 I remember I've already seen a version conflict with coala, and it says to me "upgrade please" and stuff (no exception traceback)^^

**Comment by Makman2** [comment]
@jarifibrahim `git grep ImportError` :) we don't handle it that much :3

**Comment by Adrianzatreanu** [comment]
@jarifibrahim still working on it :) ?

**Comment by jarifibrahim** [comment]
@Adrianzatreanu You can take this issue if you want. I can't figure out what exactly needs to be done. :)

**Comment by AbdealiJK** [comment]
Seems like we already catch it now - https://github.com/coala-analyzer/coala/blob/99d4c392ffbb1e1c893b0db7dfb64c3e082f741c/coalib/collecting/Collectors.py#L127

Can someone confirm so we can close this ?

**Comment by Makman2** [comment]
looks like :+1:
