### ISSUE TITLE
Fresh pip install coala - Not working

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1912]
I just did `pip uninstall coala -r requirements.txt` and then `pip install coala` to get the latest coala (0.5.0) for basic testing.

This happened:

```
$ pip install coala
Collecting coala
  Downloading coala-0.5.1-py3-none-any.whl (136kB)
    100% |████████████████████████████████| 139kB 146kB/s 
Collecting libclang-py3==0.2 (from coala)
Collecting setuptools>=19.2 (from coala)
  Downloading setuptools-20.3-py2.py3-none-any.whl (508kB)
    100% |████████████████████████████████| 512kB 52kB/s 
Collecting appdirs~=1.4.0 (from coala)
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Collecting validators~=0.10 (from coala)
  Downloading validators-0.10.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.
You are using pip version 8.0.2, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

and it keeps repeating:
```
$ pip install coala
Collecting coala
  Using cached coala-0.5.1-py3-none-any.whl
Collecting PyPrint~=0.2.3 (from coala)
  Downloading PyPrint-0.2.3-py3-none-any.whl
Collecting libclang-py3==0.2 (from coala)
Collecting validators~=0.10 (from coala)
  Using cached validators-0.10.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.
You are using pip version 8.0.2, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by AbdealiJK** [comment]
Seems to be a bug in `validators`. We should have caught this before !

Filed upstream at:
https://github.com/kvesteri/validators/issues/19

**Comment by sils1297** [comment]
can we make a workaround for the current lrelease?

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-18 2:42 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Let's wait till 5th May after we which let's fork it and make it a new pypi package

**Comment by sils1297** [comment]
@AbdealiJK no way to fix this for tomorrows release? I mean this is really bad!

**Comment by AbdealiJK** [comment]
None that I can think of. We're only using it for Link validation in one or
two places. We can add our own Link regex - but the whole license thing was
troublesome ...

**Comment by sils1297** [comment]
we can take the regex from https://github.com/kvesteri/validators/blob/master/validators/url.py , they're free software I assume otherwise we can't use them as dependency anyway

**Comment by Makman2** [comment]
as it worked before let's fix the version? :O

**Comment by AbdealiJK** [comment]
It didn't work before either (for me atleast)

**Comment by Makman2** [comment]
Oh, weird i have a validators installation :3 maybe an explicit install helps?

**Comment by AbdealiJK** [comment]
If you have setuptools installed before `validators` it works
