### ISSUE TITLE
Document lint

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1915]
We need much better documentation for Lint.

need to document:
 - lint
 - _process_corrected
 - _process_issues
 - process_output
 - match_to_result
 - check_prerequisites

These are commonly overridden and should be much better documented.

**Comment by AbdealiJK** [comment]
This probably needs someone experienced with the whole system.
But Im still marking it as difficulty/low as it's not difficult - although it needs good understanding of Lint to do it.

difficulty/low

**Comment by sils1297** [comment]
can't the API documentation be brushed up to serve this and the lint
tutorial link to it?

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-18 5:25 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
I intended this issue for the API documentation (doc comments in the function)
Seems like I didnt write that anywhere though.
Currently there are none :(

**Comment by Makman2** [comment]
Superseded by #1928 which is coming soon.
