### ISSUE TITLE
docs: Add Tutorial for LocalBearTestHelper

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#1916]
coala provides this awesome functionality, and we should do a tutorial for it, since a lot of beginner Bear writers have some difficulty understanding how to use its functionality

**Comment by AbdealiJK** [comment]
This should ideally be done with doctests and documentation inside LocalBearTestHelper I think.

**Comment by abhsag24** [comment]
@AbdealiJK but  we do provide some sort of a testing framework, for a person that just wants to use coala something like a Tutorial for that could be super useful. We do have a lot of newcomers that have some sort of difficulty in understanding what a `good_file` and a `bad_file` is and how exactly to use them, that might help them a lot too!

**Comment by sils1297** [comment]
I think this should be in the writing bears tutorial or linter bears or at
least linked from them

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-18 13:52 GMT+01:00 Abhay Raizada <notifications@github.com>:

**Comment by SanketDG** [comment]
Well there are two kinds of tests right, one with `verify_local_bear`, and the other where you have to set up the bear with its own section and message queue. I think we should cover for both.

**Comment by abhsag24** [comment]
@SanketDG i'm not sure about a tutorial for the setting up a bear thing, it's very generic, something reading the codebase should solve, and is not something which coala has built for the a user, `verify_local_bear` on the other hand is a coala framework and should have a tutorial

**Comment by SanketDG** [comment]
@abhsag24 I agree with you on this.

But how should beginners write tests then?

The part of the message queue and the section, should be mentioned somewhere then.

**Comment by Uran198** [comment]
I think that both things should be in the tutorial. When you're starting to write a bear for yourself, it's good right away to have some ideas about how to go about testing it.

**Comment by srisankethu** [comment]
Is someone doing this ?

**Comment by srisankethu** [comment]
Shouldn't this issue be in coala-bears ? as LocalTestHelper is no longer here.

**Comment by Makman2** [comment]
But I think we don't have a documentation infrastructure there currently^^ We are planning to move docs maybe into a separate repo^^
