### ISSUE TITLE
DocumentationComment: Design

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#1917]
Currently this [file](https://github.com/coala-analyzer/coala/blob/master/coalib/bearlib/languages/documentation/DocumentationComment.py) needs documentation parsing routines for several languages.

I have two ideas atm:

* Use an ambiguous regex for each kind of docstring
* Parse it manually.

**Comment by Makman2** [comment]
You mean for `Bear.run()` right?

In fact a good idea. I'm only against this if implementation produces too much code. We can force users to use the default python docstring style^^

**Comment by SanketDG** [comment]
@Makman2 

No, I meant for DocumentationComment, where right now it only has the ability to break down specific docstrings.

**Comment by Makman2** [comment]
Ah okay, for `coalib.settings.DocumentationComment`.
Then, do we need this?

**Comment by SanketDG** [comment]
woah, the real `DocumentationComment` is in settings. Didn't notice that. The file I was talking about is this: [`coalib/bearlib/languages/documentation/DocumentationComment.py`](https://github.com/coala-analyzer/coala/blob/master/coalib/bearlib/languages/documentation/DocumentationComment.py), but that is a stub. The idea is to implement documentation comment parsing for several languages including python, and since sphinx supports google and numpy style docstrings (through extensions), we should support them too.

Changing to DocumentationComment: Design.

**Comment by Makman2** [comment]
`coalib.bearlib.languages.documentation.DocumentationComment` doesn't have any parsing facilities yet, this would be done together with https://github.com/coala-analyzer/coala-bears/issues/34 .
But since the parsing is coalang related, we should keep the issue here in coala.

**Comment by AbdealiJK** [comment]
So ... um ... what's the conclusion ? What needs design now ?

**Comment by Makman2** [comment]
The conclusion is we want to implement parsing facilities into the doc-extraction stuff.

**Comment by AbdealiJK** [comment]
@SanketDG Was this done as part of GSoC ? Can you update this if it was partially addressed or close if it's completed ?

**Comment by Makman2** [comment]
done :+1:
