### ISSUE TITLE
Interactive mode: Too much reading for a first run

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1918]
IMHO, when user for the first time tries something, he may a little bit in a hurry to make it work. Then later he come back and looks how he can improve the current state of thing.
Because of this I think it would be simpler for them not to go through the interactive mode by default and have cli argument for that.

**Comment by AbdealiJK** [comment]
From gitter:
What @Uran198 means is that he wants `coala-ci` to run as the default behaviour and `coala` to run as an arg (like `--interactive`)

i.e. he would prefer default behaviour to be non interactive and just show results.

**Comment by Makman2** [comment]
In fact I like it, the only reason I have against this is that users won't get that quickly aware of the auto-patch ability we often have. But if we advertise that more, imo this change's good :+1:

**Comment by sils1297** [comment]
we gotta show the patch in noninteractive mode but the whole action concept
doesn't work like that

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-18 22:01 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
yeah that would a bit defeat the purpose (especially with default actions)...

**Comment by sils1297** [comment]
well we can show the patch, it'd not be an action but part of the visualization so it's not that confusing and has nothing to do with actions if you look from that side

**Comment by Makman2** [comment]
phew... we really need to refactor the backend stuff :D
showing the patch everytime is maybe not bad, but that depends on the size of the patch^^

**Comment by sils1297** [comment]
FWIW if we give the user something noninteractive by default he'll get tons of output and he won't be guided through it so I think that's worse than the interactive output...

**Comment by Makman2** [comment]
yeah we need to assume the worst-case scenario: a user wants to try out coala, and his codebase has tons of errors.
Interactive output is really better then^^
So we should rather have a flag `--non-interactive` to get coala-ci behaviour into coala^^

**Comment by Uran198** [comment]
Or something like `--verbose` and by default display little stuff, or `--silent` to display only affected files and number of errors.
The thing is that interactive mode for big projects may be as overwhelming if not more. He'll have to click through all the decisions.
Well, I think this is more about how to guide user when he makes his first steps in the tutorial.

**Comment by AbdealiJK** [comment]
They could use `coala-ci` or `coala-format`. So the solution here is just
to document them.

The first time a user runs coala they'd have lots of issues. After that
every other time they'd have only issues they want fixed (as others will be
ignored and the coafile will be configured).

So, let's take coala repo for example. First time we run a bear like
PyLintBear we have 500+ Results. But after we configure it we have 0
Results for the dozens of times we run coala.

I think it's more important to have the default behavior like it is now for
the dozens of times they'd use it *after* they configure coala rather than
the first.

**Comment by Uran198** [comment]
And what about by default to show the patch and propose to apply it right away? This may make simplify things.
Also, if no automatic patch can be applied, just ask "Do you wish to open affected file?(Y/n)". There will be less reading.

**Comment by Makman2** [comment]
We propose these options already :D

**Comment by AbdealiJK** [comment]
Doesn't "by default to show the patch" make it even more reading on the first run ?
Also, the patch may not be the right one. In that case open in editor makes sense (even if the patch *can* be applied successfully)
It seems we're going off topic ?

**Comment by Uran198** [comment]
I'm only against coala messages. Patches would be shown at one point one way or another. I think users would first want to look at the patch and apply it if it's OK, and as a fallback to edit file in editor. So, what about showing a patch and asking apply, move one(not apply) and open in editor question?

**Comment by Makman2** [comment]
So if you want to show the patch, we should not exceed about 10 lines. We could implement a `maxlines` option for the diff-print which would show something like 
```
-print ()
+print ()
<Diff contains further +23 additions and -12 deletions>
```

**Comment by sils1297** [comment]
I like showing a one liner with patch stats always witout asking

**Comment by Makman2** [comment]
I think that's good too (10 lines was just a suggestion)^^

**Comment by Makman2** [comment]
So is the task defined and shall we rename this issue?

**Comment by sils1297** [comment]
The task isn't well defined, if somebody would define it well it'd be wise to close this issue and open a clean new one with a well defined task.

**Comment by Makman2** [comment]
Okay I thought the consensus was that we want to display a one-liner diff everywhere^^

**Comment by sils1297** [comment]
feel free to define it *clearly* in a new issue :) make a CLI Mockup (i.e.
write down how it should look like)

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-04-13 16:39 GMT+02:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
https://github.com/coala-analyzer/coala/issues/2007
