### ISSUE TITLE
Tutorial: "Integrating coala into Your Project" section is flawed

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1919]
It's [here](http://coala.readthedocs.org/en/latest/Users/Tutorials/Tutorial.html#integrating-coala-into-your-project).

- Not a lot of users will want to use the latest unstable version of coala for their projects.
- `coala` without `coala-bears` is of not much use. And almost always there will be a need to install some dependencies for `coala-bears`.

**Comment by AbdealiJK** [comment]
About  point 1:
Do you want to change the command to clone from git and checkout a release ?

About point 2:
I agree actually.

I dont even know why we have this completely weird section.
We should remove it. The best way to use coala & bears is install with `pip` ...

**Comment by sils1297** [comment]
Can you fix it? Sounds like a five minute fix

**Comment by sils1297** [comment]
Back then we had no pip package :P

**Comment by AbdealiJK** [comment]
Wow. I see XD
