### ISSUE TITLE
docs: Move documentation to separate repo

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1922]
There is not much point in running all the tests on documentation changes. Maybe, I'm missing something.

**Comment by sils1297** [comment]
I think we have this issue already somewhere, can you dig it up?

**Comment by sils1297** [comment]
CC @AbdealiJK he filed it

**Comment by Uran198** [comment]
@sils1297 I wasn't able to find anything.

**Comment by AbdealiJK** [comment]
It was briefly mentioned at https://github.com/coala-analyzer/coala/issues/1768#issuecomment-190776043 and discussed on gitter extensively.

Good to have an issue for it.

Other pros of having a docs repo:
 - Docs for coala-bears, coala-html, etc also get included into that
 - We can have a single website in readthedocs with all supported docs

For implementation we may want to take a look at owncloud's [docs repo](https://github.com/owncloud/documentation)

**Comment by Makman2** [comment]
This doesn't affect docstrings right?

**Comment by sils1297** [comment]
@Makman2 we can have API docs for each repo individually but that's for devs only

**Comment by sils1297** [comment]
I created a repo at https://github.com/coala-analyzer/documentation/settings/branches/master. We'd need to set up docs there and then switch readthedocs.org smartly so that the URL doesn't change ideally.

**Comment by Adrianzatreanu** [comment]
done.
