### ISSUE TITLE
output: Make it shorter

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1923]
For example:
`The following actions are applicable to this result:` => ` `
`Apply no further actions` => `(e)xit`
`Open the affected file(s) in an editor` => `(o)pen in editor`
`Apply the patch automatically` => `(a)pply patch`
`Print a diff of the patch that would be applied.` => `(s)how patch`
Also, show them in different colours and interact with one (possibly first) letter. In example `e`, `o`, `a`, `s`, respectively.

**Comment by sils1297** [comment]
neat :)

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-19 6:16 GMT+01:00 Attila <notifications@github.com>:

**Comment by jarifibrahim** [comment]
I guess we should just stick to the numbers and just add the colors to the output messages (They look super cool [see this](http://imgur.com/6Z2YOYo) )

**Comment by Makman2** [comment]
@jarifibrahim I like the colors, though that interferes quite with the diff coloring :D

**Comment by AbdealiJK** [comment]
I agree. Too much color is irritating too. I'd rather not have colors for actions

**Comment by AbdealiJK** [comment]
Also, I think we should have either numbers OR those letters.
Either can be used

**Comment by Uran198** [comment]
Colour may be good because it makes important things stand out and to make it less irritating we can pick two colours and use them in turns for each action.

**Comment by jarifibrahim** [comment]
Two colors could work. We don't use `cyan` and `green` in output. So they can be alternately used for the actions.

**Comment by sils1297** [comment]
so one colour for the letters to let them stand out and leave the rest as is?

**Comment by Uran198** [comment]
What I meant is to make one line in colour `a`, next one in `b`, then `a` again and so on. In this way it'll catch an eye, but will not be screaming.

**Comment by jarifibrahim** [comment]
![asd](http://i.imgur.com/rQxpfyj.png)

@sils1297 Look at this. We'll just use numbers instead of characters.

**Comment by sils1297** [comment]
I'm not so convinced of the dual colour thing, how does it look if you
colour the `(e)` and so on all in that blue and leave the rest as is? Other
opinions?

**Comment by jarifibrahim** [comment]
![](http://i.imgur.com/Sldaz3sg.png)

The entire line in same color looks better to me.

**Comment by Uran198** [comment]
Maybe, we can fit them all in one line and add colour to this one line.

**Comment by Makman2** [comment]
I like only coloring the number, no color "overflow" and layout is better to read imo

**Comment by Makman2** [comment]
Though using letters then is really a bit confusing :D
But isnt it possible to understrike text in a terminal?

**Comment by jarifibrahim** [comment]
![](http://imgur.com/qtb9VVP.png)

Numbers, with the whole line colored looks better IMO.

@Makman2 It's possible ([see this](http://stackoverflow.com/a/17303428/3590449)).

**Comment by sils1297** [comment]
well readability suffers from the colours right?

2016-03-23 17:30 GMT+01:00 Ibrahim Jarif <notifications@github.com>:

**Comment by jarifibrahim** [comment]
@sils1297 Yes. Readability suffers from colors.

**Comment by sils1297** [comment]
Hm I find numbers easier to type than chars, it'll always be numbers...

**Comment by jarifibrahim** [comment]
So should we close the issue and leave the output the way it is currently ?

**Comment by sils1297** [comment]
@Uran198 @Makman2 what's your take on this?

**Comment by Uran198** [comment]
Well, I'd like it to be shorter. Maybe, even without colours. Also, in general I think that character is faster to type, but it's subjective.

**Comment by Makman2** [comment]
don't know... I have no problems with numbers, so changing that means just work imo^^

**Comment by jarifibrahim** [comment]
I believe numbers are easier to handle. As the project grows there might be new additions to the current options. If we change to chars, we'll have to figure out a design which can be used for the future options as well. The current numbering system works well and won't require a lot of changes if new options are added in future.

@silk1213 @Uran198 @Makman2 Maybe we'll have to take a vote for this issue.

**Comment by Makman2** [comment]
it work currently: downvote :-1:

**Comment by sils1297** [comment]
Alright please use github voting on *this coment*. Voting will be up for a day or so.

:+1: : I want chars!
:-1: : Let's not waste more time.
:tada: Let's brainstorm for something better!

**Comment by sils1297** [comment]
Ok three votes against, one laughs at us. Let's not waste more time :)
