### ISSUE TITLE
Julia dev tools

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1929]
Julia is trying to make a dev tool (IDE) for themselves like Android.
We should try to get coala in ?

https://hacknight.in/thejulialang/julia-hacknight/projects/7-ide-for-julia-eclipse-integration

Currently they have a eclipse plugin:
http://juliacomputing.com/blog/2016/02/06/Eclipse-JuliaDT.html

**Comment by AbdealiJK** [comment]
So their IDE is called JunoLab - http://junolab.org/

And it's based on top of atom (Like how Android Studio is on top of IntelliJ Idea)
Hence, we already support it :)

They don't have preinstall much, just the Julia auto-complete, snippet, etc [plugin](https://github.com/JunoLab/Atom.jl) they made. And some modified initial settings [in atom itself](https://github.com/JunoLab/atom)

It's not as customized as I thought it was. Julia devs can install coala using the coala-atom plugin, so I think it's fine

**Comment by Makman2** [comment]
@AbdealiJK closing then?

**Comment by AbdealiJK** [comment]
Yep, closing it.
