### ISSUE TITLE
index.rst still has some typos

### ISSUE THREAD

**Issue by khanstark** [coala-analyzer/coala#1930]
http://coala.readthedocs.org/en/latest/#status-and-stability-of-the-project has typos. I think by 'braches' we mean 'branches'. Needs to be rectified.

**Comment by sils1297** [comment]
Thanks for reporting this, a newcomer will look at it at some point in time, we'd like to keep typos open for them :)

**Comment by khanstark** [comment]
alright.! that's a wise thing to do!

**Comment by sils1297** [comment]
why closing it? Open newcomer issues are good :)

**Comment by gopalmeena** [comment]
Can i send PR for this issue?

**Comment by tushar-rishav** [comment]
@gopalmeena  Sure. Go ahead.

**Comment by Adrianzatreanu** [comment]
Hi, @gopalmeena 

do you need help figuring this out? We're all happy to help you on [our gitter channel](https://gitter.im/coala-analyzer/coala), just drop by and ask us anything :)

**Comment by Adrianzatreanu** [comment]
unassigning due to lack of response and long unavailability.

**Comment by emperorofmars** [comment]
I can do this, please assingn me.
