### ISSUE TITLE
bear dirs needs changing

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1932]
```python
    def bear_dirs(self):
        bear_dirs = path_list(self.get("bear_dirs", ""))
        for bear_dir in bear_dirs:
            sys.path.append(bear_dir)
        bear_dir_globs = [
            os.path.join(glob_escape(bear_dir), "**")
            for bear_dir in bear_dirs]
        bear_dir_globs += [
            os.path.join(glob_escape(bear_dir), "**")
            for bear_dir in collect_registered_bears_dirs('coalabears')]
        return bear_dir_globs
```

@hypothesist I'm pretty sure that this is what we need

**Comment by AbdealiJK** [comment]
@sils1297 I'm wondering if thats right.
If I give `-d /some/path/*/bears`
 - `path_list` would not care about it (as it's already abspath)
 - First for loop would escape the `*` and add `**` at the end
Which meant it will never search in /some/path/client/bears and /some/path/server/bears (for example)

What is the intended behaviour in this case ?

**Comment by sils1297** [comment]
```
  -d DIR [DIR ...], --bear-dirs DIR [DIR ...]
                        Additional directories where bears may lie
```

With that interpretation bear-dirs is for directories only actually. Otherwise we'd have to interpret the glob for bear_dirs.

**Comment by AbdealiJK** [comment]
Ah, I see. is this also true if I add `bear_dirs` in the `.coafile` ?

If you don't want the bear_dir to be a glob in either case - then your proposed solution looks good.

**Comment by sils1297** [comment]
coala doesn't ever differenciate if a thing comes from the coafile or from
the cli.

**Comment by AbdealiJK** [comment]
Right - so, you dont want globs there too ? (We dont have any documentation
for that yet)

**Comment by Makman2** [comment]
This would solve #1831
