### ISSUE TITLE
Annotations: handling exceptions

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#1950]
When writing custom annotation, user should be able to access exceptions, that it's raising, to debug his function. Currently all that he gets is the information that something went wrong, e. g.
```
[WARNING][14:09:44] The bear ClangComplexityBear cannot be executed. Unable to convert parameter 'max_complexity' into type <function func at 0x7fa1b4d12d90>
```
This can be pretty easy fixed, by specifying exception [here](https://github.com/coala-analyzer/coala/blob/master/coalib/settings/FunctionMetadata.py#L105) and specifying in the docs what exception should annotations be allowed to raise.

This is related to https://github.com/coala-analyzer/coala/issues/1219 discussion. I think, maybe we need to figure out a better way to use exceptions so that there will be no need in catching broad ones, because they can hide bugs or other useful information.

**Comment by sils1297** [comment]
Ah, this is kind of intended since this interacts with the user, if the bear wants a bool and the user doesn't give something booleable we want a neat message saying he should please use something bool-ish, right? We don't want to show him a traceback ideally.

**Comment by Uran198** [comment]
There'll be an agreement on which exceptions are to be considered due to wrong type that was specified and which due to something wrong and unexpected happening inside custom annotation. So, it'll show message as it did when it's because the type is incorrect.

**Comment by sils1297** [comment]
Alright so only catch TypeError essentially, let other things go through or show a traceback for them right there.
