### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#196]
I've spent some time getting the tests to work on windows so the objects should work. However I didn't get it fully to work.

So thats on the TODO list:

- [x] Make sure tests pass on this horrible system
- [x] Make sure installation works
- [x] Make sure execution works

On long term it would be nice if we'd have a continous integration server that builds our stuff on windows.

**Comment by sils1297** [comment]
seems tests don't work anymore :D

**Comment by sils1297** [comment]
on windows

**Comment by sils1297** [comment]
One issue on windows left: http://pastebin.com/MW3Fn4Jt

If I pass an _empty_ section in line 79 and 81 the error doesn't occurr anymore.

**Comment by sils1297** [comment]
even if I do
```
        self.section = Section("test", defaults=Section("def"))
        self.section.append(Setting("key", "value"))
        self.section.defaults.append(Setting("key", "value"))
        self.section.retrieve_logging_objects()
```
it works :( (Ok it throws another error. But the process gets started...)

**Comment by sils1297** [comment]
Dropping windows support. This OS is jumping on my nerves too much. I'll accept patches though.

**Comment by sils1297** [comment]
may be possible with the fixes from #386 , anyone interested in windows support?

**Comment by Makman2** [comment]
(*yeah!*)

**Comment by sils1297** [comment]
@Makman2 if you want you can take care of the windows support :) may be well possible since some other patches from @Udayan12167 recently. Just execute the tests and repair everything thats broken :). (I think its about 3 to 5 modules.)

**Comment by Makman2** [comment]
Ehh okay assign me, I'll try the next time...

**Comment by sils1297** [comment]
Good luck :) (You'll need it!)

2015-04-02 21:16 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Blocked by #419.

**Comment by sils1297** [comment]
Please also see #390 .

**Comment by sils1297** [comment]
#419 is almost fixed, just one (or two) reviews away

**Comment by sils1297** [comment]
@Makman2 how's this going btw.?

**Comment by Makman2** [comment]
I need to rerun tests with the fixed `close()` functions
coming soon :)

**Comment by sils1297** [comment]
I just booted my windows. After it installed, failed and uninstalled the updates from a month ago twice (it does it since then on every boot, how can one be so stupid...) and three reboots later I executed coala tests. A few observations:

 * One now needs to install pyreadline for windows, easy
 * Something seems to be wrong with the closing still
 * GlobTest seems to run indefinitely
 * Counting in GlobTest, 5 of 54 modules fail.

**Comment by Makman2** [comment]
For the first one: This is already fixed in my Makman2/windows-compat branch

**Comment by Makman2** [comment]
No install needed there also :)

**Comment by Makman2** [comment]
The last patch on Makman2/windows-compat: 56e3e09bef73210b8d41935cea66bd6c276e8b32
Works on current master top: 3e1f1c384ee2f06eae2f851df67e90775c93be20
On Windows 8.1 - python3 all tests pass :D

Skipped tests:
- i18nTest (msgfmt not installed)
- EspeakPrinterTest (eSpeak not installed)
- ClangCountVectorCreatorTest (libclang module not found)

I think the libclang issue is worth to support, but I would file that in an extra issue because this is an extra feature :)

**Comment by sils1297** [comment]
fwiw espeak and msgfmt can be installed easily, at least that worked last
time...

2015-05-05 0:05 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Execution seems to work, but the installation is a problem: It's difficult to let python scripts run directly from command line. I'll investigate how we can solve this (maybe a shortcut is possible that invokes python, oh yeah that's a good idea :D)

**Comment by Makman2** [comment]
The solution: Place a `.bat`-file inside a path inside PATH.
The bat-file (called `coala.bat`) should look like:
```
@START python coala "%1"
```

**Comment by Makman2** [comment]
DONE!!!
