### ISSUE TITLE
New docstring format

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1967]
Our current one sucks if you have more than brief single-line documentation (especiall see inside coala-bears JSHintBear).
I would go for this layout:

```python
"""
Brief

Detailed

:param A:
    Description of A, indented by 4 spaces
:param super_extreme_long_so_documentation_would_look_bad:
    ...
"""
```
Opinions?

**Comment by sils1297** [comment]
@Makman2 cool, document it, ship it!

**Comment by Uran198** [comment]
Why would you need both brief and detailed descriptions?

**Comment by Makman2** [comment]
@Uran198 I just used both so you see both are aligned like before^^

**Comment by Uran198** [comment]
@Makman2 Then it's fine.
I think we should also note if we should use `'''` or `"""` for docstrings.
Also, is it a good idea to have such a large docstrings? Mostly, names are self descriptive and this huge kind of stuff can be added to documentations or references. Then, for some bears we can use `**kwargs` and just pass parameters as they are. Possibly, documenting each of them.

**Comment by sils1297** [comment]
(FWIW I think we should have a brief *and* detailed description btw. for bears so we can show the brief description in some contexts and the detailed one in others when the user requests more info about the bear.)

**Comment by sils1297** [comment]
I personally really like that you can write all the documentation for the
bear in the code and you don't have to think about where to write docs. And
coala (i.e. we) takes care of organizing it properly for the user. This is
going offtopic and we should make an own issue btw.

**Comment by Makman2** [comment]
Definitely `"""`, as this is PEP conform, `'''` is no docstring specifier according to the PEP^^

**Comment by Makman2** [comment]
I think API-documentation belongs to the code, then you have directly the code beneath. Even if some names are self-descriptive, often types/parameter inputs must be specified, and Error behavior needs also specification. I want them too like we have now^^

**Comment by sils1297** [comment]
This needs to be documented and then we can use it consistently.

**Comment by Adrianzatreanu** [comment]
This should be documented in Codestyle.rst and maybe then we can use it :)

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#48
