### ISSUE TITLE
Mac support (darwin)

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#197]
Should be easier than windows since its more unix like.

TODO:

- [x] Make sure tests pass
- [x] Make sure installation works
- [x] Make sure execution works

On long term it would be nice if we'd have a continous integration server that builds our stuff on such a system.

**Comment by Giraffe94** [comment]
Would test it on Mac OS X 10.6, 10.9 and 10.10 but I need some help with installation.

**Comment by sils1297** [comment]
Cool many thanks!

First step would be to run the tests without installation. (They are meant not to rely on the installation.) It should be a simple matter of `./execute_all_tests.py` if python >=3.2 is installed.

Installation procedure is described in our README, shouldn't take more than `python3 setup.py install`. After that coala should be an installed python script, it would be great if the binary is available in the path but that depends on OS X policies.

Do not hesitate to ask if there are any problems - thanks for testing!

**Comment by sils1297** [comment]
I updated the readme and included information on how to execute tests. If you think I can do things more clearly, please say so.

**Comment by cqs7520** [comment]
`execute_all_tests.py` states `Tests finished: failures in 0 of 0 test modules` on Mac OS X 10.9 with Python 3.4 istalled
Coala installation suffers from missing root access: `error: could not create '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bears': Permission denied`

Ps.: I'm not sooo good with command line...
Pps.: It's not so good to forget your password AND your e-mail address...

**Comment by sils1297** [comment]
Tried `sudo python3 setup.py install`?

Alternative: `python3 setup.py install --prefix=/choose/any/directory/you/have/access/to` will install the thing into an alternative directory.

**Comment by sils1297** [comment]
I don't know if its sudo on mac.

**Comment by sils1297** [comment]
it is

**Comment by cqs7520** [comment]
I tried `python3 setup.py install --prefix=install` but `error: could not create '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/coalib': Permission denied`

Trying it with `sudo python3 setup.py install --prefix=install` yields `myusername is not in the sudoers file.  This incident will be reported (to Santa Clause).` Maybe it would be nice if coala does not need to be installed (makes it easier to remove it if not longer neccesary)

**Comment by sils1297** [comment]
FYI: I just merged a major documentation update into master.

For installation instructions you can now consult:
https://github.com/coala-analyzer/coala/blob/master/INSTALL.md

You can just execute coala with ./coala but the usual usecase is the installation.

**Comment by sils1297** [comment]
You can switch to a root console with `su` and then typing the password of your root account. You then can add your user to the sudoers file by typing visudo and then uncommenting the appropriate line. (Move cursor above the # sign and press x to delete it, press :wq to write and quit. Press ESC if something doesnt work to return back to the normal mode.) This is too advanced to be covered by the coala documentation.

**Comment by sils1297** [comment]
Maybe try `--prefix=./install`? Seems weird that the prefix thing doesnt work. It is provided by the python std library.

**Comment by cqs7520** [comment]
I tried `./coala` and it put out lots of Bear output (seems to work correctly)
Maybe you can give me further instructions what to test?
Can not install coala: I'm not a sudoer and the root user is deactivated for security purposes.

**Comment by sils1297** [comment]
http://support.apple.com/en-us/HT204012

Executing the tests and the coala script was a great help as a start. Since
our tests cover really many cases and you tried it it seems pretty sure
that this works on Mac. Only thing that needs specific mac testing for now
is installation.

2015-02-03 16:31 GMT+01:00 cqs7520 <notifications@github.com>:

**Comment by cqs7520** [comment]
Tried to install coala with the administrator account and it worked

**Comment by sils1297** [comment]
Cool, thank you! If you want to help us further, I'd be happy to provide assistance. We need people and theres much to do an very different areas including:

- infrastructure (docker stuff, server stuff, I'm trying to set up a pootle instance for our translators)
- translating
- documenting
- code writing (either coala or our website or bears)
- code reading/review

**Comment by sils1297** [comment]
* testing
