### ISSUE TITLE
Add newcomers guide to README

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#1975]
I think we should work on the ``Getting involved`` section a little as it seems quite plain to me. This could be polished to be newcomer-friendly and maybe include a link to our ``Newcomers`` guide from docs here too?

Idea for title: ``Newcomers Guide and Getting Involved``

idea for text: `coala is newcomer friendly and we have built an entire website just to get any contribution done really easily. If you are new and would like to contribute to us, feel free to follow *website* and read our **Getting Involved** site!

We appreciate any help! Feel free to message us on gitter if you have any questions, as we'd be happy to help you!

*box with gitter link*  `

Ideas?

**Comment by Adrianzatreanu** [comment]
I'm making this a newcomer issue as it's only editing the `README.rst` file with some text that i've already given.

**Comment by MattAllmendinger** [comment]
would like to do this
