### ISSUE TITLE
Catch VersionConflict in collect_registered_bears_dirs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1976]
As this is not being caught, http://pastebin.com/6H68P83H happens.

**Comment by sils1297** [comment]
oh I filed a duplicate of this one which is https://github.com/coala-analyzer/coala/issues/1977 but my duplicate has some reasoning why this happens so we should take that one IMO

**Comment by AbdealiJK** [comment]
Is this actually a duplicate ? We want a broad except in `run_main()`

We also should be catching VersionConflict exceptions (and maybe even others) here as we're loading bear modules ?

**Comment by sils1297** [comment]
We need an except in all main methods, having it in run_main is insufficient
