### ISSUE TITLE
docs: Use tinyurl for newcomer issues in Newcomers docs

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1980]
difficulty/newcomer
area/documentation

**Comment by dagdaggo** [comment]
I'll take care of this.

**Comment by abhsag24** [comment]
@dagdaggo assigned :)

**Comment by AbdealiJK** [comment]
What needs to be done:
The newcomer docs at http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html should use the tinyurl link http://tinyurl.com/coala-newcomer as it is smaller and easier to remember to find the "difficulty/newcomer" issues :)
