### ISSUE TITLE
docs: Use tinyurl for low difficulty in Newcomers docs

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1982]
as follow up to the tutorial

difficulty/newcomer
area/documentation

**Comment by AbdealiJK** [comment]
The newcomer docs at http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html should use the tinyurl link tinyurl.com/coala-low as it is smaller and easier to remember to find the "difficulty/newcomer" issues :)

**Comment by ingryan** [comment]
I'll do this!

**Comment by ingryan** [comment]
The documentation at  http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html already uses the tinyurl link, in line 42 of newcomers.rst:

Here is the link that will lead you to `Newcomers issues <http://tinyurl.com/coala-new>`_.

**Comment by sils1297** [comment]
Great, thanks!
