### ISSUE TITLE
Getting_Involved/Newcomers.rst: Change in "What to do after creating Pull Request".

### ISSUE THREAD

**Issue by priests** [coala-analyzer/coala#1993]
It is mentioned as
- your Pull Request doesn't, and therefore you will need to to modify it as per the review comments.
- It should be "your Pull Request doesn't get accepted, and therefore you will need to to modify it as per the review comments."

**Comment by sils1297** [comment]
What change is needed? Grammar?

**Comment by AbdealiJK** [comment]
The description was edited after the issue was made - @sils1297 check it
again or refresh ?
Some words are missing ...

**Comment by priests** [comment]
@sils1297 : I added the description later.   Yes, some words are missing.

**Comment by ingryan** [comment]
I'll fix this, it's a very quick change
