### ISSUE TITLE
GlobbingTest: Tests failing 

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#1994]
i get https://paste.ee/p/azjS1 for GlobTests, on my Fedora23 machine

**Comment by sils1297** [comment]
Seems some of the globbing tests is not immune against `pyc` files that are sometimes generated. Your tests will pass if you just do a `git clean -dfx` but we should fix this test.

**Comment by srisankethu** [comment]
adding ".pyc" with "__pycache__" at lines 221 and 334 will do! https://github.com/coala-analyzer/coala/blob/c1a41ebc92c87e75d15862d0153f81f8491ddc12/tests/parsing/GlobbingTest.py#L221
