### ISSUE TITLE
Source/TextPosition: Use position along with line and column

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#1995]
work is already being done on this on #1947 but there seems to be a lot of discussion on the design.

**Comment by abhsag24** [comment]
current implementation (in the PR): 
Make a new class called `AbsolutePosition` which inherits `TextPosition`
add functionality to convert position, to line,col to feed into `TextPosition`.

To be implemented: 
Use `AbsolutePosition` while calculating `SourceRange`

**Comment by Makman2** [comment]
Imo absolute position would be a plain int. Thats why we use classes for the row-column stuff because thats already a tuple and you can do more with it in the right context.
The problem that the row-column and absolute position are dependent on the underlying string^^

**Comment by sils1297** [comment]
I think the current solution is sane, I acked it.

**Comment by Makman2** [comment]
I would go more into a "mixin" design, there's an `AbsolutePosition` and a `TextPosition` (--> row/column), and if you want both you inherit from both too^^
Because conceptually it doesn't make sense imo, absolute positioning is not a requirement for line/column positioning and vice-versa

**Comment by Makman2** [comment]
maybe we should just store the underlying string...

**Comment by abhsag24** [comment]
@Makman2  I like storing the string idea, but what next? do w still have different classes?

**Comment by abhsag24** [comment]
we should reopen this issue if the current implementation if the current implementation doesn't satisfy

**Comment by Makman2** [comment]
I would say we have no different classes then. `TextPosition` is then able to handle everything, absolute and line/col position^^

**Comment by abhsag24** [comment]
@Makman2 there was an implementation that did this and it turned out to be very messy, @sils1297 is there a way we can get that back, for log purposes?

**Comment by Makman2** [comment]
Wasn't that because of the None-handling? We could introduce two contructors/classmethods and use lazy property evaluation methods.

**Comment by abhsag24** [comment]
but we'll still have the case where there might be ambiguity, `no line, column but position`, or `line and column but no position`, or `line, column, position but no text` to verify, how do we deal with that?

**Comment by Makman2** [comment]
depending on which constructor used we could set the laziness status together with a conversion function or so^^
We could maybe write decorators/classes for that doing these conversions in every direction, in fact I would need such a class/decorators when I come to the next-gen-design. I want to introduce a file proxy, which contains the text as a string, the filename, and the text already line-splitted.

What I have currently "prototypely" in mind is something like this:
```
class X:
    # some constructors and stuff

    @lazyproperty
    def prop(self):
        if self.propA != 0:
            return self.propA * 30
        elif self.propB:
            return self.proB / 2
        else:
            return RuntimeError("Invalid object state, can't get property 'prop'.")
```
`@lazyprop` would use some sort of caching too^^

**Comment by abhsag24** [comment]
@Makman2 even with conversion functions we'll have ambiguity in cases where enough information is not provided to help in the conversion, we could force the user to provide information, but then that'd break existing usage.

**Comment by Makman2** [comment]
then we throw an error like in my example, which imo makes totally sense. The user would need to use the right constructors we provide so there wouldn't occur such "leaks".

**Comment by abhsag24** [comment]
@Makman2 i'm not sure, if a person want's to store say a `position` without `text` i don't see any harm in that, it shouldn't lead to an error, but at the same time it would mean not being able to calculate line and column which leads us back to our current debate, IMO what we have right now is alright.

**Comment by Makman2** [comment]
yeah it currently works, I think also this is not that important, and especially we don't gain something (nearly) :3
