### ISSUE TITLE
`coalib.misc.Decorators.assert_right_type`: Add docstring

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#1997]
The docstring is missing, and I have forgotten to add it after signalling this function as being public.

**Comment by heijligen** [comment]
I can do this issue

**Comment by sils1297** [comment]
this was moved to gitlab, the issue should be moved

**Comment by Makman2** [comment]
Moved to https://gitlab.com/coala/coala-decorators/issues/4
