### ISSUE TITLE
`# Start ignoring`: Allow to provide without `# Stop ignoring`

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2003]
I think there's a usecase where you want to specify inside a file that the rest of it shall be ignored (without extra defining a stop-comment), I needed it for my `Future` module (or at least it would be nicer to have not provided an end-comment).

Don't forget to document that (especially inside the tutorials)!

**Comment by sils1297** [comment]
@Makman2 this shouldn't be documented! The user should close it and we should be forgiving if he forgets to do it but IMO it sholdn't be advertised as a feature

**Comment by Makman2** [comment]
makes sense :+1:
