### ISSUE TITLE
TextPosition: Overload comparison operators 

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#2004]
This would be super-useful IMO

**Comment by Makman2** [comment]
What functionality do you miss?

**Comment by sils1297** [comment]
Doesnt it use generate ordering yet?

**Comment by Makman2** [comment]
yeah it does^^

**Comment by sils1297** [comment]
@abhsag24 reopen if we got you wrong

**Comment by abhsag24** [comment]
ahh i got an error since i was using the wrong way, so i thought this functionality wasn't there,  sorry
