### ISSUE TITLE
docs: Add information about the use of labels

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#2009]
From the discussion in https://github.com/coala-analyzer/coala/issues/1875.
There should be an information in the contribution guide on what some labels imply, i. e.:
- if there is difficulty to the issue, then it is ready to be worked on.
- if there are no labels - it's pending review
- if there is a label `status/needs design` or `status/needs info` - there is still an ongoing discussion either on how to implement it, or should it be implemented.

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#46
