### ISSUE TITLE
docs: Add information about long issue discussions handling

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#2010]
From the discussion in #1875.
It should be documented that after the long discussion, should be created new issue with clearly defined task.

**Comment by AbdealiJK** [comment]
Where should this be added ? which file ?

**Comment by Uran198** [comment]
I think either in the wiki, at Maintainer's corner, or in the docs at getting involved.

**Comment by sils1297** [comment]
Good idea.

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#45
