### ISSUE TITLE
Result: Change error message

### ISSUE THREAD

**Issue by srisankethu** [coala-analyzer/coala#2020]
Change error message [here](https://github.com/coala-analyzer/coala/blob/master/coalib/results/Result.py#L60) from ``severity is no valid RESULT_SEVERITY`` to ``severity is not a valid RESULT_SEVERITY``. difficulty/newcomer.

**Comment by Makman2** [comment]
I don't see a difference between the messages :O

**Comment by sils1297** [comment]
@Makman2 just read it again :) or you can apply a Sequencematcher on it :P

**Comment by Makman2** [comment]
I mean a semantic difference^^

**Comment by eneukirchner** [comment]
Yes, I want to do this!
