### ISSUE TITLE
Testing_Bears.rst: Fix grammatical mistake

### ISSUE THREAD

**Issue by srisankethu** [coala-analyzer/coala#2028]
Change the sentence "coala has an awesome testing framework so you can write tests for bears with ease" [here](https://github.com/coala-analyzer/coala/blob/master/docs/Users/Tutorials/Testing_Bears.rst). difficulty/newcomer area/documentation

**Comment by Makman2** [comment]
where's the grammatical mistake?

**Comment by srisankethu** [comment]
it should be "...framework to write tests...."

**Comment by srisankethu** [comment]
I will just fix this since there are already many newcomer issues :+1:

**Comment by Makman2** [comment]
hmm but the old sentence is not wrong or bad, imo we can keep it like it is :O

**Comment by srisankethu** [comment]
the old sentence makes sense when it is "...framework so that you can write..."
