### ISSUE TITLE
Add google analytics to docs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#2040]
readthedocs should have the google analytics id (can be found below). Need to check the docs of readthedocs and figure out how to do this, or just embed this html code into their code using RST.

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76769778-2', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by tfar** [comment]
Don't forget to let the viewers of the documentation know that they are being watched and tracked if you happen to decide that adding visitor tracking to a online documentation of a software project provides enough useful information to be worthwhile.

**Comment by sils1297** [comment]
@tfar hey are you against us doing this? We'd be happy to discuss this, privacy is important. Where would be the right place to mention something like this?

**Comment by sils1297** [comment]
So my personal take on this is I'm not fully sure. The whole internet watches you already, you're being watched by GitHub as well, possibly readthedocs does that already. It's simply not possible to not watch users in a way just by observing server load. Now, taking a tool like Google Analytics gets us some more information that may help improving documentation. There's a very blurry border here somewhere that differs for different people.

I'd like to have @AbdealiJK s stand on how useful this is after all, I've never worked with that kind of data.

**Comment by AbdealiJK** [comment]
Google analytics would help track how many people find the documentation and how they find the documentation. It also has demographic information helping us plan conferences (maybe). This would help us in making things better. 

All in all: I prefer having more data even if I don't use it. But that's subjective and the community should decide (hence the issue)

My opinion on the privacy issue: If I visit a website, I expect them to have a log of me visiting it (because apache already does it with my IP, mac, etc). Internet works two ways, If I see and use public info on a website, the website can see and use my public information too.

@sils1297 If we're doing this, it'd go into a "Terms of Usage" or so file I guess.

**Comment by Uran198** [comment]
Adding this should be simple according to http://www.drmaciver.com/2015/04/getting-google-analytics-on-readthedocs/
I agree with @AbdealiJK that this can help us improve documentation and the project itself.

**Comment by tushar-rishav** [comment]
I think adding analytics script would also help us keep track of the bouncing rate. Things like how far user has read the docs by scrolling can be also be known. Overall I think it would be useful to have it if we provide a message somewhere saying that we are tracking your behaviour on this doc page.

**Comment by Makman2** [comment]
like a cookie notification on other websites :)

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#44
