### ISSUE TITLE
LineLengthBear: Crashes

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2042]
```
[WARNING][01:28:25] Bear LineLengthBear failed to run. Take a look at debug messages for further information.
[DEBUG][01:28:25] The bear LineLengthBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/coalib/bears/Bear.py", line 112, in execute
    return list(self.run_bear_from_section(args, kwargs) or [])
  File "/usr/lib/python3.4/site-packages/bears/misc/LineLengthBear.py", line 30, in run
    line_nr=line_number + 1)
  File "/usr/lib/python3.4/site-packages/coalib/misc/Decorators.py", line 298, in decorated
    return function(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'line_nr'
```
happens on coala's master

**Comment by sils1297** [comment]
@Makman2 what command did you run?

**Comment by Makman2** [comment]
just `coala`

**Comment by sils1297** [comment]
with installed coala being the one from master as well?

**Comment by Makman2** [comment]
this is the full output: https://gist.github.com/Makman2/cef1b268899db3d008a4dcfe9f9280e6

**Comment by Makman2** [comment]
so yes, the latest prerelease, for coala and coala-bears^^

**Comment by Makman2** [comment]
even with `git clean -dfx` the same happens^^

**Comment by sils1297** [comment]
WOw this is very weird...

**Comment by AbdealiJK** [comment]
I do not think this is a code related bug - more like a system related bug.

Your coala-bears is definitely not at master ad it says:
```
File "/usr/lib/python3.4/site-packages/bears/misc/LineLengthBear.py", line 30, in run
    line_nr=line_number + 1)
```
in the trace back which is not true on [master](https://github.com/coala-analyzer/coala-bears/blob/master/bears/general/LineLengthBear.py#L30)

So, can you post output of:
```
$ python3 -c "import coalib; print(coala.VERSION)"
$ python3 -c "import bears; print(bears.VERSION)"
$ pip3 list | grep coala
```

**Comment by Makman2** [comment]
This is interesting, I installed the most recent version via pip.
coala: 0.6.0.dev20160421213233
coala-bears: 0.2.0.dev20160419161846

**Comment by Makman2** [comment]
but even with older versions it should not occur^^

**Comment by AbdealiJK** [comment]
I still don't get why "File "/usr/lib/python3.4/site-packages/bears/misc/LineLengthBear.py", line 30, in run" is wrong ...

Can you open it and check if the code is what you expect ?

**Comment by Makman2** [comment]
yeah the namespace is totally wrong, package `bears.misc` does not exist any more. Don't know why python hasn't deleted it^^

**Comment by Makman2** [comment]
works again, dependency problems on my system :+1:
old ancient modules weren't removed :D
