### ISSUE TITLE
Bear-language: Wrap "no language"-message in braces

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2046]
```
The bear does not provide information about which languages it can analyze.
```
Should be
```
(The bear does not provide information about which languages it can analyze.)
```
As it's way better to read when doing `coala -B`, otherwise one thinks this is text that actually specifies some important property of the bear^^ with braces one can overread it quicker^^

**Comment by sils1297** [comment]
Apparently nobody wants this :)
