### ISSUE TITLE
Fix the asciicinema demo's max-width

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#2052]
In the pypi page, this looks really bad: https://pypi.python.org/pypi/coala

So we want to fix a width. Currently it seems to be "100%"

**Comment by AbdealiJK** [comment]
Apparently we can embed the asciinema directly by using the script tag like the website

http://stackoverflow.com/questions/9444342/adding-a-javascript-script-tag-some-place-so-that-it-works-for-every-file-in-sph

**Comment by SanketDG** [comment]
Hey thanks! That works, assigning myself this.

**Comment by AbdealiJK** [comment]
**About raw html**
It seems github recently (Oct 2015) accepted a patch to enable RAW html. But this does not seem to work in the github preview, so I think they haven't deployed it yet. https://github.com/jeremiahyan/markup/pull/1
This is the latest commit in their repo https://github.com/github/markup

**About width attribute**
The width attribute is purposely ignored by github as they prefer setting the max-width value (which can be seen on Inspecting HTML. More info at http://stackoverflow.com/questions/35486427/how-to-resize-images-included-in-github-documentation-pages

I think the best course of action is using the `:width:` in pypi as pypi does not set the max-width and hence should not override the width attribute. I do not think "raw html" will work in pypi as apparently they have a very restrictive set of supported rst commands. Only way to check is make dev versions and try things out.
