### ISSUE TITLE
Importers.py, line 82: Chek -> Check

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2058]
typo needs correction
difficulty/newcomer

**Comment by sils1297** [comment]
it's in the doc comment for `_is_defined_in` and it moved down a few lines

**Comment by AbdealiJK** [comment]
@sils1297 can you check this ? gitmate-bot seems to add low and newcomer if you add "difficulty/newcomer" in he description - that is wrong right ?

**Comment by sils1297** [comment]
@AbdealiJK lets discuss that at GitMate issue tracker/gitter

**Comment by emperorofmars** [comment]
I will do this.

**Comment by emperorofmars** [comment]
This was already done, nothing to do here.

**Comment by AbdealiJK** [comment]
Actually it's not done. The line number is reported wrongly. it is at line 82
