### ISSUE TITLE
Make circleci FASTER

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#2065]

**Comment by sils1297** [comment]
`$ pip install coala-bears colorama==0.3.6 --pre -U` seems to take 7 minutes?

**Comment by AbdealiJK** [comment]
This is not a major issue actually. The reason for it to take so long was because you updated coala-bears very frequently yesterday. Which means it kept having new releases which were picked up by `pip --pre`

So, it's simply because the cache was updating itself. The build times have decreased now to 8-9 mins.
@sils1297 can you confirm that this is fine ? I'm not sure if it can be decreased further as each step is less than 30 sec.

**Comment by sils1297** [comment]
oh this is great, thanks!
