### ISSUE TITLE
Linter: Implement csv output format

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2069]
One of our bear uses it, and it should be easy to implement some generic mapping feature for csv outputs.

**Comment by AbdealiJK** [comment]
FWIW: After https://github.com/coala-analyzer/coala-bears/issues/363 we wont have any bear which uses CSV
I think CSV is weird and it's be better to do something for supporting the popular XML standards like Xunit that circleci likes (seems to be a standard format for linters)

**Comment by Makman2** [comment]
If you think JSON is better, alright. As no bear uses CSV then right now: Implemented on demand.
