### ISSUE TITLE
Add crosstesting in the docs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#2074]
It would be nice to give a method of things to add if we want to crosstest things between coala and coala-bears as @Makman2 had to do for the Linter stuff.
Would be good to add to docs (so that if the branch which did this last time was deleted, it doesnt matter)

The last PR with crosstest is here: https://github.com/coala-analyzer/coala-bears/pull/314

Assigning Makman as he's the best one to do this I think

**Comment by Makman2** [comment]
I think that doesn't belong to the docs :O Let's just keep my branch and everything is fine, we adjust it as needed^^ As we hack quite into the CI we shouldn't make this "official"^^

**Comment by AbdealiJK** [comment]
Then I think we should clean it up and make an easy method of doing this

**Comment by Makman2** [comment]
Is there an easy way? :O

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#43
