### ISSUE TITLE
Add function to download stuff cached if needed (when running bear)

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2084]
we should use this for checkstye etc., @AbdealiJK has used this for checkstyle configs already

**Comment by AbdealiJK** [comment]
It'd be nice to make a function in Bear.py names "data_dir()" or so which
gives which folder to download bear specific stuff in

**Comment by sils1297** [comment]
CC @Adrianzatreanu this is probably related to your project.

Bears should get a simple mechanism that downloads (and sets up?) dependencies for them. Later @Adrianzatreanu s bear manager should be able to trigger that.

We should have this ASAP for checkstyle and so on. I'm throwing my time on this one now.
