### ISSUE TITLE
Bear: Add `languages_tuple` propertingy

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2087]
which converts the `LANGUAGES` into a tuple if it's a strint

**Comment by Makman2** [comment]
where's the problem with using a property for `LANGUAGES` :O another property is cumbersome imo ^^

**Comment by sils1297** [comment]
or just a function, the user has nothing to do with it

**Comment by Makman2** [comment]
but where's the gain? :O

**Comment by sils1297** [comment]
blnothing changes for the user, we have less duplication, we have the same if in multiple places which is redundant and possily error prone as we're bound to forget it next time

**Comment by Makman2** [comment]
```
GitCommitBear:
  Check the current git commit message at HEAD. This bear ensures that the shortlog and body do not exceed a given line-length and that a newline lies between them.

  Supported languages:
   * G
   * i
   * t

  Used in:
   * commit
```
We should definitely fix it asap :)

**Comment by Makman2** [comment]
maybe we can use a metaclass that automatically assigns `LANGUAGE` a tuple if provided a string.
