### ISSUE TITLE
Try to setup argcomplete inside setup.py

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2099]
Don't know whether this is possible, but maybe we can make a setup command that executes necessary argcomplete registrations?

**Comment by sils1297** [comment]
I also think we should make an own autocompletion generator script, dedicated, for performance and complexity reasons.

**Comment by AbdealiJK** [comment]
There are more meaningful discussions of this at https://github.com/coala-analyzer/coala/issues/2405 which I had created because I didn't know this existed. Closing this in favour of that
