### ISSUE TITLE
Linter: Catch if `None` is returned from `create_arguments`

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2101]
The linter currently tries to tupelize `None` which yields a `TypeError`. We should catch that case and return from `run()` directly.

**Comment by SanketDG** [comment]
Should we just check to make sure its not a tuple or raise an Exception?

**Comment by Makman2** [comment]
it needs to be checked/catched inside `Linter.run()` so it doesn't crash, maybe log an error or so too^^
-> just check, no extra raise :)
