### ISSUE TITLE
Stable API

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#2110]
On Linuxwochen one guy asked a lot about stable API and when will it happen. Also, I don't think he would use it until that point. Maybe, we should have at least approximate plan for the future.

**Comment by Makman2** [comment]
Me and @sils1297 have talked about this, and we were convinced to wait for the next-gen-bears stuff (from me), after that we could try to keep a stable API.

**Comment by Uran198** [comment]
I understand, but just an approximate date, perhaps, may be helpful, or at least `not sooner than` date. What I'm assuming is that this may stop from even trying coala much more that one person.

**Comment by sils1297** [comment]
I  can imagine 1.0 after GSoC

**Comment by Uran198** [comment]
I'd maybe have one or two months after that reserved as well.
IMO, We should announce that and mention at least in README.

**Comment by sils1297** [comment]
Feel free to go ahead

**Comment by AbdealiJK** [comment]
We should make a milestone for 1.0 and add it here (with the date)

**Comment by sils1297** [comment]
Milestone available, set to end of september. Can this be closed then?
