### ISSUE TITLE
ConfigurationGatheringTest fails

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2111]
https://gist.github.com/Makman2/a093c14125916f310ec220f6f167f661

Works on the CI though^^

**Comment by hypothesist** [comment]
@Makman2 I'm suddenly facing this too. Any solutions to this? Or just `py.test -k "not Conf"`?

**Comment by Makman2** [comment]
Yes, just ignore the test via `-k "not ConfigurationGathering"` (or `-k "not Conf"` if it works) :+1:

**Comment by Makman2** [comment]
Duplicate of https://github.com/coala-analyzer/coala/issues/2210#event-680601791 and got solved by now :+1:
