### ISSUE TITLE
Make a merge_docs decorator for classes

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2114]
@Makman2 introduced a rather verbose pattern of merging signatures, we should rather have a decorator for that!

**Comment by Makman2** [comment]
Sorry I don't understand the goal of this issue completely :/

**Comment by sils1297** [comment]
```python
@merge_signatures(("run", "self"), ("do_something", "self", "irrelevant"), classdoc=True)
class Something:
    def run(self, bla, bla1):
        pass
    def do_something(self, irrelevant, relevant):
       pass
```

and that should do the whole metadata merging for the class documentation, run and do_something with self and irrelevant in omit for do_something e.g.

**Comment by Makman2** [comment]
does that shortcut something? currently I merge metadata if I delegate some functionality to different functions that shall expose their settings via the parameters. These params are passed everytime to `run` and need to be manually delegated to the according functions (via `FunctionMetadata.filter` or how it was called again).

**Comment by Makman2** [comment]
Via your decorator I have no access to the metadata stuff any more to perform this parameter delegation^^

**Comment by sils1297** [comment]
the dacorator can make the metadata filter function available easily

**Comment by Makman2** [comment]
Just agreed together that this is not really important (and also not cool *cough*) :P
