### ISSUE TITLE
ShowPatchAction bug with printing unified diff

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#2117]
`.coafile`:
```
[Default]
bears = PEP8Bear
files = py.py
```
`py.py`:
```python
def helloWorld():



++
	return(print("""hello World"""))

 #s

helloWorld()
```
When running coala, I get the following patch:
```
----|    | /media/data/data/Projects/example/coala_showcase/py.py
|    |++++| /media/data/data/Projects/example/coala_showcase/py.py
|   1|   1| def helloWorld():
|   2|   2| 
|   3|   3| 
|    |++++| 
|    |   4|+    return(print("""hello World"""))
|   4|   5| 
|   5|   6| ++
|   6|   7|     return(print("""hello World"""))
```
It split the patch. The corresponding issue is https://github.com/coala-analyzer/coala-bears/issues/396.
Also, it should have outputted something like `|    |   4|+++`, instead of `|    |++++| `
A little artificial example, but can happen when dealing with text files.

**Comment by sils1297** [comment]
I'm currently thinking about a smart solution: we could introduce a parameter to `split_diff` so diffs get only splitted if they are further away than n lines.

**Comment by sils1297** [comment]
this should fix it from coala side, bears will then be a bit more tolerant by default and can set the distance as they need it

**Comment by Makman2** [comment]
Though this is often highly problem related, it depends on the tool if they allow to provide for each single issue a separate patch, but the distance parameter is anyway a good idea :)

**Comment by Makman2** [comment]
So yes I agree, this is fixed from coala side, it can't predict which changes belong functionally together.
@Uran198 you agree too?

**Comment by sils1297** [comment]
Yes, the tools should use the distance parameter. @Makman2 can you expose it in the linter?

**Comment by Makman2** [comment]
See https://github.com/coala-analyzer/coala/issues/2144
