### ISSUE TITLE
DocumentationComment: two classes in codebase.

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#2118]
Currently there are two classes for DocumentationComment:-

* [`DocumentationComment(desc, param_dict, retval_desc)`](https://github.com/coala-analyzer/coala/tree/master/coalib/settings/DocumentationComment.py)

This also has a function `from_docstring()` which parses doc comments and extracts the description, params and return values.

* [`DocumentationComment(documentation, marker, range)`](https://github.com/coala-analyzer/coala/tree/master/bearlib/languages/documentation/DocumentationComment.py)

How do we handle these two classes?

My initial idea is to have `DocumentationComment(documentation, marker, range)` where `documentation` is again a `namedtuple` of the various parts:

```python
from collections import namedtuple
namedtuple('DocComment', 'desc, params, retval')
```

Thoughts?

CC @Makman2

**Comment by sils1297** [comment]
/me hates @Makman2 for introducing the second class. Having two equally named classes is *bad*.

**Comment by Makman2** [comment]
@SanketDG good idea, though it's language dependent which attributes go into the `documentation` param.
@sils1297 the old class was just for python docstrings, and another name did not make sense :3
