### ISSUE TITLE
Installation: Update

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2124]
Many people are getting this issue: https://github.com/coala-analyzer/coala/wiki/FAQ#installation-is-failing-help

we should deal with that in the install docs.

difficulty/low
importancs/high

**Comment by rmariano** [comment]
Do you plan to address this in the documentation? Maybe we could add the pip version we depend on, to our ``requirements.txt``/``setup.py`` so it's part of the installation. Just my 2 cents.

**Comment by sils1297** [comment]
Neat, I wonder if that would help though since I would guess it first parses the whole requirements.txt before it resolves the dependencies, thus it fails on parsing instead of giving the user a message that a higher pip is needed I guess?
