### ISSUE TITLE
Make first steps better visible

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2125]
Installing and running coala for the first time should be really easy. I think we should provide getting started instructions more clearly. Also:

> yeah, there's a link to that in readme.md. But for me atleast, every click a project forces me to take beyond readme.md to get to hello world is walking on thin ice :smile:

**Comment by sils1297** [comment]
> It would've been nice if there was a hello world-kind of example for running coala. Something like this:

> cat (bla bla) > foo
> coala --bears=SpaceConsistencyBear --files=foo

**Comment by loota** [comment]
It would be astonishing to see right away in the readme.md something along the lines of

"List all available bears
coala --show-all-bears

List bears relevant to JavaScript
coala -l js"

**Comment by loota** [comment]
If IRC channel is linked to gitter then it would be nice to also advertise the irc channel in readme.md

**Comment by sils1297** [comment]
Forgot to mention this issue in the commit, but this is fixed by:

- 56f981f README: Mention IRC and telegram
- c9307fe README: Add bear listing examples
- ebeace9 README: Add minimal hello world example
- 2c1e6b4 README: Add pip debian information

(All of which are acknowledged and will be merged when build pass.)
