### ISSUE TITLE
Use `--cov-fail-under` in circleci and pytest

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#2126]
There's this nice `--cov-fail-under` arg in pytest which we should consider as a backup. Especially because codecov became unstable a while back.

Also: `--no-cov-on-fail` would be useful to not do coverage if the tests fails (As it'd be useless anyway)
EDIT: Actually `--no-cov-on-fail` may be useful for debugging sometimes @sils1297 had said once. So maybe we don't want that.

**Comment by underyx** [comment]
`--cov-fail-under` will cause issues cause codecov.io is unifying the coverages from different python versions; I wouldn't want a newcomer deealing with those, so I'm raising the difficulty.

**Comment by AbdealiJK** [comment]
Closing this as it doesn't seem feasible. To do this we'd need to use `--cov-fail-under 99` which is a hack. Now it seems codecov is back on track and working fine, so I'm closing this.
