### ISSUE TITLE
Merge coala and coala-bears README

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2128]
both diverge and people seem to land on both of them, I think we should have one of them redirect to the other one or so? Not sure :/

area/documentation
status/needs design

**Comment by abhsag24** [comment]
maybe we can "generate" the readme for coala-bears at the time of installation? and just update the readme at the repo at the time of a version bump for coala?

**Comment by Adrianzatreanu** [comment]
The readmes have changed drastically, closing if you think this was fixed :)
