### ISSUE TITLE
Option to exit between result prompts

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#2134]
It'd  be nice to have an option or atleast a message saying, `press ctrl + D to exit`

**Comment by abhsag24** [comment]
print `Please enter the number of the action you want to execute (Ctrl-D to exit)` in the `results` prompt according to discussion at gitter :)

**Comment by Makman2** [comment]
you can just type CTRL+C like you would expect from a terminal application, imo no adjustment needed^^

**Comment by abhsag24** [comment]
@Makman2 but a `(Ctrl-D to exit)` wouldn't harm right?

**Comment by Makman2** [comment]
does coala exit on `CTRL+D`?

**Comment by abhsag24** [comment]
yes :)
