### ISSUE TITLE
Tests fail with .coarc

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#2142]
`~/.coarc`:

```
[Default]
files = *.py
max_line_length = 80
```

Tests failing: `coalaTest`, `ConfigurationGatheringTest`

**Comment by sils1297** [comment]
using `-I`

**Comment by sils1297** [comment]
...should solve that issue :P

**Comment by Makman2** [comment]
This could be a duplicate of https://github.com/coala-analyzer/coala/issues/2111

**Comment by Makman2** [comment]
@sils1297 and how does using `-I` solve that? You can't pass `-I` through py.test, or do you mean to change the coala arguments inside the tests?

**Comment by sils1297** [comment]
Inside the tests

**Comment by sils1297** [comment]
still valid?

**Comment by Makman2** [comment]
nope :)
