### ISSUE TITLE
Document Config Generation

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2145]

**Comment by sils1297** [comment]
for linter

**Comment by AbdealiJK** [comment]
I think the best way is to make a website which has a table of the configs being used right now, the documentation related to that param, and the bears it's being used in. This website/webpage should have a search box for easy searching and should be auto generated from the bears itself.
This webpage would help third party bear writers too ! And would be a really cool one-page documentation of all the "features" coala provides. And also which bears it provides them in.

Possible methods of doing this:
 - Make a parser using our documentation parsing routines and create a webpage with it. And then link this in the docs.
 - Configure sphinx to autogenerate this (somehow? if it's possible...) I think sphinx is pretty flexible ?

I think this page should reside in our documentation and should be "autogenerated" in every readthedocs build.

**Comment by sils1297** [comment]
@AbdealiJK are you sure this comment was on the right issue? Did you mean to comment on https://github.com/coala-analyzer/coala-bears/issues/460 ?

**Comment by AbdealiJK** [comment]
Yes indeed. I confused the issues.
It was meant for https://github.com/coala-analyzer/coala-bears/issues/460

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#42
