### ISSUE TITLE
coala readme isn't nice on pypi!

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2148]
difficulty/low
importance/critical

Can somebody look at this ASAP? @Adrianzatreanu @AbdealiJK

**Comment by Adrianzatreanu** [comment]
What do you mean readme on pypi?
Also why does this have 2 importance labels?

**Comment by sils1297** [comment]
https://pypi.python.org/pypi/coala is totally misformatted! Same for coala-bears.

**Comment by Adrianzatreanu** [comment]
Can fix this when i get home, in 4 or 5 hours. Leaving unassigned as its critical and someone may want to work on it earlier than me

**Comment by Adrianzatreanu** [comment]
Closed by https://github.com/coala-analyzer/coala/pull/2163

**Comment by Adrianzatreanu** [comment]
reopening until fixing for coala-bears.
