### ISSUE TITLE
Add LICENSE attribute for bears

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2153]
I'm not sure if bears must be AGPLv3 since they use an API from coala that is licensed this way, still their wrapped tools might not be free software and we may want to have a LICENSE attribute.

Any thoughts?

**Comment by Makman2** [comment]
if that is possible I would go for it, more people can use coala.

**Comment by Adrianzatreanu** [comment]
Being fixed here, amonst others https://github.com/coala-analyzer/coala/pull/2338

**Comment by AbdealiJK** [comment]
Closing as https://github.com/coala-analyzer/coala/pull/2338 was merged
