### ISSUE TITLE
Linter: Use static message for Result when output format is `regex`

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala#2156]
It would be nice if we can have the option to override the default message of `Results` section in the new Linter v2 API. Would solve the issue at https://github.com/coala-analyzer/coala-bears/issues/31 and other such future bears too, where the linter doesn't have an explanatory error message. 

cc @Makman2

**Comment by Makman2** [comment]
What do you want exactly to manipulate?
It's possible modify messages for the default executable check and the custom prerequisite check command. And for the results it depends on the output format, for `corrected` you can provide a message that shall be used everytime, for `regex` you match the message inside the output of the used executable.

**Comment by sils1297** [comment]
Give it a static message instead of a regex match group

**Comment by Makman2** [comment]
ah okay, yes can do that :+1:
