### ISSUE TITLE
OpenEditorAction: Be aware of renamings and deletions

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2168]

**Comment by sils1297** [comment]
was this solved @Udayan12167 ?

**Comment by AbdealiJK** [comment]
Bump ?

**Comment by sils1297** [comment]
@Udayan12167 this is important, can we have this ASAP?

**Comment by Udayan12167** [comment]
@sils1297 It was fixed as there is a test for the scenario in openeditoraction

**Comment by sils1297** [comment]
so this can be closed?
