### ISSUE TITLE
Remove raise_error function

### ISSUE THREAD

**Issue by Uran198** [coala-analyzer/coala#2182]
[Here](https://github.com/coala-analyzer/coala/blob/master/tests/TestUtilities.py#L47) it is:
```python
def raise_error(error, *args, **kwargs):
    raise error(*args, **kwargs)
```
Maybe it had some usage in the past, but it apparently only clutters code right now.

**Comment by sils1297** [comment]
this is relevant if you want to make lambdas that raise stuff, it's not used anywhere?

**Comment by Uran198** [comment]
Yeah, only in that lambdas, but for example one of the lambdas:
```
            import_fn.side_effect = (
                lambda *args, **kwargs: raise_error(VersionConflict,
                                                    "msg1", "msg2"))
```
How using `raise VersionConflict("msg1", "msg2")` worse?

**Comment by sils1297** [comment]
you can't raise in a lambda because a raise isn't an expression, a function
however is so having a function that raises is the only way to raise a
thing in a lambda

**Comment by Uran198** [comment]
I think all the use cases can be removed with mocks and `side_effect`s. You can use side_effect like:
`import_fn.side_effect = VersionConflict("msg1", "msg2")` to the same effect as with lambdas.

**Comment by sils1297** [comment]
oh yes mocking is way better probably.
