### ISSUE TITLE
Glob: support **.py for **/*.py

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#219]

**Comment by sils1297** [comment]
like those: http://editorconfig.org/

**Comment by smfn3321** [comment]
Although it is nor explicitely stated [here](http://python.readthedocs.org/en/latest/library/glob.html), I do not think the python implementation in 3.5 will allow this.

Their examples include:
```python
>>> import glob
>>> glob.glob('./[0-9].*')
['./1.gif', './2.txt']
>>> glob.glob('*.gif')
['1.gif', 'card.gif']
>>> glob.glob('?.gif')
['1.gif']
>>> glob.glob('**/*.txt', recursive=True)
['2.txt', 'sub/3.txt']
>>> glob.glob('./**/', recursive=True)
['./', './sub/']
```

I do however understand the simple explanation in editorconfig, that '*' matches any sequence of symbols not containing os.sep() while '**' matches any sequence of characters. 

@sils1297 if you really want this functionality I will probably add it through a specific workaround where i replace '**letters' with `**/*letters`. Should I do that?

**Comment by sils1297** [comment]
No, its ok for me to not have that functionality, especially if 3.5 doesn't implement it either.
