### ISSUE TITLE
Add space-case algorithm

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2193]
Currently case algorithms supported are snake-case, camel-case and pascal-case.

Space-case uses uppercase letters at the beginning of an expression and separates them with spaces:

```
Hello World Thingy Separated With Spaces
# equivalent in snake-case:
hello_world_thingy_separated_with_spaces # <-- actually not here...
```

Task is to implement a `to_spacecase` algorithm inside `coalib.bearlib.naming_conventions` together with some doctests (see the other algorithms and take them with slight modifications), and also to make the other algorithms "space-case-aware", i.e. that separators like the space are treated correctly and actually identified as a separator and upper-case letter are recognized as identifiers that start a new expression/word.

**Comment by Asnelchristian** [comment]
can i work on this ?

**Comment by sils1297** [comment]
sure
