### ISSUE TITLE
External coalang

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#2199]
so right now coalang files are packaged, which is fine for most of the existing bears but right now they just cover 2 languages and even when they would expand it'd be impossible to cover `all` languages, so it might be a good idea to provide an option for an `external coalang` for undocumented languages.

opinions: @fneu @Makman2  @sils1297 

CC: @SanketDG

**Comment by Makman2** [comment]
I'm not sure we want this, more maintenance for us (as stuff gets just more complicated) + it's encouraged to merge settings for missing languages into the repo.

**Comment by Makman2** [comment]
also each class loads everything manually,  we don't have some kind of coalang manager or so^^

**Comment by abhsag24** [comment]
^That's what the feature is about, adding that kind of a coalang manager, also do we expect the user to merge his choice of language into coala first in order to use it? and we dont have to manage it right? it's the user's choice if he/she wants to merge it. Also i have opened #2200 so users will have to follow the template their in order to create a new coalang file

**Comment by Makman2** [comment]
you know that `DocstyeDefinition` has it's own coalangs too? imo this is quite complicated to have some manager, especially as every coalang is distributed in a different module^^ manually loading stuff is easier imo

**Comment by abhsag24** [comment]
yes, but they remain like they are right? we don't change them just add a feature to create own coalangs too. We don't change the existing structure. 
>especially as every coalang is distributed in a different module^^

yeah so we follow a `standard template` which every coalang has to follow or atleast one template for `LanguageDefinition` and one for `DocStyleDefinition`

**Comment by abhsag24** [comment]
> manually loading stuff is easier imo

we will still manually load most of the stuff, like `JAVA, C, C++, python, ruby` and so on but for more obscure languages like `brainfuck` or `FALSE` we can't expect the user to first send in a `PR` with us in order to load his/her desired language right? especially if they are not a coala contributor.

**Comment by Makman2** [comment]
well when they can send a PR they can also modify that on their clone and install that.
And what is the "existing structure"? Just the format of the file is the same, there are no naming conventions or anything for the settings.
Alright I think before we are drive this discussion-car into the ocean, we should make a concrete design on how the manager should look like :+1:

**Comment by fneu** [comment]
Uh, generally I think this is a valid concern but somebody needs to come up with a concept and some free time.

**Comment by abhsag24** [comment]
> well when they can send a PR they can also modify that on their clone and install that.

well i disagree i think the "user" shouldn't need to modify the code-base in order to use `coala`

> Alright I think before we drive this discussion-car into the ocean, we should make a concrete design on how the manager should look like :+1:

Agree i'll try and come up with one soon.

**Comment by Makman2** [comment]
hm yeah that's quite simple :+1:
