### ISSUE TITLE
No bears to show.

### ISSUE THREAD

**Issue by dnozay** [coala-analyzer/coala#2205]
http://coala.readthedocs.io/en/latest/Users/Tutorials/Tutorial.html#prerequisites

I just installed `coala` (nothing else) and followed the above page.

```
(k)/tmp > (6) coala --show-language-bears C
[WARNING][14:20:18] The default coafile '.coafile' was not found. Ignoring it.
No bears to show.
```

This could tell the user that they need to install something else?
More often than not, new users want to have all the bears.

**Comment by sils1297** [comment]
Feature request, seems sane to me, scheduling for 0.8 maybe?

**Comment by sils1297** [comment]
doing this for this release now since this is a weak point as figured out in usability testing
