### ISSUE TITLE
Can't invoke coala with python3.4 -m coala

### ISSUE THREAD

**Issue by JelleZijlstra** [coala-analyzer/coala#2206]
```
$ python3.4 -m coala
/opt/local/bin/python3.4: No module named coala
```

**Comment by sils1297** [comment]
@JelleZijlstra so I think this should be done by setuptools, we're using their entrypoints and if they don't provide it we'd have to hack around that which I'd like to avoid :/

Any ideas?

**Comment by sils1297** [comment]
we do:

```
          entry_points={
              "console_scripts": [
                  "coala = coalib.coala:main",
                  "coala-ci = coalib.coala_ci:main",
                  "coala-dbus = coalib.coala_dbus:main",
                  "coala-json = coalib.coala_json:main",
                  "coala-format = coalib.coala_format:main",
                  "coala-delete-orig = coalib.coala_delete_orig:main"]},
```

**Comment by JelleZijlstra** [comment]
Not too familiar with this mechanism, but one part of the puzzle is probably that your library is called coalib rather than coala. When I try to invoke coalib.coala, I get nothing:

```
$ python3.4 -m coalib.coala
$
```
which is better than an error. Maybe you need to add an `if __name__ == '__main__': main()` to coalib/coala.py.

**Comment by sils1297** [comment]
hm, we could do that for all of the binaries - still it would be more of a hidden feature...
