### ISSUE TITLE
Add documentation for all settings exposed by coala --help

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2215]
@tltuan this might be something we could do together

**Comment by sils1297** [comment]
this should go into the coafile specification as a chapter "Common settings"

**Comment by sils1297** [comment]
and maybe make an example

**Comment by hypothesist** [comment]
@sils1297 Any status on this?

**Comment by sils1297** [comment]
Nope, nobody is assigned

**Comment by hypothesist** [comment]
1.0 then

**Comment by sils1297** [comment]
Can't we somehow have this?

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#40
