### ISSUE TITLE
Description of `--save` option is not very descriptive

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala#2218]
Based on this description I thought it would save the results to a file or something:

```
  -s [FILE], --save [FILE]
                        Filename of file to be saved to, if provided with no
                        arguments, settings will be stored back to the file
                        given by -c
```

Also, it might be worth add something like
>[…] the file given by -c**, which is .coafile by default**

difficulty/low
type/documentation

**Comment by Makman2** [comment]
thanks for pointing that out, actually this is really not informative.

maybe something like this?
> Filename of file where configuration shall be saved to (including settings provided via command line and used configuration file), if no file is provided, settings will be stored back to the file given by -c. If no -c is provided, filename is implicitly '.coafile'.
