### ISSUE TITLE
Move tutorial to users section

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2235]
_From @sils1297 on June 2, 2016 17:12_

http://coala.readthedocs.io/en/latest/Users/Tutorials/Tutorial.html should appear in the users section.

difficulty/newcomer

_Copied from original issue: coala-analyzer/coala-bears#482_

**Comment by sils1297** [comment]
_From @gitmate-bot on June 2, 2016 17:12_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by jschwarzwalder** [comment]
I'm going to try and see if I can do it
