### ISSUE TITLE
Pylint codestyle rating to low

### ISSUE THREAD

**Issue by smfn3321** [coala-analyzer/coala#224]
Messages
--------

|message id |occurrences |
|---|---|
|missing-docstring              |425         |
|too-few-public-methods         |47          |
|invalid-name                   |44          |
|dangerous-default-value        |25          |
|no-member                      |19          |
|attribute-defined-outside-init |19          |
|too-many-arguments             |15          |
|protected-access               |14          |
|unused-variable                |13          |
|abstract-method                |10          |
|bare-except                    |9           |
|arguments-differ               |8           |
|too-many-instance-attributes   |6           |
|no-self-use                    |5           |
|bad-whitespace                 |5           |
|bad-continuation               |5           |
|unused-import                  |3           |
|star-args                      |3           |
|cyclic-import                  |3           |
|line-too-long                  |2           |
|unused-argument                |2           |
|super-init-not-called          |2           |
|missing-final-newline          |2           |
|invalid-sequence-index         |2           |
|duplicate-code                 |2           |
|unnecessary-lambda             |1           |
|too-many-locals                |1           |
|no-name-in-module              |1           |
|fixme                          |1           |
|expression-not-assigned        |1           |
|abstract-class-not-used        |1           |

Global evaluation
-----------------
Your code has been rated at 7.65/10

**Comment by sils1297** [comment]
could you adjust pylint to accept line length of 120 and update the data?

**Comment by smfn3321** [comment]
Well this should drop line-too-long to 0 until we introduce our soon-to-come guidelines?

**Comment by smfn3321** [comment]
Oh and rating improved, of course, to from 6.71/10 to 7.65/10 ;)

**Comment by sils1297** [comment]
oh I opened a new bug for this... since this is old closing this one.
