### ISSUE TITLE
.meta description -Uncommon Capitalization

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2248]
in index.rst 
`.. meta::`
`    :description: coala is a simple COde AnaLysis Application. `

the O and L are capitalized which is slightly confusing.

Isn't this only read by robots? Do we need the capitalization in the description?

**Comment by Makman2** [comment]
we should maybe use bold style instead :+1:

**Comment by underyx** [comment]
Should check for other occurrences as well such as https://github.com/coala-analyzer/coala/blob/b2e1251359d48eb5f94d9dd70abd0e111eec557f/coalib/parsing/DefaultArgParser.py#L37

**Comment by sils1297** [comment]
this should get solved with https://github.com/coala-analyzer/coala/pull/2259/commits/1809c21cf1bce49314d48ccf500938243e16e793 which is already acked.

As I was not aware of this issue, I'm closing this manually and without a fixes notice.
