### ISSUE TITLE
indentation bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#225]
shouldn't be that complex, usually you only have to look at brackets (and strings and commits because you should ignore brackets there.) and colons or so. I think we can do a pretty generic algorithm for that.

**Comment by sils1297** [comment]
depends on #250

**Comment by sils1297** [comment]
#250 is in review and work can be build upon that

**Comment by sils1297** [comment]
similar to our matlabindentationbear

**Comment by sils1297** [comment]
see https://github.com/coala-analyzer/coala/blob/master/bears/matlab/MatlabIndentationBear.py for initial approach, something like that could work well for basic indentation checking. We then need to add things like correct bracket positions and stuff like that, should be possible.

**Comment by AbdealiJK** [comment]
@sils1297 why not use a language specific linter in such cases ? Writing your own logic is tiresome and not required IMO
Like `indent` for C languages

**Comment by sils1297** [comment]
because having one indentation engine that is usable for lots of languages
would be awesome, remember the goal of coala is not to just wrap linters
but also allow creation of new routines for new languages. That also makes
it very easy to at least provide some basic indentation support for
whatever languages users demand.

2016-02-16 12:46 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by Makman2** [comment]
agreeing with @sils1297. Even though we focus on providing functionality by implementing linters, self-written bears need utilities for code-analysis :)

**Comment by Redridge** [comment]
As @sils1297 said, this requires much more planning than I initially thought. I say better leave it for now.

**Comment by sils1297** [comment]
Can you share your experiences and drafts so we can build on it the next
time?

2016-02-18 19:31 GMT+01:00 Alexandros Dimos <notifications@github.com>:

**Comment by abhsag24** [comment]
decisions: 
1. will take `indent_types` , and comments as dict parameters , where the key is a `start_indent` and value is an `end_indent` , for comments the key and value pair are useful for multi-line comments, where key can be start of comment and value the end.  

2. Languages like python can have `end_indent` as None , 

3. Basic structure to be initially like MatlabIndentationBear but i do believe it will be totally different by the final version.

**Comment by Redridge** [comment]
Here is my draft from when I tried it. 
https://github.com/Redridge/coala/commit/ca8df0cbdb2e885d77e948a838386c9e3eed0da4

It is able to:
- Get the dict out of .coalang files using LanguageDefinition
- Indent C files without comments or missleading strings (with ';', '{', '}' int them)

I don't know if it is of much help though

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#40
