### ISSUE TITLE
Tagging: remove it?

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2257]
We don't need it!

**Comment by sils1297** [comment]
CC @Udayan12167

**Comment by sils1297** [comment]
I and @Makman2 agree that we should just remove it. @hypothesist will get conflicts and has to reintroduce some stuff for caching but at least he doesn't have to care about caching anymore.

@scottbelden is currently working on the help and stuff and maybe also removes the arguments while he's at it so users aren't confused :)

**Comment by scottbelden** [comment]
I was just planning to make a deprecated section until it was known for sure that no one was using them.

**Comment by sils1297** [comment]
@hypothesist you'll wanna have a fixes for this in your commit

**Comment by hypothesist** [comment]
Oh right, didn't know about the issue.
