### ISSUE TITLE
docs: Document usage of `python -m pip` if pip is not working

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2261]
On windows sometimes pip is screwed, we maybe should document the usage of `python -m pip` then.

Though I'm not sure, it's in fact a platform problem^^

**Comment by jschwarzwalder** [comment]
On a Windows 8 a machine, trying to get coala up and running user found these instructions: 
http://coala-analyzer.org/#details

`sudo pip3 install coala-bears` does not work, `pip3 install coala-bears` does not work, `pip install coala-bears` does not work.

We tried to add C:\Python34\Scripts to the path, and reinstalling Python 3.5 and continued to get the error message

Fatal error in launcher: Unable to create process using '"C:\Python34\python.exe" "C:\Python34\Scripts\pip3.exe" -V'

when we tried to run pip3 -V I got the message 
pip 8.1.2 from c:\python27\lib\site-packages (python 2.7)

another solution we tried was to delete pip3.exe from the C:\Python27 folder

**Comment by AbdealiJK** [comment]
Could you provide more details about how python was installed?
It seems to me as though python2, python3, pip2 and pip3 are getting confused by the system.

So:
Which versions of python are installed? Are these installed from the python exe at python.org ?
What's in the path (related to python) ?

I think:
"C:\Python34\python.exe" -m pip install coala-bears
Should work for you

**Comment by jschwarzwalder** [comment]
I have Python27 and Python34 installed on my computer 
I had someone who did this for me on Monday.

I had to add those folders to my path
Before today I only have Python27/Scripts in my path

As part of my troubleshooting I tried to add Python34/Scripts to my path and even removed Python27/Scripts from my path
each time I was getting the same error that `Fatal error in launcher: Unable to create process using '"C:\Python34\python.exe" `

**Comment by jschwarzwalder** [comment]
I downloaded Python 3.5.1 and reinstalled it from https://www.python.org/downloads/ to try and solve the problem but continued to get the issue.

**Comment by jschwarzwalder** [comment]
We were able to use `python3 -m pip install coala-bears` and found success

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#37
