### ISSUE TITLE
Demo (Click to View) Confusing/Fast

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2264]
I started learning about the project by clicking on the Github page. I went to the readme and clicked on Demo (Click to View). It opened full screen and I tried to follow along and read the text on the screen and it started to change before I had finished reading everything.

Since it was going so fast I assumed there might be a narrator talking about the project, but I had my volume muted. I looked for a button to turn on captions, but found none, so I went back to the Read.me to look for text explaining the project. 

The only thing I got out of the video was that you use coala in the command line.

**Comment by sils1297** [comment]
I can remove the autoplay if that helps
