### ISSUE TITLE
Is coala a proper noun

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2265]
When reading Readme I would have liked the name of the software to stand out in some manner. It was not consistently italicized and was not capitalized. It was primarily noticeable in the second sentence in the [About Section](https://github.com/coala-analyzer/coala#about)

> coala is a language independent analysis toolkit. It empowers developers to create rules which a project's code should conform to. **coala** takes care of showing these issues to users in a friendly manner, is versatile and can be used in any environment. Patches to automatically fix code will be managed too. coala has a set of official bears (plugins) to provide an out-of-the-box analysis functionality for many popular languages in addition to some generically applicable algorithms.

**Comment by sils1297** [comment]
Alright so the solution here is to make coala italic in all places.

@Makman2 interested? Quickie.
