### ISSUE TITLE
Supported Languages - Link to Bears

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2267]
From the About in the Readme I clicked a link that took me to the [Supported Languages](https://github.com/coala-analyzer/coala-bears/wiki/Supported-languages)

I first looked to see if the language my project was currently written was listed - Meteor, then when it was not listed I looked to see if Mongo, Angular, or Express was listed.
I did see that Javascript was listed and hoped that that would be good enough to run my project. 

I wanted to be able click on the text and read more about what Bears were used with that language and hopefully obtain clarification on whether JavaScript would be sufficient to test my code.

**Comment by Adrianzatreanu** [comment]
i understand, ill fix this today for more clarity, and im awaiting your response once im done to know if its better.

**Comment by Adrianzatreanu** [comment]
https://github.com/coala-analyzer/coala/wiki/Supported-Languages should fix this
