### ISSUE TITLE
Wiki - Home is empty

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2268]
In the Wiki for Coala analyzer  the Home page has no text, and should possibly be changed to Welcome coala bears!

https://github.com/coala-analyzer/coala-bears/wiki

**Comment by Adrianzatreanu** [comment]
https://github.com/coala-analyzer/coala-bears/wiki please close the issue if you think this suffices :)

**Comment by sils1297** [comment]
@Adrianzatreanu actually the latest version is 0.2

**Comment by Adrianzatreanu** [comment]
done, changed

**Comment by sils1297** [comment]
@jschwarzwalder reopen if this needs our attention. Seems fixed.

**Comment by sils1297** [comment]
@Adrianzatreanu IMO it's ok to close issues if they are fixed, you'd do the same by making a commit with a closes note, right? If a user as a problem he can stil reopen.

**Comment by Adrianzatreanu** [comment]
well yes, but sometimes you are not sure if what youve done is fixing the issue correctly, but ok, ill close them from now on
