### ISSUE TITLE
all languages prototype - possibly remove or reorder

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2269]
From [Supported Languages](https://github.com/coala-analyzer/coala-bears/wiki/Supported-languages)  I wanted to learn more so I clicked on the first link under Home on the right.

It took me to [all languages prototype](https://github.com/coala-analyzer/coala-bears/wiki/all-languages-prototype) which had the same information in a different layout from what I was looking at. 

I then noticed that the order on the right was ordered in a way where the flow would be better starting at the bottom and moving up the links.

Consider reordering

**Comment by Adrianzatreanu** [comment]
Sorry but I don't really understand what you're saying with the flow. However, that was just a prototype that myself I failed to delete a few weeks/months ago. The same table is used in the README https://github.com/coala-analyzer/coala-bears#about so if the issue stands there too, please let me know here, not closing issue yet.
