### ISSUE TITLE
Getting Started from Repository & Wiki

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2272]
Since the repository was the first thing that came up in Google I wondered if I needed to fork and download the repository to start using it. 

I read the ReadMe, specifically the About section, and then went to the pages in the Wiki exploring what languages and Bears are supported and was slightly lost in that area. 

I like I likely would have forked the repository at that point since there wasn't a wiki page directing me on how to get Started with using Coala

**Comment by Adrianzatreanu** [comment]
i dont think many people read the wiki before the readme, and we have this in the README: https://github.com/coala-analyzer/coala#newcomers-guide-and-getting-involved

**Comment by sils1297** [comment]
still they might possibly!

**Comment by Adrianzatreanu** [comment]
so we should have a wiki page pointing them to getting started then

**Comment by yash-nisar** [comment]
I would like to get assigned !

**Comment by sils1297** [comment]
Sure, go ahead! Thanks for your help!

**Comment by yash-nisar** [comment]
**Newcomers** can get started [here](https://github.com/coala-analyzer/coala#newcomers-guide-and-getting-involved).

A list of all available bears can be found here and all supported languages here.

I am planning to add the first line. Does this look good or should I incorporate any changes ?

**Comment by sils1297** [comment]
@jschwarzwalder would that help you?

**Comment by sils1297** [comment]
@yash-nisar the `here` link doesn't really work for me FWIW

**Comment by yash-nisar** [comment]
@sils1297 I had added it in the first (new)line and not in the second line. The second line was meant as a reference in the wiki with respect to which the first (new)line would be added.

**Comment by yash-nisar** [comment]
@sils1297 There has been insufficient response from @jschwarzwalder . How do I proceed with this issue ?

**Comment by mr-karan** [comment]
Your [here](https://github.com/coala-analyzer/coala#newcomers-guide-and-getting-involved) points me to coala github repo

**Comment by yash-nisar** [comment]
Yes, I would add the following line to the wiki page of coala which would help the newcomers to get started. Does it sound good ?

**Comment by yash-nisar** [comment]
I think I should add this [link](http://coala.readthedocs.io/en/latest/Getting_Involved/Newcomers.html) instead. Isn't it @mr-karan

**Comment by yash-nisar** [comment]
Is [this] (https://github.com/coala-analyzer/coala/wiki) alright ?

**Comment by sils1297** [comment]
@yash-nisar I don't think we'll want to link to the wiki, rather to the docs, the wiki is largely unmaintained.

CC @Adrianzatreanu who wanted to make our documentation meaningful again, I think he might be able to help you figuring out the right thing here.

**Comment by yash-nisar** [comment]
@sils1297 I have modified the wiki page and added a link for the newcomers since @Adrianzatreanu had mentioned that we should have a wiki page pointing the newcomers to get started.

**Comment by jschwarzwalder** [comment]
Sorry I didn't get previous ping.

The only thing I would suggest be added is a mention that you need to have python installed in order to use coala, but I think that is a different issue :smile: 

Since its initial post changes have been made to both website and the repository making it easier to find information.

**Comment by sils1297** [comment]
Are you implying that this issue can be closed?

**Comment by Adrianzatreanu** [comment]
closing, the python thingie was mentioned in new docs
