### ISSUE TITLE
Document bear API

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2276]

**Comment by abhsag24** [comment]
@sils1297 you mean the bear class?

**Comment by Adrianzatreanu** [comment]
it's unclear to me either, what exactly do you want to be documented?

**Comment by sils1297** [comment]
The API a bear writer can use to create a bear

**Comment by Adrianzatreanu** [comment]
So you basically want a website on readthedocs where one could specify all the methods for the class which he has available and how he should write that bear?

**Comment by abhsag24** [comment]
so we should have tutorials for `Diff` and `SourceRange` too right?

**Comment by sils1297** [comment]
Currently if you want to write a bear, you have to go through the tutorial
which is not always what you want, sometimes you want a quick API reference
and work out your own stuff

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#36
