### ISSUE TITLE
Improvement suggestion: SpaCy instead of NLTK for part of speech tagging

### ISSUE THREAD

**Issue by tmylk** [coala-analyzer/coala#2285]
Comparison of SpaCy to NLTK by the author of SpaCy
https://www.quora.com/What-are-the-advantages-of-Spacy-vs-NLTK

**Comment by sils1297** [comment]
CC @Makman2 @SanketDG for GitCommitBear

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#495
