### ISSUE TITLE
nobody finds default_actions

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2287]

**Comment by underyx** [comment]
Should have an arg like `--fix-all` or something.

**Comment by sils1297** [comment]
Found a way to alias argparse stuff, will look into this. I'll first solve https://github.com/coala-analyzer/coala/issues/2233 for this and alias it to that then.

**Comment by sils1297** [comment]
@underyx I named it `--apply-patches`, that alright?
