### ISSUE TITLE
external coalang dir does not work for bears on windows 

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#2307]
Related link for failing CI: https://ci.appveyor.com/project/coala/coala-bears/build/1.0.1405/job/4o9tbb9p333dmtno

**Comment by Makman2** [comment]
if you provide paths inside the settings, escape backslashes! otherwise coala will escape them for you, so:
```
some_path = C:\\Users\\whoami\\x.coalang
```
can be escaped via 
```
section["some_path"] = StringProcessing.escape("\\", path)
```

**Comment by abhsag24** [comment]
Closing this since it isn't related to external coalangs but how paths are specified in the settings
