### ISSUE TITLE
List of Show Language Bears is too long

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2323]
I still don't quite know how to "run" coala

I am trying to go through [the tutorial ](http://coala.readthedocs.io/en/latest/Users/Tutorials/Tutorial.html) and got to this line:

`coala --show-language-bears C` 

It displays too much information about each bear, and I can't see all of the supported bears [Screenshot](http://prntscr.com/bfki3i)

Is there a better first command to run? 
Can we instead list the bear names and give an option to look up a specific bear?

**Comment by sils1297** [comment]
Hi, this has changed in the upcoming release. coala will show only bear names by default and tere will be additional arguments to get more output. If this doesn't fix it yet, please reopen the issue.
