### ISSUE TITLE
Tutorial Getting Started

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2326]
The [first action](http://coala.readthedocs.io/en/latest/Users/Tutorials/Tutorial.html#let-s-start) you direct the new user to try is to list all the bears that are supported by C.

This can be confusing and overwhelming for very first users.

Maybe you should walk them through running a bear that works for all languages on one specific file and then teach them how to find all the bears, or provide a link to a list of bears they can also try on their file.

Then you can direct them on what to expect when you just type in coala.

**Comment by Makman2** [comment]
Yeah this is kind of too much and unrelated for the following tutorial, we should just remove that :+1:

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#33
