### ISSUE TITLE
Tutorial: Explain --save 

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2327]
In trying to get coala to work I was typing in the commands in the [Tutorial ](http://coala.readthedocs.io/en/latest/Users/Tutorials/Tutorial.html#let-s-start) without understanding how everything works. I typed in: `coala --files=src/\*.c --bears=SpaceConsistencyBear --save` and 'coala -S Makefiles.bears=LineLengthBear Makefiles.files=Makefile --save' 

Now I can't get coala to [work at all](http://prntscr.com/bfkuul), and I'm not sure how to "reset"

**Comment by Makman2** [comment]
for your snippet: `--save` saves your given CLI configuration to `.coafile`, which coala picks up by default if it does exist. 3: possibilities:

1. Just run coala again overriding the settings you need for that run
2. Delete `.coafile`
3. Use `-I` (which ignores the `.coafile` and uses CLI-settings only)

Need to agree also with `--save` usage inside the tutorial, it isn't explained and it doesn't seem to be necessary^^ we should explain that later inside the coafile-explaining section or so

**Comment by sils1297** [comment]
I'm for a better explanation, think we should keep using `--save` because it's easier for the users than reading up on how to write coafiles.

**Comment by Makman2** [comment]
at least explaining is good, otherwise it's really a bit "where the heck does it come from..." :+1:

**Comment by hypothesist** [comment]
I'm for keeping `--save` too: in coala-quickstart, the user may be asked questions for non-optional settings that are not filled yet, so we can suggest to the user to run `coala --save` the first time to automatically save the settings.
