### ISSUE TITLE
cat doesn't work in Windows

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2328]
in the [Configuration File](http://coala.readthedocs.io/en/latest/Users/Tutorials/Tutorial.html#configuration-files) section of the Tutorial it tells me to type in ` cat .coafile ` on windows the command it `type .coafile`

**Comment by Makman2** [comment]
you mean this link, right? http://coala.readthedocs.io/en/latest/Users/Tutorials/Tutorial.html?highlight=cat

indeed `cat` is linux only, we could mention `type` in a note or beneath in braces or so ^^
