### ISSUE TITLE
rebasing is hard

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2329]
I am trying to make a few changes to the docs, and I'm stuck in a confusing loop of trying to fix things for the gitmate, and then also trying to --amend or squash the fixes together which is utterly confusing and frustrating. and isn't working.

I [closed one](https://github.com/coala-analyzer/coala/pull/2315) and tried to [open](https://github.com/coala-analyzer/coala/pull/2318) another, but then when there were things I needed to "fix" I was unable to get the fixes to apply the the initial pull request. 

For editing documentation. 

I need more instructions than: the [Git_Help](http://coala.readthedocs.io/en/latest/Users/Tutorials/Git_Help.html)  

At this point I feel like I need to delete the whole project, download it again and then try to make the change

Is that the solution??

**Comment by sils1297** [comment]
@jschwarzwalder this is kind of the same as https://github.com/coala-analyzer/coala/issues/2339 , if you mind me closing this in favour of the other, please reopen.
