### ISSUE TITLE
coala should tell you if everything is OK

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#2331]
As title says, for a new user, it looks as if coala is just ``executing some sections``, without giving a real output once it's done. If there's nothing new to be done, it should print something like ``Everything went fine, nothing to change``.

**Comment by sils1297** [comment]
Yes, nice one. We can collect stats about what happened and show the number of results that were yielded

**Comment by sils1297** [comment]
we already have the exit code

**Comment by Adrianzatreanu** [comment]
i splitted it in 2 different issues, should I make only one? https://github.com/coala-analyzer/coala/issues/2332

**Comment by sils1297** [comment]
I think this is only one issue and shouldn't be done isolated from each other.

**Comment by Adrianzatreanu** [comment]
alright, refer to the other one then.

**Comment by Adrianzatreanu** [comment]
https://github.com/coala-analyzer/coala/issues/2332 moved here
