### ISSUE TITLE
PyPI metadata messed up?

### ISSUE THREAD

**Issue by fneu** [coala-analyzer/coala#2334]
```
fabian@leap:~> pip search coala
coala (0.4.1.dev20160202130739)  - Code Analysis Application (coala)
  INSTALLED: 0.6.0
  LATEST:    0.4.1.dev20160202130739
```

pip does correctly install 0.6.0 but shows wrong info
https://pypi.python.org/pypi/coala

**Comment by sils1297** [comment]
@fneu any idea why? Can you reproduce this in a clean virtualenv?

**Comment by fneu** [comment]
no idea whatsoever, haven't looked into PyPI deployment at all, yet. 

It works on clean docker environments...

**Comment by sils1297** [comment]
closing this as probably an upstream issue, if you can reproduce it, report an issue at pip I guess

**Comment by fneu** [comment]
@sils1297 I'm gonna ask them and report back if it is an issue on our side.
