### ISSUE TITLE
Couldn't Test the Bears

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2343]
I tried to run the code `$ pip3 install -r test-requirements.txt`

I didn't realize I needed to download coala and be in the folder where I downloaded coala to get the test-requirements.txt file.

I tried to add notes to the [Testing page](http://coala.readthedocs.io/en/latest/Getting_Involved/Testing.html)

Once I downloaded the repository and used cd to get to the right folder I was able to get it to work.

Filled out pull request to try and add instructions on where to be before running the code [#2318](Testing.rst: Add directions about getting started #2318) & [#2315](https://github.com/coala-analyzer/coala/pull/2315)

At first I tried to add a instructions to download the project with the git code, but was asked to not include code to clone again. so I changed from:

> Before you run tests, make sure you `[install coala.](http://coala.readthedocs.io/en/latest/Users/Install.html/)`
> 
> To run tests, you will need to open a file located in the default coala directory If you have not already, you can start by cloneing a copy of the project to your local machine.
> 
> Either fork the repo on Github [https://github.com/coala-analyzer/coala](https://github.com/coala-analyzer/coala), or clone it directly from coala
> 
> `$ git clone https://github.com/coala-analyzer/coala.git`
> Then navigate to the directory where coala is located

I changed it to 

> If you have not already, you can start by following the [coala Tutorial](https://github.com/jschwarzwalder/coala/blob/1f127d070eca3d6ec8d6646a4320ceab02982d2d/docs/Getting_Involved/Users/Tutorials/Tutorial.html).
> 
> Before you run tests, make sure you [install coala](https://github.com/jschwarzwalder/coala/blob/1f127d070eca3d6ec8d6646a4320ceab02982d2d/docs/Getting_Involved/Users/Install.html).
> 
> To run tests, you first need to install some dependencies. This can be done by executing in your coala directory:

@sils1297 I linked to the User Tutorial where they can find the information about how to clone the repository which you have to do to run the tests because you asked me not have the code for how to clone the repository directly on this page. 

sils1297 says you don't need to install coala to run the tests, but I don't know how to run the tests without installing coala. When I tried I was unsuccessful. Please identify any steps that need to happen before running `$ pip3 install -r test-requirements.txt` if an install is not the correct pre-step. 

If the requirement is simply to run that file, maybe we should link to its location in the repository for users to download and install.

**Comment by jschwarzwalder** [comment]
I asked my husband to try running the tests on http://coala.readthedocs.io/en/latest/Getting_Involved/Testing.html 

He was unsuccessful when he typed in `pip3 install -r test-requirements.txt`

I then had him clone the repository, and then he was able to execute the file

![image](https://cloud.githubusercontent.com/assets/8946787/16074418/473d1d04-329f-11e6-9cbb-291f9e0be311.png)

No where did it say what version of python he would need. and he is trying to figure out now how to run it with python3 It looked like it was running with python 2.7

![image](https://cloud.githubusercontent.com/assets/8946787/16074469/7edff600-329f-11e6-9ea6-38504282f6b3.png)

http://prntscr.com/bglopg


He found in the logs that he didn't have permission, so he ran it with sudo.
That worked to execute the command `pip3 install -r test-requirements.txt`

He then got the following error:
![image](https://cloud.githubusercontent.com/assets/8946787/16074552/d5505f2a-329f-11e6-8a32-bee4bc538dc9.png)

http://prntscr.com/bglpni

**Comment by AbdealiJK** [comment]
Hey, so there seems to be some confusion.

To run the tests, you need to install all of the dependencies of coala and also the `test-requirements.txt` in the github repo. You **need** to clone the repo too, because you need the `tests/` folder where the tests are and also the `test-requirements.txt` file to get pytest and so on.

So, I think the exact steps on a clean virtualenv to run tests would be:
```bash
$ git clone <repo url>
$ cd coala-bears # (or whatever the repo's folder name is)
```
Then you need to install the dependencies of coala in `requirements.txt` and also the additional requirements for testing `test-requirements.txt`:
```bash
$ pip3 install -r requirements.txt -r test-requirements.txt
```

Finally, to run the tests:
```
$ python3 -m pytest
```

Note: You may need sudo with `pip3` if you're not using a virtualenv

Also, `python3 setup.py install` or `pip3 install .` or `pip3 install -e .` will also install all the requirements from `requirements.txt` for you (as it installs coala's dependencies automatically)

**Comment by Adrianzatreanu** [comment]
well seems to have been worked on, closing for now. please ask to reopen if you still think this needs work
