### ISSUE TITLE
JShintBear does not fulfill all requirements

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2347]
I wanted to run coala on my javascript file so I went to the folder the project is stored in and tried to enter type .coafile, but I"m not sure anything happened.

I then used windows to create a file called .coafile and saved it in the folder of my javascript project.

I copied from the [Tutorial](http://coala.readthedocs.io/en/latest/Users/Tutorials/Tutorial.html#configuration-files) and looked on [coala-bears](https://github.com/coala-analyzer/bear-docs/#javascript) to find a bear that would potentially work with Javascript. 

My file looked like this

```
[Default]
bears = JSHintBear
files = src/*.js
use_spaces = yeah
```
I tried to run it and was told there were no js files and that JShintBear does not fulfill all the requirements.

![](http://image.prntscr.com/image/7bc9ca59e0094aa4820d5e68dd0c0a08.png)

http://prntscr.com/bgj0d5

What requirements?

Can I use space consistency bears on Javascript? 
Not sure what I'm doing wrong

**Comment by hypothesist** [comment]
JSHintBear uses an external linter called `jshint` [[link]](https://github.com/jshint/jshint). So the second message says you don't have it installed (or you have it but it is not in your `PATH` variable and coala can't find where it is).

About the first message, are you sure you have all your `.js` files in the `src` directory? Can you maybe show the output of `dir src`?

**Comment by sils1297** [comment]
@hypothesist I think we should drastically improve those missing dependencies messages and give the user a link or command to install the stuff.

CC @Adrianzatreanu we could use your requirements objects for this.

**Comment by AbdealiJK** [comment]
I made a very similar "better error message" for matplotlib a while back.
If the person who is doing this wants to reference it:
https://github.com/matplotlib/matplotlib/commit/068ed423561f8d5d8f951a5c2bbb6edd04600618

**Comment by Adrianzatreanu** [comment]
this is not needed to be worked on as my tool will solve this differently i guess. closing
