### ISSUE TITLE
Show a diff of changes automatically applied the last time coala was run

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#2348]
Somewhat related to https://github.com/coala-analyzer/coala/issues/2332

**Comment by sils1297** [comment]
sounds like a wontfix for me, use git if you want that? We already create .orig files.

**Comment by hypothesist** [comment]
It doesn't necessarily have to be a git repo. Even if it was, other changes might interfere with `git diff` results.

Maybe we could just do ``os.system("for f in `find . -name \*.orig` ; do diff $f ${f%.*} ; done")`` or something like that.

Not really important (as you said we have the orig files)

**Comment by sils1297** [comment]
Making it a wontfix, IMO this is certainly out of scope, though we can of course discuss it if you think it isn't.
