### ISSUE TITLE
default_actions is not existant

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2349]
I got coala to work! I had to manually write my .coafile, cause I'm not sure how to get it to work otherwise, but its mostly going ok..

I was trying to run coala on some js files and I was configuring the coafile to make it so I don't have to hit 2 then 0 to apply all the changes that converts tabs to spaces

![image](https://cloud.githubusercontent.com/assets/8946787/16072228/a47cb584-3294-11e6-8a4d-b63b88471eee.png)

I made the .coafile looks like this:
```
[Default]
bears = SpaceConsistencyBear
files = server/*.js, routing/*.js, client/*.*
use_spaces = yeah
default_actions = bear:ApplyPatchAction
```

![image](https://cloud.githubusercontent.com/assets/8946787/16072181/6e0bc4d6-3294-11e6-83b6-0ed350627d85.png)

**Comment by jschwarzwalder** [comment]
Fix is `default_actions = SpaceConsistencyBear: ApplyPatchAction `

Will be fixed in the next release

**Comment by sils1297** [comment]
ah so the documentation is the problem again.

**Comment by sils1297** [comment]
> Will be fixed in the next release 

I assume the `--apply-patches` argument fixes this for you. Reopen if it doesn't.

**Comment by jschwarzwalder** [comment]
I've not tried, and will try to test it later.

**Comment by jschwarzwalder** [comment]
yes --apply-patches did work
