### ISSUE TITLE
Prerequisites for coala

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2359]
Since coala can run analysis on ANY language, there are some prerequisites that some users may not have if they are not python programmers.

Creating a seperate page that can be linked to on pages like [GettingStarted/Testing](https://coala.readthedocs.io/en/latest/Getting_Involved/Testing.html) or [Install](https://coala.readthedocs.io/en/latest/Users/Install.html) can provide support for successfully running coala from ground 0 without cluttering up the begining of the instructions for the 80% of users that already have  things like python3 and pip installed. 

> Prerequisite - coala requires python 3 https://www.python.org/download/releases/3.0/. You will need to make sure that is installed
> 
> Check what version you have installed with `python -V`
> 
> To run tests, you first need to install some dependencies. This can be done by following these steps:
> 
> **Download the repository**
> ```
> $ git clone https://github.com/coala-analyzer/coala.git
> $ # Use https://github.com/coala-analyzer/coala-bears.git for coala bears
> ```
>  
> **move to the coala directory** 
> ```
> $ cd coala  # cd coala-bears when testing bears
> $ # Use pip for python 3 on windows
> 
> ```
> **pip these files that should install everything you need for the tests**
> `$ pip3 install -r test-requirements.txt -r requirements.txt`
> 
> Let us know if you get any errors

or 

```
Setting up a Development Environment
====================================

In order to help develop coala, you will need the following prerequisites:

- Python 3.3 or higher installed on your PC (Check with ``python --version``)
- Clone the repository:
  ``git clone https://github.com/coala-analyzer/coala.git``, or
  ``git clone https://github.com/coala-analyzer/coala-bears.git`` if you want
  to develop the bears.
- Install the requirements:
  ``cd coala; pip install -r requirements.txt -r test-requirements.txt``, or cd
  into ``coala-bears`` respectively. Be sure that your pip really uses Python
  3, you might need to use ``pip3`` on some linux distributions.
```

**Comment by Makman2** [comment]
So you want to split up information that belongs either to python or to coala?

**Comment by jschwarzwalder** [comment]
@Makman2 I was trying to propose that we make one page that has information on how to install python3, and possibly has informatino about how to clone the coala project

This is in relation to #2350
