### ISSUE TITLE
external_bear_wrap: Add support for different Result creation modes

### ISSUE THREAD

**Issue by Redridge** [coala-analyzer/coala#2368]
Currently the external_bear_wrap decorator uses `Result.from_values()` to create the results needed.
It would be nice to extend the decorator's functionality to be able to use other `Result` creation methods too

**Comment by sils1297** [comment]
I'd just use the standard result constructor always and use  the same json format as we use for coala json output

**Comment by Makman2** [comment]
agreeing, let's just enforce a standard we are already using. There are way too many possibilities to create such an external bear, having the one "right" way supported by us simplifies stuff for the user^^
