### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by CarIosRibeiro** [coala-analyzer/coala#2383]
If do you like to help to have coala translated to your mother languange this is your place, welcome a board!

**Comment by sils1297** [comment]
We will talk about this in person, a cEP will have to be worked out for this.

**Comment by AbdealiJK** [comment]
Would this be a probably outreachy project ?
 - Figure out how to do it and make cEP
 - Implement it
 - Get 100% document in atleast 1 language

**Comment by sils1297** [comment]
IMO we should think very hard on if we want to do this. My current opinion
is that if there's an external contributor who wants to do it for some
reason that would be fine but he'd also have to stay around and maintain
it. I don't think we should waste an outreachy project on this, given that
it'll cost some sponsor of us 6000$ directly.

**Comment by AbdealiJK** [comment]
Hmm. So, close as `wontfix/accepting patches` ?

**Comment by sils1297** [comment]
yes

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/
