### ISSUE TITLE
Add default PR description

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#2389]
I was submitting a patch at `scikit-image` and I was really impressed with their default PR message:

```
## Description
[Tell us about your new feature, improvement, or fix! If relevant, please supplement the PR with images.]


## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]


## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]
```
The checklist is really nice and serves as a better reminder of "things to do" as compared to writing it in a documentation.

**Comment by AbdealiJK** [comment]
You can find their other templates and this one at https://github.com/scikit-image/scikit-image/tree/master/.github

**Comment by hypothesist** [comment]
We could also add something about doctests. Also modify the first check point to something like "Run `coala` on the project before submitting" as that should pretty much cover any code standards issue. (We could also convince `scikit-image` devs to use coala.)

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#31
