### ISSUE TITLE
Docs Revision should be easier

### ISSUE THREAD

**Issue by jschwarzwalder** [coala-analyzer/coala#2392]
Trying to add small things to the docs should be significantly easier. 

I don't feel like making changes should require only one commit, and require so much negotiation on what gets pushed without have have very clear outline of how to handle rebasing and editing comment messages, files, and pull requests.

I tried to make changes to files as requested in a review and they seem to have gotten lost because I was switching between two branches trying to edit the commit messages.

Shouldn't there be an override feature where senior members can just edit these and send a message to me the newbie contributor on what to do better next time, rather than being stuck in pending status for weeks?

Could we consider making a different repo for Read the Docs so that it have less strict requirements for committing so instructions can more easily be fixed and updated. 

I feel like making it hard to make doc changes means that more new contributors are going to get frustrated and lost. 

Otherwise can someone pair with me to edit the docs and make sure I'm using the correct tense/verbage.

**Comment by jschwarzwalder** [comment]
git push origin master --force

**Comment by AbdealiJK** [comment]
I think that most of the members who contributed to docs up until now were devs initially and had to write docs :D 
I completely understand why a documenter - who has no idea about code would find it frustrating, and something should definitely be done (Thanks for opening this issue so we don't ignore this)

So, as we have a new documentation repo, that's a step forward.
Also we **should** allow simple edits made in the Github web interface there IMO and not care about whether the commit history is nice and so on - or a admin/maintainer should care about the commit history but not a new documenter who is just interested in a one-off contribution and not planning on heavy contribution.
@coala-analyzer/coala-admins opinions ?

**Comment by Makman2** [comment]
Imo if someone wants to do a commit, he/she should follow our style. Mostly everything in our workflow has a reason^^

If someone just wants to provide some changes without diving into git, it's possible to file an issue and copy the new text there. Or just submit a PR with mentioning that someone shall take over and make everything nice and clean for merge.

**Comment by Adrianzatreanu** [comment]
I think that, as @Abdealjk said, anyone who's willing to contribute with documentation, probably has a background that includes using git before. So simple git knowledge cannot be simplified by our side, as we do not own git :)

As per the workflow: we have already moved the repo somewhere else, and more or less I've been maintaining it lately and it is less strict than coala, from the reason you mentioned: its just documentation, not a linux kernel. We still have rules, we dont merge with bad commit messages, but I will ack a commit if it has 2 changes and not one, because you dont need to debug documentation :) people shouldnt have to have advanced git knowledge just to write some documentation..

**Comment by Adrianzatreanu** [comment]
And I think this is the best we can do from our side to making it as easy as possible to contribute to documentation :) if anyone has better ideas, im open to hearing them!

**Comment by AbdealiJK** [comment]
One point mentioned in the initial message was whether the user needs to know how to rebase.
So, are we allowing those merge commits ? Or are rebases necessary ?
As rebases are indeed difficult for new people

**Comment by Makman2** [comment]
maybe no rebases (if there are no conflicting changes), but at least no merge commits, because reverting commits with these is horrible^^

**Comment by AbdealiJK** [comment]
Never had to work with merge commits, so will take your work about that :)

So, I'm closing this with the conclusion that we'll be a bit lenient about these things for the documentation repo. Hopefully the workflow for the documentation will become easier as we get more documenters who are not coders !
Possibly we want to move this dissuccion into the dcos repo @Adrianzatreanu as a record so it doesnt get lost ?

**Comment by fneu** [comment]
would it make sense to move the documentation repo to gitlab for the sake of merge commits?

**Comment by Adrianzatreanu** [comment]
@fneu it is moved..somewhere...on gitlab.. but its outdated and people have been working on the github one still :D havent got the time yet to do a full migration, will do it in the future :)

**Comment by sils1297** [comment]
ahm why are you accepting PRs on GitHub though? What's missing for the migration?

**Comment by Adrianzatreanu** [comment]
thats a very good question :D
