### ISSUE TITLE
Add installation methods for GoRequirement and JuliaRequirement

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#2398]
GoRequirement and JuliaRequirement also could have the ``install_command`` method which builds the command from its attributes, and the ``is_installed`` method which checks whether it is installed or not.
I'm encountering lots of problems on my OS with those 2 and i cannot test them properly. If there's anyone who has those installed and is willing to do it, I'd very much appreciate.

Examples for pip of those commands:
```
def install_command(self):
       return "pip install {}=={}".format(self.package, self.version)
```
and
```
def is_installed(self):
      return not call_without_output(('pip', 'show', self.package),)
```

**Comment by RohanVB** [comment]
I'd like to try this one.

**Comment by Adrianzatreanu** [comment]
hey @RohanVB feel free to ask me if there's anything you need, as I've done this for other 3 managers :)
