### ISSUE TITLE
Improve warning message when user prompts to run a bear and no matching bears are found

### ISSUE THREAD

**Issue by RohanVB** [coala-analyzer/coala#2402]
According to the tutorial video on http://coala-analyzer.org/#intro, usage of SpaceConsistencyBear is shown. 

**Note 1:**
 _coala was installed on a virtual environment._

The warning message is displayed when the steps below were followed:

> sudo pip3 install coala-bears
> coala --bears=SpaceConsistencyBear --files=test.py --save
> 
> [WARNING][23:50:40] No bears were found matching 'SpaceConsistencyBear'.
> Executing section Default...

**Note 2:** 
_The test.py file was created as :_ 

> _vim test.py_

_and it contained the following:_

> _def something():_
>    (4 whitespaces)     _a=5_

**Comment by Adrianzatreanu** [comment]
What better ideas do you have? ``No bears were found matching x. Make sure you typed the name correctly or install it from here link_coala-bears_repo``? or what do you have in mind?

**Comment by RohanVB** [comment]
I agree. Prompting the user to check for typos, otherwise displaying instructions to get bears would be helpful.

**Comment by yash-nisar** [comment]
I would like to get assigned.

**Comment by yash-nisar** [comment]
@Adrianzatreanu Could you please brief me about the source file associated with this issue ?
