### ISSUE TITLE
Add SystemManagerRequirement

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#2411]
It makes sense to add a `SystemManagerRequirement` which then is subclassed into `AptGetRequirement`, `DNFRequirement`, `ZypperRequirement`, and so on.

Many times, it makes a lot more sense to use a system packages when available. Especially for that stuff that needs `cabal` and so on where installation time for installing packages was huge in our CI.

**Comment by Adrianzatreanu** [comment]
I think we are making those ``conda`` packages.

**Comment by sils1297** [comment]
yep those will be conda, @AbdealiJK reopen if there's a misunderstanding :)

**Comment by AbdealiJK** [comment]
Ah, apologies. Seems like I missed some conversation in between and  also wasn't thinking correct.
