### ISSUE TITLE
Change Coala to coala

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#2414]
https://raw.githubusercontent.com/coala-analyzer/coala/93da64190db8a6220a42e3f0562fd1b06acab742/docs/index.rst

`Getting Started with Coala <Users/Tutorials/Tutorial>` should have `coala` not `Coala`

**Comment by jschwarzwalder** [comment]
I can fix this

**Comment by hypothesist** [comment]
@jschwarzwalder assigned you
