### ISSUE TITLE
docs: Add FAQ page

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#2427]
I've noticed there's a lot of newcomers that ask similarily the same questions, as in: What are those things failing/not failing in my PR, what issue do I choose etc, because probably they are too lazy to read the full docs (I cannot blame them, it's a lot!).

To fix this, I was thinking we could have a FAQ page where we'd put a few questions that we could simply redirect people to and there they'd read pretty much all they need to know.

**Comment by sils1297** [comment]
Like it, we have something drafty already at https://github.com/coala-analyzer/coala/wiki/FAQ , let's move it to the docs?

**Comment by Adrianzatreanu** [comment]
ah, great, I had no idea about it.

**Comment by Adrianzatreanu** [comment]
I'll read it and work around it then so we can delete the page after :)
