### ISSUE TITLE
Videos for newcomers doc

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#2430]
In the newcomers docs we should have an ascii cinema or Video tutorial on how to use git for our workflow.
Just makes it so much easier because people get confused about `rebase -i` and so on frequently.

I'm thinking 3 videos:
 - How to make a contribution: (Clone, create branch, edit file, commit, push, possibly also add how to make a PR if it's not ascii cinema)
 - How to modify my last commit / modify my commit message / modify my earlier (not last) commit
 - How to rebase

**Comment by hypothesist** [comment]
I made this a week ago: https://asciinema.org/a/78683

**Comment by hypothesist** [comment]
It kinda covers most points. It could be more comprehensive though. Anyway, this is the source file I used to generate that: https://github.com/hypothesist/termtype/blob/master/rebase_tutorial.example

**Comment by Adrianzatreanu** [comment]
that's cool, looking forward to someone adding them

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#29
