### ISSUE TITLE
Filter bears by CAN_DETECT or CAN_FIX

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala#2431]
I think we should have a ``coala`` command that would be able to show you what coala does for a specific language. I think right now we have one that shows you what bears you can use with your language (if im not mistaken) but i think we should have one that would basically be taking all those bears that use that language, and then unify the sets with can_detects and those with can_fix and show a thing per total :D

**Comment by Adrianzatreanu** [comment]
Example to clarify:
``coala --show-capabilities Python``
and you have a list
``coala can detect and fix for Python: Formatting, Syntax.``
``coala can only detect for Python: Security.``

"this is an example, thats not what coala does for python right now"

**Comment by Asnelchristian** [comment]
I completely agree, :)

**Comment by Adrianzatreanu** [comment]
You wanna do it?

**Comment by Asnelchristian** [comment]
It sounds fun

**Comment by Asnelchristian** [comment]
yeah
