### ISSUE TITLE
It takes a long time to execute even the simplest commands

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala#2442]
```
$ time coala --help
coala -h  0.98s user 0.15s system 99% cpu 1.133 total
```

I'm sure there is some unnecessary work being done here if printing the help text takes an entire second.

**Comment by hypothesist** [comment]
@underyx related https://github.com/coala-analyzer/coala/issues/2344

**Comment by underyx** [comment]
Not just related actually, that's a duplicate. Closing.
