### ISSUE TITLE
JSONEncoder: Add skipkeys to ignore encoding invalid chars

### ISSUE THREAD

**Issue by tushar-rishav** [coala-analyzer/coala#2446]
We may rather use [skipkey](https://docs.python.org/3.4/library/json.html#json.JSONEncoder) to ignore the errors while encoding non acceptable chars. This would require to tweak the `create_json_encoder` a bit.

**Comment by sils1297** [comment]
I don't fully understand, why's this needed?

**Comment by tushar-rishav** [comment]
Having this we won't need to catch any errors explicitly that are thrown
while encoding non int, float etc (invalid chars). One use case is in
encoding bears. :)
It's not very important though so we may drop it. :)
ᐧ

On Wed, Jul 13, 2016 at 7:30 PM, Lasse Schuirmann <notifications@github.com>
wrote:

> I don't fully understand, why's this needed?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/coala-analyzer/coala/issues/2446#issuecomment-232364010>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHDgOcPyQZRa-DGqdKmSTEnRX3bOsEquks5qVO-agaJpZM4JLbUN>
> .
>



-- 
Best regards,
Tushar Gautam
http://gtushar.co

**Comment by Makman2** [comment]
> ... encoding bears.

sorry I don't understand this too :O

**Comment by tushar-rishav** [comment]
Sorry. I meant the parsing that happens using JSONEncoder while dumping a
dictionary. For eg bears data.

**Comment by Makman2** [comment]
We shouldn't ignore encoder errors as it results in non-desired output.

**Comment by tushar-rishav** [comment]
Um alright. :smile:
