### ISSUE TITLE
`StringProcessing.unescape`: Introduce new parameter: expand_dict

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2447]
The `expand_dict` is a list which contains characters with special meaning, like for `\n` or `\t`:
```
{"n": "\n", "t": "\t"}
```
As default `expand_dict` should contain everything python uses as escape character :+1:

**Comment by Asnelchristian** [comment]
can i work on this :)

**Comment by sils1297** [comment]
can we have it empty by default? Otherwise it may break things, those areas are very sensible. CC @fneu as well, we need to be careful here.

**Comment by Makman2** [comment]
hm then you can just do: `unescape(my_string, {})`
this is imo shorter than specifying the "python-dict" and passing that if you need python escapes.

bottom-line:
disabling the python-dict is easier than enabling it :+1:

**Comment by Asnelchristian** [comment]
StringProcessing was deleted :)

**Comment by Asnelchristian** [comment]
coala_utils is now the one we use right ? :)

**Comment by Makman2** [comment]
right, migrated to https://gitlab.com/coala/coala-utils/issues/10 .
