### ISSUE TITLE
Make the project specific bear feature more discoverable

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala#2451]
After https://github.com/coala-analyzer/coala/issues/2450 is closed there should be a default directory inside project directories where custom bears can be added. This feature is really useful, but hard to come across right now.

area/documentation

**Comment by sils1297** [comment]
We should also write about the `.bears` directory after it exists, see https://github.com/coala-analyzer/coala/issues/2450

**Comment by underyx** [comment]
How about adding a new flag/subcommand to `coala` that generates a boilerplate bear in `.coabears/`, like cookiecutter? We could also extend that feature to make it really easy to submit the bear for inclusion in the coala-bears project.

**Comment by sils1297** [comment]
CC @mr-karan that would be part of his tool

**Comment by mr-karan** [comment]
I did something of this sorts @underyx https://gitlab.com/coala/coala-bear-management

**Comment by sils1297** [comment]
@mr-karan we'll need this for normal bears as well

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#28
