### ISSUE TITLE
Codestyle: Add continuation line policy

### ISSUE THREAD

**Issue by fneu** [coala-analyzer/coala#2454]
Basically we are already enforcing a style, where multiple-line lists, dicts, tuples, function definitions, function calls, and any such structures either:

- stay in one line
- span multiple lines that list one parameter/ item each

Since this is not covered by PEP8 we should add a section to our [codestyle](https://github.com/coala-analyzer/coala/blob/master/docs/Getting_Involved/Codestyle.rst)

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#27
