### ISSUE TITLE
argparser contains duplocation

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2460]

**Comment by Makman2** [comment]
Could you be a bit more precise?

**Comment by sils1297** [comment]
yeah I was in a hurry, if you look down somebody copied the arguments for
coala for coala-json including helptexts etc

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/
