### ISSUE TITLE
Fix typo: docs/Tutorial: seperated -> separated

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#2475]

**Comment by swrj** [comment]
Is this for the two instances for the word "seperated" in tutorial.rst located in docs/users/tutorials? If so, you can assign me to this issue

**Comment by hypothesist** [comment]
I think I made this issue for one of them, but go ahead and fix both :)

@swrj assigned you

**Comment by swrj** [comment]
You can close this issue, refer to https://github.com/coala-analyzer/coala/pull/2644.
