### ISSUE TITLE
Fix typo: Lint.py: succesfully -> successfully

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala#2478]

**Comment by splinterific** [comment]
I wouldn't mind taking this one if thats ok! 

https://github.com/coala-analyzer/coala/blob/7cda7e37743be228369b353a9c05f26a75a2e9c8/coalib/bearlib/abstractions/Lint.py#L295

**Comment by sils1297** [comment]
go for it

**Comment by splinterific** [comment]
Pull Request submitted - https://github.com/coala-analyzer/coala/pull/2618

**Comment by sils1297** [comment]
wrong reference in the commit, closing manually.
