### ISSUE TITLE
Fix typo: LineParser.py: seperator -> separator

### ISSUE THREAD

**Issue by Redridge** [coala-analyzer/coala#2495]

**Comment by pasta-driven** [comment]
I'd like to get assigned.

**Comment by sils1297** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://gitter.im/coala-analyzer/coala) and tell us about them :)
