### ISSUE TITLE
Fix typo: ConsoleInteraction: a -> A 

### ISSUE THREAD

**Issue by Asnelchristian** [coala-analyzer/coala#2503]
Change ``a`` -> ``A`` in the following lines:
[line 1](https://github.com/coala-analyzer/coala/blob/master/coalib/output/ConsoleInteraction.py#L434)
[line 2](https://github.com/coala-analyzer/coala/blob/master/coalib/output/ConsoleInteraction.py#L454)
[line 3](https://github.com/coala-analyzer/coala/blob/master/coalib/output/ConsoleInteraction.py#L466)

**Comment by tveyben** [comment]
I'd like to fix this issue :-)
