### ISSUE TITLE
Fix typo: ConsoleInteraction.py: its -> 'it is'

### ISSUE THREAD

**Issue by Asnelchristian** [coala-analyzer/coala#2504]
[line](https://github.com/coala-analyzer/coala/blob/master/coalib/output/ConsoleInteraction.py#L583)

**Comment by hypothesist** [comment]
@Asnelchristian I changed the title (this and one other issue) so that it matches with the other typo issues we have. Hope that's okay :)

**Comment by Asnelchristian** [comment]
:+1:

**Comment by tveyben** [comment]
I'd like to fix it

**Comment by tveyben** [comment]
I'd take another issue

**Comment by yash-nisar** [comment]
I would like to fix this issue.

**Comment by sils1297** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://gitter.im/coala-analyzer/coala) and tell us about them :)

**Comment by yash-nisar** [comment]
Thanks, I appreciate it.

**Comment by sils1297** [comment]
You're assigned, welcome :

**Comment by sils1297** [comment]
:)
