### ISSUE TITLE
Collectors: Correct docs 

### ISSUE THREAD

**Issue by Asnelchristian** [coala-analyzer/coala#2506]
Ensure that the param docs start with a capital letter in the following functions:
* ``icollect``
* ``collect_files``
* ``collect_dirs``
* ``icollect_bears``
* ``filter_section_bears_by_languages``
* ``collect_all_bears_from_sections``

**Comment by tushar-rishav** [comment]
I wanna work on this

**Comment by swrj** [comment]
I could work on this.

**Comment by Makman2** [comment]
I've sent out an org invitation to you, as soon as you've accepted you get assigned to this issue :)
But you can already start working :+1:

**Comment by swrj** [comment]
I have accepted the invitation.

**Comment by swrj** [comment]
Sorry for the delay and the mess above, I'm new to VCS's.

**Comment by sils1297** [comment]
that "mess" is totally fine - it shows that you're learning which is actually way better than just delivering good work ;)
