### ISSUE TITLE
Means to detect settings from code/section

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#251]
We need some kind of settings detector that is basically a bear that inspects the code or the section and guesses settings from that.

Examples:

 * PEP8 - a PEP8Detector could provide all those PEP8 settings finely prepared if the user inspects .py files.
 * Indentation: read all files, probably there will be no tabs or no with tab replaceable spaces -> easily guess tab/spaces

How could we do that internally:

 * Write some of those things.
 * Invoke them if settings are missing, before asking the user.
   * They will return settings with a probability value
 * We have some thresholds internally to either:
   * Use this setting, notify user
   * Ask user, provide guessed setting and probability as default value.
   * Ask user, provide no default value

I see forward to any feedback to this idea.

**Comment by fneu** [comment]
@sils1297 I'm not entirely sure this is possible for things that are more complex than maybe indentation. Especially not in a way that different bears can make use of this. I honestly don't see this as a core functionality for coala (like managing bears and make it easy to write them) so I'd vote for closing this as wontfix for now.

A bear can always provide this functionality itself through the use of some default value for it's setting or similar.

**Comment by sils1297** [comment]
So there's some js linter (I think jscs) that runs the different "rules" with different settings over the code and then counts the issues. I kind of like that...

**Comment by hypothesist** [comment]
Close this in favor of https://github.com/coala-analyzer/coala/issues/1348 ?
