### ISSUE TITLE
Make coala nonlinear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#252]
Currently coala has a linear workflow. However if we want to support outputters that either

 * Expose coalas interface to some IDE or
 * Expose coalas interface to a GUI

we need to let the outputter control what coala's doing. This by itself should not be a big problem with our current architecture, the thing I'm most worried about is cancelling things but thats also a human doable task.

**Comment by sils1297** [comment]
many bugs depend on this one.

**Comment by shivanipoddariiith** [comment]
I have a little WIP, which I designed, after talking to @Udayan12167 . Its very rough and would probably help us to progress further in terms of adding new stuff to the current initial mockup, moving around UI elements, and so on. Once we have a fair idea about what to achieve, me or @Udayan12167  could get this done in collaboration with the gnome-design team (an in a neater place like inkscape).

![coala](https://cloud.githubusercontent.com/assets/2330579/6657062/cf863936-cb65-11e4-9bdf-23e44e078694.jpg)

**Comment by sils1297** [comment]
@shivanipoddariiith maybe we want to discuss this over there: https://github.com/coala-analyzer/coala-design/issues/1

I think it fits better.

**Comment by sils1297** [comment]
requires #386
