### ISSUE TITLE
Documentation, Guide to Write a Bear: Result of command execution different from documented

### ISSUE THREAD

**Issue by alan-martinovic** [coala-analyzer/coala#2528]
### Overview Description
In https://github.com/coala-analyzer/coala/blob/master/docs/Users/Tutorials/Writing_Bears.rst there is a part stating:

> Try executing
> 
> coala -d bears -b CommunicationBear --show-bears
> This will show the user a bunch of information related to the bear like: - A description of what the bear does - The sections which uses it - The settings it uses (optional and required)

# Actual Results
    $ coala -d bears -b CommunicationBear --show-bears
    CommunicationBear
    HelloWorldBear

**Comment by sils1297** [comment]
@hypothesist release relevant

**Comment by splinterific** [comment]
I'd like to work this please! going to update this page but also fix the same on http://coala.readthedocs.io/en/latest/Users/Tutorials/Tutorial.html - https://github.com/coala-analyzer/coala/blob/master/docs/Users/Tutorials/Tutorial.rst
