### ISSUE TITLE
Feature, Versioning: Automatically version with `git describe`

### ISSUE THREAD

**Issue by alan-martinovic** [coala-analyzer/coala#2534]
## Overview Description

When reporting bugs for development version, it's important to know what exact commit the bug occurred at. 
Having this easily accessible with the `-v` flag would help bug reporters provide this information by default instead of additionally explaining them to check `git log` for the commit SHA.

This feature suggest automatic versioning based on the git tags and commit SHAes.

An example implementation would change the behaviour of `get_version()` in https://github.com/coala-analyzer/coala/blob/master/coalib/__init__.py#L8 to call and parse `git describe --tags` to get the version automaticly.

**Comment by alan-martinovic** [comment]
I would like to take this on

**Comment by alan-martinovic** [comment]
Now that I think about it, instead of making it dynamically generated in the code, it should be a hook executed on each commit that updated the VERSION string.

**Comment by sils1297** [comment]
it must be executed upon installation and written to a file right?

**Comment by alan-martinovic** [comment]
I see it being executed on the server upon a push.
Not sure what you mean with installation.

**Comment by sils1297** [comment]
well when I checkout another commit the version would change; so when running setup.py we'd want to determine the version from the git commit right?

**Comment by Makman2** [comment]
when using a commit hook isn't the version contained inside the commit you checkout?

**Comment by alan-martinovic** [comment]
> well when I checkout another commit the version would change; so when running setup.py we'd want to determine the version from the git commit right?

Not following  :)
The current idea is like this.

1. There is a python script in the repo called `get_version`.
2. The script generates a VERSION file.
3. The script takes into account if it's a development or release version.
4. This is done by checking the commit distance from the last tagged commit.
5. On every push, the server executes the script which auto generates the VERSION file.

In this case the development versioning is an automated process and the only thing left is to tag when there is a release version.

Your thoughts? :)

I'm doing the script currently and am not totally sure how to do the server implementation part, but would guess it's doable and would be willing to research it or pair with someone who knows for the server side implementation.

**Comment by sils1297** [comment]
We already have something like it in `.ci/adjust_version_number.py` FWIW

**Comment by sils1297** [comment]
You're saying that a server actually does an automatic commit on every push to update the VERSION file in the repo? That sounds like a lot of generated commits...

**Comment by alan-martinovic** [comment]
Fair :)
Not feasible, closing
