### ISSUE TITLE
"Files that will be checked" debug message appears twice

### ISSUE THREAD

**Issue by encukou** [coala-analyzer/coala#2544]
### "Files that will be checked" debug message appears twice

# Steps to Reproduce

1. Run `coala -f src/*.c -d bears -b HelloWorldBear -L DEBUG --flush-cache`
# Actual Results

    ...
    [DEBUG][11:46:11] Files that will be checked:
    /home/pviktori/dev/coala-tutorial/src/main.c
    [DEBUG][11:46:11] Files that will be checked:
    /home/pviktori/dev/coala-tutorial/src/main.c
    ...

# Expected Results

Message appears only once

# Reproducibility

I used a fresh checkout of coala-tutorial

**Comment by sils1297** [comment]
CC @hypothesist can you fix this real quick?
