### ISSUE TITLE
Long questions don't wrap correctly

### ISSUE THREAD

**Issue by encukou** [coala-analyzer/coala#2546]
### When Coala asks for user input, long questions are wrapped incorrectly.

# Steps to Reproduce

1.  Run `coala -f src/*.c -d bears -b CommunicationBear -L DEBUG`

# Actual Results

    $ coala -f src/*.c -d bears -b CommunicationBear 
    [WARNING][11:51:46] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag.
    .) needed by CommunicationBear: ting "user_input" (Arbitrary user input.

# Expected Results

Question wraps to the *next* line, not the current one

# Reproducibility

I used a fresh checkout of coala-tutorial

**Comment by sils1297** [comment]
@mr-karan are we using prompt toolkit by now? What's wrong here? It did work in the last release I think...

**Comment by sils1297** [comment]
CC @hypothesist this is release critical
