### ISSUE TITLE
In the README.rst file, the statement above the command prompt should be an example specific to Python

### ISSUE THREAD

**Issue by RohanVB** [coala-analyzer/coala#2551]
The current command prompt is displayed as : 

> To see what coala can do for your language, run:
> 
> `$ coala --show-bears --filter-by-language Python`

Since we are giving an example, the statement above the command prompt should be specific to Python.

**Comment by sils1297** [comment]
Isn't that obvious? I feel like an example with a real language is more useful than "insert language". Not that I'm sure...

**Comment by RohanVB** [comment]
It's obvious, but I don't feel its correct. If python has to be in the prompt, the sentence above should be an example specific to using it with terminal, making it 'For example, to see what coala can do with Python, run:' Because right now one is generalised, the other is specific.

**Comment by sils1297** [comment]
cool so let's change the explanation above?

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#24
