### ISSUE TITLE
Documentation: Add docs for all the metadata attributes

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2553]
CC @Udayan12167 @Adrianzatreanu

**Comment by arush0311** [comment]
Can you tell me what you mean by metadata attributes and where they can be found?

**Comment by Adrianzatreanu** [comment]
I think he's referring to the attributes found in https://github.com/coala-analyzer/coala/blob/master/coalib/bears/Bear.py , such as REQUIREMENTS, CAN_DETECT, LICENSE, etc :D

**Comment by arush0311** [comment]
Can I take this? I might need some help though.

**Comment by Adrianzatreanu** [comment]
feel free to, i can help you if needed

**Comment by Adrianzatreanu** [comment]
This is being moved to https://github.com/coala-analyzer/documentation, please pick it up from there, thank you!

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#22

**Comment by Adrianzatreanu** [comment]
https://github.com/coala-analyzer/documentation/issues/22
