### ISSUE TITLE
Documentation: Reorganisation of sidebar links.

### ISSUE THREAD

**Issue by RohanVB** [coala-analyzer/coala#2556]
Some things like 'What are those things failing/passing on my Pull Request?' are placed under 'FOR USERS' whereas it should be under 'Developer resources' or 'Getting started'.

The sidebar should be hierarchical, in terms of step by step processes the 'Getting started' part should come before the 'Developer resources' 

'Why did you choose the name' etc,. would have a better place under General/Home.

Shortening of some of the longer sidebar links would also help faster navigations by using concise terms that describe the sentences.

**Comment by sils1297** [comment]
Indeed, CC @Adrianzatreanu @tushar-rishav 

We're planning some docs work soon :)

**Comment by Adrianzatreanu** [comment]
This was a bug where the FAQ questions were under the toctree instead of under the page. This has beeen fixed in the new docs repo.
