### ISSUE TITLE
what happens if a bear returns something strange?

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#256]
I think we dont check that.

**Comment by sils1297** [comment]
So in the BearRunner class we handle the results of the bears, some exception handling there is needed.

**Comment by Udayan12167** [comment]
Define strange or do we have some test cases in which this happens?

**Comment by sils1297** [comment]
We currently assume, bears return a list of Results. It is to investigate what happens if:

 * a bear returns no list at all, e.g. an int or so
 * a bear returns a list of ints or so.

In the former case it probably fails somewhere in the BearRunner class, in the latter in the Interactor somewhere.

**Comment by Udayan12167** [comment]
so when a bear returns something strange would raising a custom exception be okay?

**Comment by sils1297** [comment]
IMO we'll want that logged as an error and not use the result. Most
important thing is to have an important log message.
Am 23.02.2015 10:20 schrieb "Udayan12167" <notifications@github.com>:

**Comment by Udayan12167** [comment]
The result should be checked in the _run_bear method in the BearRunner class and there we use a self.err to log the message? My only question is if we trigger the error message through an exception?

**Comment by Udayan12167** [comment]
The other option i have in mind is we catch the error in the execute method of the Bear class and log the error there?

**Comment by sils1297** [comment]
_run_bear method is a good entrypoint. However exceptions are usually failures, so triggering an exception within the module and then catching it is usually a bad practice because you can just not trigger the exception in the first place.

Since the user may overwrite the execute method (even though I don't see a usecase but he can) I'd rather check it in the BearRunner.

**Comment by Udayan12167** [comment]
if a bear returns none does that also count as strange behaviour? I have been able to implement the feature but because im checking if the instance of return value of bear is a list .It is breaking some tests in the bearrunnertest.py because the level of the messages is set to error where as is expects debug.

**Comment by sils1297** [comment]
None should definitely be allowed, with your reasons. Furthermore you see that the None case is handled currently in our code.

**Comment by Udayan12167** [comment]
Just have a look if it is implemented properly and the test case is exhaustive or requires more cases.

**Comment by sils1297** [comment]
Cases are good, reviewing right now.

**Comment by sils1297** [comment]
Thanks for the patch by the way :)

**Comment by Udayan12167** [comment]
I did not get the coverage part? Rest i have done all changes.

**Comment by Udayan12167** [comment]
I hope everything is fixed now :)

**Comment by sils1297** [comment]
Travis says your build is failing: Tests finished: failures in 1 of 50 test modules, skipped 0 test modules.

**Comment by sils1297** [comment]
https://travis-ci.org/coala-analyzer/coala/builds/51944824

**Comment by Udayan12167** [comment]
Fixed

**Comment by Udayan12167** [comment]
Umm now?

**Comment by sils1297** [comment]
Did you check it yourself before asking again?

2015-02-24 10:01 GMT+01:00 Udayan12167 <notifications@github.com>:

**Comment by Udayan12167** [comment]
Yeah

**Comment by sils1297** [comment]
Why does scrutinizer show trailing whitespace then?

2015-02-24 10:03 GMT+01:00 Udayan12167 <notifications@github.com>:

**Comment by Udayan12167** [comment]
It showed a green tick on my last commit and then i cant see the scrutinizer link

**Comment by sils1297** [comment]
Green tick isn't enough. If you click on "Show all checks" you can click on
"details" and then browse the issues you introduced and see some ratings on
the code you're introducing. If rating goes up thats good, if rating goes
down you should have a further look at function complexities. Looking at
new issues is usually a good idea independently from rating. Trailing
whitespace is very trivial and if you just run the coala application in the
coala repository root coala will even correct it by itself. Forthermore
many editors (e.g. pycharm) strip trailing whitespace by themselves.

2015-02-24 10:19 GMT+01:00 Udayan12167 <notifications@github.com>:

**Comment by Udayan12167** [comment]
I cant see a show all checks button.

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/333
Down below. You may have to wait a few seconds because the travis and scrutinizer servers need some time to register. You sure you don't see it?

**Comment by Udayan12167** [comment]
Hey sorry, i just ended up running coala and fixing it. Pycharm has that option enabled but was not doing it. I apologise again for this stupid error.

**Comment by sils1297** [comment]
did you find the scrutinizer link in the end?

**Comment by Udayan12167** [comment]
Yeah
