### ISSUE TITLE
Manage all asciinemas

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala#2574]
So should we do something about all `asciinemas` that are made by contributors? Simply tweeting them doesn't preserve the info, perhaps we can even display them on bear docs. 

How should we go about this?

**Comment by sils1297** [comment]
Nice, we can put them in the bear documentation comment :)

**Comment by sils1297** [comment]
@mr-karan wanna take this on? Going through the tweets, adding them to the doc comments?

**Comment by mr-karan** [comment]
@sils1297 Sure, if I get time from the other GSoC important task? Since the deadline is in next 11-12 days, my first priority is of course my gsoc work but if it's not too urgent, can I do this on leisure?

**Comment by sils1297** [comment]
heh, sure. Maybe somebody else can do this quick? This might be a good
starting point for a newcomer.

**Comment by mr-karan** [comment]
I'll probably do this on the coming weekend, if anyone else can do it before that, feel free to take else I'll take it up.

**Comment by mr-karan** [comment]
This is such a boring task, so I hacked up a quick script and let the machine do it :stuck_out_tongue_closed_eyes: 

https://gist.github.com/mr-karan/a8b525bca2587ae56981b33316e8f7aa
