### ISSUE TITLE
coala-json: Invalid JSON File

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala#2578]
Here's how to reproduce: 

`coala-json --show-bears >> out.json`

out.json -> http://dpaste.com/32JNCBR

When you lint this on http://jsonlint.com/, it produces the error:

```
Error: Parse error on line 4458:
...42:21.539644"	}]} {	"bears": [{		"AU
---------------------^
Expecting 'EOF', '}', ',', ']', got '{'
```

**Comment by mr-karan** [comment]
@arafsheikh

**Comment by arafsheikh** [comment]
It says `Valid JSON` for me.

**Comment by arafsheikh** [comment]
You ran the command twice so it's two JSON outputs appended. If you remove everything below L4458 it becomes valid.

**Comment by mr-karan** [comment]
Oh I didn't notice. Sorry my bad
