### ISSUE TITLE
Contributors list on the website should show the list in descending order of number of commits

### ISSUE THREAD

**Issue by shaswatrungta** [coala-analyzer/coala#2601]

**Comment by sils1297** [comment]
hey @shaswatrungta thanks for reporting this. This is an issue with the website, I'll move the issue over there.

Indeed the people list is a bit buggy but often it actually shows it right for me :P CC @arafsheikh I think he implemented this. Often is certainly not enough ;)

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/website#54
