### ISSUE TITLE
What to do with the getting involved readme?

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2610]
We've got http://coala.readthedocs.io/en/latest/Getting_Involved/README.html and I'm not sure if we want to keep it, we already have the newcomers guide for coding. At least we should link to it on the top and update it I think.

area/documentation

CC @Adrianzatreanu

**Comment by Adrianzatreanu** [comment]
done in the coala-docs repo, just closing, not migrating the issue.
