### ISSUE TITLE
Linter_Bears.rst: Link to API docs

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala#2614]

**Comment by swrj** [comment]
Could you clarify what is needed to be done?

**Comment by SanketDG** [comment]
@swrj sure! 

So in Linter_Bears.rst, there is this piece of text:

> If you need more information about the ``@linter`` decorator, refer to the API
documentation. It's more versatile than described in this little tutorial.

The task is to link the text "API documentation" to our api docs http://coala.readthedocs.io/en/latest/API/modules.html

**Comment by Makman2** [comment]
@SanketDG do we have the possibility to use some "relative" link, so we don't need to link hardcodedly to our website?

**Comment by SanketDG** [comment]
Yes we can by using the `:doc:` thing

`:doc `API documentation <API/modules>`

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#21
