### ISSUE TITLE
Constants.py: Use uniform quoting standards

### ISSUE THREAD

**Issue by adtac** [coala-analyzer/coala#2634]
We have a mix of `'` and `"`

**Comment by Makman2** [comment]
I would pledge for the same standards like python prints `repr(mystring)`
1. if only `'` occur inside string, use `"`
2. If `'` and `"` are mixed inside string, use `'`
3. Otherwise use `'` everywhere

**Comment by swrj** [comment]
I could do this. I will only use single quotes instead of double quotes.

**Comment by Makman2** [comment]
@swrj that's still the question how we want to quote now^^

**Comment by hypothesist** [comment]
I like `"` more, but that's probably because I started programming with C/C++. `'` is ingrained in my brain to be for chars.

**Comment by sils1297** [comment]
So as a normal programmer you'd prefer ' because on the english keyboard
layout (which is the only thing in this world *right?*) you don't need
shift to type it.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by hypothesist** [comment]
Can confirm. English is the only language, oui :P

**Comment by Makman2** [comment]
so these rules now?
> 1. if only ' occur inside string, use "
2. If ' and " are mixed inside string, use '
3. Otherwise use ' everywhere

**Comment by hypothesist** [comment]
@Makman2 that's going to be a lot of changes throughout coala

**Comment by Makman2** [comment]
we should write a bear for that, if possible with patches :)

**Comment by beatrix-bodo** [comment]
Working on this one

**Comment by underyx** [comment]
@Makman2 relevant: https://github.com/coala-analyzer/coala-bears/issues/557
