### ISSUE TITLE
Diff.delete_lines: Delete also end_line

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2641]
When I'm giving `Diff.delete_lines(4, 7)`, it would only delete lines 4, 5 and 6. I think it should also delete line 7.

So just increment the 2nd parameter of `range` inside `Diff.delete_lines` and document that properly.

**Comment by sils1297** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://gitter.im/coala-analyzer/coala) and tell us about them :)

**Comment by sils1297** [comment]
@kmo1 ^
