### ISSUE TITLE
Flake8Bear

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala#2682]
The only thing right now that checks for Python syntax errors is pylint, but that might be too strict for some projects, so flake8 should be a nice alternative bear for the purpose.

**Comment by underyx** [comment]
Whoops, searched in the wrong repo, issue already exists here: https://github.com/coala-analyzer/coala-bears/issues/169

**Comment by sils1297** [comment]
might it be simpler to give our pylintbear a setting syntax only or so?
