### ISSUE TITLE
Library and default_coafilenot in the same place after install.

### ISSUE THREAD

**Issue by sims1253** [coala-analyzer/coala#269]
Done on my vm running Ubuntu 14.04.1 LTS

http://pastebin.com/jwzcyQR8
http://pastebin.com/X6S2dLX8

**Comment by sils1297** [comment]
Thanks for reporting, I'm currently investigating the possibility of
removing the default_coafile after all. We've had much discussions over
this back then...

2015-02-13 17:33 GMT+01:00 sims1253 <notifications@github.com>:

**Comment by sils1297** [comment]
This seems to be a problem of ubuntu, another person has verified your report.

Will need fixing soon, I'll care for it.

**Comment by sils1297** [comment]
Could you please test this with the following commands:
```
cd coala
git pull
git checkout origin/wip/sils/bearrunner
sudo ./setup.py install
coala
```

**Comment by sims1253** [comment]
http://pastebin.com/h09EdNtF
seems to work

**Comment by sils1297** [comment]
merged
