### ISSUE TITLE
Improve documentation about how to set the default editor

### ISSUE THREAD

**Issue by liberforce** [coala-analyzer/coala#2697]
I've tried using coala, and had to struggle to set  my editor in a permanent way.

The documentation only talks about an editor in https://coala.readthedocs.io/en/stable/Users/Tutorials/Tutorial.html . However it doesn't say how to set it permanently.

Another thing is that typing "editor" in the search field in the top-left corner of this page doesn't have the page in the results. In the end, I just added 'editor = vim' in my .coafile and it worked.

**Comment by sils1297** [comment]
Hi @liberforce I'll move this issue over to https://github.com/coala-analyzer/documentation/issues .

Thanks for reporting it, that can probably easily be added inside the note. If you're interested in contributing to coala that might be a nice thing :)

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/documentation#94
