### ISSUE TITLE
Leave space when asking for action number.

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#270]
Leave a space after the question `Please enter a number of the action you want to execute.`
The number is printed directly behind it:
`Please enter a number of the action you want to execute.0`
Shall be:
`Please enter a number of the action you want to execute. 0`

**Comment by sils1297** [comment]
thanks, will deal with that shortly, totally true

**Comment by sils1297** [comment]
will be fixed with that commit. I'll make sure to update CE3D submodule as soon as this is approved for master.

**Comment by Makman2** [comment]
Yes seems to be solved in #290.
