### ISSUE TITLE
caching affects other sections

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2708]
when I run `coala section` and the section yields no result and then after I run `coala anothersection` which would yield results, coala "caches" and doesn't show me results until I run `coala anothersection --flush-cache` :(

type/bug importance/critical

@hypothesist can you look into this ASAP? It's a pretty evil issue.

Thanks @netman92 for finding it.

**Comment by hypothesist** [comment]
@sils1297 we can solve this if we include the section that is being run when we compute the settings hash. This will force cache flush though. But that shouldn't really affect the people for whom caching is very important -- those who run the same commad repeatedly.

**Comment by sils1297** [comment]
Can you fix this ASAP? We should Napier it ASAP
