### ISSUE TITLE
Fix typo: ShowPatchAction.py: `Wether` -> `Whether`

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala#2719]
Here's the line in question:

https://github.com/coala-analyzer/coala/blob/f3765bce44acb5ef75d2387acb830ab4b601d197/coalib/results/result_actions/ShowPatchAction.py#L86

difficulty/newcomer

**Comment by sils1297** [comment]
@Satyam-Bharadwaj 
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://gitter.im/coala-analyzer/coala) and tell us about them :)
