### ISSUE TITLE
Coala return message when doing nothing

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#272]
What about a message if coala can't find anything instead of just returning?

**Comment by sils1297** [comment]
A similar thing is #267 by the way. I'll see forward to getting this added. Not sure I can do it today.

**Comment by sils1297** [comment]
I assume you don't mean doing nothing but no output. coala does actually check your code.

**Comment by sils1297** [comment]
fixed by the commit above.

**Comment by Makman2** [comment]
What does coala now prints? I stumbled upon this string:
```
No existent section was targeted nor enabled. Nothing to do.
```
But if nothing happened during check, this doesn't really apply, does it?
Or do I miss the right string?

**Comment by sils1297** [comment]
See 64d0398e and #267 : we're showing now "Executing section {}..." or something so you'll see coala's actually doing something.
