### ISSUE TITLE
Move js.coalang file from languages folder to definitions subfolder

### ISSUE THREAD

**Issue by meetmangukiya** [coala-analyzer/coala#2723]
`js.coalang` is a language definition file, it should be placed in `definitions` folder where definitions of other languages reside as well
```sh
/coalib/
     bearlib/ 
           languages/
                 definitions/
                         # This is where it should be 
                 # This is where it is 
                 js.coalang
```

difficulty/newcomer

**Comment by beatrix-bodo** [comment]
This issue is solved by https://github.com/swrj/coala/commit/fc5d11e1a0d579cf4eb929ffd157b97f43070c9b

**Comment by sils1297** [comment]
@beatrix-bodo you sure? That commit is on master on a fork, not on our master.

**Comment by beatrix-bodo** [comment]
@sils1297 my mistake.
