### ISSUE TITLE
CONTRIBUTING.rst: 'Writing Good Commits' link is broken

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala#2727]
The [contributing guidelines](https://github.com/coala-analyzer/coala/blob/master/CONTRIBUTING.rst) have a link to the 'Writing Good Commits' docs page, but the link gives a 404 error.

difficulty/newcomer
area/docs

**Comment by AbdealiJK** [comment]
Don't we have InvalidLinkBear to avoid these things ?

**Comment by sils1297** [comment]
Actually yes, we didn't use it yet - we should start!
