### ISSUE TITLE
Shell.py: Fix typo in L9

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#2731]
Inside the "docstring" in https://github.com/coala-analyzer/coala/blob/19b6e22edd093fee3f5eaa17c761007f47204a34/coalib/misc/Shell.py#L9

`surpresses` -->`suppresses`

**Comment by beatrix-bodo** [comment]
@sils197 is this a duplicate of https://github.com/coala-analyzer/coala/issues/2484 ?

**Comment by sils1297** [comment]
Yes, thanks!
