### ISSUE TITLE
Newlines in coafiles

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#274]
coala gives me for example this file:
```
[Default]
bears = SpaceConsistencyBear
files = src/*.c
use_spaces = True
[Makefiles]
bears = LineLengthBear
files = Makefile
max_line_length = 80
```
I would make a return between two sections. So it looks like this:
```
[Default]
bears = SpaceConsistencyBear
files = src/*.c
use_spaces = True

[Makefiles]
bears = LineLengthBear
files = Makefile
max_line_length = 80
```
This is only a suggestion, but I think that it's more readable and cleaner especially when you use command-line-generated coafiles in your projects.

**Comment by sils1297** [comment]
I totally agree, thanks for filing. However it's difficult to realize:

You should have noted that coala is able to edit the coafile. So you can change it via command line. In this case coala will preserve your newlines and comments in case you manually edited the file. Spaces within one line will be erased and formatted defaultly.

That makes it a tiny bit more complex but we'll do it of course, thanks for filing. (No priority bug though.)
