### ISSUE TITLE
`get_available_decodeerror` is duplicated in coala-bears

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala#2743]
Occurrences are:

https://github.com/coala-analyzer/coala-bears/blob/master/bears/js/JSONFormatBear.py#L12-L16

and

https://github.com/coala-analyzer/coala-bears/blob/master/bears/js/JSComplexityBear.py#L10-L14

**Comment by meetmangukiya** [comment]
I'll take on this one :D

**Comment by meetmangukiya** [comment]
+ [ ] Change the name of the function to `get_available_decode_error`
@underyx agree?

**Comment by Makman2** [comment]
can't we drop this function by now? we don't support python below 3.4 anymore I believe^^

**Comment by underyx** [comment]
The exception is new in 3.5 though.

**Comment by Makman2** [comment]
ohh indeed have confused myself, sorry :)

**Comment by Makman2** [comment]
looks like we need to reintroduce the compat-module again :P

**Comment by Makman2** [comment]
@meetmangukiya best is you create a new module `Compatability` (or if you want, short `Compat`) inside `coalib.misc`. There the exception should go imo^^

**Comment by meetmangukiya** [comment]
@makman2 What exception :( ?

**Comment by Makman2** [comment]
instead of just copying the function `get_available_decodebla`, it's nicer to do
```
# Inside compat module
try:
     JSONDecodeError = json.decoder.JSONDecodeError
except AttributeError:
    JSONDecodeError = ValueError

# inside bears:
from coalib.misc.compatability import JSONDecodeError
```

**Comment by meetmangukiya** [comment]
@Makman2 as @underyx already suggested, `coalib`, afaik is a folder in `coala` and this file is in `coala-bears`, how are we going to make the import :/

**Comment by Makman2** [comment]
Don't understand you exactly. If you implement the exception here in the coala codebase, then you need to change the bears accordingly in coala-bears to make use of the new "feature".

As coalib will be installed globally, importing from a bear is not a problem at all, our bears already do that quite often.

**Comment by meetmangukiya** [comment]
Since, the two files to be changed are in two different repository, I'll raise a PR in both of them.

**Comment by meetmangukiya** [comment]
btw @Makman2 I never knew we could even import variables in python :+1:

**Comment by Makman2** [comment]
a function is nothing else than an object too :) just like any other variable :)
