### ISSUE TITLE
OpenEditorAction: Use system editor

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#275]
Would be nice to have, I don't know how to do that *right* though so its no priority for now.

**Comment by sils1297** [comment]
maybe take a look at how other programs do it:
http://stackoverflow.com/a/2596835

**Comment by sils1297** [comment]
I think with #330 we're having a nice way to set this permanently that is more consistent than this proposal. We can however use the environment variable as default value or so... let's do that!

**Comment by Makman2** [comment]
That's the same thing I had in mind

**Comment by sils1297** [comment]
This is not really a priority because the GUI will probably have editing features later so let's not waste time here.
