### ISSUE TITLE
Add python 2 support

### ISSUE THREAD

**Issue by mgracer48** [coala-analyzer/coala#2763]
I think it be great if we could do this

**Comment by sils1297** [comment]
coala being run under python 2? That's technically very difficult. coala uses some python 3 only features to automatically guess APIs for the analysis routines, see also coala.io/writingbears - we couldn't use those in python 2.

[Python 2 is dead.](http://pythonclock.org/), it's not properly maintained and "unless I push to the wrong branch accidentally" (quote from Guido) nothing will happen to it. It would mean more than an inconvenience for us to support it.

People using python 2 are free to run coala in a tox environment or a docker container (which is recommended for CI).

Closing this as wontfix/not happening, if there are valid arguments this can be reopened of course.

**Comment by sils1297** [comment]
P.S. coala can analyze python 2 code but not run on python 2
