### ISSUE TITLE
Auto detect invoked text editor

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#278]
Auto detect it if the user enters an editor and try to invoke it with command line args that let editor start up in a new process (so if the editor is already started the new started editor is not shut down because it passes the document to open to the already running editor).

@sils1297 
I think a database won't be an overkill. You just need to check if this editor is desired and get a corresponding key, the command line args that let the process startup alone.

If you think it's anyway an overkill, then ignore me :)

**Comment by sils1297** [comment]
You've actually convinced me. gedit has the `-s` flag and its cool. Lets do that.

**Comment by sils1297** [comment]
actually git suffers from the same problem, just mentioning

**Comment by sils1297** [comment]
Sublime has subl as commandand goes with --wait

**Comment by AbdealiJK** [comment]
By database, do you mean a full fledged sqlite/sql engine ?
Or a simple file with a dictionary of constants holding which editor should be mapped to what ?

**Comment by sils1297** [comment]
I'd use a default python dictionary, hardcoded, in the OpenEditorAction.py.

**Comment by Makman2** [comment]
Would also be my suggestion. There are not thousands of editors, a full database system is really too much^^

**Comment by AbdealiJK** [comment]
I've attempted to fix it above (you can check it in the reference above)

The way I did it is minimal .. It assumes the user types "subl" (for sublime) with no other flags. So, for example if a user types "subl -n" as the input to coala, it will not automatically add the "--wait" flag.
The solution i can think of is to take the first word (i.e. split by space) and compare that.

But, if users use a prefix before it ... for example : `env WINEPREFIX="~/.wine32" notepad` it again won't work. So, the solution to this would be to search all words and not just the first word.

But (again) then, we could have editor clashes ... if 1 editor has a very common name and is used as an argument in another editor, this again it will give errors.

Any suggestions on nice, neat way of fixing this ? Any clue about how git does it ?

**Comment by Makman2** [comment]
At first glance I think when the user inputs himself command line args, he wants to override the default ones. So not trying to append our flags is then alright. Especially when I see your complex `env WINEPREFIX="/.wine32" notepad` example, I would suggest that you want to do something special where coala shouldn't interfere.
So I would keep your solution as it is (I need to see through it detailed, I just saw roughly the list in there :P) and maybe just add whitespace-trimming features (if you don't have it already).
There are already ideas (and I think also an issue, but don't know where :| ) to pass the editor you want to use via command line and then coala doesn't need to ask you again. Especially when it comes to configuring the standard editor in a default coafile the user can himself add the right flags to work properly.

**Comment by AbdealiJK** [comment]
The whitespace trimming is ther, so, cool - i guess it's good to go.
Will send a pull request.

**Comment by Makman2** [comment]
PS: Git doesn't do it. If you invoke for example (I tested it) gedit and it's already open for a commit, git exits instantly and says "no commit message specified, aborting".

**Comment by Makman2** [comment]
PS2: But you can specify the needed flags via `git config --global core.editor "gedit -s"`.

**Comment by sils1297** [comment]
yeah, so we'll need to do better than git

**Comment by Makman2** [comment]
If you do it, then do it right :P

**Comment by AbdealiJK** [comment]
As I am unable to apply labels, I am writing it here : pending review #322
