### ISSUE TITLE
Improve help text

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#279]
I would improve the help text for `-s`/`--save` and `-c`/`--config` to know how coala actually stores files.
Now the help text is
```
-s [FILE], --save [FILE]
    Filename of file to be saved to, defaults to config file
-c [FILE] [FILE...], --config [FILE] [FILE...]
    Configuration file to be used
```
I would write (as much as I know):
```
-s [FILE], --save [FILE]
    Filename of file to be saved to. When not specifying a file and --config/-c
    is not provided, defaults to './.coafile'. If --config/-c is provided the file is saved
    to the one specified with this argument.
-c [FILE] [FILE...], --config [FILE] [FILE...]
    Configuration file to be used. Executes each specified separately.
    If no file is specified './.coafile' is used.
```
Maybe the text for `-s` is a bit redundant, but I hope you get the idea.

**Comment by sils1297** [comment]
please look also at #280

**Comment by sils1297** [comment]
Please take a look at those commits and see if they fix the issue for you.

**Comment by Makman2** [comment]
If the `-c` argument anyways takes only one **[FILE]**, the help message for it is okay.
But I would improve `-s` a bit more. See the commit there^^

**Comment by sils1297** [comment]
Please let's discuss this here, I'd be happy to change the message if you can come up with a better one that is not (much) longer than this one.

**Comment by Makman2** [comment]
Sorry for being a time absent.
I would modify your help text for `-s` like this:
```python
SAVE_HELP = _('Filename of file to be saved to. If provided with no '
              'arguments, settings will be stored back to the config file'
              'specified from -c. If -c is also not specified, settings will be stored'
              'in \'./.coafile\'.')
```
So in fact it should look like this:
```
Filename of the file to be saved to. If provided with no arguments, settings will be
stored back to the config file specified from -c. If -c is also not specified, settings
will be stored in './.coafile'.
```

**Comment by sils1297** [comment]
How about omitting the last sentence? We specify at the -c help text that
it defaults to .coafile.
Am 18.02.2015 16:13 schrieb "Makman2" <notifications@github.com>:

**Comment by sils1297** [comment]
check out the new text in that commit

**Comment by Makman2** [comment]
You don't want to say a word about *./.coafile* heh? But okay, I think it suffices to mention the -c flag.

**Comment by sils1297** [comment]
Too long. Help text needs to be short and precise.

2015-02-18 16:48 GMT+01:00 Makman2 <notifications@github.com>:
