### ISSUE TITLE
Ctrl+C takes long to quit

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#282]
Currently we wait for all bears to finish if Ctrl+C is pressed. Would be better to communicate with them and make them quit early.

**Comment by sils1297** [comment]
This involves:

- [ ] Research on cancellables
- [ ] Using cancellables whereever needed
- [ ] Handle cancellables and KeyboardInterrupt in some methods

**Comment by Udayan12167** [comment]
Would like to add make BearRunner asynchronous to this.

**Comment by sils1297** [comment]
Could you put this at another bug and place a reference here? I'll set the
blocked label then.
Am 14.03.2015 14:02 schrieb "Udayan12167" <notifications@github.com>:

**Comment by Udayan12167** [comment]
Are we using multiple threads to run multiple bears at the same time

**Comment by sils1297** [comment]
No. We actually use multiple processes.
Am 14.03.2015 14:26 schrieb "Udayan12167" <notifications@github.com>:

**Comment by sils1297** [comment]
A BearRunner is one worker process. Worker processes take the next bear and
execute it. SectionExecutor coordinates everything and interfaces to the
interactors. (Especially the section executor is a very interesting part
for the delinearization of coala btw.)
Am 14.03.2015 17:18 schrieb "Lasse Schuirmann" <lasse.schuirmann@gmail.com>:

**Comment by sils1297** [comment]
tied to GUI which will not be included in next release.

**Comment by sils1297** [comment]
@Udayan12167 how's progress going on this?

**Comment by Makman2** [comment]
I think this is related to #915 since we don't have a real quitting model implemented^^

**Comment by Makman2** [comment]
@sils1297 would close this in favor of #915 and #933.
