### ISSUE TITLE
Add option to skip to next issue.

### ISSUE THREAD

**Issue by sims1253** [coala-analyzer/coala#286]
At the moment you can only open an editor or aplly the patch automatically. How about the possibility to just skip to the next issue.

**Comment by sims1253** [comment]
I should read

**Comment by sils1297** [comment]
I'd be happy to accept proposals on how we can make the text clearer.

**Comment by sims1253** [comment]
maybe just add the 0 option to the list below so it is not over-read easily

**Comment by sils1297** [comment]
This is what we had before but then we received a bug report: #271
