### ISSUE TITLE
align documentation comments

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#299]
needs specification and implementation

**Comment by sils1297** [comment]
We currently do:
```
:param something: A very
long line
```
and we want:
```
:param something: A very
                  long line
```

- [ ] Specify in CODESTYLE.md
- [ ] Make sure its aligned everywhere, we can do that on the fly when reformatting this and that.

**Comment by AbdealiJK** [comment]
I've done a search for `:param` and gone through the files with them - I *may* have missed one or two ... but there arent any doc comments I found with the old codestyle.

The commit : https://github.com/coala-analyzer/coala/commit/c4074240dfeac9641a5d37c3769621e98ad839b0  adds the rule to our codestyle.

So, closing this - If you ever find any comment with old codestyle when doing something else - do change it

**Comment by sils1297** [comment]
very good, thanks!

2015-07-14 16:48 GMT+02:00 AbdealiJK <notifications@github.com>:
