### ISSUE TITLE
Bear: Rename run_bear to run

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#303]
And rename he run method to something else. After all run is a more intuitive name for the bear writer than run_bear

**Comment by Udayan12167** [comment]
Im working on this bug and have fixed it with the run_ bear method named as run and the run method renamed to run_main.

**Comment by Udayan12167** [comment]
Just check out the final version

**Comment by Udayan12167** [comment]
Have a look now

**Comment by Udayan12167** [comment]
I think the commit message is fixed now.
