### ISSUE TITLE
Temporary file when opening editor

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#305]
We should mention somewhere that we're giving the user a temporary file only in the OpenEditorAction

**Comment by sils1297** [comment]
or maybe let him use the real file instead...

**Comment by Makman2** [comment]
I'm not sure about this either. But with temporary files you have the ability to perform magic stuff (like patching etc.) because you don't update the real file and have two copies of them: The modified one and the original one.
I would keep the temporary files and mention it somewhere.

**Comment by sils1297** [comment]
well we could perform magic stuff also with the real file because we can keep the original one in memory.

**Comment by sils1297** [comment]
having a notice to the user is a good first step.

**Comment by AbdealiJK** [comment]
If a file is huge, we cannot keep it in memory - may cause issues ?  
What we can do is make a backup of it in a temporary location, and give the user the original one to edit.
Then do a diff with the temporary file created.

**Comment by sils1297** [comment]
> If a file is huge, we cannot keep it in memory - may cause issues ?

Usually text files arent very big. If they grow bigger its likely the editor isnt able to handle the file anyway. In times where every PC has at least 1GB of memory (plus swap space) keeping text files in memory shouldnt be an issue.

Making a backup is a good idea, independently from the OpenEditorAction. I've filed #326 for that.

**Comment by AbdealiJK** [comment]
Ok, I am a bit lost.
So, do we do anything other than the message mentioning that this is a
temporary file ?

**Comment by Makman2** [comment]
> well we could perform magic stuff also with the real file because we can keep the original one in memory.

Yes that's right but if our program crashes this is really bad. Then the original one is lost. Better keep the old version than the coala patched one. But maybe #326 handles this^^

**Comment by sils1297** [comment]
no, #326 is something else, sorry @AbdealiJK this is getting a bit confusing now. I'm trying to summarize:

 * Backup is completely handled by #326 
 * The openeditoraction:
   * Saves the current file into the target file
   * Let the user edit it (as before) 
   * Get the diff (as before)

I think this is the most intuitive behaviour. The finalize method of the interactor won't notice file changes in the original file so it doesnt matter how we leave the file basically ;)

**Comment by sils1297** [comment]
revoking first sentence of last comment, backup is fully handled by #326

**Comment by Makman2** [comment]
Now I'm confused... xD
What handles now what? oO
Is this issue now covered from #326?

**Comment by sils1297** [comment]
Great... for now we get a better message ;)

2015-02-23 20:02 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by sils1297** [comment]
getting really confusing, I'll open another bug
