### ISSUE TITLE
Editor opened by coala is in German

### ISSUE THREAD

**Issue by ankitstarski** [coala-analyzer/coala#306]
During `Coala`'s checks if it encounter inconsistencies, it prompt you to apply a fix or edit in a editor.
I chose editor, then it prompts for the name of editor; I entered `gedit`:
It opens a `gedit` window, but in German language, which is not my locale.
![screenshot from 2015-02-21 01 11 46](https://cloud.githubusercontent.com/assets/3841578/6308399/163d3310-b96a-11e4-9bdf-7cd800d47505.png)

**Comment by sils1297** [comment]
we do `os.system(editor + " " + tempname)` so i dont see how locale gets changed

**Comment by sils1297** [comment]
some locale was set in the main routine which was forgotten
