### ISSUE TITLE
BracketBear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#310]
Would be nice to have a bear that checks if brackets are aligned:
```
while something {
```
vs.
```
while something
{
```

**Comment by Udayan12167** [comment]
Couldi get a better explanation. Does this mean that the bracket should always be in a seperate line?

**Comment by sils1297** [comment]
No, the bear would request a setting from coala so the user can decide how he wants his brackets aligned.

**Comment by sils1297** [comment]
needs solving of #250 first in order to do it appropriately and not again and again for each language.

**Comment by sils1297** [comment]
#250 is in review and work can be build upon that

**Comment by Makman2** [comment]
Would reference #403

**Comment by sils1297** [comment]
this is a part of #403

**Comment by sils1297** [comment]
not happening soon, focusing on https://github.com/coala-analyzer/coala/issues/897
