### ISSUE TITLE
OpenEditorAction discards line additions

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#316]
I was trying the coala-tutorial, and had some problems when i came across the makefile part :  
`coala -S Makefiles.bears=LineLengthBear Makefiles.files=Makefile --save`

So, coala asked me to edit the file (as expected) and then asked for my editor:
 1. When I put `subl` for the sublime text editor, it opened a temporary file and it was blank. I had no clue what to do.
 2. When I put `vim` it opened a temporary file with the content of the Makefile in it. I edited the file by splitting the comment (which was >80 char) into 2 different lines. Saved it, and quit. On checking my Makefile, it seems coala had deleted my second comment and left only the first comment.

**Comment by sils1297** [comment]
Hi, the first thing is a known bug, please use `subl --wait`as command.

**Comment by sils1297** [comment]
Editing with vim should work indeed, I'll investigate this further - thanks for the report!

**Comment by AbdealiJK** [comment]
So, I used `subl --wait` and I could open the file successfully.

With `subl --wait` : I got the same problem as I got in vim. If I split 1
line into 3 lines, it would only save the first line

**Comment by sils1297** [comment]
Yeah, that's #278 then.

**Comment by sils1297** [comment]
I can confirm that the second thing is an issue, sadly.

**Comment by sils1297** [comment]
Minimal testcase in DiffTest.py:
```
    def test_from_string_arrays(self):
        a = ["q", "a", "b", "x", "c", "d"]
        b = ["a", "b", "y", "c", "d", "f"]
        self.uut = Diff.from_string_arrays(a, b)
        self.assertEqual(self.uut.apply(a), b)

        a = ["first", "third"]
        b = ["first_changed", "second", "third"]
        self.uut = Diff.from_string_arrays(a, b)
        self.assertEqual(self.uut.apply(a), b)
```

**Comment by sils1297** [comment]
seems to occur when the first line gets changed and a second one gets added.

**Comment by sils1297** [comment]
Bug is in Diff.py, from_string_arrays. We do `matcher.get_grouped_opcodes(1)` and assume that each change group affects only one line in the origin and target file, however it may replace one line with two others in the target group. Other potential bug is addition of several lines and to be tested.

**Comment by sils1297** [comment]
or deletion of several lines.

**Comment by sils1297** [comment]
I think I've covered all cases now, @AbdealiJK could you do some testing on this branch?
