### ISSUE TITLE
User settings

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#317]
Would be nice if we had a settings file for user settings. E.g. some users want a GUI, some maybe not so this shouldn't be defined per project.

Some .coarc in user directory maybe?

Maybe we should think about having systemwide settings too...

**Comment by sils1297** [comment]
We kind of have system wide settings with our default_coafile which is great IMO. Let's do user settings as an intermediate level.

**Comment by Makman2** [comment]
That's a good idea.
Maybe add another layer above *default_coafile* to have custom system settings and keep the *dafult_coafile* as it is.

**Comment by sils1297** [comment]
Exactly.

**Comment by sils1297** [comment]
needs #332 first

**Comment by sils1297** [comment]
Ready to be implemented!

 * [ ] Add `~/.coarc` to StringConstants as USER_COARC
 * [ ] Parse and merge it in SectionManager
