### ISSUE TITLE
Special keys during input in terminal

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#320]
While trying to give an optionon the action or while giving the name of the text editor to open the file with, if I try to press the left arrow key or other special character keys, it gives the ascii characters.

So, for example if I type : `subk --wait` and try going to the left to edit it, it gives : `subk --wait^[[D^[[D`

PS : Not sure if this is because of the type of terminal, etc that I am using.

**Comment by sils1297** [comment]
I'm having the same issue on gnome terminal with zsh shell.

Reading http://ubuntuforums.org/showthread.php?t=1658534&p=10309613#post10309613 this should be easy to fix.
