### ISSUE TITLE
ConflictError : When editing a line in text editor

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#321]
Way to recreate :
 - Let's say I have 2 errors in my program and I run coala
 - I open the editor to fix the first issue and notice the second issue and fix that too.
 - Coala will tell that it found a second issue on that line
 - If the "fix it for me"action is chosen, an error is thrown

```
coalib.results.Diff.ConflictError: An already changed line cannot be changed.
```

**Comment by sils1297** [comment]
Well those fixes aren't mergable. I suppose it would be the best to offer
the user some options e.g. to discard one of the conflicting patches
Am 22.02.2015 16:05 schrieb "AbdealiJK" <notifications@github.com>:

**Comment by sils1297** [comment]
ah this is a duplication of #491 which is a bit clearer so I'm keeping that one open.
