### ISSUE TITLE
Giving -c with a directory yields an exception

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#323]
Try: `coala -c /some/directory/`

**Comment by sils1297** [comment]
Better handling would be:

 * Use .coafile in that directory if it exists
 * If the given file or no coafile in that directory exists, log it as an error and continue without using the coafile.

**Comment by Makman2** [comment]
Agree^^

**Comment by AbdealiJK** [comment]
Can you assign this to me ?

Also, what did you mean by log as an error ? How do I do that ?

**Comment by sils1297** [comment]
there is a log_printer member usually everywhere around (and bears have their own logging methods but in the end a LogPrinter gets it) that has a fail() or error() method or so.
