### ISSUE TITLE
StringConverter: Support dictionary conversion

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#325]
DIctionaries are a standard type used often and we should be able to coonvert into that.

**Comment by sils1297** [comment]
needs #160

**Comment by sils1297** [comment]
blocked by #405

**Comment by sils1297** [comment]
how's that:

```
lasse@lssteadarch ~/prog/coala (git)-[wip/sils/cc] % python3
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from coalib.misc.StringConverter import StringConverter
>>> lst = StringConverter("a,b,c")
>>> dct = StringConverter("a:b,c,d")
>>> list(dct)
[('a', 'b'), ('c', ''), ('d', '')]
>>> dict(dct)
{'c': '', 'd': '', 'a': 'b'}
>>> list(lst)
['a', 'b', 'c']
>>> dict(lst)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: dictionary update sequence element #0 has length 1; 2 is required
>>> 
```

**Comment by Makman2** [comment]
That's a really nice and convenient feature, :+1:

**Comment by sils1297** [comment]
so users get an exception if a bear wants a dict and the input is not dict-able. Plus if a bear wants a list and the user inputs a dict he'll get a strange list and needs to care about this... this is not ideal IMO...

**Comment by Makman2** [comment]
1. The user is responsible for this imo
2. If bears result in strange result then, I would then place a type-condition^^

**Comment by sils1297** [comment]
wouldn't it be nicer that we get him a normal list ignoring colons if he wants a list and get him a dict or an exception if he wants a dict? I'm not sure yet how this is realizable technically, so far the only way I've come up to convert it into a dict is via the iterator which is also used for the list...

**Comment by smfn3321** [comment]
Sorry I don't have time right now since we have guests, but I don't agree with:
```>>> list(dct) 
[('a', 'b'), ('c', ''), ('d', '')]```
especially if compared with
```
>>> list(lst) 
['a', 'b', 'c']```

I think this is what Lasse means. Leave the List alone as much as possible please. If we define List as "comma separated values", we should allow all non-comma characters (and escaped commas) in the string and the list.

**Comment by sils1297** [comment]
I don't see the alternative happening from a technical standpoint. Only way
to do that *may* be deriving StringConverter from a dict itself and then
alter the iter method... NOT nice.

2015-05-02 18:29 GMT+02:00 Fabian Neuschmidt <notifications@github.com>:

**Comment by sils1297** [comment]
just for the record, this would be a prototype implementation, while not escaped lists/dict make a big headache... http://pastebin.com/q1hP0LCY

**Comment by Makman2** [comment]
Where's the problem with two functions: `to_dict` / `to_list`?

**Comment by sils1297** [comment]
@Makman2 bears couldn't just write `some_param: dict` but they had to import our conversion function. Would be a solution but usability could be better...

**Comment by sils1297** [comment]
because the `dict` object, i.e. whatever is after the colon, will be applied as a function to the StringConverter object. So best would be if we could *be* something so the dict function thinks we're a dict and doesnt use iter but something else and the list function just uses iter as before.

**Comment by Makman2** [comment]
But using the two functions would enforce to interprete the string as a dict and not a list. Then the user knows instantly that he typed something wrong

**Comment by sils1297** [comment]
I think I found a way...

**Comment by smfn3321** [comment]
@sils1297 I'm interested in your solution :D
You would have to *be* a lot of things to make the `dict()` and `list()` functions like you

**Comment by sils1297** [comment]
@smfn3321 I am too... I lost it while trying to refine it. But after returning an iterator of a dict both conversions worked... something like that...

**Comment by smfn3321** [comment]
dict or dict.items... I'm thinking about it, but I did not yet find anything realy convincing

**Comment by sils1297** [comment]
```
>>> class t:
...  def keys(self):
...   return {1:2,3:4}.keys()
...  def values(self):
...   return {1:2,3:4}.values()
...  def __getitem__(self, key):
...   return {1:2,3:4}.__getitem__(key)
...  def __iter__(self):
...   return iter([1,3])
... 
>>> 
>>> g = t()
>>> dict(g)
{1: 2, 3: 4}
>>> list(g)
[1, 3]
>>> 
```

**Comment by smfn3321** [comment]
Oh, so `dict()` doesn't even use `iter()` if it doesn't have to? neat!

**Comment by sils1297** [comment]
well otherwise `dict({1:2})` wouldn't be possible

**Comment by sils1297** [comment]
Done in the referenced commit! :)
