### ISSUE TITLE
Config variable to decide where to store the temp files

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#327]
It may be a good idea to have a config variable which decides whether to save the orig and tmp files created by coala. In /tmp or just beside the file (How vim's .sw* works)

**Comment by sils1297** [comment]
For the OpenEditorAction?

**Comment by sils1297** [comment]
Can you provide a usecase? I cant think any situation where I'd want to influence this.

**Comment by AbdealiJK** [comment]
It's a personal preference. 

So, many a times I do something horrible in vim (being the complicated tool it is for a gui person like me), have no idea how to get back my original data, and am forced to do a ctrl+c or close the terminal :P

And I get my earlier data from the sw* file which is stored near the file I was trying to edit.

Ideally, coala should be easy enough to use that this is not needed ... but it's always better to keep it.

**Comment by Makman2** [comment]
If you want move them from the low-space SSD to the HDD (for example).
But maybe something like a "working-directory" is better in this case^^ That influences all file processes^^

**Comment by sils1297** [comment]
> If you want move them from the low-space SSD to the HDD (for example).
We usually work with files <1KB.

**Comment by Makman2** [comment]
Okay then the other way around: You have a HDD that you don't use so much, but the temporary files are stored there. But if coala wants to access them, the HDD needs to spin up, that needs time and also for laptops this costs energy.
(That's the case with my laptop, I need to fix this sometimes. The energy cost is not the problem but the spin up time goes on my nerves...)

**Comment by sils1297** [comment]
Then you swap out your /tmp directory because thats where all temporary
files lie.

2015-02-23 20:01 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
That's a thing, never mind.

**Comment by sils1297** [comment]
@AbdealiJK our temporary files are stored with all the other temporary files and when you get your editor you see the location. Thus I don't see the need for such a setting.

**Comment by AbdealiJK** [comment]
Makes sense. As we can't find any good use case, let's close this
