### ISSUE TITLE
Codestyle: Binary and unary operators

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#328]
Like in [CE3D](https://github.com/Makman2/CE3D) I would suggest the same rules for binary and unary operators:
> Unary operators (for example &, *, -> and ++) don't have spaces between their associated expressions:
> ```cpp
>  int& var; // OK.
>  int & var2; // Not OK.
>  int const& var3; // OK again.
>  int & const var4; // Redundant and not OK.
>  
>  int* pointer;
>  var = * pointer; // Not OK.
>  var2 = *pointer; // OK.
>  var3 = &(*pointer); // Also OK.
>
>  Foo x;
>  x->func(); // OK.
>  x -> func(); // Not OK.
>
>  int i;
>  i++; // OK.
>  i ++; // Not OK.
>  ```

For binary operators use a space between their associated expression (interestingly CE3D has no rule explicitly for this :O).

**Comment by Makman2** [comment]
Opened issue in CE3D # 173

**Comment by AbdealiJK** [comment]
There are guides in pep8 for binary and unary operators, and scrutinizer checks it too.
So, these are already encompassed in pep8 : https://www.python.org/dev/peps/pep-0008/

**Comment by sils1297** [comment]
To be more exact: https://www.python.org/dev/peps/pep-0008/#other-recommendations

So in some cases we probably don't want that space (e.g. for function parameter defaults)

**Comment by sils1297** [comment]
Uhm we have that?
Am 26.07.2015 3:25 vorm. schrieb "Makman2" <notifications@github.com>:

**Comment by Makman2** [comment]
Since @AbdealiJK stated that this rule is covered from PEP8, and since we behave also different from case to case, I think we don't need this rule for now^^

**Comment by sils1297** [comment]
Ok :)
Am 26.07.2015 9:44 nachm. schrieb "Makman2" <notifications@github.com>:
