### ISSUE TITLE
SpaceAroundBear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#329]
Thats two very simple bears that can be used to force having spaces around operators. As argument they take two well named list of strings (one for which spaces shall be around, one for which no spaces shall be around) and whenever one of those strings occurs in the code the bear shall check if there are (no) spaces around the string.

If the given criteria does not match, the bear shall provide a patchresult fixing the issue.

**Comment by shivanipoddariiith** [comment]
@AbdealiJK still on this one ? I've written some code on these lines earlier, could help you out with it if you are up for it :)

**Comment by AbdealiJK** [comment]
I'm a bit busy right now (and will be busy until ~Saturday).
@shivanipoddariiith - Do you want to take the issue up ?

**Comment by shivanipoddariiith** [comment]
@AbdealiJK Yes, working on the HTML printer, post that we could work on it together too (if you get free by then, else I'll take it up :) )

**Comment by sils1297** [comment]
@AbdealiJK how's it going?

**Comment by sils1297** [comment]
not happening soon, for now we're focusing on integrations with others.
