### ISSUE TITLE
Make ResultAction settings settable from config files

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#330]

**Comment by sils1297** [comment]
Shouldn't be that hard, since it's a section anyway.

**Comment by AhmedKamal1432** [comment]
@sils1297  I still little confusing , what is the repeated information that the user enter and we should save it ? or invoke it ?

**Comment by sils1297** [comment]
The result actions currently get invoked by the Interactor class. Some of them require some settings which can be given via a section. (E.g. the OpenEditorAction needs the "editor".)

### Currently...

...we are asking the user, pack the values into a section and give it to the action.

### In the future...

...we want to retrieve the settings from the section we're currently working on. (Probably best to get that into a current_section member when invoking `begin_section()`) If no settings exist, we want to add them. This way the user can write them to the config file if needed.
