### ISSUE TITLE
Make default_coafile editable

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#332]
Currently we require a few things from the default_coafile. They are unneeded restrictions. So here's the todo:

 * [x] Remove restriction that it has to exist.
 * [x] Let it be empty if it is
 * [x] Parse not only default but all sections

**Comment by Makman2** [comment]
Do you mean to make it modifiable by user? If so why don't create an extra layer of coafiles for this purpose like I suggested in #317? If the user breaks something in his file he could then relay on the default one. Or do I misunderstand something?

**Comment by sils1297** [comment]
Basically the idea is to not rely on that default_coafile anymore and
providing it to the user as a system configuration.

2015-02-24 19:27 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Ah okay. But where to save the system default settings? directly in code?

**Comment by sils1297** [comment]
What do you mean by saving system default settings? It's a system config
file, I wouldn't provide a way to alter it despite manual editing.

2015-02-24 20:06 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Okay I think I misunderstand the system a bit, but I think you have nearly the same thing in mind like me. Ignore me :)

**Comment by Udayan12167** [comment]
So whatever is given in the default_coafile. The user should be able to provide that?

**Comment by Udayan12167** [comment]
Do we want the user to make one .coafile and use the default settings from that or we want the user to make both the default_coafile and the .coafile?

**Comment by sils1297** [comment]
We want to:
 * Ship with a default default_coafile
 * Let the user edit the default_coafile
 * Use the default_coafile as before. (Maybe rename it to make it clearer it's a global configuration for coala)

**Comment by sils1297** [comment]
Is this better? Many things are currently getting a bit confusing. Sorry for not being clear in the beginning.

**Comment by Udayan12167** [comment]
Yeah this is better. Do you want to provide a command line option in coala which opens the default_coafile for editing ?

**Comment by sils1297** [comment]
No. Usually if users want to alter those files they do that themselves. If they want to let coala do that they can use the -c argument.

**Comment by sils1297** [comment]
Udayan, are you planning to work on this? Could please let me know if you work on something? Otherwise I may do conflicting things.

**Comment by Udayan12167** [comment]
Yeah i am

**Comment by sils1297** [comment]
Marking as important because some other changes depend on it and will be on hold as long as this one's in progress.

**Comment by sils1297** [comment]
Thanks, thats a good one.

**Comment by Udayan12167** [comment]
So basically we change the default_coafile to something like : 
[Default]
Some settings...

And then in the sectionmanager.py we parse it as a normal .coafile instead of just taking the default section.

**Comment by sils1297** [comment]
No need to change the default_coafile. The [default] is implicitly assumed for every coafile.

Second point is true. It will need special handling though because the default_coafile will then hold defaults for all sections. Makes it a bit tricky.

**Comment by Udayan12167** [comment]
Oh, much clearer now. :)

**Comment by Udayan12167** [comment]
So if input is taken through command line, if i understand the code correctly there is only one default section created?

**Comment by sils1297** [comment]
I took the freedom and did the first part (allowing empty default_coafile) because it wasn't in your plan, if you did it too, we can reject the commit anyway and take yours.

**Comment by Udayan12167** [comment]
So if there is no default_coafile should we still exit saying the installation is broken or an empty file is required?

**Comment by sils1297** [comment]
On long term we just want to throw a warning in that case. It's your
decision if you do that or not. If you don't I'll do later.

2015-03-02 12:10 GMT+01:00 Udayan12167 <notifications@github.com>:
