### ISSUE TITLE
"./execute_all_tests.py" command doesnot execute test files 

### ISSUE THREAD

**Issue by AhmedKamal1432** [coala-analyzer/coala#334]
"Run our tests. Just execute `./execute_all_tests.py`" 
in "doc/getting_involved/README.md" and "doc/getting_involved/TESTING.md" files 

when run it this message appear "bash: ./execute_all_tests.py: No such file or directory"

but there is no file with this name (I think it should be ./run_tests.py)

**Comment by sils1297** [comment]
Oh, yeah, thanks! Missed documentation correction.

2015-02-24 12:36 GMT+01:00 AhmedKamal1432 <notifications@github.com>:
