### ISSUE TITLE
PyLint bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#335]
A bear that invokes pylint on the file and converts the results into coala results.

Shouldn't be too hard.

**Comment by sils1297** [comment]
Would be good to also expose some settings, at least optional.

**Comment by Udayan12167** [comment]
The settings for Pylint you mean?

**Comment by sils1297** [comment]
Yes.
Am 25.02.2015 06:32 schrieb "Udayan12167" <notifications@github.com>:

**Comment by Udayan12167** [comment]
So how do we provide these options to the bear? Right now i dont see anything in the sectionmanager.py to provide options to a bear?

**Comment by sils1297** [comment]
No, Bears aren't using SectionManager. Did you read WRITING_BEARS.md? All needed from coala side to do this is explained there. You'd then in the bear routine get results from pylint and return them as coala Results.

**Comment by Udayan12167** [comment]
So we ask the user for user input. Wouldnt it be better if the user could provide options for bears in the .coafile itself?

**Comment by sils1297** [comment]
> Wouldnt it be better if the user could provide options for bears in the .coafile itself?

He can. If you did the TUTORIAL you probably saw that coala saves those values into the .coafile if invoked with the -s argument and doesn't ask next time.

**Comment by AbdealiJK** [comment]
I have a windows computer temporarily and tried this.
The error is because `parts` in the Pylintbear's `parse_line()` is hardcoded with the 2nd element being the error message.
The value or parts in windows:
```
[' C', '\\..........................\\bears\\tests\\linters\\test_files\\pylint_test.py', '8', ' error (E0211, no-method-argument, Something.method_without_self) Method has no argument\n']
```

It seems as though python on windows uses `:` from C: as a delimiter - hence the problem
The original line was:
```
C:\...................\bears\tests\linters\test_files\pylint_test.py:8: error (E0211, no-method-argument,
Something.method_without_self) Method has no argument
```

**Comment by sils1297** [comment]
@AbdealiJK many thanks, I'll try to fix that with that info now.

**Comment by sils1297** [comment]
@AbdealiJK @Makman2 there seems to be another problem...

**Comment by sils1297** [comment]
at least on appveyor I still get no results
