### ISSUE TITLE
Invalid default coafile

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#336]
In https://github.com/coala-analyzer/coala/commit/d7fef4621bd27d9fb5224048ce0fa17fb7b26de2#diff-a0e4f723f6df10e75b0dc8fc4e75584dR78
The default coafile written is "./coafile" (file named "coafile" in current directory) which is incorrect. The default file it needs to check should be ".coafile" in the current directory

**Comment by sils1297** [comment]
merged
