### ISSUE TITLE
Editor Plugin - Interactor

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#337]
It would be really easy to use to have a sublime outputter. The way I think it would be is:

While typing code, it would highlight certain regions to show that it is erronous. There is a plugin which does some parts, eg : https://github.com/SublimeText/TrailingSpaces which handles all  trailing spaces.

This could also be helpful, because when a user uses the terminal to run coala, if the user chooses to apply a patch manually using sublime, this plugin could make it very easy to use by highlighting the appropriate areas nicely.

**Comment by Makman2** [comment]
That's a good feature for all editors. But that requires some work to do the highlighting etc properly.
Anyway nice idea :+1:

**Comment by sils1297** [comment]
Depends on #252, in the end this is something similar to an IDE Interactor. The way to do this is very similar in my mind:

1. Write a DBusInteractor that exposes the output api via dbus and simplifies where possible
2. Write a Plugin for the editor

This applies to all editors so I'm renaming this a bit.

**Comment by sils1297** [comment]
Done!
