### ISSUE TITLE
ConfParserTest creates unneeded temporary dir and doesn't tidy up

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#342]
around line 33: `self.nonexistentfile = os.path.join(tempfile.gettempdir(), "e81k7bd98t")`

**Comment by AbdealiJK** [comment]
There is no temporary directory created.
The `tempfile.gettempdir()` command does not create a new temporary directory.
it just returns the temp directory itself (platform independantly)
eg: It gives `/tmp/` in unix

**Comment by sils1297** [comment]
Oh great thanks! sorry my mistak

2015-02-25 13:40 GMT+01:00 AbdealiJK <notifications@github.com>:
