### ISSUE TITLE
Doc: Write guide for test writing

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#349]
Would be nice to have a small document on how to write tests for coala. Whoever does it, take a look at how we write our tests and ask us if anything is unclear.

**Comment by Makman2** [comment]
Since I'm currently writing a test for my string processing function, I'll self assign me :)

**Comment by Makman2** [comment]
Wrote a basic template.
What's missing:
- A little introduction how tests basically work, what should be tested etc.
- A list of possible assertion functions
- Improving the template a bit^^
- IMPORTANT: What concretely the tear-down mechanism does, I don't know how it works^^
  For now I put a todo in the current commit^^

**Comment by sils1297** [comment]
I'll look at it. Thanks
Am 02.03.2015 19:34 schrieb "Makman2" <notifications@github.com>:

**Comment by Makman2** [comment]
Updated it significantly.
The only thing missing is: Do I covered all assert functions? There should be one that asserts whether a function does **not** raise an error.

**Comment by Makman2** [comment]
Eh make a pull request... It's nearly production ready^^

**Comment by AbdealiJK** [comment]
While I was searching earlier, I couldn't find the assert to check if a
function does not throw an error.

Wasn't in docs either (afaik)

**Comment by Makman2** [comment]
Hm maybe our dear @sils1297 has the answer we desire :P

**Comment by Makman2** [comment]
PS: pull request open at #353.

**Comment by sils1297** [comment]
I don't think such a function exists. Never found it too.

2015-03-03 2:45 GMT+01:00 Makman2 <notifications@github.com>:
