### ISSUE TITLE
generate class diagram

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#350]
we should have a possibility to do that.

**Comment by tripleq** [comment]
May you assign me to this?

**Comment by sils1297** [comment]
@tripleq any progress?

**Comment by sils1297** [comment]
hey, just try `pyreverse -o png coalib/bearlib/abstractions coalib/bearlib/__init__.py coalib/bearlib/languages coalib/bearlib/spacing  coalib/bears coalib/collecting coalib/default_coafile coalib/__init__.py coalib/misc coalib/output coalib/parsing coalib/processes coalib/__pycache__ coalib/results coalib/settings coala`

**Comment by sils1297** [comment]
need so many paths because you can't exclude things and we don't want clang and tests in there, right?

**Comment by AbdealiJK** [comment]
yes, that does work (kind of) .. In my opinion, the cleaner (more intuitive) command is : 
```
pyreverse -p coala `find coalib/* -maxdepth 0 -type d ! -name "tests"`
```
But this still gives out some classes which are not necessary ... and there are these unusual orphaned classes, I don't understand how they could exist ... they should be used somewhere right ?

Also, why exactly is clang bindings there in ./coalib/bearlib/parsing/clang ? Shouldn't this be a dependency rather than copy pasting the code here ?

**Comment by AbdealiJK** [comment]
I've attached the images below. Could someone check if these seem correct ?

In the class diagram: 
 - Let's take one particular example. `log_printer` is a variable in SectionManager and it could be ConsolePrinter, FilePrinter or NullPrinter - which is correctly shown in the image. Code reference - `self.log_printer = ConsolePrinter(log_level=log_level)` in SectionManager.
 - Now let's check the relation between Diff and LineDiff. In Diff, the code reference is - `self._changes.get(line_nr, LineDiff())` ... which isn't exactly a direct assignment, but it basically means that LineDiff is a member of Diff. But this isn't shown in the diagram.

Package diagram also has similar issues.

Any ideas on how we can handle this ? Pyreverse seems to have restrictions (and It's supposed to be the most popular one)

Class diagram:
![classes_coala](https://cloud.githubusercontent.com/assets/2200743/7530771/44f713ea-f56c-11e4-8075-bc0921af101a.png)

Package diagram:
![packages_coala](https://cloud.githubusercontent.com/assets/2200743/7530776/4cebbcae-f56c-11e4-9dfb-6da51fc3a4cf.png)

**Comment by sils1297** [comment]
> Also, why exactly is clang bindings there in ./coalib/bearlib/parsing/clang ? Shouldn't this be a dependency rather than copy pasting the code here ?

I think the pypy package is only for python 2 since there are no official python 3 bindings for clang so I imported them. A cleaner solution would probably be making an own package out of the clang python3 bindings... I opened #509 for investigation, thanks for the heads up.

Indeed the relations seem to be incomplete. Also it might be of more use if we would create a smaller diagram for each class (I think epydoc does this). Maybe we should give epydoc a try?

**Comment by AbdealiJK** [comment]
We can create smaller class diagrams with pyreverse too, just have to run
multiple commands individually.
Anyway, I'll try out epydoc too.

This also brings up another question - what's the final aim of making this
? Do we put it in docs ? or will it be saved somewhere ? (I've seen
integration with sphinx, but integration with rtfd - not sure yet)

**Comment by sils1297** [comment]
I'm not sure what exactly we want. I don't think a generated documentation is really that helpful... maybe we end up with a small script that just generates those diagrams for devs? If we want I'm sure we can get that integrated into readthedocs...

**Comment by sils1297** [comment]
What do you want?

**Comment by AbdealiJK** [comment]
I just wanted it as a reference, the full diagram is sufficient for me.

**Comment by AbdealiJK** [comment]
Ok. So, by "integrating into readthedocs" what did you mean ?
We don't have a class by class documentation there, so can't make smaller UML diagrams for each class - no particular place they would fit.  
I went through a lot fo things related to `mkdocs` - the documentation generator we use. It doesnt have any plugin per se for UML. We could make an image and show it in readthedocs.

**Comment by sils1297** [comment]
Yeah, I was thinking about generating the image as a build step i readthedocs and put that on some page. No UML or class docs.

**Comment by AbdealiJK** [comment]
I generated a cleaner version of the packages class ... but it's still pretty difficult to read.
Any suggestions on how to make it readable - theres no point in keeping this in docs other than decoration

![packages_coala coala](https://cloud.githubusercontent.com/assets/2200743/8423445/e31cb336-1f06-11e5-82ae-765a39398910.jpg)

**Comment by sils1297** [comment]
@AbdealiJK what would you suggest? I personally don't need a class diagram, if someone does what we have here will probably not help, right? Would you spend more time on creating something cooler or rather drop it as wontfix for now?

**Comment by AbdealiJK** [comment]
I'd rather drop it as a wontfix - as I don't know myself what can be done
