### ISSUE TITLE
Define error codes for exiting

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#351]
Since we only exit with 2-3 error codes I would introduce a finer-graded scale, for example:
- `0`: successful
- `1`: error / yielded results
- `2`-`127`: other logic errors (so they are defined by the programming logic, not exceptions)
- `-128`: unknown error/exception
- `-1`-`-127`: Any other **known** error (like the keyboard interrupt)

**Comment by sils1297** [comment]
- [ ] Write a definition of this down so users have something they can look at
- [ ] change retvals

**Comment by sils1297** [comment]
http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by Makman2** [comment]
Perfect, let's use this

**Comment by sils1297** [comment]
anyone interested in working out a spec?

This should include:

 * What we return in which case (e.g. if we get an invalid glob we can't continue)
 * What exception we use internally to communicate that

**Comment by sils1297** [comment]
- [ ] add a markdown documentation file with retval specification under `doc/`
- [ ] add it to `mkdocs.yml`

**Comment by Udayan12167** [comment]
So a little more information on what the documentation file contains.
I see three error codes as of now 0,1 and 255.

**Comment by Udayan12167** [comment]
Here is a list of the exits i have found and there current exit codes in coala:
- 1 : Succesful results are yielded.
- 255 : Keyboard Import
- -1 : Invalid pattern given to icollect in collector.
- 255 : Any other exception
- Unknown : argparse (Working on it.)

**Comment by Udayan12167** [comment]
Here is a list of the exits i have found and there current exit codes in coala:
- 1 : Succesful results are yielded.
- 255 : Keyboard Interrupt 
- -1 : Invalid pattern given to icollect in collector.
- 255 : Any other exception
- Unknown : argparse (Working on it.)

**Comment by sils1297** [comment]
I suppose we want to change KeyboardInterrupt to 130 according to http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by Udayan12167** [comment]
Yeah i was just figuring out what all error codes to change.

**Comment by Udayan12167** [comment]
Proposal :
Default value is -1. 
- 0 : Succesful results yielded.
- 130 : Keyboard Interrupt
- 1 : Any other exception
- 2 : Argparse bad usage of parameters
- 255( which is technically similar to -1) : For invalid pattern in collectors.
