### ISSUE TITLE
Linting Coala code with Pylint

### ISSUE THREAD

**Issue by tripleq** [coala-analyzer/coala#354]
It's nice to have tool for developers

**Comment by sils1297** [comment]
@smfn3321 already linted coala once, it's probably not more than a command and maybe a config.

**Comment by tripleq** [comment]
Problem is that on almost every module we get  "Missing module docstring" error and it's not possible to turn that error off in config file. If you want to turn off that error you have to disable whole C0111 and i don't think that is acceptable.

**Comment by sils1297** [comment]
What does C0111 contain?

**Comment by tripleq** [comment]
Only doc string warnings but if i disable it i we wont get any doc string warnings, not even in methods or classes. Is that ok?

**Comment by sils1297** [comment]
I think it is ok for now.

**Comment by sils1297** [comment]
On long term we'll probably want to have everything documented.

**Comment by sils1297** [comment]
@tripleq any progress?

**Comment by sils1297** [comment]
`pylint coalib` does the job. We should look at those results.

**Comment by AbdealiJK** [comment]
1 Major issue is that pylint doesn't understand our enum. Opened https://bitbucket.org/logilab/pylint/issue/576/another-enum-issue for that

**Comment by sils1297** [comment]
I think this bug is superfluous by now, we have the PyLintBear in the works and as soon as this is finished we'll want to autopylint coala in our CI.
