### ISSUE TITLE
Tidy up repository root

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#355]
Currently we have a very chaotic repository root directory. There's several scripts (content generation, tests, setup...), some documentation content (TUTORIAL), and so on.

Let's fix that. So goal here is to restructurize this a bit. I'm open for ideas!

**Comment by Makman2** [comment]
First I wouldn't have a coalib directory, coalib is a core as well as the bears. So first idea:
- Make a coala source folder (naming *coala* or *src*), put the *bears* into it and all subdirectories from *coalib*

**Comment by sils1297** [comment]
I however like the distinction of coalib (coala internal libraries, usable
by everyone), bears (modules) and the coala executable.

2015-03-03 18:53 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
okay makes sense, thought that was a sudden splitup during the development^^

**Comment by sims1253** [comment]
How about this:

**root:**
-readme
-install
-setup
**bears:**
**coalib:**
**doc:**
**locale:**
**tests:**

**Comment by sils1297** [comment]
Where do you put the rest?

2015-03-04 15:46 GMT+01:00 sims1253 <notifications@github.com>:

**Comment by sims1253** [comment]
Well you have 
.coafile, .gitignore, .travis, license which i guess have to stay at root.
I don't know what manifest is for so ...
install could go to doc, tutorial too, both gen scripts and run_tests into tests.
that would be it i guess.

**Comment by sils1297** [comment]
gets a bit better with https://github.com/coala-analyzer/coala/pull/428

**Comment by sils1297** [comment]
I think its now rather good cleaned up, don't know what to change. Closing.
