### ISSUE TITLE
run_tests: better error message when coverage3 not installed

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#356]

**Comment by sils1297** [comment]
@shivanipoddariiith interested? Then you get to see our testing infrastructure :)

**Comment by shivanipoddariiith** [comment]
Sure! :)

**Comment by shivanipoddariiith** [comment]
https://github.com/coala-analyzer/coala/pull/369
Does that  ^ fix some of this for us here ? :)

**Comment by sils1297** [comment]
no, this PR doesn't seem to have anything to do with coverage measurement.

Try invoking `./run_tests.py -H` and you'll probably get that error message. You can fix this by installing a package that is usually called `python-coverage3` or so.

**Comment by shivanipoddariiith** [comment]
Ah, didn't get that by running it. I did not even install python-coverage separately.

**Comment by sils1297** [comment]
@shivanipoddariiith so you get that coverage report?

**Comment by shivanipoddariiith** [comment]
Yep, I do. "Coverage failed. Falling back to standard unit tests."

**Comment by sils1297** [comment]
So this bug is about that message :)

**Comment by shivanipoddariiith** [comment]
So, I installed coverage via easy_install. And I still get the same message. Which was confusing.
Here is a paste about the same. -> http://fpaste.org/195856/14259186/raw/

**Comment by sils1297** [comment]
You need to install coverage for python3. Needs to be available as `coverage3` command (which holds true on every linux distro I tested)

**Comment by shivanipoddariiith** [comment]
Looking for OSX, probably something different, since these don't work.

**Comment by sils1297** [comment]
Well, run_tests looks for the coverage3 binary. And executes the test with that instead of python3.

**Comment by sils1297** [comment]
So you sure you didn't install the python 2 version? Your paste looks to me as if your easy_install thing installs python2 things only.

**Comment by shivanipoddariiith** [comment]
Okay, so the only workaround for MacOSX is to work in a virtual python3 env and then install coverage. Is there any place I could put the steps in maybe ?
As a fix for the better message, I'd just say "Install code coverage measurement for python3"
(Yep easy_install in the default python2.7 was a bad idea :)

**Comment by sils1297** [comment]
you can create a markdown file in doc/getting_involved/MAC_hints.md or so.

Message sounds better. You take care of this?

**Comment by sils1297** [comment]
Maybe also add package name to the message `python-coverage3`
