### ISSUE TITLE
Organizing issues and new labels

### ISSUE THREAD

**Issue by sims1253** [coala-analyzer/coala#359]
first sketch of labels I did after reading all open issues.

https://gist.github.com/sims1253/9e84974e0b5f66f8cf9f

**Comment by sils1297** [comment]
Phew, that's a lot of labels you propose. I'd rather strip it down a bit, e.g. Documentation and Wiki/Tutorial are basically the same. We also should ask ourselves for what we want labels to use. As it goes for me:

 * I want some easy/hard stuff so I can direct beginners to the easy stuff and avoid the hard stuff when going further.
 * Importance is clearly needed.
 * And in the end I want something not so fine grained to filter bugs by some topic. E.g. documentation makes totally sense but having a label for each kind of documentaiton does not IMHO.

What do you think?

**Comment by sims1253** [comment]
They would replace the existing labels, just to clarify.
And yea I can see how one could disagree with the number. Could probably half them or get rid of even more. Will see after dinner.

**Comment by Makman2** [comment]
Be careful, replacing labels is not handled right in GitHub. If you rename a label the current one is renamed, but label assignments inside the history are kept as they are. That can confuse quite a lot.

**Comment by sims1253** [comment]
My Idea was to remove all labels and make a fresh start. So delete the old ones first, then create new ones and label stuff.

**Comment by sils1297** [comment]
Not sure, I'm against this since it's quite some work going through
everything and relabelling. What advantage does this bring?

2015-03-04 21:20 GMT+01:00 sims1253 <notifications@github.com>:

**Comment by sils1297** [comment]
I mean, you could do it but I don't want to relabel everything. And first
we should agree on some labels.

2015-03-04 21:43 GMT+01:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

**Comment by sims1253** [comment]
well you stated that labels are "desorganized" so i thought we might try to get a new set of labels with clear definitions so they desorganized part would go away. 
As for the advantages this could bring I guess you can have better overview, it could become easier for not so involved people to see through the forest of issues but after all a label is nothing more than a sign what the issue is about or like a small note so others can quickly see what is important/where help is needed and so on.

Of course we first would have to agree on a set of labels (which does not have to be final as needs can change) that is why i opened this issue :) And as I'd like to help but am not really able to contribute via code i could do the relabelling (i think not every issue must have a label by the way)

**Comment by sils1297** [comment]
We have various needs, including documenting, translating and so on. You'd
help us a great deal if you only test coala.

Since some labels are staying (e.g. important, easy) my suggestion would be
to keep those, rename similar ones and delete the others.

2015-03-04 21:51 GMT+01:00 sims1253 <notifications@github.com>:

**Comment by sims1253** [comment]
I will test as soon as I can patch together another commit for Economy but I'm not as productive as I'd like me to be atm.
Of course for existing labels there is no need to remake them. What do you say about the new, shorter list of categories I made? (updated gist)

**Comment by sils1297** [comment]
I think we'll need something like `needinfo` which is used when a bug awaits information from reporter or so to be adressed.

**Comment by sils1297** [comment]
@sims1253 any progress?

**Comment by sils1297** [comment]
I think we want labels for `easy` and `hard` in terms of difficulty (how much you need to know coala) and `fast` or so for things that can be implemented with not much time. (E.g. something can be `hard` and still `fast` to do. `easy` matters to newcomers, `hard` matters to new people looking for a small challenge [-> do not take hard ones], `fast` matters to me :P)

**Comment by sils1297** [comment]
@sims1253 take a look at https://waffle.io/coala-analyzer/coala

**Comment by sils1297** [comment]
ok I guess this'll have to develop naturally we don't have time for that, labels aren't that bad either.
