### ISSUE TITLE
making travis faster...

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#360]
just found http://mislav.uniqpath.com/2013/12/travis-cached-bundle/ while browsing for something completely else.

**Comment by shivanipoddariiith** [comment]
Working on this.

**Comment by shivanipoddariiith** [comment]
Fixing this issue requires us to install the travis "cache-bundle" and the "s3-put" scripts, which have the following dependencies:

- An Amazon S3 bucket in the default region
- Amazon access credentials via environment variables (see below)
- Gemfile.lock checked into version control
- openssl
- curl

The most immediate concern I have is that of the amazon credentials etc we need to use, so as to create an Amazon s3 bucket and access credentials discussed above (and in the post formally mentioned.)

**Comment by sils1297** [comment]
Yeah than that probably doesn't make sense. Thanks for investigating.
@Makman2 can you close this one?
Am 06.03.2015 21:42 schrieb "Shivani Poddar" <notifications@github.com>:
