### ISSUE TITLE
run_tests.py: Add assert call statistic

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#363]
During the tests I've thought about feature that displays together with your test how many assert calls were made. Especially helps to see if you've forgotten to place asserts in a test.

Obviously this information is only displayed when specifying verbose mode (`-v`)

**Comment by sils1297** [comment]
I'm not sure I get the  advantage of that. It's probably hard to realize as well.

**Comment by Makman2** [comment]
I know this is quite an advanced feature. I had the need for it when I hardly rebased the escaping functions branch. Merging was quite difficult and it was hard to check whether each test case had asserts in it (and so not testing anything).

But I think it serves you a good overview how much tests your test case really processes.

Not sure about this feature either, I thought it is an idea worth mentioning it^^

**Comment by sils1297** [comment]
> Merging was quite difficult and it was hard to check whether each test case had asserts in it (and so not testing anything).

One can test something without asserts. E.g. just execute a function to validate it doesn't throw an exception.

**Comment by Makman2** [comment]
No because there was so much code to merge it was troublesome to check that each function had kept its assert statements, because the merge conflict merged too much together.

**Comment by sils1297** [comment]
seems a *very* special case to me. Plus I still don't know how that would be doable.

**Comment by Makman2** [comment]
To do that: subclass `unittest.Test` and override all assert functions. Insert in each one a counter^^
Hm shouldn't be too hard and gives you more information^^

**Comment by sils1297** [comment]
Somehow I don't like this proposal...

2015-03-06 19:31 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Why not? Then we have a `coala.Test` class, a super duper class tailored for coala's needs :)

**Comment by sils1297** [comment]
Just... no.

2015-03-06 19:34 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Your choice :(

**Comment by sils1297** [comment]
You really want that, huh? I'd rather go for some grepping approach than
overriding each and every assert call...

2015-03-06 19:40 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
but counting each assert call in file is not counting each assert call in runtime^^
I think subclassing is a good way to do that, but if you don't want it, it's okay. I know why this is somehow awkward.
If you think this feature is not a "real" feature you can close the issue^^

**Comment by sils1297** [comment]
I'm just not convinced that it helps anyone really. I don't want to close
bugs because it's not my opinion, I don't want to be a dictator concerning
all coala stuff so I'm open for more arguments or maybe another example or
so...

2015-03-06 19:50 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
My main argument: It displays more information about each test case executed, so you really see how many asserts were performed. So you can check if you expect 5 and get 5 asserts, or if you want above 1000 asserts but you just get 10 you know you made a mistake.
\+ When using subclassing you have a custom test class for coala, I think that is not bad^^

**Comment by sils1297** [comment]
Ok, you're good to go. Let's see what code comes out there. And please do some performance measurement, I can imagine that if we do an extra operatin for every of those asserts tests might take a bit longer.

**Comment by sils1297** [comment]
@Makman2 any progress?

**Comment by Makman2** [comment]
No not really^^ First tries revealed intercepting the test-workflow is quite difficult.
