### ISSUE TITLE
Message for opening an editor not clear enough

### ISSUE THREAD

**Issue by shivanipoddariiith** [coala-analyzer/coala#366]
While running tests from CLI from "coala --files=src/*.c --bears=SpaceConsistencyBear --save", coala prompts with errors and asks the user to choose from selecting one of the 2 options:

|    |    |  1: Open a temporary clone of the file in an editor.
|    |    |  2: Apply the patch automatically.

While the first one is not descriptive enough to suggest that the only editors that can be opened are the ones in the user's path, the second one is ambiguous too.
![screen shot 2015-03-05 at 11 17 56 pm](https://cloud.githubusercontent.com/assets/2330579/6510683/8a2a19fa-c38d-11e4-879e-32ff5a8dd1e7.png)
![screen shot 2015-03-05 at 11 17 26 pm](https://cloud.githubusercontent.com/assets/2330579/6510682/89ec578c-c38d-11e4-9ace-f80530d8d3f4.png)

In my opinion this can be fixed by specifying the "Applications" path instead of the user path for opening the respective editors.

**Comment by sils1297** [comment]
I don't understand what you mean by "Applications" path and user path.

**Comment by sils1297** [comment]
@shivanipoddariiith this bug still valid? Could you elaborate your problem if not?

**Comment by shivanipoddariiith** [comment]
Nope, not valid anymore, this seems to work for me now! :)
