### ISSUE TITLE
commit message guidelines: imperative present tense

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#371]

**Comment by Makman2** [comment]
Do you want make a complete rebase on master or why this issue? oO

**Comment by sils1297** [comment]
no it's important that the commit message is not only present tense:

`Adding something`

but imperative tense:

`Add something`

(at least thats the common way and thats how we do it.) This is not explained correctly in our guidelines,

**Comment by Makman2** [comment]
Ah okay for the specification.

**Comment by sils1297** [comment]
Yeah, anything that is on master remains on master, I'm not *that* crazy :D

2015-03-09 22:02 GMT+01:00 Makman2 <notifications@github.com>:
