### ISSUE TITLE
Multithreaded test suites

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#374]
Execute each test suite in its own thread/process to speed up execution, especially if you run all tests (to see if your component integrates successfully).

IMPORTANT:
The print result order needs to be the same like single-threaded, otherwise it gets really confusing when reading the outputs, even if the output is delayed until previous ones finish.

**Comment by sils1297** [comment]
this could actually fairly easy with a multiprocessing Pool. See
https://docs.python.org/2/library/multiprocessing.html#using-a-pool-of-workers

**Comment by Udayan12167** [comment]
multiprocessing pool wont work as the function needs to be a top level function which needs to be parallelised whereas the __execute_test function is not. 
http://stackoverflow.com/questions/8804830/python-multiprocessing-pickling-error

**Comment by sils1297** [comment]
thats weird but we could make it a toplevel function.

Alternative?

**Comment by Udayan12167** [comment]
http://stackoverflow.com/questions/11726809/python-efficient-workaround-for-multiprocessing-a-function-that-is-a-data-membe

we could pickle that method without making it a top level function.

**Comment by AbdealiJK** [comment]
This got much easier now because due to https://github.com/coala-analyzer/coala/issues/508 we anyway had to make it a top level function.
