### ISSUE TITLE
Make SectionManager non-coala specific

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#377]
Let's generalize SectionManager a bit: it could be a nice object that allows to fetch several config files and handles how values override each other. This shouldn't be specific to coala.

**Comment by Udayan12167** [comment]
As i have worked on SectionManager thoroughly i would like to have a go at this...
What features do we require?

**Comment by sils1297** [comment]
@Udayan12167 you sure? I think you are working on the most important parts for your application. This bug is not a priority bug and if you have limited time I'd advise for putting it into the mockup so you get better chances.

**Comment by sils1297** [comment]
Basically currently we are specific to coala in some little details, e.g. the default names of the config files . So it would probably good to have a parameter for that and make some things like default config file optional. This way one could reuse the sectionmanager class easily within other projects.

**Comment by Udayan12167** [comment]
By putting it in the mockup you mean my gsoc application?

**Comment by sils1297** [comment]
yes

**Comment by AbdealiJK** [comment]
Closing this issue as this class doesn't exist anymore due to https://github.com/coala-analyzer/coala/issues/508
