### ISSUE TITLE
Timeout for testexecution

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#379]
would be nice to have a timeout when executing tests so if you get an endless loop you get to see the output.

If thats not possible a start would be to dump current output at Ctrl+C...

Makes me thing we could do a Timer object you could start that raises an exception after some time or so...

**Comment by AbdealiJK** [comment]
Fixed in https://github.com/coala-analyzer/coala/commit/2e81e07c7616051571def327d7e9606f9ac0deb6
