### ISSUE TITLE
test against python 3.5

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#383]
neww python version is coming up, could someone test coala with the alpha so we can make coala ready for it if it needs adjustements?

**Comment by AbdealiJK** [comment]
I just ran it with python 3.5.0b2 ... I ran all tests except dbus - because compiling dbus is a pain.
The only error I got was `popitem() takes no keyword arguments` in the test `ConfParserTest`

**Comment by sils1297** [comment]
Thats pretty cool! Sounds like easily fixable, you think we can get that python version into circle easily or do we need to compile it?

**Comment by AbdealiJK** [comment]
We could get it into circleci pretty easily - but it's have to build the
python as circleci doesnt cache it.
So, the build time won't increase much - but, we don't have any other
containers at the moment.
We'd have to remove the 4th container - and that will increase build time a
little

Also, we have nothing to fix - it's a bug in python3.5 ... they will fix it
soon - it's on their bug tracker



On Thu, Jun 25, 2015 at 11:17 PM, Lasse Schuirmann <notifications@github.com

**Comment by sils1297** [comment]
I think having a python 3.5 build is more important than having a dedicated
node for test skipping.
Am 27.06.2015 12:13 nachm. schrieb "AbdealiJK" <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Alright - but there's no point in doing it now - because it will keep
failing.
We wait for python to fix that and then do it?

Adding python 3.5 in circleci is very simple as of now.

Also, if we want gi or dbus tests, then we'll need python headers which are
currently being installed using the deadsnakes repo - so, that will have to
use python 3.5 too

**Comment by sils1297** [comment]
ok cool :)

2015-06-27 16:13 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
@AbdealiJK can you give us a link to the python 3.5 bug that needs fixing before we can do CI with it?

**Comment by AbdealiJK** [comment]
The mailing list discussion - https://mail.python.org/pipermail//new-bugs-announce/2015-June/023210.html
Here's the bug issue tracker - http://bugs.python.org/issue24394

It says it was fixed right after beta2 was launched. so it wont get done until beta3.
I could do it with the development python3.5 ... but I dont think we should

**Comment by AbdealiJK** [comment]
Beta 3 came out of july 5 (5 days ago)

I ran tests with 3.5.0b3 and everything works !

**Comment by AbdealiJK** [comment]
Oops. Spoke to soon.
There seems to be a non deterministic bug. which gives this sometimes:

```
 69/78 | ShowBearsTest
test_show_bears (__main__.ShowBearsTest) ... FAIL

======================================================================
FAIL: test_show_bears (__main__.ShowBearsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/data/jhbuild/other-installs/coala/coalib/tests/output/ShowBearsTest.py", line 46, in test_show_bears
    self.assertEqual(expected_string, stdout.getvalue())
AssertionError: "Some[122 chars].\n\nKeywordBear:\n  Checks the code files for[594 chars]\n\n" != "Some[122 chars].\n\nLineLengthBear:\n  Yields results for all[594 chars]\n\n"
  SomeglobalBear:
    Some Description.
  
    Used in:
     * default
     * test
  
    No needed settings.
- 
-   No optional settings.
- 
- KeywordBear:
-   Checks the code files for given keywords.
- 
-   Used in:
-    * default
-    * test
- 
-   Needed Settings:
-    * cs_keywords: A list of keywords to search for (case sensitive). Usual examples are TODO and FIXME.
-    * ci_keywords: A list of keywords to search for (case insensitive).
  
    No optional settings.
  
  LineLengthBear:
    Yields results for all lines longer than the given maximum line length.
  
    Used in:
     * test
  
    Needed Settings:
     * max_line_length: Maximum number of characters for a line.
  
    Optional Settings:
     * tab_width: Number of spaces to show for one tab. (Optional, defaults to '4'.)
  
+ KeywordBear:
+   Checks the code files for given keywords.
+ 
+   Used in:
+    * default
+    * test
+ 
+   Needed Settings:
+    * cs_keywords: A list of keywords to search for (case sensitive). Usual examples are TODO and FIXME.
+    * ci_keywords: A list of keywords to search for (case insensitive).
+ 
+   No optional settings.
+ 
```

@Udayan12167 Is this one of those issues which occurs because dicts are not ordered ?

**Comment by AbdealiJK** [comment]
This is completed in https://github.com/coala-analyzer/coala/commit/b96ff0427e84f514d90fc467873a81643f2bdba5

Closing this issue as this has now been added to circleci and is part of our testing from now on

**Comment by sils1297** [comment]
@AbdealiJK thanks! :)
