### ISSUE TITLE
Untie interactors/loggers from section

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#386]
This solves some recursive import problems I think plus it would be very weird to have ConsoleOutput for one section, a GUI for another and VoiceOutput for yet another section.

**Comment by Udayan12167** [comment]
If we have just one ConsoleIntercator instantiated in the SectionExecutor class and use that to interact with the console will that work? Would it cause any problems to the order of how the results are output to the console?

**Comment by Udayan12167** [comment]
Okay not that simple the acquire_settings method is specific to each Section.

**Comment by Udayan12167** [comment]
The two places where Console Interactor from the section class is being used is:
1. SectionFiller
2. SectionExecutor

At both the places if we provide a new instance of the ConsoleInteractor instead of using the instance of ConsoleInteractor coming from section should decouple the ConsoleInteractor from Section class.

**Comment by sils1297** [comment]
Ah. Let me take a look. Thats actually easy to solve since we had that once...

The old bug: https://github.com/coala-analyzer/coala/issues/131

Will provide more info in a few minutes.

**Comment by sils1297** [comment]
So, in order to have one global interactor and log printer we'll just create the ones we need in the SectionManager. Since the SectionManager invokes the SettingFiller at a later point we can just pass it there. We then pass the interactor and log_printer back to the coala main script which in turn passes it to the SectionExecutor which can use it instead of the ones given from the section.

Tricky part is to make few good readable clean commits out of this, my proposal spontaneously popping out of my head - so feel free to disagree:

In the first commit you could move the `retrieve_logging_objects` function from the `Section` to the `SectionManager` and set the interactor and log_printer (still in the Section) from the outside.

Second you can use the new global interactor and log_printer within the SectionManager everywhere instead of the ones from the section.

Third you can pass interactor and log_printer to the SectionFiller and use them there instead of the ones from the section.

Fourth you can pass interactor and log_printer back to coala main script and use them in the main script instead of the ones from the section.

Fifth you can pass interactor and log_printer to the SectionExecutor and use the global ones there too.

Sixth you can remove the interactor and log_printer from the Section together with the assignments.

**Comment by Udayan12167** [comment]
As of now with the retrieve_logging_object each section is allowed to have different type of log_printer(ConsolePrinter,NullPrinter,FilePrinter) by having a single global log_printer how do we tackle this problem?
Same goes for the Interactor where options are only limited to (NullInteractor and ConsoleIntercator)?

**Comment by Udayan12167** [comment]
So i just read the issue again that solves the output problem what about the logs now and also which section of all the sections parsed by Section Manager decides what type of interactor is instantiated and which type of log_printer is instantiated?

**Comment by sils1297** [comment]
> As of now with the retrieve_logging_object each section is allowed to have different type of log_printer(ConsolePrinter,NullPrinter,FilePrinter) by having a single global log_printer how do we tackle this problem?

We just don't allow that anymore.

**Comment by sils1297** [comment]
> So i just read the issue again that solves the output problem what about the logs now and also which section of all the sections parsed by Section Manager decides what type of interactor is instantiated and which type of log_printer is instantiated?

The default section. Just like the save parameter. Everything that is valid globally comes from the default section.

**Comment by Udayan12167** [comment]
Cool

**Comment by sils1297** [comment]
> The default section. Just like the save parameter. Everything that is valid globally comes from the default section.

That makes most sense because the default section exists in every case :)

**Comment by Udayan12167** [comment]
@sils1297 Have a look this is the first commit and the critical one the other ones should be trivial after this. Had to change `retrieve_logging_objects()` a little.
