### ISSUE TITLE
add pip package

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#391]

**Comment by sils1297** [comment]
Someone told me that adding a pip package should be fairly easy.

**Comment by sils1297** [comment]
http://docs.python-guide.org/en/latest/shipping/packaging/

**Comment by fneu** [comment]
https://pypi.python.org/pypi

**Comment by sils1297** [comment]
https://packaging.python.org/en/latest/distributing.html#uploading-your-project-to-pypi

2015-06-17 12:45 GMT+02:00 Fabian Neuschmidt <notifications@github.com>:

**Comment by sils1297** [comment]
test package: https://testpypi.python.org/pypi/coala

**Comment by sils1297** [comment]
blocked by https://github.com/coala-analyzer/coala/issues/693 , creating the test package was nice:

```
python setup.py register -r https://testpypi.python.org/pypi
python setup.py sdist upload -r https://testpypi.python.org/pypi
```

plus logging in and stuff.

**Comment by sils1297** [comment]
```
lasse@lssteadarch ~/prog/coala (git)-[wip/sils/cc] % sudo pip install -i https://testpypi.python.org/pypi coala                                                                                               :(
Collecting coala
  Downloading https://testpypi.python.org/packages/source/c/coala/coala-0.1.1.tar.gz (119kB)
    100% |████████████████████████████████| 122kB 2.1MB/s 
Installing collected packages: coala
  Running setup.py install for coala
Successfully installed coala-0.1.1
lasse@lssteadarch ~/prog/coala (git)-[wip/sils/cc] % coala
Executing section PythonCheck...
Executing section DOCS...
lasse@lssteadarch ~/prog/coala (git)-[wip/sils/cc] % 
```

**Comment by sils1297** [comment]
our last release (0.1.1) is now available via pip. TODO: automate release process for the next release and ffix the version number issue.

**Comment by sils1297** [comment]
version numbers are fixed, we now auto deploy master to pypi dev packages with circleci build number
