### ISSUE TITLE
escaping stuff: scrutinizer issues

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#392]
https://scrutinizer-ci.com/g/coala-analyzer/coala/inspections/8589a071-2905-40dd-a562-bfae3b8f40e5/issues/

need to fix after merging the escaping stuff

**Comment by sils1297** [comment]
plus you wanted to add another test

**Comment by Makman2** [comment]
What shall I fix explicitly? Many things are just complexities which I can't change.
Okay duplicated code is obvious, but rename methods to conform the naming convention?

**Comment by sils1297** [comment]
some renamings should probably be done too, yes. We already talked about the rest on gitter.

**Comment by Makman2** [comment]
So you think the current changes suffice?

**Comment by sils1297** [comment]
yeah its ok. Your judgement...

2015-03-26 17:14 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
I haven't really new ideas, so okay :)
