### ISSUE TITLE
**a not detected as invalid glob pattern

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#401]
http://pastebin.com/dE60VYe7

**Comment by smfn3321** [comment]
I can confirm a similar behaviour on current master:
http://pastebin.com/VJ6ikbaV

I can not explain this behaviour at the moment though, since manual investigation yields that this should not happen:

```
>>> from coalib.parsing.Glob import glob
>>> glob("**a")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/fabian/Projekte/coala/coalib/parsing/Glob.py", line 213, in glob
    return list(iglob(pattern, files, dirs))
  File "/home/fabian/Projekte/coala/coalib/parsing/Glob.py", line 194, in iglob
    selector = _make_selector(pattern_parts)
  File "/home/fabian/Projekte/coala/coalib/parsing/Glob.py", line 20, in _make_selector
    raise ValueError("Invalid pattern: '**' can only be "
ValueError: Invalid pattern: '**' can only be an entire path component
>>> glob("**a/")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/fabian/Projekte/coala/coalib/parsing/Glob.py", line 213, in glob
    return list(iglob(pattern, files, dirs))
  File "/home/fabian/Projekte/coala/coalib/parsing/Glob.py", line 194, in iglob
    selector = _make_selector(pattern_parts)
  File "/home/fabian/Projekte/coala/coalib/parsing/Glob.py", line 20, in _make_selector
    raise ValueError("Invalid pattern: '**' can only be "
ValueError: Invalid pattern: '**' can only be an entire path component
```

**Comment by smfn3321** [comment]
ok, more weird stuff (I'm not too deep into this atm so sorry if I'm missing stuff at places):

placing the line:
```python
print("called on '{}'".format(pattern))
```
right after the docstring in the iglob method, leads to:
```
[localghost] coala > ./coala -f **a
# bunch of bear stuff here
Executing section PythonCheck...
called on '/home/fabian/Projekte/coala/coala'
```
and
```
[localghost] coala > ./coala -f **a/
# bunch of bear stuff here
Executing section PythonCheck...
called on '/home/fabian/Projekte/coala/**a'
[ERROR][20:40:36] An unknown error occurred. 
# and so fourth
```

**Comment by smfn3321** [comment]
in out project, `iglob()` is only called by `icollect()` which in this case gets called by `_instantiate_processes()` in SectionExecutor.py:
```filename_list = collect_files(path_list(self.section.get('files', "")))```

while in the case of `-f **a`
the section contains `"**a/"` of which path_list makes `['/home/fabian/Projekte/coala/**a']`,
in the case of `-f **/a`
the section contains `"coala"` already which is weird. path_list makes `['/home/fabian/Projekte/coala/coala']` out of that which leads to the observed behaviour

**Comment by smfn3321** [comment]
@sils1297 at this point I assign you because I think you will have an easier time to explain how the "coala" string lands in the files setting of the active section when `./coala -f **a` is called

**Comment by sils1297** [comment]
actually I think the shell globbed here :) try outputting sys.argv with **a and **a is probably expanded by the shell.
