### ISSUE TITLE
search_in_between function with nesting

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#402]
Add a new function that supports nesting.
Means:
```
<This is a nested <thing>>
```
Shall not match
```
This is a nested <thing
```
So maybe provide a custom class where the match itself is provided together with the nestings in form of a list or an iterator again.
So we get somethin' like:
```
This is a nested <thing>
- thing
```
Could be a nice thing for bears that use regexes in code (for example if you have C++ templates, you can open as many `<>`  sub-templates as you want).

**Comment by sils1297** [comment]
thats a cool one indeed, however we probably also want an unescaped version of it

**Comment by Makman2** [comment]
Tried to read about how to implement them with regexes, but python does not support so called "recursive patterns". So need to do it manually a bit.
There exist an extension module for it but that is not in the standard lib, so I wouldn't use it^^

**Comment by smfn3321** [comment]
I came so a similar conclusion when implementing _iter_or_combinations() for globs which parses nested parenthesized parts of strings recursively, maybe you want to take a look at it?

Also, I like an approach given [here](http://stackoverflow.com/questions/4284991/parsing-nested-parentheses-in-python-grab-content-by-level) using a stack:

```python
def parenthetic_contents(string):
    """Generate parenthesized contents in string as pairs (level, contents)."""
    stack = []
    for i, c in enumerate(string):
        if c == '(':
            stack.append(i)
        elif c == ')' and stack:
            start = stack.pop()
            yield (len(stack), string[start + 1: i])

>>> list(parenthetic_contents('(a(b(c)(d)e)(f)g)'))
[(2, 'c'), (2, 'd'), (1, 'b(c)(d)e'), (1, 'f'), (0, 'a(b(c)(d)e)(f)g')]
```
maybe this fits to what you're trying to do?

**Comment by sils1297** [comment]
@smfn3321 what was the reason for choosing the other approach btw.?

**Comment by smfn3321** [comment]
The reason was that I needed to eliminate the parentheses by "expanding" all parenthesized substrings with the different options. I did not care for indentation level, i.e. (1|(2|3)) and (1|2|3) were the same to me. Therefore the recursive approach seemed easier and more appropriate

**Comment by Makman2** [comment]
I maybe have a new idea not to yield a tuple/class, but just return the first level. If the user wants more, he can just invoke this function again.

**Comment by sils1297** [comment]
@Makman2 sounds reasonable. Then we probably don't want any nesting but just search for the opening delimiter *from the left* and the closing delimiter *from the right*. We wouldn't have to worry about recursion then :)

**Comment by Makman2** [comment]
That's the point :)

**Comment by smfn3321** [comment]
@sils1297 This is dangerous since it will fail on stuff like "This is a <beautiful_thing> and a <ugly_thing>"

**Comment by smfn3321** [comment]
I guess you would want to yield just "beautiful_thing" in the above case, so you would neet so search for the first closing delimiter *from the left* and the rightmost opening delimiter left of it.

**Comment by sils1297** [comment]
@Makman2 @smfn3321 is right! @smfn3321 thanks for noting.

**Comment by smfn3321** [comment]
This is the relevant code from _iter_or_combinations, which does not take escaping into account for now:
```python
    # Taking the leftmost closing delimiter and the rightmost opening delimiter
    # left of it ensures that the delimiters belong together and the pattern is
    # parsed correctly from the most nested section outwards.
    closing_pos = pattern.find(closing_delimiter)
    opening_pos = pattern[:closing_pos].rfind(opening_delimiter)

    if (
            (closing_pos == -1) != (opening_pos == -1) or
            # Special case that gets overlooked because opening_delimiter
            # is only being looked for in pattern[:-1] when closing_pos == -1
            (closing_pos == -1 and pattern.endswith(opening_delimiter))):
        raise ValueError("Parentheses of pattern are not matching")

```

**Comment by Makman2** [comment]
Why would this approach fail on "This is a <beautiful_thing> and an <ugly_thing>"? In my opinion my function would return two items.

**Comment by smfn3321** [comment]
Note that I forgot to escape a part of my answer at first and that I wrote it in reponse to @sils1297 because he said "opening delimiter from the left and closing delimiter from the right"

**Comment by Makman2** [comment]
I just parse my rough and only basic prototype so you get an idea:
```python
def func(begin, end, string):
    regex = r"(" + begin + r")|(?:" + end + r")"
    nesting_level = 0 for match in search_for(regex):
        if (match.group(1) is not None):
            nesting_level += 1
        else:
            if (nesting_level == 0):
                yield match
            else:
                nesting_level -= 1
```

**Comment by Makman2** [comment]
Ah okay I've misunderstood :O
