### ISSUE TITLE
C++ language support

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#403]
Write bears to support minimal C++ codestyle rules.
I have following bears/features in mind:
- Obiously indentation things (but needs special settings to adjust special unindented code parts)
- Force using `{` and `}` in `if`'s and so on. So single statements are not allowed
- Check declaration styles (type in an own line, parameters one line each, `const` after type declaration etc.)
- Class layout: `public`, `protected`, `private` or other modifier orders
- No code in header files! (Exception: Template code)
- Explicitly apply access modifiers (Means: all fields in classes that don't have an access modifier are implicitly private (in structs public), but marking them explicitly is safer and more consistent)
- Single space after `if`'s `for`'s and so on (or even no space)

And if possible:
- Unneeded headers included, but that would involve a complete parsing/lookup engine
- Template guidelines, but this is quite difficult, especially when using template meta-programming defining layouts is quite tricky.

For that purpose something like a C++ parsing engine needs to be created that holds regexes and functions to parse specific parts like function, declaration etc.

**Comment by sils1297** [comment]
depends on https://github.com/coala-analyzer/coala/issues/250

**Comment by sils1297** [comment]
#250 is in review and work can be build upon that.

**Comment by sils1297** [comment]
Hey, @Makman2 how about you doing a C linter integration for the time being? After pylint was that easy?

**Comment by Makman2** [comment]
yeah why not, open an issue and suggest an exisiting tool to use^^

**Comment by sils1297** [comment]
for now this'll be covered by https://github.com/coala-analyzer/coala/issues/897 and the already existing clang and indent bear.
