### ISSUE TITLE
unescape() function for StringProcessing

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#410]
Write a function that deletes all escapes from string, so you don't need to take care of escaping things anymore in this string.
Would be needed from coalib/misc/StringConverter.py at line 64.

**Comment by sils1297** [comment]
and at several other places, I requested it several times but you didn't seem to hear :D good that you got that demand now ;)

**Comment by Makman2** [comment]
Sorry I didn't understand what you wanted explicitly :/

**Comment by sils1297** [comment]
@Makman2 how didn't you understand what I want? Basically I want the reverse of `re.escape` :)

**Comment by sils1297** [comment]
you can also move that function https://github.com/coala-analyzer/coala/blob/master/coalib/misc/StringConverter.py#L63 into string processing with an own tes.

**Comment by Makman2** [comment]
yeah thanks :D

**Comment by Makman2** [comment]
What about known sequences like `\n` or `\t`?

**Comment by sils1297** [comment]
you can't really generalize that. If you have those in an escaped string
you'll want \\n there.

2015-04-22 16:23 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by sils1297** [comment]
IMOI

2015-04-22 16:52 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

**Comment by Makman2** [comment]
I'm fighting with myself with the sense of that function again: The idea behind escape sequences is to postprocess them to special characters that can't easily be written. Just to remove escapes is the same as not having any^^

**Comment by sils1297** [comment]
not really, think of an escaped string in
whateverprogramminglanguageyouwant. If you want that string you need to
unescape everything that is between not escaped quotes to get the real
thing. Unescaping and escaping are thus important serializing tools.

2015-04-22 17:03 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
ah okay I confused myself again, thought I should keep the escaped char. Means
`\n` would serve unescaped `n`, but it should serve nothing :D
