### ISSUE TITLE
unescaped_find() for StringProcessing

### ISSUE THREAD

**Issue by smfn3321** [coala-analyzer/coala#414]
For example in globs, the position of delimiters is really important. To support escaping these delimiters, a function like `string.find()` is needed that finds the first occurence of an unescaped sequence. It would be cool to have such a function in StringProcessing.

Also, equivalents to `rfind()` and `findall()` could be useful

**Comment by sils1297** [comment]
Doesn't unescaped search for cover that? Just push your string through
regex.escape and use that as pattern.
Am 30.03.2015 20:21 schrieb "Fabian Neuschmidt" <notifications@github.com>:

**Comment by Makman2** [comment]
That is `unescaped_search_for()` that will be covered from #394.

**Comment by Makman2** [comment]
Somethin like `rfind()` is not possible with regexes. They don't allow to search backwards. To do so you need to reverse the search string and the regex expression. But if you need an `rfind()` result you can collect each string via `list()` and then reverse it.

**Comment by smfn3321** [comment]
Hm okay, I pushed a couple of ideas to #418.

I basically used the python builtins and added an escape check for a specific position based on your regular expression. This should be reasonably fast and easy to use although it arguably does not give as much control as one get's by passing regular expressions to the functions.

**Comment by sils1297** [comment]
@smfn3321 this is fixed isn't it?

**Comment by smfn3321** [comment]
Well, is `unescaped_search_for()` in master now?

**Comment by sils1297** [comment]
no :(

**Comment by Makman2** [comment]
Can we close this issue? `unescaped_search_for()` is in master^^
