### ISSUE TITLE
StringProcesses.search_in_between() does not produce minimal results

### ISSUE THREAD

**Issue by smfn3321** [coala-analyzer/coala#416]
```
>>> list(SP.search_in_between("[a]","[c]","aabcc"))
['ab']
```

Now, this one might be by design, but I would prefer `.search_in_between` to return results as minimal as possible. If on evaluates "begin" and "end" like parentheses, the above string could have been read as "((b))" and I think the most obvious result would have been just ['b'].

At least for somebody that is not familiar with the StringProcessing internals

**Comment by Makman2** [comment]
This is covered from #402 that supports your desired nesting feature.
