### ISSUE TITLE
documentation: code in note is bad

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#430]
see http://coala.readthedocs.org/en/wip-sils-docs/Getting_Involved/Writing_Tests/#reason-why-this-function-is-untestable

**Comment by Makman2** [comment]
That seems to apply for all nested constructs, not only code...

**Comment by sils1297** [comment]
correct, also applies to code in bullets. Seems the markdown parsing isn't the best one. (Although several plugins are enabled - we can use tables :))

**Comment by sils1297** [comment]
I filed https://github.com/mkdocs/mkdocs/issues/488 upstream. What do we do with this for now?

**Comment by sils1297** [comment]
they have it in their milestone for next release :)

**Comment by sils1297** [comment]
please take a look at the workaround https://github.com/mkdocs/mkdocs/issues/488#issuecomment-97420055

**Comment by AbdealiJK** [comment]
I think this can be closed ?

**Comment by sils1297** [comment]
@AbdealiJK why that? We still have ugly docs.

**Comment by AbdealiJK** [comment]
Ah - I see, I just realized which part you were referring to

**Comment by Makman2** [comment]
Issue still there^^

**Comment by AbdealiJK** [comment]
@Makman2 the link @sils1297 gave is for his personal branch wip-sils-docs.

Did you check the "latest" branch ? It works for me. http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Tests

**Comment by AbdealiJK** [comment]
reopening as this caused master's zanata to fail last time.

**Comment by AbdealiJK** [comment]
sorry - wrong issue. closing it again.
