### ISSUE TITLE
travis -> circle ci

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#432]
circle ci is way faster than travis and supports sshing into it for debugging which is very cool.

Useful resources:
http://www.jetthoughts.com/blog/tricks/2014/11/24/run-tests-against-multiple-ruby-versions-on-circleci.html
https://github.com/miry/multiple_ruby_for_circleci/blob/master/circle.yml

We need to parallelize the different python versions ourselves. A bit bash scripting is needed.

**Comment by Makman2** [comment]
Just interest: Do you know which OS they are running?

**Comment by sils1297** [comment]
ubuntu

2015-04-14 16:55 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by sils1297** [comment]
https://circleci.com/gh/coala-analyzer/coala

First builds work. TODO:

- [ ] Multiple python versions - please in parallel
- [ ] Upload coverage information (trivial)

**Comment by sils1297** [comment]
also: travis will soon gain support for mac which we want so I'm not sure we should do the switch. Anyone feel free to reopen if you think switch is worth, continuing discussion.

**Comment by sils1297** [comment]
I'll leave circleci active so if we have problems we can use that for debugging.
