### ISSUE TITLE
drop support for python 3.2 & 3.3

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#434]
does anyone still use a distribution with one of those versions? Even the debian released this month has 3.4.

**Comment by Makman2** [comment]
If we drop I would open an issue for my string processing module to turn simple loop-yields into `yield from`.

**Comment by sils1297** [comment]
let's make a todo list:

- [ ] Use subtests here and there (regex module?)
- [ ] use `yield from` in string processing
- [ ] remove own barrier implementation

please comment anything else.

**Comment by sils1297** [comment]
@smfn3321 could you state your opinion on this here?

**Comment by smfn3321** [comment]
Well, yield from should be used in most of our iterators. Including collectors and globs. I would take care oft them.

**Comment by sils1297** [comment]
I meant opinion on dropping the support.

**Comment by sils1297** [comment]
ok for now dropping support wouldn't be a great win while we loose ability to siupport pypy. Since static code analysis is a matter where preformance is relevant for now we'll not be dropping support for python 3.2.
