### ISSUE TITLE
Write git tutorial and other developer info

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#435]
Already started http://coala.readthedocs.org/en/latest/General_Dev_Info/git_tutorial_1/ , part 2 is in progress.

**Comment by AbdealiJK** [comment]
Is this completed ? didnt you publish part 2 in your blog ?

**Comment by sils1297** [comment]
nope, part 2 and 3 still to go

2015-07-16 17:02 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by Makman2** [comment]
@sils1297 Wanna do this for 0.3?

**Comment by sils1297** [comment]
@Makman2 nope. Writing that really sucks up time. Which I don't have.

**Comment by sils1297** [comment]
This is an ongoing personal effort of mine and I probably shouldn't clutter this bugtracker with it. Closing.
