### ISSUE TITLE
Suppress editor output

### ISSUE THREAD

**Issue by smfn3321** [coala-analyzer/coala#441]
When an (gui-)editor is opened through coala, the editor may print debug information that should be suppressed because it displaces coala output and is not useful.

Note that suppressing all editor output may be problematic because oftentimes a cli-editor like emacs or vim may be used.

**Comment by sils1297** [comment]
We can keep a list of "GuiEditors" similar to the dict we have for editor arguments and pipe stdout into `/dev/null` when in question.

**Comment by sils1297** [comment]
@smfn3321 you have kate in mind? I have kate, subl, gedit, any others important?
