### ISSUE TITLE
Tmpfiles should have a useful name

### ISSUE THREAD

**Issue by smfn3321** [coala-analyzer/coala#442]
When opening an editor through coala to manually change lines that get critisized by a bear, the user is provided with a copy that is named something like tmp9klbj0q7Bear.py which does not tell the user, which original file he is editing. This information IS provided by coala beforehand, but it would be helpful to i.e. use the original file name as prefix for the temporary file.

**Comment by sils1297** [comment]
maybe seperation via underscore

2015-04-15 15:00 GMT+02:00 Fabian Neuschmidt <notifications@github.com>:
