### ISSUE TITLE
remove default values for printers

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#447]
its ugly to create printers as default values, their scope should be explicitly outside the object so its clear that if its closable the outside scope has the responsibility to close it.

**Comment by sils1297** [comment]
there is one in FunctionMetadata

**Comment by sils1297** [comment]
This is not really `important` but it's a cause of bugs because sometimes this default value is used leading to not the right printer being used for logging at times.

**Comment by AbdealiJK** [comment]
Would be nicer to make a concept of globalvariables.

class or named tuple or dict named "GlobalVariables" in __init__ from which
default values like this are taken - and the class's variable can be
changed by the ConfParser on runtime

**Comment by sils1297** [comment]
@AbdealiJK how's that nicer? Global variables are bad.

**Comment by AbdealiJK** [comment]
I dont see why you say global variables are bad.

It'd be good to have 1 place where every class can check what the loglevel
is, makes it uniform and solves the problem stated above

**Comment by sils1297** [comment]
> I dont see why you say global variables are bad.

Global variables hide coupling. Or if I might cite the zen of python:

> Explicit is better than implicit.

If we pass the log printer as an argument, the functions don't rely on a certain state of the environment and are easier to reuse elsewhere. At the same time you can see right from the signature what things it uses, global variables hide this information. It's just cleaner to have the function signature state *all* inputs instead of secretly pulling global in global variables.

**Comment by AbdealiJK** [comment]
I was thinking something more like the global variable would be the default
argument for the loglevel. Doesn't hide the coupling - just ensures that
you have the right default argument.

So, something like
```
void foo(bar=None):
    if bar == None:
        foo = globalVars.BAR
```

**Comment by sils1297** [comment]
@AbdealiJK what advantage does this provide?

**Comment by AbdealiJK** [comment]
That you have a common default value which can be changed dynamically

**Comment by sils1297** [comment]
Well, the idea is to remove this default value overall. The problem is that whenever we use the default value in coala it's *just wrong* because we don't use the LogPrinter which is chosen by the user and this is actually a bug. E.g. if you use `coala-dbus` there are some functions which will use the ConsolePrinter for logging instead of exporting the stuff to json. So that's a bug that needs fixing. The best way is to explicitly enforcing the user of those functions to pass a log printer so nothing can go wrong. So that's the underlying issue, using global variables does not solve the problem but just adds coupling to environment making stuff less reusable.

**Comment by Makman2** [comment]
I think https://github.com/coala-analyzer/coala/issues/975 supersedes this issue^^

**Comment by sils1297** [comment]
yeah
