### ISSUE TITLE
create review guidelines

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#457]
From gitter:

uhm for an ideal review you'd first read the code
then check out the commit locally
check the surrounding code if something was forgotten there
e.g. sometimes imports get unused by removal of class usage
or so.
you could run the tests for every commit
in the end take a look at scrutinizer
and at least for the last commit check the branch coverage locally

I'd be glad to have some guideline for that and other opinions. @Makman2 could you tell me how you do reviews?

In the end I'd love to have this page http://coala.readthedocs.org/en/latest/Getting_Involved/Review/ extended by a review guide.

**Comment by Makman2** [comment]
1. Looking over the code
2. If bigger commits or more complicated ones I'll run all tests on each commit.
I don't look at scrutinizer and coverage^^
