### ISSUE TITLE
line length bear improvement proposal

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#468]
sometimes one uses URLs in comments or for whatever reason cannot obey the maximum line length.

Usuallyh because spacing matters in such things - eg. URLs again. Thus the easy way to go IMO is if we detect a line that is too long, check if there are spaces within it. If there are no spaces in this line we assume spacing is not allowed and breaking is not possible.

Any opinions on this? @smfn3321 ?

**Comment by sils1297** [comment]
corner case:

```
    # some_url
```

**Comment by sudheesh001** [comment]
Why not just regex for a url until a whitespace character, there's a rare chance that we have decoded url's ?

**Comment by sils1297** [comment]
Yeah would be nice to have some regex, if it matches allow line to be longer.

**Comment by sils1297** [comment]
or maybe a simple list of globs that we can use with Globbing.fnmatch? That's actually fairly simple.

**Comment by AbdealiJK** [comment]
Closing this as we have a `ignore_length_regex` in LineLengthBear's settings. https://github.com/coala-analyzer/coala/commit/9cc2a54874119a7ed049996c2c28ffd6c7839b4d

**Comment by sils1297** [comment]
:D I was really the one who did it? I had no idea that was even solved
