### ISSUE TITLE
results: Show patch

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#487]
if we offer the user to apply a patch we also should offer him to take a look at it.

How do we do that?

**Comment by Makman2** [comment]
We could maybe orientate on git?

**Comment by sils1297** [comment]
unified diff? Probably the best for console. Plus we need colors for the diff, makes a huge difference. But the problem is not the visualization but how to offer it to the user in a generic way.

**Comment by sils1297** [comment]
internal we have those ResultActions, showing the diff could be one of them but it depends on the interactor so maybe the interactor should handle that directly

**Comment by Makman2** [comment]
Doing via interactor would allow to offer more advanced behaviour like `git add -p` does for example.

**Comment by sils1297** [comment]
one step at a time. This would mean we had to reimplement this for every interactor and you know I'm obsessed with DRY...

**Comment by Makman2** [comment]
This is just a possibility :)

**Comment by sils1297** [comment]
blocked by https://github.com/coala-analyzer/coala/issues/648

**Comment by sils1297** [comment]
Not longer blocked, @AbdealiJK would you like to give this a try?

**Comment by sils1297** [comment]
As for design, this can be done similarly to the `PrintDebugMessageAction`, just make the action specific to the output.

**Comment by sils1297** [comment]
I'll attempt to do this now, commit will look similar to 8dac418130b6a90a485142894d246769b6ff6fc5
