### ISSUE TITLE
architecture: How do we pass files to bears?

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#495]
# What we have

We currently create a dictionary which holds the file name and the file contents.

# Issues with current design

1. We can't process non-unicode files.
2. We can't process files that are "virtual" i.e. only exist in memory and not on the fs. (Will need that for editor plugins/IDE support.)

# Goals

 * We'd need to be able to only give the file contents, i.e. assign `None` to the file name.
 * We'd need to be able to only give the filename and not the file contents or classify the filecontents (binary/text).

I'd be happy if anyone has an idea how we can solve that.

**Comment by Makman2** [comment]
I think streams are the best solution.
We only need to read/write access, meta-data can be extracted from the specific stream type.

**Comment by sils1297** [comment]
We're using a dict because then we only have to load in all files once and we have it in memory once reducing file IO. (Not every bear re-reads the file.)

So you want to load each file in memory and provide a stream to the bears to that file in memory? How do you handle filenames or no filenames? Could you be more concrete?

**Comment by Makman2** [comment]
Yeah, files are loaded into memory where a stream is provided for. Bears only accept streams now. So if you have code that is only in memory you can just pass a memory stream.
The dict wouldn't change at all, you just wrap the binary data into a memory stream. If a bear needs a file name for the stream, it can look up it in the file-data-dict. If he finds a name, the bear knows that this stream originates from a file. If not, the source is unknown (i.e. somewhere from memory).

For the look-up mechanism: If a bear needs to process a file (or is passed a file to process), the dict manager creates a stream for the bear and stores the reference inside a list. The bear can look up via some functions that browse through the lists for each file loaded.

**Comment by Makman2** [comment]
So my first idea...

**Comment by sils1297** [comment]
also at some point we need to worry about resource management, i.e. there  may be more/larger files than we can hold in memory and we need to cope with that. Ok. This is a real corner case, who has more than 4 gib of code...

**Comment by sils1297** [comment]
but reading the file on-demand only would be nice, e.g. some bears might invoke linters that read the files themselves.

**Comment by sils1297** [comment]
superseeded by https://github.com/coala-analyzer/coala/issues/1084 , which should solve this bug.
