### ISSUE TITLE
unescaped_search_in_between: how to get position?

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#499]
the unescaped_search_in_between function returns only a list of strings but doesn't indicate where it found them. This would be vital if we e.g. search for multiline comments in files to exclude them.

**Comment by sils1297** [comment]
we'll need that soon, so adding 0.2 alpha milestone

**Comment by Makman2** [comment]
Three options:
1. New function that returns the `MatchObject` or a tuple
2. Modify current one and return a tuple
3. No function at all, you need to handle it yourself with `unescaped_search_for()` (not so cool)

**Comment by sils1297** [comment]
would be consistent to change everything so we return a match object or so everywhere dont you think?

**Comment by Makman2** [comment]
The problem is that the user then gains control about the regex, where the main problem is where he needs to extract the string (so from which group).

**Comment by Makman2** [comment]
This behaviour could change when we refine/update our functions

**Comment by sils1297** [comment]
then we may create an own object. I'd love to have an object with the following properties:

 * `start` and `end` indicate where I find it
 * `str` conversion just returns the string

shouldn't be hard...

**Comment by Makman2** [comment]
That really needs design, I'll look over it^^

**Comment by sils1297** [comment]
thx

2015-05-04 15:04 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
A suggestion:
@sils1297 the most important things are the string itself and it's position in the base string. Returning a tuple should be a good solution (a tuple with (string, start_pos)). Every module that implements now the StringProcessing functions can work as they do, but if a user wants the position, he just needs to catch the second tuple element. The end position is retrievable via `len(string) + start_pos`.

**Comment by Makman2** [comment]
That wouldn't break backward compatability and keeps the easy handling :)

**Comment by Makman2** [comment]
Okay that is not working... I think...

**Comment by sils1297** [comment]
but we don't have many uses so we could do that. Tuple is nice to iterate over.

**Comment by Makman2** [comment]
Imo the class is better, the tuple contents are position dependent. Using a class ensures the same way of access to the string and extra stuff (like begin and end position). And you can also iterate over these classes :O

**Comment by sils1297** [comment]
so what kind of class and usages do you have currently in mind? Could you list advantages disadvantages? I've lost the overview a bit right now...

**Comment by Makman2** [comment]
Just like you suggested: An immutable class that holds the string (accessible via `str`), start and end position.

Advantages:
- No positional arguments
- We can extend the class

Disadvantes:
- Needs a new class
- StringProcessing functions that use this class are not that intuitive anymore, you need to know the new object (even if it's simple)
- We need to rewrite every currently used function which signature will now change due to the new object

Maybe we provide an overload that uses the new object and one that just returns plain strings. Maybe we call the new function `unescaped_search_in_between_ex` or something similar. Then we don't need to rewrite every code that uses the old function^^

**Comment by Makman2** [comment]
New advantage:
- backwards compatability (as long as you don't change an already existing function)

**Comment by Makman2** [comment]
Opinions?

**Comment by sils1297** [comment]
I'd just say just go ahead, maybe post the definition of the result class here to see if anyone from the community has an improvement idea before you refactor everything...

**Comment by sils1297** [comment]
on demand
