### ISSUE TITLE
Allow Keyboard interrupt to abort a single test

### ISSUE THREAD

**Issue by fneu** [coala-analyzer/coala#500]
We can aaccept keyboard interrupt on test execution to skip a single test if it is endlessly looping for example. I think it is a good idea to add a little timer afterwards to allow the abortion of test execution altogether. It would be slightly annoying to abort 50 tests otherwise.

**Comment by AbdealiJK** [comment]
Solved in https://github.com/coala-analyzer/coala/commit/07a1c37b3e26cfca285e5e1aa09a076cfb89a04e
