### ISSUE TITLE
check objects ending with "er"

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#508]
See http://www.yegor256.com/2015/03/09/objects-end-with-er.html

Indeed we have some objects from the beginning left where we had the opinion that everything needed to be an object. We changed that philosophy. So we'll need to refactor a few things a bit, at least:

 * [x] BearRunner
 * [x] SectionExecutor
 * [x] SectionManager
 * [x] TestHelper

filing this bug was long overdue... good that a reminder came up

**Comment by sils1297** [comment]
good progress, some parsers and sectionfiller are done too :) it's way better!

**Comment by sils1297** [comment]
Classes that need attention, i.e. renaming or refactoring:

- [ ] Printer and derivatives
- [ ] Interactor and derivatives
- [ ] All Parser classes
- [ ] Bear - essentially we're throwing an analysis routine into a class in order to give it some implicit information and that stuff. We should think about at least making it possible to just give a method.

**Comment by sils1297** [comment]
Printer -> Rename to Output
Parser -> Refactor into function classes
Bear -> see https://github.com/coala-analyzer/coala/issues/720

**Comment by sils1297** [comment]
This is an ongoing effort, not a release blocker.

**Comment by Makman2** [comment]
I think we removed everything. Printer are covered from `PyPrint`, `Interactor` does not exist any more and the parser classes make sense, since they do parse and hold the parsed content (so they have a state what means they need to be classes).
