### ISSUE TITLE
Shows "..." when it's not supposed to

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#514]
If a problem is found in the 4th line, 
```
| ...| ...| 
|   1|   1| #include <stdio.h>
|   2|   2|  d
|   3|   3| int main (int argc, char ** argv) {
|   4|   4| 	if ( 1 ) { 
|    |    | [NORMAL] SpaceConsistencyBear:
```
The "..." is shown, although there is no line above the 1st line.

Also, shouldn't it be showing a "..." below the snippet ?

**Comment by sils1297** [comment]
Will be fixed implicitly when I remove the "..." printing at least for now :)

**Comment by sils1297** [comment]
oh this got implicitly fixed :)
