### ISSUE TITLE
improve packaging

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#522]
someone should read http://www.scotttorborg.com/python-packaging/index.html

**Comment by sils1297** [comment]
We should add dependencies to our setup.py. I think after that it should be pretty good suited for the next release now we even have auto-pypi development releases.

**Comment by AbdealiJK** [comment]
dependencies were added in https://github.com/coala-analyzer/coala/commit/929a53c377adca2d5cb48686d4bb6bf5abf3616f

**Comment by sils1297** [comment]
thanks
