### ISSUE TITLE
multiprocessing.Queue is not FIFO

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#525]
it has some flushing internally, i.e. it only flushes when someone asks for something with `get` on the other side or when the process ends I believe. But its not deterministic...

We need to apply this diff to the BarrierTest:

```
diff --git a/coalib/tests/processes/BarrierTest.py b/coalib/tests/processes/BarrierTest.py
index 0024a42..eb60484 100644
--- a/coalib/tests/processes/BarrierTest.py
+++ b/coalib/tests/processes/BarrierTest.py
@@ -10,11 +10,12 @@ from coalib.processes.Barrier import Barrier
 
 def proc_one(queue, barrier):
     queue.put(1)
-    time.sleep(0.1)
     barrier.wait()
     queue.put(2)
 
+
 def proc_two(queue, barrier):
+    time.sleep(0.1)
     queue.put(1)
     barrier.wait()
     queue.put(2)
```

Then the issue gets revealed once upon a time on some systems... so we'll need to find a replacement for our control queue in SectionExecutor and we'll need to fix the BarrierTest. At least...

**Comment by sils1297** [comment]
(windows support depends on this because the issue also shows up on appveyor.)

**Comment by sils1297** [comment]
also see http://bugs.python.org/issue4999

**Comment by Makman2** [comment]
Important here: Even the builtin `multiprocessing.Barrier` contains this bug.
(Maybe we should file this bug in python).

**Comment by sils1297** [comment]
@Makman2 this is no bug in the barrier but in the queue. The barrier works fine.

**Comment by sils1297** [comment]
work in progress on wip/sils/qeue
