### ISSUE TITLE
Troubleshooting guide

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#526]
Since we had many problems on this stony path of development, I think it's worth to write some problems and solutions into a troubleshooting guide.

What I would add first (since this problem inspired me to do so):
- We use the new `setuptools` module that is not installed by default for python version 3. Ubuntu needs for example a package where you just type `python3` as prefix instead of `python`, so:
  
  `sudo apt-get install python-setuptools` --> `sudo apt-get install python3-setuptools`

**Comment by sils1297** [comment]
Hey, I'd rather revert back to distutils. right now setuptools doesn't add any great value for us, we can write the entrypoints ourselves and we spare some headache for the user so I'd rather do this. What do you think?

**Comment by Makman2** [comment]
Should work. I think the main issue before with distutils was that coala was not imported because the `__init__.py` was missing in root. But my new renaming commit moves the coala main executable anyway to coalib.

**Comment by Makman2** [comment]
Anyway: You think this guide is a good idea?

**Comment by sils1297** [comment]
sure, having official troubleshooting info is great. What would go in there right now?

**Comment by Makman2** [comment]
Maybe how to generate documentation?
The setuptools story just gave me the idea, I don't remember any things that needed troubleshooting.

But maybe it comes in my mind:
- "I want to use the code clone detection bear, but it doesn't work."
  You need libclang to get the code clone detection working. For Ubuntu/whatever type `sudo apt-get install libclang-package-name-i-dont-know-now`, and for other system type `...`. If your system does not provide a package for libclang, see the libclang site.

**Comment by Makman2** [comment]
Since instalation stuff (and also other problems) are already covered from the readme, I close this issue.
If we have something to troubleshoot we do that explicitly for that case.
