### ISSUE TITLE
Handle file write fail exception

### ISSUE THREAD

**Issue by Udayan12167** [coala-analyzer/coala#533]
When confwriter is writing to a file if incase the file is open and write fails. We should handle that exception or case properly.

**Comment by sils1297** [comment]
so we need to add `:raises` documentation to confwriter and catch it outside. I think thats the cleanest.

**Comment by AbdealiJK** [comment]
Any ideas on how I can reproduce this ?

**Comment by sils1297** [comment]
uhm just tried with an editor but it doesn't lock the file for write... @Udayan12167 ?

**Comment by AbdealiJK** [comment]
Yep, I tried with evince, audacious, libreoffice ... nothing seems to give lock the file.
I tried opening it with another python session and that didnt do the trick either

**Comment by AbdealiJK** [comment]
As @Udayan12167 doesnt remember how to reproduce, closing this. Reopen if it reoccurs
