### ISSUE TITLE
Using new style 'super()' base constructor

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#534]
Since python3 only uses the new-style classes, we should also use the `super` base constructor. If we use it we don't need to worry about base class names anymore, `super` just invokes it regardless of ID/name.

**Comment by sils1297** [comment]
see https://docs.python.org/2/library/functions.html#super

**Comment by sils1297** [comment]
so

- [ ] We need to write down how to invoke base class constructor in our code style spec
- [ ] We need to use it everywhere.

@Makman2 can you take care of the former?

**Comment by Makman2** [comment]
yep :)

**Comment by sils1297** [comment]
https://fuhm.net/super-harmful/

we really want that? We need more info IMO.

**Comment by sils1297** [comment]
https://rhettinger.wordpress.com/2011/05/26/super-considered-super/

Im not sure what to make of all of that, don't have time right now.

**Comment by Makman2** [comment]
Especially reading the first article, I think he mixes a bit with "Dylan" (never heard about such a language), that seems to work completely different (something about generic functions instead of classes, not really the same^^).
When I fix some minor issues assigned to me, I'll read in detail^^

**Comment by Makman2** [comment]
I really can't imagine why python would implement such a function if it works so badly like described^^

**Comment by sils1297** [comment]
ok that sounds like super is the superior approach still. Also in https://rhettinger.wordpress.com/2011/05/26/super-considered-super/ they just use `super()` with no arguments which looks nice.

I think we should fully understand the consequences of using super before going ahead and begin use it. It does seem to make a difference in corner cases.

**Comment by AbdealiJK** [comment]
Just a note here, if there are two classes that are base classes ... it get's a little weird according to the comments in http://stackoverflow.com/questions/2399307/python-invoke-super-constructor

In a class like `class B(A, AA):` to call constructor of `A` ... `super(B, self)` is needed and to call constructor of `AA` ... `super(A, self)` needs to be used. This seems pretty non intuitive to me. 

This does occur in our code though - example : `NullPrinter`

**Comment by AbdealiJK** [comment]
I found this :
http://blog.codekills.net/2014/04/02/the-sadness-of-pythons-super/
Which is a nicer post IMO as the author doesn't seemed too biased and gives
the solution to the "super" problem.

I've tried these codes, and yeah - they work as he describes

So, the major issue with super is when there are multiple classes inherited
from. super gives back only 1 class - and it chains to give all the other
classes.
The issues mentioned in the port is a rare issue ... but can easily creep
into code if someone uses it without understanding super ... The solution
was to change `B(A,AA)` to `B(AA,A)` ... which is not very easy to catch

IMO super makes things more pythonic, but has a chance or two which will
not work. As we have a lot of inheritence in our codebase - it's cleaner
and more explicit to not use super.

**Comment by Makman2** [comment]
I think ill try to implement super for every class in a new branch, if it works and seems intuitive, we can merge it^^

**Comment by AbdealiJK** [comment]
I tried implementing this in branch `ajk/super` https://github.com/coala-analyzer/coala/tree/ajk/super

I found some issues with passing arguments in ColoredLogPrinter. It needs to send `print_colored` to `ColorPrinter` and `log_level, timestamp_format` to `LogPrinter`. When I so something like:

```
super().__init__(print_colored=print_colored,
                         log_level=log_level,
                         timestamp_format=timestamp_format)
```

It says `TypeError: __init__() got an unexpected keyword argument 'log_level'` - so, I think we need to add `**kwargs` to every class' `__init__` and pass that kwargs to the super's `__init__` also - only then will it pass from `ColoredLogPrinter` -> `ColorPrinter` -> `LogPrinter`

**Comment by sils1297** [comment]
So obviously it has it's limitations when it comes to multiple inheritance
- are there any major advantages despite not having to rename classes
automatically?

2015-06-27 14:09 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Only advantage which I wonder if we'd use is the fact that you can change to which argument the class goes to dynamically. Mentioned [here](https://rhettinger.wordpress.com/2011/05/26/super-considered-super/)

Haven't been able to find any other advantage while reading about it online.

**Comment by sils1297** [comment]
@AbdealiJK do you recommend the switch?

**Comment by AbdealiJK** [comment]
Nope, I am against it.
It does make things nicer but when multi inheritance is there - it's not very intuitive and makes things a fair amount more complicated (to me atleast :P) . The dynamic arg changing thing is pretty confusing.

**Comment by sils1297** [comment]
Thanks. Then we can consider this resolved, we're staying traditional :)
