### ISSUE TITLE
add `ignored` setting

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#537]
we'll want to be able to ignore files. Would be nice to have an option `ignored` (on cli `-i` or `--ignored`) which is a list of globs to exclude files.

**Comment by fneu** [comment]
I'm still on this, in case I can't do it anymore until Tuesday, someone has to pick an appropriate place in one of collector functions and run a glob of "forbidden" files against the matches it is about to yield.

**Comment by sils1297** [comment]
@fneu is gone :) Anyone volunteering?

**Comment by sils1297** [comment]
@fneu reassigning you, after the priority bugs this is also an important thing to have.
