### ISSUE TITLE
Travis needs to be told about sudo access

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#542]
According to the docs : http://docs.travis-ci.com/user/workers/container-based-infrastructure/

Travis needs to be told that sudo is required. I'm not sure how our current .travis.yml is working, but it seems to be giving an error in my fork.

`sudo: True` needs to be added on top.

This may be because I am using the github educational pack, which also gives me travis educational pack - The system that travis gives could be fundamentally different ?

**Comment by sils1297** [comment]
Actually it would be great to be able to switch to the container based infrastructure to speed up builds, can we do some research on if this is possible? There must be a way to install dependencies within the containers...

**Comment by AbdealiJK** [comment]
What si the current infrastructure you are using ?

**Comment by Udayan12167** [comment]
We could use docker. Open source for container infrastructure.

**Comment by sils1297** [comment]
IIUC if we use docker we can't use sudo so how'd we install deps then?

2015-05-18 16:20 GMT+02:00 Udayan Tandon <notifications@github.com>:

**Comment by Udayan12167** [comment]
http://stackoverflow.com/questions/25845538/using-sudo-inside-a-docker-container

**Comment by sils1297** [comment]
that is with docker in general, I assume travis changes the user before giving the container to us so we probably can't install stuff. If we could we wouldn't need  sudo after all, this obviously needs some more experimenting.

**Comment by sils1297** [comment]
http://docs.travis-ci.com/user/apt/

So that way one can install deps without needing sudo. However currently we're symlinking libclang with sudo which is an evil thing to do, we should rather change our clang bindings to accept the .1 so file, then use this apt command to get deps and then we should be able to switch to the faster and more reliable container based infrastructure.

**Comment by sils1297** [comment]
I've filed https://github.com/travis-ci/travis-ci/issues/3943 and https://github.com/travis-ci/travis-ci/issues/3942 so we get our deps whitelisted.

**Comment by AbdealiJK** [comment]
This is not required anymore as travis has been removed and circleci is being used

**Comment by sils1297** [comment]
Thanks
Am 27.06.2015 1:40 nachm. schrieb "AbdealiJK" <notifications@github.com>:
