### ISSUE TITLE
circle-ci not using .misc/.install.sh

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#551]
Is there any reason that circle.yml does not use .install.sh ? It uses it's own apt-get command.
This makes it repetitive, i.e. if I need another dep, i need to change in two places

**Comment by sils1297** [comment]
.install.sh has the command for installing coverage and coveralls which is specific to travis. We could  check in an environment variable there if we're on travis or not and put that into the if, then I'm in for using .install.sh
