### ISSUE TITLE
can't execute coala

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#552]
@Makman2 what have you done?

http://pastebin.com/b4SRJ2AX

**Comment by Makman2** [comment]
Windows works, will now test on Ubuntu...

**Comment by sils1297** [comment]
Well NTFS is unsecure by default so if its a permission problem you won't
find it on windows.
Am 18.05.2015 19:33 schrieb "Makman2" <notifications@github.com>:

**Comment by Makman2** [comment]
Can't confirm bug. Ubuntu 14.04 LTS works.
I definitely removed all site-packages and the scripts that are run in command shell.

**Comment by Makman2** [comment]
@sils1297 Be sure you install coala with sudo. It seems that you have the coala packages not installed.
The script tries then to invoke the coala main module^^

**Comment by sils1297** [comment]
Maybe its an upgrade problem, I.e. the problem occurs if you don't have a
clear system but some stuff left... I'll try clearing everything...
Am 18.05.2015 19:38 schrieb "Makman2" <notifications@github.com>:

**Comment by sils1297** [comment]
I installed with sudo.
Am 18.05.2015 19:40 schrieb "Makman2" <notifications@github.com>:

**Comment by Makman2** [comment]
I'm quite sure that I removed everything.
I first removed the bears and coalib packages from filesystem
Then I got the same error like you (obviously)
After that I removed the invocation scripts, so I couldn't run coala from command line anymore.
Buf after reinstall everything worked again.
I did this for both, Windows and Ubuntu.

**Comment by sils1297** [comment]
It seems to he so. After cleaning up everything it works again. Maybe we
should file a bug with pythons distutils, it should have overwritten that
stuff ..
Am 18.05.2015 19:40 schrieb "Lasse Schuirmann" <lasse.schuirmann@gmail.com>:

**Comment by Makman2** [comment]
Until now I didn't have such problems. Maybe somehow it got canceled or you used a wrong branch :O
If you know something concrete about the issue I think you can file a new one (regarding distutils).
