### ISSUE TITLE
run_tests --html doesn't work in ubuntu

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#553]
In ubuntu and debian systems, coverage isn't installed in `/usr/bin/coverage3` ... rather, it is installed as `/usr/bin/python3-coverage`. Hence, `--html` flag doesn't work. The corresponding launchpad bug is [here](https://bugs.launchpad.net/horizon/+bug/1241332)

It would be better to use `python3 -m coverage` as this is platform independent.

**Comment by sils1297** [comment]
We have ubuntu systems for continuous integration and that works fine. But
the `python -m` thing seems cleaner indeed.

2015-05-19 4:16 GMT+02:00 AbdealiJK <notifications@github.com>:
