### ISSUE TITLE
circle build fails sometimes

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#559]
I get the warning "Warning: The build VMs have a memory limit of 4G. Your build hit this limit on one or more containers, and your build results are likely invalid." from time to time.

However I wonder what the reason for this might be as the build does not contain any memory intensive steps and 4G should suffice without any problems.

I'm in contact with the people from circleci to solve that issue.

**Comment by sils1297** [comment]
they bumped up our memory limit, thats only a workaround though...

**Comment by AbdealiJK** [comment]
I found out why this happens.

In our code, we auto detect the cpu count using `multiprocessing.cpu_count()` and use that to create more processes. But what if I have a RAM constraint ? This is not taken into account.
[here](https://circle-artifacts.com/gh/AbdealiJK/coala/105/artifacts/0/tmp/memory-usage.txt) you can find the memory usage... You see that there are some internal processes like erlang, mysql etc - probably for the web UI to work - and we have 4 processes from Bears each taking up 32MB (In my local computer it seems to be taking ~20MB)

So, we need to run lesser parallel bears than the number of cores.

**Comment by sils1297** [comment]
> and we have 4 processes from Bears each taking up 32MB

They provide 4 Gigabytes of RAM by default, are you saying we could even touch that with like 16 processes or so?

**Comment by AbdealiJK** [comment]
They provide 4 gb of RAM for the whole virtual machine ...
From that 50

**Comment by AbdealiJK** [comment]
%-| I got my math wrong (thought 100MB = 1GB)

**Comment by sils1297** [comment]
But I think you're right we can close this indeed. They have that bug upstream and they worked around for us so the problem doesn't affect us anymoe. No need for us to care anymore.
