### ISSUE TITLE
Default configs for files based on file extensions or language

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#568]
Currently, when no coafile is there (i.e. when a file is not inside a project), it throws an error.

it would be good to have an inbuilt coafile in coala which is used in such cases, and it can have different sections for various programming languages. The file extension can be used to estimate the programming language, and this internal coafile can have some default bears which can run for this programming language - making it easy to run coala on non-project files (i.e. standalone files containing code)

**Comment by sils1297** [comment]
This would be a similar concept to what we plan with guessing settings. I'm not sure if we should not rather prefer doing settings guessing right instead of having this. Rather do it once and do it good even if it takes longer.

**Comment by AbdealiJK** [comment]
In setting guessing it would first search for project config, then for home coarc, then finally go to this as fallback.

I felt they were independant - and this is not really a subset of setting guessing. setting guessing doesn't necessarily need this, it's just one of the possible fallbacks.

Hence made a new issue for it

**Comment by sils1297** [comment]
I agree but you'd normally use either one approach or the other for the
same thing. I think guessing is superior because we can e.g. look at the
files and guess indentation from the contents instead of having some
default for the language that only fits half the times.
Am 21.05.2015 19:03 schrieb "AbdealiJK" <notifications@github.com>:

**Comment by Makman2** [comment]
Guessing is definitely better imo like @silk1213 has written.
Anyway what we should do: If no coafile is found, we should display an information that we use our built-in (maybe guessed) settings, so the user doesn't wonder from where the "new" coafile falls^^

**Comment by sils1297** [comment]
closing in favour of https://github.com/coala-analyzer/coala/issues/1348
