### ISSUE TITLE
sys.path in TestHelper has all directories in test folder

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#574]
In the tests, paths are added to the path and not removed. This causes the sys.path to get cluttered and makes modules clash

```
def __check_module_skip(filename):
        module_dir = os.path.dirname(filename)
        if module_dir not in sys.path:
            sys.path.insert(0, module_dir)
```

**Comment by sils1297** [comment]
how about we write a preserve_sys_path contextmanager (like suppress_stdout), something like

```
@contextmanager
def preserve_sys_path():
    old = sys.path.copy()
    yield
    sys.path = old
```

So I'd say lets use this around all that?
