### ISSUE TITLE
build coala on different distributions

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#578]
shippable.com seems to offer continuous integration on different docker images. So we may be able to use that so we can offer official support for several platforms.

I know that this would bump the complexity of our CI even higher but it might be cool and we might find one or a few bugs from time to time with that.

Any opinions?

**Comment by Makman2** [comment]
As long as each CI itself is not too complex to maintain, I would go for it ;D

**Comment by AbdealiJK** [comment]
Do we want another CI ?
Isn't circleci + appveyor + travis(for mac ... eventually) enough ?

**Comment by sils1297** [comment]
Well, that's the question. We've had distribution specific bugs before but
probably the amount of ci we do is high enough... Feel free to close
Am 27.06.2015 1:37 nachm. schrieb "AbdealiJK" <notifications@github.com>:
