### ISSUE TITLE
ClangCloneDetectionBearTest on Ubuntu fails

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#586]
I recently installed `munkres` on my Ubuntu VM, but when running the tests:
```
 55/61 | ClangCloneDetectionBearTest
test_clones (__main__.ClangCloneDetectionBearTest) ... ok
test_dependencies (__main__.ClangCloneDetectionBearTest) ... ok
test_invalid_conditions (__main__.ClangCloneDetectionBearTest) ... ok
test_non_clones (__main__.ClangCloneDetectionBearTest) ... FAIL

======================================================================
FAIL: test_non_clones (__main__.ClangCloneDetectionBearTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mak/dev/coala/bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py", line 59, in test_non_clones
    lambda results:
  File "/home/mak/dev/coala/bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py", line 93, in check_clone_detection_bear
    result_check_function(uut.run_bear_from_section([], arg_dict))
  File "/home/mak/dev/coala/bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py", line 60, in <lambda>
    self.assertEqual(results, []))
AssertionError: Lists differ: [Result:
 origin: 'ClangCloneDetectionBear[3600 chars]22.'] != []

First list contains 9 additional elements.
First extra element 0:
Result:
 origin: 'ClangCloneDetectionBear'
 file: '/home/mak/dev/coala/bears/tests/codeclone_detection/clone_detection_samples/non_clones/test.c'
 line nr: 48
 severity: 2
'Code clone found. The other occurrence is at file /home/mak/dev/coala/bears/tests/codeclone_detection/clone_detection_samples/non_clones/test.c, line 27, function memcpy(void *restrict, const void *restrict, int). The similarity is 0.825.'

Diff is 3769 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 4 tests in 1.159s

FAILED (failures=1)
[WARNING][00:54:55] Unable to convert condition_list to the desired data type.
######################################################################
```

**Comment by sils1297** [comment]
Can we meet for investigation?

**Comment by Makman2** [comment]
Yeah, wednesday again?

**Comment by sils1297** [comment]
ok but not for so long

2015-05-30 19:39 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
no problem^^

**Comment by Makman2** [comment]
This seems to be an import problem on my side. Copying the `pad_matrix` algorithm that causes the problem directly into the code detection functions yields to a successful test. But using from munkres yields the mentioned error^^

**Comment by Makman2** [comment]
This seems to be a package problem using the apt-get pkg from the repos and not pip.
pip recognized the package, but suggested me to upgrade. After upgrade everything went fine :)

**Comment by Makman2** [comment]
Or maybe this was a python2 - python3 conflict somehow, but anyway pip is the better was :)

**Comment by sils1297** [comment]
maybe our users will have the same problem so I think we should pay
attention

2015-06-03 21:09 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Okay I'll try to reproduce this issue on a new machine using again Ubuntu 14.04 LTS.
I'll investigate it further^^ It could be a random broken dependency chain on my side.

**Comment by AbdealiJK** [comment]
I am able to reproduce this If I use `apt-get`'s python3-munkres package - munkres' version is 1.0.6
If I use `pip3`'s `munkres3` package I don't get the problem. - munkres' version is 1.0.5.5

So, I think the newer munkres version must have the issue

**Comment by Makman2** [comment]
Okay this is bad...

**Comment by sils1297** [comment]
Ok, can someone file that bug upstream?

2015-06-05 12:19 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by sils1297** [comment]
Filed upstream. They also seem to have that fixed in next minor release so no need to keep this open.

**Comment by sils1297** [comment]
Oh btw. I also have a fix that does the padding "manually" because it's better so this won't occur anymore.
