### ISSUE TITLE
test gedit plugin on windows

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#588]
```
sils	Hey, was there any progress on getting a gedit release out for other platforms (mac, windows)? I recall some blog post on windows a few months ago but I'm looking more for a possible release, i.e. does it make sense to spend work on getting a gedit plugin to work on windows/mac if the backend it connects to already is multi platform?
nacho	hey sils 
		there are plans
		though we need to fix the installer
		in the meantime you could use msys2 directly
sils	nacho, thanks!
```

According to that it would actually be possible to do that. @Makman2 do you have time to support this cause? This will probably grow complex to a degree and I don't think we can do this without you doing most of the stuff. If we want to truly support windows this would be cool to have.

So on short term we would need to get our dbus api to work on appveyor.

**Comment by Makman2** [comment]
You really want that for 0.2 alpha?
I think this is not a priority for now. Especially gedit on Windows...

**Comment by sils1297** [comment]
well Abdeali needs to know about that to work, right?

**Comment by Makman2** [comment]
But I think he concentrates on Linux, doesn't he?
Imo it's no problem that we first support Linux and over time also Windows. Like I said, gedit on Windows is another story^^

**Comment by AbdealiJK** [comment]
Also, dbus daemon on windows will be more difficult.

Yes, I concentrate on Linux

-----Original Message-----

**Comment by Makman2** [comment]
I think @AbdealiJK you should first implement everything on Linux, and then we'll see :)

**Comment by sils1297** [comment]
for now I don't see that coming, we have dbus support on linux though.
