### ISSUE TITLE
coala's version

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#592]
Currently, the version is used in setup.py and generate_pot.sh
(And they're both different)
it'd be better to have a version.txt file which can be used with `cat` and file read operations inside python as this would maintain consistency

**Comment by sils1297** [comment]
we also havee a version in zanata, the thing is in zanata, we currently track the next version and in the program we track the current version.

**Comment by sils1297** [comment]
just to not make it so easy for everyone :P

**Comment by sils1297** [comment]
@AbdealiJK we now can use `coala -v` to get the version to stdout. So you want that to be used in generate_pot, right? Shouldn't be hard.
