### ISSUE TITLE
New guideline about member visibility

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#594]
We need a guideline on naming conventions for member visibility.

*Inside classes*:
- No underscore: **public**
- One underscore `_`: **protected**
- Two underscores `__`: **private**

*Outside classes*:
- No underscore: **public**
- One underscore `_`: **private** (since double-underscore could interfere with special meanings)

Maybe we want also a "friend" accessor, but I don't think that makes sense right now^^

**Comment by sils1297** [comment]
please don't write that there is "private" and "protected", its somehow similar but its not the same. `_` is basically a sign saying `Don't touch me from the outside!!!`, `__` is a sign `REALLY, don't touch me from the outside, even if you're deriving from my class!`. `__` is special, please read http://stackoverflow.com/questions/1301346/the-meaning-of-a-single-and-a-double-underscore-before-an-object-name-in-python

**Comment by Makman2** [comment]
`__`: Even for classes?
And yes, sorry I didn't point out that underscores are no real visibility modifiers, they're just an indication :)

**Comment by sils1297** [comment]
> `__`: Even for classes?

I don't really get that question, especially for classes `__` is special, just read the stackoverflow posts.

**Comment by Makman2** [comment]
I thought you meant last time that outside classes the double-underscores have special meanings, but this makes more sense.
So then I've no idea, especially how to differentiate between "private" and "protected".

**Comment by Makman2** [comment]
I think we don't need such a guideline, we make it appropriate for every case individually.
If no one wants to say a word to this, I'll close this issue soon.

**Comment by sils1297** [comment]
ok
