### ISSUE TITLE
Need a function similar to fnmatch in glob

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#596]
In python's glob there's a function called `fnmatch` which allows to check if a filename would be in a glob of a pattern.

Currently, in our implementation, the only way to do that is by checking the output of `glob`
So, `glob('/**/*.py')` returns all matches and to check if a file is there we do: `file_name in glob('/**/*.py')`
This is bad, as if a pattern like `/**/*.py` is given, it'd take a huge time on most harddisks - while the actual regex test is very simple and much faster.

**Comment by smfn3321** [comment]
Ok, I will ad this functionality to our globbing soonish.
