### ISSUE TITLE
Highlight whitespace

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#606]
Now the the trailing whitespace is invisible when the bear finds one. We should do it like git and highlight it with a red color. Also I would make a specific message for the user, that it was concretely a trailing whitespace the bear found.
Current output:

```
/home/mak/dev/coala/coalib/tests/parsing/StringProcessingTest.py
| ...| ...| 
|   6|   6| from coalib.parsing.StringProcessing import unescape
|   7|   7| from coalib.parsing.StringProcessing import position_is_escaped
|   8|   8| 
|   9|   9| # TODO If no tests are performed, insert a skip here (if it doesn't disarm 
|    |    | [NORMAL] SpaceConsistencyBear:
|    |    | Line contains spacing inconsistencies.
|    |    | The following options are applicable to this result:
|    |    |  0: Do nothing.
|    |    |  1: Open a temporary clone of the file in an editor.
|    |    |  2: Apply the patch automatically.
|    |    | Please enter the number of the action you want to execute. 2
```

Line 9 contains the trailing whitespace btw.

**Comment by sils1297** [comment]
ah yeah we wanted that anyway, we wanted to replace spaces with a unicode
multiplication dot and tabs with an arrow or so highlighting it colorly :)
maybe there's another bug but this one is good too

2015-05-29 23:09 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by sils1297** [comment]
I think thats a general CLI feature, not tied to any bear

**Comment by sils1297** [comment]
I filed #609 for you
