### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc3' in file ./coalib/misc/StringConstants.py on line 35, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#610]
http://pastebin.com/fAchc2Gu

**Comment by Makman2** [comment]
Just use another character that is ASCII, I think I already had problems with this string on line 35.

**Comment by Makman2** [comment]
Maybe it's the `\u2192`

**Comment by Makman2** [comment]
Or better option: I think prepending an `u` before string makes it unicode, maybe this works^^

**Comment by Makman2** [comment]
The problem still persists?

**Comment by AbdealiJK** [comment]
Do you still get this ?

**Comment by sils1297** [comment]
no
