### ISSUE TITLE
SectionManager.run/gather_configuration: Return list of Section

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#611]
Implement a new class `Section` that represents a section and stores all relevant data.
This class shall be used in `SectionManager.run`/`gather_configuration`.

**Comment by Makman2** [comment]
Oh we already have a `Section` class: `coalib.settings.Section`

**Comment by sils1297** [comment]
we could store the bears in the section, that would be interesting and maybe simplify a few things because we can do the collecting too in the Section class

**Comment by sils1297** [comment]
see #792
