### ISSUE TITLE
Makman2's modules initialize test data in setUp

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#616]
@Makman2 you usually use setUp to initialize test strings and make them basically object global available.

Please consider simply doing an object static variable, i.e.:

```python
class SomeTest(unittest.TestCase):
    test_string1 = "..."

    def test_something(self):
        self.assertEqual(self.test_string1, "whatever")
```

This is better for performance because its not recreating all those objects every time but only when the class definition is executed (i.e. on importing) and IMO a little cleaner because you see at an instant that you're declaring object wide statics here.

I think we want to avoid setUp and tearDown mechanism as much as possible as they provide coupling between tests.

Should be easy to fix though!

**Comment by Makman2** [comment]
Oh yeah that's a really good point, I'll do this after the first stuff gets merged^^
