### ISSUE TITLE
unescaped_search_for() includes preceding escaped backslashes into the match

### ISSUE THREAD

**Issue by fneu** [coala-analyzer/coala#635]
When using `unescaped_search_for` to look for an unescaped pattern, the backslashes preceding the pattern are included into the match:

```python:
>>> from coalib.parsing.StringProcessing import unescaped_search_for
>>> next(unescaped_search_for(")","(\\\\)"))
<_sre.SRE_Match object; span=(1, 4), match='\\\\)'>
```

I consider this to be a bug, because it must not be interpreted as a "inhibited escape" but as an escaped backslash (therefore being a backslash without a special meaning) preceding the pattern that is being looked for.

**Comment by Makman2** [comment]
Will fix that by using `position_is_escaped` to strip results from normal `search_for`.
