### ISSUE TITLE
NestedSearchInBetweenTest: some regex patterns contain non escaped special chars

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#646]
Some test patterns have chars that have special meaning and are escaped because of that. But the declared strings are not raw!

**Comment by sils1297** [comment]
can you make them raw? Should be a matter of seconds... if tests don't pass
we can revert.

2015-06-11 9:27 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
yeah that was my idea^^
