### ISSUE TITLE
Non-ASCII character in setup.py

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#661]
When I try to do `python setup.py install` in Ubuntu 14.04 I get the following error:
```
  File "setup.py", line 15
SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 15, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

I believe it;s due to @Makman2 's name in the maintainers list

**Comment by sils1297** [comment]
you sure you executed that with python3 and not 2? Probably related to https://github.com/coala-analyzer/coala/issues/610

**Comment by AbdealiJK** [comment]
Ah. You're right - it's due to python2 and doesn't happen in python3.

With python3 I am getting another error : 
```
Error: could not create '/usr/local/bin/coala': Too many levels of symbolic links
```

Any clue about that ?

**Comment by sils1297** [comment]
that sounds bad. No clue.

2015-06-14 15:32 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by Makman2** [comment]
I'll try on my machine^^

**Comment by Makman2** [comment]
No such problems, my Ubuntu 14.04 LTS passes^^

**Comment by AbdealiJK** [comment]
That's weird. I'm closing this issue though - as it's resolved.

**Comment by AbdealiJK** [comment]
^ That was caused due to an unknown reason where /usr/local/bin/coala was a link to itself (hence the recursive link)

Once I deleted my /usr/local/bin/coala - everything worked fine. Must've been an artifact from something I had done earlier that I don't remember

**Comment by sils1297** [comment]
ok cool, thanks

2015-06-14 20:12 GMT+02:00 AbdealiJK <notifications@github.com>:
