### ISSUE TITLE
Glob does not work right ...

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#665]
For a test project https://github.com/Makman2/MP, where I have TODOs that I want to match with a keyword bear, I use the following pattern:
`src/**/*.java`
I definitely have TODOs and they are in files below the src-directory.
But coala does not recognize them :(

Using the pattern `**/*.java` works^^

**Comment by sils1297** [comment]
@Makman2 can you still reproduce that? @fneu did a heavy update on the globs. Please hurry, otherwise fneu won't be there to fix it.

**Comment by sils1297** [comment]
@Makman2 from code it looks like he fixed this on the way

**Comment by fneu** [comment]
this works for me with the new globs, with the exact same filesystem organization, a .txt file with "TODO" in it, and the glob pattern mentioned above. Please reopen if you experience this or a similar problem.
