### ISSUE TITLE
rultor: Add release script

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#668]
Would be good to have an automated release. Rultor can do that, we already can use it for merges right now.

These are the commands I used last time to create the deliverables:

```
python3 setup.py bdist --formats=gztar,zip,rpm
python3 setup.py sdist --formats=gztar,zip
```

We probably want to create something for windows too and that will need some dependencies but AFAIK it's possible to do from a linux build server.

**Comment by sils1297** [comment]
Actually I'm not sure we want rultor to do that. Would be nice to simply push something to a release/v... branch and our CI takes automatically care of that stuff.

**Comment by AbdealiJK** [comment]
I agree about doing it in CI - rultor is a little unstable. CircleCI's
"deploy" is meant for it.

What exactly does making a release comprise of ? I mean we are currently
doing pypi packages ... what's the diff between that and a release ? Only
the version number ?

**Comment by sils1297** [comment]
In the ideal case it's only the version number :) So for a release you
usually want a description what happened since the last one, would be nice
to extract that from the RELEASE_NOTES.md file automatically.

2015-07-02 9:43 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
actually we could make a rultor release script that pushes the release to that branch and circle does the deployment stuff then, shipping pypi packages. I think rultor might be able to even create releases on github...

**Comment by sils1297** [comment]
- [ ] `rultor release v0.2` should trigger the release
- [ ] rultor must release from master and push that to a 0.2 branch (according to how we name release branches)
- [ ] circle should push source distribution as release from release branches

**Comment by sils1297** [comment]
that PR (#803) already does basic releasing. Missing functionality is only uploading to pypi from rultor preferrably as per #804 .
