### ISSUE TITLE
write man-pages

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#68]
example could be:
https://bitbucket.org/logilab/pylint/src/7fc6c6cc2ef3519015b60d2d77995c92fe14a78f/man/pylint.1?at=default

**Comment by sils1297** [comment]
moving to 0.2, this is linux/unix only. For now we have the help output and the tutorial introduced in #273

**Comment by sils1297** [comment]
might be related to #302

**Comment by sils1297** [comment]
so its probably best to generate them from argparse or so, please see http://bugs.python.org/issue14102 . Here's a tutorial: https://andialbrecht.wordpress.com/2009/03/17/creating-a-man-page-with-distutils-and-optparse/

**Comment by sils1297** [comment]
maybe we can use http://crunchyfrog.googlecode.com/svn/tags/0.3.4/utils/command/build_manpage.py to generate the man page from our setup.py, could someone investigate?

**Comment by AbdealiJK** [comment]
I finally used http://crunchyfrog.googlecode.com/svn/tags/0.3.4/utils/command/build_manpage.py

**Comment by AbdealiJK** [comment]
#711 can generate manpages using `python setup.py build_manpage` or `python setup.py build` but this is not installed (just created in coala's root) nor does it run with `python setup.py install`

Still needs work.

**Comment by AbdealiJK** [comment]
Apparently this doesn't seem feasible without a custom bash script which is made to run after the install command.

It's nicely documented here - https://github.com/sampsyo/beets/issues/1501

**Comment by sils1297** [comment]
Postponing bug until 0.3. I still think we'll want a manpage, even if it needs a custom bash script.

**Comment by AbdealiJK** [comment]
So, apparently it's really bad if we install man page along with `pip` and setuptools. It's highly unrecommended - because then you can't use the package in a virtualenv easily.

So, it is recommended to add the manpage as a data_file and use the distribution's package manager to install manpages to the correct directory.
I think this is a valid point not to do this

**Comment by sils1297** [comment]
that makes me sad :( I had a dream... a dream in which coala has a man page... a dream in which every python program has an autogenerated manpage. Well...

**Comment by AbdealiJK** [comment]
This issue is not yet complete.

I still need to make it work with `python setup.py install`

**Comment by AbdealiJK** [comment]
Hey, so ... I have slight issues with making it work with `python setup.py install`
To make it install with `setup.py install` I need to do this:
```
class BuildPyCommand(setuptools.command.build_py.build_py):
    def run(self):
        self.run_command('build_manpage')
        setuptools.command.build_py.build_py.run(self)
```

This makes the `coala.1` file when I run `python setup.py install`. But now to move it to the installation path - i need to add to `package_data`. But it checks if the file exists before the `run` is called.

So, we have 2 options:
 - Make an empty `coala.1` file which will be filled when running the install
 - Override the `__init__` or something to run the `build_manpage` before the file's existence is checked.

I prefer the first.

**Comment by AbdealiJK** [comment]
Nevermind. I can fix this by using `data_files` rather than `package_data`
