### ISSUE TITLE
Bears need not support all python versions

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#708]
Bear developers should be able to decide which python versions they want to support.

For example : It may need an external dependency which is not available for py3.2 ... making it unusable in that version.

**Comment by AbdealiJK** [comment]
Another example which recently came up - pylint bear. - pylint does not support 3.2 anymore.

Same can be also valid for OS - some bears may not run on Windows due to deps.

**Comment by sils1297** [comment]
@AbdealiJK best thing would be to just raise an import error right? We need to catch exceptions on import anyway and can show that to the user as an error message. See https://github.com/coala-analyzer/coala/issues/603

**Comment by sils1297** [comment]
@AbdealiJK so that way we get a generic mechanism and not somthing tied to python version or OS or dependencies.

**Comment by AbdealiJK** [comment]
Yep, that does make sense.

**Comment by sils1297** [comment]
so then we could actually close this and only do #603, right?
