### ISSUE TITLE
Allow writing a simple decorated function instead of a bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#720]
most bears are just a function. Should be easy to have a decorator for this, right?

**Comment by sils1297** [comment]
example

```python
@local_bear
def KeywordBear(file, filename, keyword: str):
    for line in file:
        if keyword in line:
            yield Result("KeywordBear", filename, line, "Keyword found")
```

**Comment by sils1297** [comment]
Prototype implementation: https://github.com/coala-analyzer/coala/commit/9b75fc72d1c5d16117db820d696ebd0940c655ae

Not sure if that's the cleanest way to go but its the easiest by far.

**Comment by AbdealiJK** [comment]
What's the benefit for this though? I think a standard/single way to make bears is simpler.

Instead of adding 1 line of decorator `@local_bear`, you'd have 1 line of `class SpaceConsistencyBear(LocalBear):`

Syntatically it's not become easier and multiple methods which are exactly equivalent (with no additional benefits) make it confusing.

**Comment by sils1297** [comment]
@AbdealiJK the number of lines is actually the same in most cases.

One of the main aspects is that an analysis routine is by its nature a function. Throwing this into a class is unneeded and adds the possibility of hiding parameters for the analysis in the classes state. I.e. a function is more transparent and explicit. Also the look&feel is lighter and you get rid of four spaces extra indentation.

```python
class SomeBear(LocalBear):
    def run(self, *args, **kwargs):
        self.section["hidden_secred"]  # Bears can steal settings behind users back
    @staticmethod
    def get_dependencies():
        return [Dependency]
```

vs.

```python
@bear(BEAR_KIND.LOCAL, depends_on=[Dependency])
def do_something(*args, **kwargs):
    pass
```

So we have 4 spaces less indentation, three lines saved when using dependencies and the readability improved as well. It just makes sense to have the dependencies right above the function. It doesn't make sense to have a stupid "run" method, this name has absolutely no meaning.

**Comment by sils1297** [comment]
plus with the decorator one could even build the function such that you could easily just execute the function without coala which is great for testing (i.e. the decorator would take care of getting dependency executed in that case)

**Comment by sils1297** [comment]
So I'm in favor of full removal of the bear class and introduction of a decorator. It's only one decorator, not two! This allows us to fully get rid of the LocalBear/GlobalBear distinction in conjunction with https://github.com/coala-analyzer/coala/issues/724 .

The `bear` decorator could just use a coala pool to parallelize over files and within coala there's no difference between global and local bears, there's just generic data parallel programming! This also implies that finally any bear can be easily be dependent on any other bear allowing to do file parallel processing after some global processing which is nice :)

**Comment by AbdealiJK** [comment]
I'm in favour of it if youre removing the class :)

**Comment by sils1297** [comment]
closing because growing chaotic, reopening new bug soonish.
