### ISSUE TITLE
Next Generation Bears [$110]

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#725]
This is an umbrella bug for https://github.com/coala-analyzer/coala/issues/724 , https://github.com/coala-analyzer/coala/issues/722 , https://github.com/coala-analyzer/coala/issues/720 with complete removal of the old Bear class.

I opened this because I'll be putting a bounty on it soon :)

**Comment by sils1297** [comment]
I'm always there for helping designing this, trying to add info here and there.

**Comment by sils1297** [comment]
Requirements, this is the order in which I'd try to implement that stuff:

- [ ] A coala pool exists. Ideally it should provide the same functionality as multiprocessing.pool
    - [ ] If coala runs with only one process it simply uses traditional map/imap functions.
    - [ ] Else it parallelizes the execution over the processes coala has spawned anyways. This is at the same time a full abstraction over the hardware, i.e. that stuff could easily run across multiple machines if coala supports that later. Dataparallel programming in a pythonic and easy way managed by coala. (Yeah!)
- [ ] Results can be yielded or returned as list (i.e. function can be written as a generator)
    - [ ] If results are yielded they should be immediately transferred to the other process allowing e.g. a GUI to display a result while the bear still runs.
- [ ] A `bear` decorator exist.
    - [ ] That decorator provides the ability of automatically using coalib.pool for parallelizing over files, e.g.
        ```
        @bear(file_parallel=True)
        def some_bear(file, filename): pass
        ```
        - [ ] If no coala pool is given it just uses multiprocessing pool
- [ ] Bears can set dependencies in their signature `@bear() def some_bear(dependencies: [some_bear])` and will get a dict then with the bearnames as key and the values.
    - [ ] If no dependency results are given, the `bear` decorator executes `some_bear` automatically so it can be used without coala. This can get complex with multiple dependencies...
- [ ] All bears are refactored to use that (easy :))
- [ ] The Bear class doesn't exist anymore.

**Comment by sils1297** [comment]
Example of a local bear:

```python
from coalib.bears.bear import bear
from coalib.bearlib.pool import coala_pool

def without_comments(line): pass  # DEMO

@bear(file_parallel=True)
def remove_comments(filename, file, pool: coala_pool):
    # bear decorator postprocesses the result and adds the function name as origin and the
    # file in case of file-parallel data processing
    return HiddenResult(pool.map(without_comments, file))

@bear(file_parallel=True)
def find_keyword(filename, file, keyword: str, dependencies: [remove_comments]):
    # bear decorator knows that only results for the current file are interesting and
    # filters out all others, we know remove_comments only yields one result per file
    without_comments = dependencies[remove_comments][0]
    for line_nr, has_kw in enumerate(without_comments):
        yield Result(...)
```

**Comment by AbdealiJK** [comment]
@sils1297 - Let's take an example.
If I want to write a global bear to find some specific info about each file and then concatenate all these to give back 1 final output - how would I do this ?
Currently, `@bear @file_parallel` would run a function on every file. But what If I want to use the results of all these to do something else ?

For example - Something like find number of lines of code in the whole project

**Comment by sils1297** [comment]
```python
@bear
@file_parallel:
def count_file_lines(filename, file):
    yield HiddenResult(len(file))

@bear
@depends_on(count_file_lines)
def count_all_lines(file_dict, dependency_results):
    yield Result("All files have {} lines.".format(sum(result.value for result in dependency_results[count_file_lines])))
```

**Comment by AbdealiJK** [comment]
AH - looks cool.
So, global bears aren't parallelized

**Comment by sils1297** [comment]
@AbdealiJK there is no local or global bear anymore - there are only decorators like `file_parallel` that do data parallel execution of your bear. There are just bears.

**Comment by AbdealiJK** [comment]
So, decorators needed will be `depends_on` , `bear` and `file_parallel`. Anything else to add ?

**Comment by AbdealiJK** [comment]
Another question, as the bears have become functions now - there are a few ways to implement the bear_gathering.
 1. We set a condition that the filename and function name has to be same - which is a little irritating.
 1. We search all *.py files in the bear_dir to get the function name which is same as the bear

Also, currently the bear names in config files are camel case (eg: SpaceConsistencyBear) do we want to change that to underscore ? as they are now functions ?

**Comment by sils1297** [comment]
Actually I think the cleanest way is to use python annotations. So basically we want to import everything that is marked with the `@bear` decorator. We could just make the `@bear` decorator alter the signature, i.e. it adds an annotation for the return value. Think of it: a bear is anything that yields results so we could annotate it like

```
from coalib.results.Result import Result

def this_is_a_bear_without_using_a_decorator(file_dict) -> Result:
    pass
```

So the `@bear` decorator does nothing but adding this Result annotation and coala just checks for this annotation. This way we don't even rely on our decorators or the name of them.

**Comment by AbdealiJK** [comment]
But how would you differentiate between names ? If I write SpaceConsistencyBear in my coafile, How do I know which function to run ?

the bear-dev would have to specifiy what he wan't his bear to be called somewhere

**Comment by sils1297** [comment]
it would collect all functions from the SpaceConsistencyBear.py file. So we thought a lot about this problem and we chose this way because it allows grouping bears in an easy way (we also added an extra mechanism for that) and we know which files to search.

**Comment by AbdealiJK** [comment]
I see - so, I cannot define 2 bears in the same file ?

**Comment by sils1297** [comment]
If you define 2 bears in the same file your user can only execute both or none of them. They will both be imported.

**Comment by Makman2** [comment]
For the `@bear` decorator: Maybe we want to use a parameter that determines the parallelization, since this field is everytime associated with a bear and is required. We could default to global since this is the simplest parallelization model.

For example:
```python
@bear(Parallelization.FILE_PARALLEL)
def my_bear(whatever_input):
    pass
```

**Comment by Makman2** [comment]
And after short reading about annotations this is imo the way to go, since we can't remove the bear class completely. The bear class works in background, the new annotations shall create this class for us simply so we just need to write a decorated function.

**Comment by sils1297** [comment]
> For the `@bear` decorator: Maybe we want to use a parameter that determines the parallelization, 
> since this field is everytime associated with a bear and is required. We could default to global since 
> this is the simplest parallelization model.
> 
> For example:
> ```python
> @bear(Parallelization.FILE_PARALLEL)
> def my_bear(whatever_input):
>     pass
> ```

The idea is to split off parallelization from the coala internals. The bear doesn't need to have anything to do with parallelization so we can split it off. That being said if you want to do a global bear it get's easier for you. Second thing, we'll allow *arbitrary* parallelization, not only file wise but whatever-wise; you'll be able to write decorators for whatever you want. You can only do that as own decorators or you would need to come up with a parallelization object or so. IMO this is more generic, you can even chain decorators.

**Comment by Makman2** [comment]
okay if the next gen system would allow that this is definitely cooler and more flexible :)

**Comment by sils1297** [comment]
simple bear decorator solving the metadata problem:

```python
def copy_metadata(source, target, omit):
    if hasattr(source, "__metadata__"):
        target.__metadata__ = source.__metadata__
    else:
        target.__metadata__ = FunctionMetadata.from_function(source, omit)

def bear(func):
    def invoke_bear(**kwargs):
        func(**kwargs)

    copy_metadata(func, invoke_bear, ('self', ))
    return invoke_bear
```

**Comment by fneu** [comment]
> But how would you differentiate between names ? If I write SpaceConsistencyBear in my coafile, How do I know which function to run ?

or we name them `module.bear_name`. That is not beautiful but convenient, and most other options are bad:
 * bear name is interpreted as file name and all functions are imported: missing flexibility to import just one bear.
 * bear name is interpreted as function name: we need to search and there can be naming conflicts.

**Comment by sils1297** [comment]
closing because growing chaotic, reopening new bug soonish.
