### ISSUE TITLE
AppVeyor is not building PRs from forks

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#728]

**Comment by Makman2** [comment]
does this still aply?

**Comment by sils1297** [comment]
I think so, we should test...

2015-07-12 0:35 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by AbdealiJK** [comment]
https://github.com/coala-analyzer/coala/pull/753 - appveyor, circleci and scrutinizer are running on the PR from my fork.

Reopen if the issue occurs again

**Comment by sils1297** [comment]
thanks!

2015-07-13 7:11 GMT+02:00 AbdealiJK <notifications@github.com>:
