### ISSUE TITLE
coala tries to impolrt each bear twice

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#730]
at least this output seems to suggest that, in order to get that one nees to raise an exception in the SpaceConsistencyBear module code.

```
lasse@lssteadarch ~/prog/coala (git)-[sils/cliord] % ./coala -b SpaceConsistencyBear -c non
[WARNING][13:26:47] The requested coafile '/home/lasse/prog/coala/non' does not exist. Thus it will not be used.
[WARNING][13:26:47] Unable to collect bears from /home/lasse/prog/coala/coalib/misc/../../bears/spacing/SpaceConsistencyBear.py. Probably the file is malformed or the module code raises an exception.
[WARNING][13:26:47] Unable to collect bears from /home/lasse/prog/coala/coalib/misc/../../bears/spacing/SpaceConsistencyBear.py. Probably the file is malformed or the module code raises an exception.
Executing section Default...

```

**Comment by AbdealiJK** [comment]
This isn't really a bug ...
The file needs to be imported twice - once to check if it's localBear and the second time to check if it's a global bear.

So, if there is an exception while importing - it can't run the `kind()` function and so gives this warning twice

**Comment by sils1297** [comment]
Ah, right. So IMO we should try to import each bear only once and then check for locality/globality. However this will be implicitly solved with the new bear design so marking it as blocked.

**Comment by sils1297** [comment]
This will implicitly be fixed when we remove local bears.
