### ISSUE TITLE
Give nice error messages when files are run with python2

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#733]
Currently if `run_tests` or `coala` or `setup.py` etc are run with python2 it shows error messages like

```
Traceback (most recent call last):
  File "coala", line 18, in <module>
    from coalib.coala import main
  File "............/coala.py", line 14, in <module>

    from coalib.output.ConsoleInteractor import ConsoleInteractor
  File ..............\coalib\output\ConsoleInteractor.py", l
ine 29
    pre_padding: int=3,
               ^
SyntaxError: invalid syntax
```

It makes sense to catch these and show an error message that tells the user to run it with python3

**Comment by sils1297** [comment]
I think setup.py should catch that: https://github.com/coala-analyzer/coala/blob/master/setup.py#L13

Would be nice for run_tests and coala probably...

**Comment by sils1297** [comment]
actually this is difficult because the syntax changes and python seems to read the whole file first and then begin to execute it. I.e. in run_tests it will yield a syntax error, we cannot raise an exception first, same with setup and Mischas ü in his name. Given that I'd leave it with https://github.com/coala-analyzer/coala/pull/734 .

**Comment by sils1297** [comment]
@AbdealiJK agreed?

**Comment by sils1297** [comment]
ALthough it would be really beneficial to have a better way...

**Comment by AbdealiJK** [comment]
I asked this on SO and got responses in 5 mins :)
http://stackoverflow.com/questions/31240907/how-to-throw-exception-if-script-is-run-with-python-2?noredirect=1#comment50479994_31240907

Could you check it out - im not free atm

**Comment by sils1297** [comment]
I think I found a way, need to make the file at least syntactically python2
compliant, that involves using escapes instead of the ü for mischa

2015-07-06 10:35 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
Thanks, got a fix :)

**Comment by AbdealiJK** [comment]
This broke again - the issue is that `Constants` which is being imported in `setup.py` has non ascii chars.

So, the check needs to be done before this import
