### ISSUE TITLE
feature: Make PyLintBear global

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#735]
Shouldn't be that hard actually, add `{file}` to the msg pattern and parse it. Attention: that msg pattern may contain any signs dependent on the platform, so we probably want some multi-char delimiter like `PYLINT_PATH_DELIM` for seperating it from the rest, anyone using a PYLINT_PATH_DELIM in his path is hereby declared stupid and coala-hostile :)

**Comment by AbdealiJK** [comment]
if this is done - the PIPE needs to be changed to tmpfile also

**Comment by Makman2** [comment]
@sils1297 Maybe move to 0.4?

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#52
