### ISSUE TITLE
Add .service file for coala-dbus

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#738]
Coala-dbus needs a .service file which needs to be installed in the right directory for dbus to be able to start it automatically.

**Comment by AbdealiJK** [comment]
A question about this ... How exactly do we "install" this ? 

There doesnt seem to be any standard way of doing this ... platform independently.

Can I simply copy the .service file to a directory like `/usr/share/dbus/session-services` ?

**Comment by sils1297** [comment]
uhm this feature is linux only anyways right? So we just need to be distribution independent am I wrong? No idea how dbus<->mac looks
