### ISSUE TITLE
LanguageToolBear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#740]
Using https://pypi.python.org/pypi/py4j/0.8.2.1 we could use the API given at http://wiki.languagetool.org/java-api to create nice  natural language checking.

**Comment by sils1297** [comment]
Actually py4j isn't what we want as we want to use java classes, not communicate with a java app.

We probably want https://pypi.python.org/pypi/JPype1-py3/0.5.5.2 or https://github.com/CellProfiler/python-javabridge/ .

The latter would be cool, I filed an issue for them to support python3 https://github.com/CellProfiler/python-javabridge/issues/54 .

**Comment by sils1297** [comment]
Blocked by https://github.com/originell/jpype/issues/145 , PR in the works on https://github.com/coala-analyzer/coala/pull/742

**Comment by sils1297** [comment]
found workaround on #743

**Comment by AbdealiJK** [comment]
Why dont we use a python library equivalent for languagetool ?

**Comment by sils1297** [comment]
First, I don't know one, second LanguageTool is pretty good, you think we
find something with similar quality?

2015-07-08 10:46 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
ah you mean something like https://pypi.python.org/pypi/language-check/0.7.1 ?

**Comment by AbdealiJK** [comment]
Yeah :)
That will be much better than using jpype ... but i still dont like the
java dependency

Have you tried checking if one of these alternatives is natively written in
python or can be installed with system binaries ?
http://alternativeto.net/software/languagetool/

**Comment by sils1297** [comment]
they don't look that promising to me...

2015-07-08 10:58 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
merged
