### ISSUE TITLE
i18nTest and DiffTest do interfer because of multithreading

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#746]
```
 28/78 | DiffTest
msgfmt: error while opening "build\locale\bn_BD\LC_MESSAGES\coala.mo" for writing: No such file or directory
```
Can be easily reproduced when using `-j16`.

**Comment by sils1297** [comment]
note: nondeterministic. Several tests use translation files, however the i18nTest writes to them and does stuff with them so we either need to set up some rules for tests (i18n and Diff may not execute at the same time or wait for each other?) or we just silence the message.

Btw. the fault is not difftest, as it gets executed asynchronously, it comes from some other test *after* difftest.

**Comment by Makman2** [comment]
what about a file lock infrastructure for our tests? so you don't use directly `open()` etc, instead you use `CoalaTest.request_file_for_read` / `CoalaTest.request_file_for_write` or similar^^

**Comment by AbdealiJK** [comment]
But why is the file being opened for writing ? It should just want to read the translations from there right ?

**Comment by AbdealiJK** [comment]
Also - why does it try to do anything in the `build` directory anyway ?
For me it creates the `build/locale` directory on it's own

**Comment by Makman2** [comment]
yeah your commit seems to fix that.
Anyway we should maybe think about such a file structure I mentioned^^
But thinking about it further, I would say on-demand.

**Comment by AbdealiJK** [comment]
I think that's a bit too complicated. I think it's better to move all tests that need translations into 1 file - and this should work because then 2 tests won't try to write to the same file

**Comment by sils1297** [comment]
How about for translation generation testing we use a temporary directory, the other tests should just read and generate only on demand. We could easily generating mo's before executing tests.

**Comment by AbdealiJK** [comment]
Makes sense to generate mo files before running tests.

**Comment by AbdealiJK** [comment]
Could you suggest a way to do this ?

If I siimple compile it in TestHelper then coverage is lost for compilation.

I was thinking making a test named _i18nCompileTest.py - which will be sorted to the top due to the `_` and will be run before all other tests. But this is also not very good because the second test may need this and would wait.

What we could do also is that we can compile it once to `build-test` in TestHelper and then inside i18n again let it compile once in another folder (or same folder) just for the coverage

**Comment by sils1297** [comment]
> What we could do also is that we can compile it once to build-test in TestHelper and then inside i18n again let it compile once in another folder (or same folder) just for the coverage

I'd compile it where it belongs in TestHelper and in i18n use another folder because others only read

**Comment by Makman2** [comment]
Fixed
