### ISSUE TITLE
use python-gettext

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#752]
@Makman2 you check this out soon?

using
http://babel.pocoo.org/docs/babel-docs.pdf
for i18n is probably better and easier for the user as it can get installed via pip.

**Comment by sils1297** [comment]
I'm playing with this now.

**Comment by sils1297** [comment]
Babel seems unmaintained sadly and it doesn't work for me, I believe thats a known bug but the maintainer just isn't around, I dopped them a bug report.

**Comment by AbdealiJK** [comment]
What's wrong with gettext btw ?

**Comment by sils1297** [comment]
gettext is hard to install, a pip module is way more comfortable for our users as it gets installed automatically during our setup step. Makes also ci easier.

**Comment by sils1297** [comment]
babel is unmaintained and does not work. python-gettext is unmaintained but works so I'm taking it, if it gets a problem we can maintain it ourselves, its few lines of code. (Or even switching back would be easy.)

**Comment by sils1297** [comment]
python-gettext doesn't work on pypy. Let's stick with traditional gettext :(
