### ISSUE TITLE
PylintBear needs better tests

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#761]

**Comment by sils1297** [comment]
actually we need better test utilities for bears. And then we can ramp up tests for all bears.

**Comment by sils1297** [comment]
see discussion on https://github.com/coala-analyzer/coala/commit/7de0d957e07a8804706f834db41346d49c2cb9ef , I think this is newcomer suitable

**Comment by abit2** [comment]
I would like to work on this.

**Comment by sils1297** [comment]
@abit2 hi, splendid! Please approve our invitation to our org at https://github.com/orgs/coala-analyzer so we can assign you :)

**Comment by abit2** [comment]
@sils1297 @AbdealiJK not able to reproduce this issue.

**Comment by AbdealiJK** [comment]
@abit2 there is nothing to reproduce here. The tests for PyLintBear works fine for now.
The issue being brought up here is that the test isn't checking the correct thing.

We use `LocalBearTestHelper` which just checks if there were invalid lines in the test file or not using `assertLineValid` and so on.
The better method would be to have a function which takes in a list of line/col pairs and checks if the bear gave issues in those line/col

So, it would involve making a new function which takes in a list of line/col pairs and checking that results from the bear are at that point. And then revamping tests which use `LocalBearTestHelper` to use that

**Comment by AbdealiJK** [comment]
@sils1297 do you remember what this but is about ? The description i wrote above is actually for https://github.com/coala-analyzer/coala/issues/1111
