### ISSUE TITLE
pypi badges

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#763]
The project - https://pypi.python.org/pypi/beets has nice badges in the pypi page itself - this would be a good addition for coala.

Also, there is a pypi badge - mentioning the version of the project on pypi - that would also be a good addition to our README

[![Pypi](http://img.shields.io/pypi/v/coala.svg)](https://pypi.python.org/pypi/coala)

**Comment by sils1297** [comment]
We probably want to mirror our readme up to the front page of pypi, that's
an own bug.

As for the badge our URL seems to be http://img.shields.io/pypi/v/coala.svg
, feel free to add it.

2015-07-14 6:28 GMT+02:00 AbdealiJK <notifications@github.com>:
