### ISSUE TITLE
Json Interactor and LogPrinter

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#764]
I'd like a json interactor - simplest usecase is that if another program wants to use the results from coala, it'd be a very simple call like

```
p = subprocess.Popen(["coala", "--json", "/path/to/proj"], stdout=PIPE)
results = json.loads(p.stdout.readlines.())
```
Clean and simple.

The `--json` should be named better - maybe bring back the interactor cmd line arg.

Note : This is very useful in things where 
 1. You dont want to import coala like a library (due to various reasons like dependency problem?)
 2. You don't want to setup a dbus api and protocol for the whole thing - again, this can be when you cannot install dbus - examples: windows, inside a virtualenv, a minimal python installation where dbus is difficult to install, etc
 3. Also, This could later be directly used in the coala as a web service idea - and this would not restrict us to python based web frameworks

**Comment by sils1297** [comment]
nice idea, probably we simply want a `coala-json` binary for this as we
decided to split different output formats into different binaries. This
should be very easy to do.

2015-07-14 6:41 GMT+02:00 AbdealiJK <notifications@github.com>:
