### ISSUE TITLE
LanguageToolBear: Language detection

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#771]
depends on https://github.com/myint/language-check/issues/9

Actually we may want to implement the setting guessing things before tackling this.

**Comment by AbdealiJK** [comment]
We probably want to use https://pypi.python.org/pypi/guess-language rather ... its what language-check uses internally

From their code: `language_check/main.py`
```
                try:
                    from guess_language import guess_language
                except ImportError:
                    print('guess_language is unavailable.', file=sys.stderr)
                    return 1
                else:
                    language = guess_language(text)
                    if not args.api:
                        print('Detected language: {}'.format(language),
                              file=sys.stderr)
                    if not language:
                        return 1
 ```

**Comment by sils1297** [comment]
@AbdealiJK would be nice to fix https://github.com/myint/language-check/issues/9 upstream rather than here, don't you think?

**Comment by AbdealiJK** [comment]
@sils1297 I was talking about the same PR. I was trying to fix that when I read the code and found out that they're just using the module `guess-language`.
Not much point in exposing it from language-check because we can just use `guess-language` - it's easier.

They just do `guess_language(text)`

**Comment by AbdealiJK** [comment]
@sils1297 Sorry, seems like I was mistaken.
In language-check ... if you use `LanguageTool` class they do not auto guess the language
If you use the cmdline argument only they autoguess.

I am using guess_language in our own code (as they do not add it in their requirements.txt anyway). It seems easier to me.
