### ISSUE TITLE
Implement nice __repr__()

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#781]
The current `__repr__()` functions often use `__str__()`, which just contains data but no identification of the object (what `repr()` is supposed to return). Keeping track with python, I would suggest following naming scheme:
```
<ClassName object(member1: value1, member2: value2, maybe additional information) at 0xAAAAAA>
```

@coala-analyzer/coala-contributors opinions?

**Comment by sils1297** [comment]
@Makman2 can you provide a list of objects that need that refactoring?

**Comment by Makman2** [comment]
- `CountVector`
that's all :O

**Comment by sils1297** [comment]
@Makman2 please wait with the Count Vector, otherwise people could say others helped me writing the code for my thesis.
