### ISSUE TITLE
DBusTest fails for me locally

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#785]
I don't know why , @AbdealiJK I already sent you some debug information. Not sure how we can continue here...

**Comment by AbdealiJK** [comment]
Could you reiterate the debug info here?

The test takes about 60s even though it should be killed in 20s. And could you post the link to the paste in with the errors?

Also, what platform and python version?

And does it always fail? Or only sometimes?

-----Original Message-----

**Comment by sils1297** [comment]
@AbdealiJK it does always fail. Here's the output:

https://gist.github.com/sils1297/387d64d97020fa84d6de

**Comment by AbdealiJK** [comment]
I think the only way to figure it out is test which commit makes it fail.

Could you try it with the original dbustest pushed for the first time and after multiprocessing was introduced ?

I can't test it out ... So, need your help with this bug.

-----Original Message-----

**Comment by sils1297** [comment]
I'll bisect this.

2015-07-15 14:47 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
@AbdealiJK so it seems something in my environment makes the test break, seems to have nothing to do with commits.

**Comment by AbdealiJK** [comment]
Yay :)

Alright. Would be good to document this and add a check in the test if possible

-----Original Message-----

**Comment by sils1297** [comment]
buut question is what is wrong with my environment :P the other dbus tests
work by the way

2015-07-15 14:58 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Other dbus tests don't really use dbus. They just test that the classes work. This one actually tests dbus.

-----Original Message-----

**Comment by sils1297** [comment]
Oh, I'm using GNOME 3.16 on ArchLInux ;) and well I *could* reboot my
system because I think it did an update and kernel live patching doesn't
seem to be available yet :(

2015-07-15 15:00 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
The restart fixed it for @sils1297 , so closing this issue

**Comment by sils1297** [comment]
I should restart every few weeks or so...
