### ISSUE TITLE
Uninstalling coala doesnt remove everything

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#787]
Currently, if I do `python setup.py intall` it works fine.

But when I do `pip uninstall coala` after that - it doesnt work and removes only:
```
Uninstalling coala:
  /home/ajk/.pyenv/versions/3.4.2/bin/coala
  /home/ajk/.pyenv/versions/3.4.2/bin/coala-ci
  /home/ajk/.pyenv/versions/3.4.2/bin/coala-dbus
  /home/ajk/.pyenv/versions/3.4.2/lib/python3.4/site-packages/coala-0.1.1.dev0-py3.4.egg
```

A lot of files are left. The whole coalib :|

**Comment by sils1297** [comment]
you need to install with pip, I think you can do something like `pip
install --local .` or so... pip probably installs in some other manner than
usual setuptools? Could you try that?

2015-07-15 15:58 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Ah, right - If I install with `pip install .` it uninstalls everything
correctly
