### ISSUE TITLE
add requirements checking

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#791]
see https://requires.io/github/coala-analyzer/coala/requirements/?branch=master

we probably should fix our requirements to specific versions to test against...

**Comment by AbdealiJK** [comment]
Preferably not specific versions - better to use `>=`

**Comment by Makman2** [comment]
Allowing requirements to have a higher version number is better, allows to use an improved version of a package (as long as they don't change API heavily, then we can restrict versions, but cleaner would be to adapt code again).
Also: coala works fine with the newest packages. I would say we deal with specific ones if the need arises.

**Comment by sils1297** [comment]
They may break API, for stability we should fix versions and update those, rerun tests and commit
