### ISSUE TITLE
YAML configs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#795]
Out of curiosity here. Why don't we use YAML for configs ? It seems to be pretty popular (appveyor, circleci, mkdocs use it)

I believe it preserves order when reading (the same order can be used for writing) - http://yaml.org/type/omap.html

**Comment by sils1297** [comment]
One could write a parser for those. However I personally find the format
rather confusing and have yet to understand why people use it.

2015-07-16 7:14 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
Accepting patches for this one.

**Comment by AbdealiJK** [comment]
Hey, I want to do this.
I'm reopening it so that I remember to do it when I get free (assigning myself) :p

**Comment by AbdealiJK** [comment]
Closing again >_>
Note that apparently yaml's specs run in pages and is a very complex config language according to most people. https://github.com/coala-analyzer/cEPs/issues/11
