### ISSUE TITLE
master breaks sometimes

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#804]
hey, this is a serious one. Currently master breaks sometimes because we do some deployment stuff.

So let's try to simulate deployment on WIP branches, we already build the documentation e.g. on circle.

**Comment by sils1297** [comment]
oh hey moving deployment steps into rultor would actually solve a few things, maybe we should consider that! Because rultor does master fast forward after deployment. TBH I think that's the way to go although its uncomfortable...

**Comment by sils1297** [comment]
related to https://github.com/coala-analyzer/coala/issues/668

**Comment by sils1297** [comment]
pypi development release deployment depends on https://github.com/yegor256/rultor/issues/896

**Comment by AbdealiJK** [comment]
We had done this earlier, remember ? And rultor couldn't understand how to do encrypt the ZANATA_KEY and that caused lots of issues - resulting in finally doing it in circleci

**Comment by AbdealiJK** [comment]
I think time is a better metric too.

Specifically in the format - %Y%m%d%H%M%d - this will ensure that the last uploaded version is the latest dev version - makes more sense too because it gives more info on when it is uploaded

**Comment by sils1297** [comment]
> We had done this earlier, remember ? And rultor couldn't understand how to do encrypt the ZANATA_KEY and that caused lots of issues - resulting in finally doing it in circleci

Well, I suppose we didn't do it right. Using rultor has two advantages:

1. If we trigger rebuild on master on an old commit, the old data will be uploaded and override the actual newer one. Bad.
2. We can only prevent master to break if we do deployment before the merge but we need to do it after the review. Only rultor can do that.
