### ISSUE TITLE
test pip package after upload

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#805]
we shouldn't only deploy the pip package but also test that it actually works. I.e. just do the pip install and check the version number or so.

**Comment by sils1297** [comment]
@AbdealiJK , want to give it a try? You do have more bash experience than me and its a two liner.

**Comment by AbdealiJK** [comment]
How do you want to test that it works ? run it on our repo again ?

**Comment by sils1297** [comment]
```
pip install --pre coala --upgrade
coala -v
```

and that the output of `coala -v` is the same as `cat coalib/VERSION`

**Comment by sils1297** [comment]
on rultor

**Comment by AbdealiJK** [comment]
Ahh :P alright - I thought more rigorous testing

**Comment by sils1297** [comment]
not really, this test is only to test if the right version gets uploaded to
pip, we should do more integration testing in general but that shouldn't go
into rultor.

2015-07-18 13:46 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Oh wait, so this test is done in rultor ?

**Comment by sils1297** [comment]
yes because rultor deploys to pypi, you'll want to put it into
deploy.pypi.sh. It can't be tested elsewhere can it?

2015-07-18 13:47 GMT+02:00 AbdealiJK <notifications@github.com>:

> Oh wait, so this test is done in rultor ?
>
> On Sat, Jul 18, 2015 at 5:15 PM, Abdeali Kothari <abdealikothari@gmail.com
> >
> wrote:
>
> > Ahh :P alright - I thought more rigorous testing
> >
> > On Sat, Jul 18, 2015 at 5:15 PM, Lasse Schuirmann <

**Comment by AbdealiJK** [comment]
Fixed in https://github.com/coala-analyzer/coala/commit/66956d3c7468acdff543c8b63b330f2988d14b0e
