### ISSUE TITLE
Filternames are messy

### ISSUE THREAD

**Issue by smfn3321** [coala-analyzer/coala#81]
Because it is impractical to use the class name of a filter as it's filter_name for the filter import, the file name is being used.

To keep a certain consistency for filter identification throughout the program, only the one class should be imported from a filter file, that matches the file basename in a case sensitive way.

As a result, file and class name can be used for identification at any time without naming inconsistencies.

**Comment by sils1297** [comment]
IMO this is fixed, we don't import ancestors and bears can be specified by file basename. If anyone has complaints about this he can reopen.
