### ISSUE TITLE
coala-dbus: LogPrinter

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#811]
when running `coala-dbus` if there is an error that occurs internally, it is not caught. Or if the coalib is unable to give a result to a section in any way, the issue is not explained.

This should result in an Error message of some kind.

Also, Warnings, etc should be made possible

**Comment by sils1297** [comment]
Or we could "preview" the dbus api for 0.2

**Comment by AbdealiJK** [comment]
Fixed in https://github.com/coala-analyzer/coala/pull/854
