### ISSUE TITLE
coala-dbus: Config api

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#812]
Need to implement a configs api like how the `-S` currently works in cli

**Comment by sils1297** [comment]
shouldn't be hard, CliParser should be able to deal with an arbitrary argument parser

**Comment by sils1297** [comment]
@AbdealiJK any progress?

**Comment by AbdealiJK** [comment]
@sils1297 do we really want this ? We're not using dbus anywhere at the moment, and I think it should be made on a need basis.

**Comment by sils1297** [comment]
ok
