### ISSUE TITLE
rultor: Use own docker image

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#813]
this should speed up merges is functionally purely optional but not that hard to do.

**Comment by AbdealiJK** [comment]
So, I was able to create a docker with language-tools pre-installed. This fixes the pypi issue :)
I also installed all coala deps for ease of use.  

Im not sure how to push it. I did `docker push abdealijk/coala` and it uploaded some 400MB worth of stuff. But I can't see it in the docker hub.

Any help ?

**Comment by sils1297** [comment]
Can you send me the dockerfile and I'll take care?

2015-07-19 11:03 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
I didnt use a docker file. I pulled the rultor image and ran commands
inside it and then commited. I didnt use the dockerfile > build method

**Comment by sils1297** [comment]
can we discuss on gitter?

2015-07-19 11:42 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
I'm creating a rultor-python docker image in this repository:
https://github.com/coala-analyzer/rultor-python . I'll set up a docker hub
account for coala so it'll autobuild from this repository and we'll want to
create a dockerfile, that's way better maintainable. I'll help you with
that, it's really easy.

2015-07-19 11:46 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

**Comment by sils1297** [comment]
here's the build: https://registry.hub.docker.com/u/coala/rultor-python/
although it'll fail because there's no dockerfile.

2015-07-19 11:53 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:
