### ISSUE TITLE
Constants: Add os check functions

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#817]
we should have that centralized. Probably we want to rename the file to Constants or so, I'd really rather use an Enum instead of a string for this value.

**Comment by sils1297** [comment]
Actually we probably rather want functions `is_windows` and so on because that's shorter and with that enum it gets incredibly long.

**Comment by Makman2** [comment]
You think we need this? Using `platform` is imo not so complicated and well readable:
```python
import platform
system = platform.system()
if system == "Windows":
 #Windows
 pass
elif system == "Linux":
 # Linux
 pass
elif system == "Darwin":
 # OSX
 pass
```
And then we don't need another test for this "boilerplate".

**Comment by sils1297** [comment]
agreed
