### ISSUE TITLE
Editorconfig parser

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#819]
It may make sense to support parsing editorconfig. That should be fairly simple actually with the generality we have in the modules but there are way more important features out there right now. (https://github.com/coala-analyzer/coala/issues/725, I'm looking at you!)

**Comment by AbdealiJK** [comment]
This is a duplicate of https://github.com/coala-analyzer/coala/issues/204

**Comment by sils1297** [comment]
right thanks
