### ISSUE TITLE
Use sphinx for DBus API documentation

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#820]
that scales better. Not sure how that works out with readthedocs but we'll find a way.

**Comment by AbdealiJK** [comment]
No nice way to do it - https://github.com/mkdocs/mkdocs/issues/20

**Comment by sils1297** [comment]
Sphinx generates rst documents, wen can convert those to md with pandoc.
Am 18.07.2015 8:25 nachm. schrieb "AbdealiJK" <notifications@github.com>:

**Comment by sils1297** [comment]
closing in favour of https://github.com/coala-analyzer/coala/issues/1198
