### ISSUE TITLE
Reduce size of main script 

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#825]
This bug solves a 2 issues

 1. Reduce `coala-json` size
 2. Solve the pylint issue of having similar lines of code in the `coala-*` scripts

**Comment by sils1297** [comment]
@AbdealiJK isn't this solved by my recent addition of the coala-main routine? More or less...

**Comment by AbdealiJK** [comment]
Yes, it is. I thought you were trying to solve this bug with that.
