### ISSUE TITLE
readthedocs in google doesnt show a good summary

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#839]
Not sure how to fix this per se ...

But when I search for "coala rtfd" on google, I get a very bad summary (It shows the ascii art as the summary ...)

![capture](https://cloud.githubusercontent.com/assets/2200743/8772322/dd95d626-2ee8-11e5-9da4-64b804764ebd.PNG)

**Comment by AbdealiJK** [comment]
The folks at readthedocs suggested adding metadata. This is how it should be done in markdown:

http://pythonhosted.org/Markdown/extensions/meta_data.html

**Comment by sils1297** [comment]
for me the first result shows our summary text actually. But adding metadata sounds good and easy to do.

**Comment by AbdealiJK** [comment]
Out of curiosity: What did you search for ?

searching for `coala` gives the git repository which shows the summary correct

searching for `coala rtfd` shows the readthedocs page showing the ascii art
