### ISSUE TITLE
Error message since zanata generated last

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#841]
```
locale/de_DE.po:450: `msgid' and `msgstr' entries do not both end with '\n'
msgfmt: found 1 fatal error
```

from ~450:
```
+#: coalib/tests/output/ConsoleInteractionTest.py:402
+msgid "No bears to show.\n"
+msgstr "Es können keine Bären gezeigt werden."
```

It seems to be valid.

**Comment by sils1297** [comment]
wait, does that command fail?

**Comment by sils1297** [comment]
@AbdealiJK I corrected the translation in zanata, can you use the zanata pull script, try again and make a translation PR?

**Comment by AbdealiJK** [comment]
No, it does not fail - it must be a warning - this happens in tests ... and the translation tests do work without errors at the moment
