### ISSUE TITLE
ConsolePrinter: doesnt test COMPLEX_TEST_STRING

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#842]
There is no test with `COMPLEX_TEST_STRING` and ConsolePrinter. THis is bad because apparently `print` of COMPLEX_TEST_STRING doesnt work on windows.

**Comment by Makman2** [comment]
Imo the solution would be to encode the string manually with using the `errors="ignore"` parameter.

**Comment by sils1297** [comment]
@Makman2 IMO this isn't really release relevant, I'm happy to have it fixed for the release but it shouldn't be a blocker.

**Comment by sils1297** [comment]
plus, @Makman2 please move over to PyPrint :)

**Comment by Makman2** [comment]
Moved to https://github.com/coala-analyzer/PyPrint/issues/18.
