### ISSUE TITLE
LogPrinter: Document functions

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#843]
This is really necessary because of the different log types and mechanisms (like `log_message` vs `log` etc)

**Comment by sils1297** [comment]
@Makman2 can you please move this over to PyPrint, close this, and write a better summary of what you want? Maybe I'm just too tired but this is confusing me.

**Comment by Makman2** [comment]
I think we just close this and make it up to https://github.com/coala-analyzer/PyPrint/issues/17 to handle docs right^^
