### ISSUE TITLE
coala-json: Print json output to file

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#846]
usually wanted for data analysis.

**Comment by sils1297** [comment]
I hacked that in because I needed it: https://gist.github.com/sils1297/95be94393478b03a4f43

but it's not really clean...

**Comment by AbdealiJK** [comment]
This is very easy in all platforms.
`coala-json > file.json`

**Comment by sils1297** [comment]
indeed but it fails when you want to have log messages on the  console and
only json to file :)

2015-07-21 11:12 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
related: https://github.com/coala-analyzer/coala/issues/847

Maybe we'll just want this one and ignore the other? Or we could print log messages to stderr and the other stuff to stdout so when you reroute stdout you only get your content stuff and no logging.

**Comment by sils1297** [comment]
> Maybe we'll just want this one and ignore the other?

Yeah that was stupid. :) So we'll want a console option like `-o some_file.json` or so for this one. Ready to be worked upon!

**Comment by AbdealiJK** [comment]
@sudheesh001 This has now become really easy because Ive already given a custom argparser

**Comment by sudheesh001** [comment]
@AbdealiJK On it !
