### ISSUE TITLE
coala-json: Log messages to console

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#847]
it's nice to see there's progress, easy way would be using consoleprinter for logging or at least offer that to the user

**Comment by sils1297** [comment]
I hacked that in because I needed it: https://gist.github.com/sils1297/95be94393478b03a4f43

but it's not really clean...

**Comment by sils1297** [comment]
Ok we'll probably want an option like `--text-logs`or so that then does not log to json but simply to stdout. Ready to start!

**Comment by AbdealiJK** [comment]
@sils1297 maybe we want to output the logs to stderr ? This way we can easily distinguish between actual output and logs

**Comment by sils1297** [comment]
@AbdealiJK yes that we should probably do in general! Probably PyPrint needs an option for that? Can you file appropriate bugs?
