### ISSUE TITLE
travis: add german build

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#849]
we should be building against a localized environment. German is the most translated stuff in coala so we probably want a build node on travis which has `LANG=de_DE.UTF8` exported.

**Comment by sils1297** [comment]
depends on https://github.com/coala-analyzer/coala/issues/848

**Comment by AbdealiJK** [comment]
Seems to be working in travis - https://travis-ci.org/coala-analyzer/coala/builds/71871803

But to make sure, you'd want to print `python -c "import locale; print(locale.getdefaultlocale()"` to be sure

**Comment by sils1297** [comment]
@AbdealiJK I'm convinced https://travis-ci.org/coala-analyzer/coala/builds/71871803 doesn't work as intended, german build fails for me locally

**Comment by sils1297** [comment]
Not blocked anymore.

**Comment by AbdealiJK** [comment]
Actually it is blocked. Travis doesn't support locales.

https://github.com/travis-ci/travis-ci/issues/2598

**Comment by sils1297** [comment]
We can do it on circle then.
Am 06.08.2015 3:43 nachm. schrieb "AbdealiJK" <notifications@github.com>:

**Comment by sils1297** [comment]
i18n was removed
