### ISSUE TITLE
rultor: check for duplicate translations

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#850]
from gitter conversation:
"probably we want to search the POT file, get all strings to translate, strip whitespace off and search for duplicates or so"

**Comment by AbdealiJK** [comment]
There's a bug on zanata about this already https://bugzilla.redhat.com/show_bug.cgi?id=1225236

**Comment by sils1297** [comment]
@AbdealiJK they want to merge translations, we want to fail  rultor because we think we shouldn't do that stuff in the first place

**Comment by sils1297** [comment]
too much on our plate right now, shifting indefinitely into the future

**Comment by sils1297** [comment]
patches welcome of course.
