### ISSUE TITLE
Turn LogPrinter into an adapter

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#863]
Means the user does not need to derive from `LogPrinter` to use logging capatabilities, he just needs to pass the printer the LogPrinter shall work on top.

**Comment by sils1297** [comment]
Sounds good, example usage?

2015-07-22 23:57 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
```
# ConsolePrinter with logging capabilities:
logger = LogPrinter(ConsolePrinter())
# Happy logging!
```

**Comment by sils1297** [comment]
maybe the class should just be a `Log`? This is more objecty...

2015-07-23 0:02 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Possible, but imo a `Log` wouldn't derive from a printer, so I think `LogPrinter` is a better name.
A `Log` would give you access to all logged messages in my opinion, since it holds a log.
