### ISSUE TITLE
Implement a Log class

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#864]
A Log class is a simple list of log entries where logging functions are wrapped around.

We can just rename the `ListLogPrinter` to `Log` and modify it a bit.

**Comment by AbdealiJK** [comment]
What we can do is add if conditions to check if the `printer` given as arg has the function `print`

If it does not - we can check if it has the `append` or `push` and use those (so that ListLogPrinter and QueueLogPrinter can be implemented using something like `LogPrinter([])`)

**Comment by Makman2** [comment]
Checking if it's actually a printer is nice, but that would be for the `LogPrinter` class.
And I'm not sure if we should support `append` etc, since it just not uses the printer interfaces.

**Comment by Makman2** [comment]
So the design we come up with:
```python
class Log:
  def __init__(self, log_func):
    self._log_func = log_func

  def log(message):
    self._log_func(message)

  # Other logging functions...
   
 @classmethod
 def from(cls, obj):
   if isinstance(obj, Printer):
     return cls(obj.print)
   elif isinstance(obj, list):
     return cls(obj.append)
    # ...
   
# The user does:
Log.from(ConsolePrinter())
```

**Comment by Makman2** [comment]
Maybe we can also support multiple logging devices, means you can do this:
```python
mylist = []
Log.from(ConsolePrinter(), mylist)
```
and `Log` would output to both^^
Just as an idea.

**Comment by sils1297** [comment]
@Makman2 can you migrate this bug to the pyprint repository and close this
one?

2015-08-11 15:06 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by sils1297** [comment]
this is actually done, right?

**Comment by sils1297** [comment]
no it isn't my fault...

**Comment by sils1297** [comment]
@Makman2 I guess you'll want to move this into PyPrint? Can you write a nice summary of what you want over there and close this?

**Comment by Makman2** [comment]
Moved to https://github.com/coala-analyzer/PyPrint/issues/17.
