### ISSUE TITLE
No error if config file not found

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#866]
The exitvalue of coala in the case of "config file not found" is 0.

```
ajk:~ $ coala -c f
[WARNING][18:18:12] The requested coafile '/home/ajk/f' does not exist.
Executing section Default...
ajk:~ $ echo $?
0
```

If this is intended behaviour, I think this is unusual. Because if I do `coala-ci`, it would return 0 => It assumes no problems found in the file while it never actually did anything.

**Comment by sils1297** [comment]
well it's a warning, no erro

2015-07-24 14:50 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Yes, I know - but that's bad in `coala-ci` - where it wouldnt have analyzed the project as expected, and there would be no info given to the user that the config file was not being used

**Comment by AbdealiJK** [comment]
PS : I was just using `coala-ci --find-config` and it took me about 10 mins to realize that it wasnt finding any config file

**Comment by sils1297** [comment]
IMO we should be consistent, either it's an error and it fails or it's a
warning and coala continues.

2015-07-24 15:06 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Yes, i agree consistency is better.
So, I prefer throwing an error everywhere :)

**Comment by sils1297** [comment]
ok so f we make it an error the user either needs to have a config or needs
to set the `--save` flag. Do we want that?

2015-07-24 15:15 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
`--save` is not helpful in the `ci` scenario.

Maybe we can have a cmd line arg which tells which log-level should be considered as an "error" for the exitcode

**Comment by sils1297** [comment]
well save is not really *relevant* in the ci scenario.

I'm not sure if we want to make it that complicated with another cli arg...

2015-07-24 15:20 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
Ok, we'll want an Error if

a) No config was found and
b) Save flag was not set

**Comment by sils1297** [comment]
@AbdealiJK care to give this a try? Shouldn't be hard. Please self assign if you agree.

**Comment by AbdealiJK** [comment]
I'd rather complete the LinterBear before going into other bugs

**Comment by Makman2** [comment]
the new design will be:
- a missing `.coafile` will trigger a warning.
- a missing and explicitly passed custom coafile will trigger an error and return the error-code 2.
- nothing is triggered if coafile found
If the `--save` flag is specified, none of the cases above triggers something.
