### ISSUE TITLE
Sort imports alphabetically

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#868]
Some files have many imports, and I think structurizing them makes them better readable.
We could write a simple bear for this. This bear would just regex for import statements and would order them^^
This bear would just be prototype, when we implement a complete AST for python files we would improve the bear with it obviously.

**Comment by sils1297** [comment]
sounds good and easy, alphabetically?

2015-07-24 16:35 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
i.e.
```python
import readline
import shutil
import sys

from coalib.misc.DictUtilities import inverse_dicts
from coalib.misc.Exceptions import PermissionException
from coalib.misc.i18n import _
from coalib.output.printers.ConsolePrinter import ConsolePrinter
from coalib.output.printers.LOG_LEVEL import LOG_LEVEL
from coalib.output.printers.NullPrinter import NullPrinter
from coalib.results.Result import Result
from coalib.results.result_actions.OpenEditorAction import OpenEditorAction
from coalib.results.result_actions.ApplyPatchAction import ApplyPatchAction
from coalib.results.RESULT_SEVERITY import (
    RESULT_SEVERITY,
    RESULT_SEVERITY_COLORS)
from coalib.settings.Setting import Setting
```
system imports and coala imports will be separated.

**Comment by sils1297** [comment]
yes

2015-07-24 16:44 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by sils1297** [comment]
@Makman2 assigning you. TODO:

- [ ] Write that down in the codestyle specification.
- [ ] Write a simple bear that takes care of that. An approach could be scanning for the import keyword and then sort those lines alphabetically but only within their own blocks, i.e. if the user has two newlines (or any non-import line) between two imports they could be treated as separate blocks and sorted independently. Just an idea.

**Comment by sils1297** [comment]
There's isort which does this, there's already a PR which adds a bear for it, we just have to add a test there, merge and use it!

**Comment by sils1297** [comment]
See https://github.com/coala-analyzer/coala/pull/1152

**Comment by Makman2** [comment]
Since #1152 is merged, we only need to integrate that into the coafile, then we can close this issue :)

**Comment by sils1297** [comment]
this is kinda blocked since we still rely on sys.path modification in tests, will be doable when wee use pytest :)

**Comment by sils1297** [comment]
Ok this would be newcomer suitable as soon as we switched to pytest (thus currently blocked): just use the `PyImortSortBear`, add it to the coafile, fix everything (best to use default_action for this - see tutorial) using coala and do the commit.

**Comment by abit2** [comment]
Please ,can someone elaborate.

**Comment by Makman2** [comment]
@abit2 what do you mean with "elaborate"? This issue is blocked until we switched to `pytest` as a test framework. Currently we use `unittest` which requires to insert a `sys.path.insert(0, ".")` so coala imports are recognized correctly. Because of that the *PyImportSortBear* can't work correctly.
I hope it's a bit better understandable now :)

**Comment by CruiseDevice** [comment]
Using just isort will solve this issue? I searched for isort library, i think isort will do the work.

**Comment by sils1297** [comment]
As pointed out above the `PyImortSortBear` can be used, it'll automatically take care of this. Please note that this issue has `status/blocked` which means that it depends on another issue to be resolved, namely the PyTest switch as it allows us to free our imports from the `sys.path` mangling currently needed because we use our own test framework.

**Currently this issue is blocked. Do not attempt to work on it.**

**Comment by AbdealiJK** [comment]
I implemented pytest and removed those pesky `sys.path` lines. And I also added PyImportSortBear in coafile.
But, the bear doesn't seem to be working. Can someone take a look ? https://github.com/coala-analyzer/coala/commit/48748751fdb91806082f6ae28090e64041939ea9
