### ISSUE TITLE
0.3 release name

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#873]
Anyone having a proposal for the 0.3 release name, successor of coala wombat, please post it here.

I hereby nominate `coala kangaroo`. :)

**Comment by sils1297** [comment]
and we need to craft the appropriate logo :)

**Comment by sils1297** [comment]
inspiration: https://en.wikipedia.org/wiki/Fauna_of_Australia

**Comment by cw1** [comment]
How about 'platypus'? As mammal, it's unique, and as oviparous animal it is the most natural thing in the world (Just like coala: unique but still a natural thing).

**Comment by sils1297** [comment]
Sounds cool :)

**Comment by sils1297** [comment]
Taking that.
