### ISSUE TITLE
coala install: 'astroid' dependency 'logilab-common' fails if above version 0.63

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#879]
Steps to reproduce:
- if you don't have `astroid`, install it
- upgrade `logilab-common` (at least to a version above 0.63)
- run the setup script `python ./setup.py install`

To be able to install coala again, just upgrade the astroid package (even if it's already latest version):
`pip install astroid --upgrade`

**Comment by sils1297** [comment]
Workaround in PR https://github.com/coala-analyzer/coala/pull/880 . Not sure how we can fix this properly for our users.

**Comment by AbdealiJK** [comment]
So, this is only for windows ?

**Comment by sils1297** [comment]
It occurs on appveyor because they changed some packages I presume but it may be valid on all distributions.

**Comment by Makman2** [comment]
Seems to be only a windows issue, on Ubuntu it works well even with `logilab-common` version > 1.0

**Comment by sils1297** [comment]
This is a pip issue and has nothing to do with our requirements definition, right?
