### ISSUE TITLE
cp850 vs cp1252 - windows likes cp1252 but uses cp850 actually

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#883]
The previous bug we had for `run_tests.py` I tried to solve with a simple encoding routine - `message.encode(locale.getpreferredencoding(), errors="ignore")` - did not work because windows prefers cp1252, but uses cp850 actually. The bugging characters where actually supported by cp1252, but not from cp850!
the best approach is to get the used encoding via
`sys.stdout.encoding`
and use that.

**Comment by sils1297** [comment]
@Makman2 maybe we should have some utility function that handles the encoding

**Comment by Makman2** [comment]
This is console related, and shorter than `sys.stdout.encoding` we won't get. I wouldn't favor one^^
