### ISSUE TITLE
Can't "exit" cmd on Windows after running tests

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#886]
After running tests on the cmd it does not close when typing `exit`, it just does nothing and waits forever.
Seems we don't close some resources right^^

**Comment by Makman2** [comment]
This is either a problem of the libclang tests or gettext tests, because after I enable the according packages for windows via environment, I can't exit. If not enabling, exit is normally possible.

**Comment by Makman2** [comment]
No that is not a problem of the libclang or gettext tests, after running tests several times without those I can't exit too...

**Comment by Makman2** [comment]
Exiting works only with CTRL+BREAK^^

**Comment by sils1297** [comment]
@Makman2 assigning you for investigation because noone of us can help you here I fear.

**Comment by sils1297** [comment]
Relevant issue pointed out in these commits: https://github.com/coala-analyzer/coala/pull/960

**Comment by Makman2** [comment]
I would refer to #915, this should fix it.

**Comment by Makman2** [comment]
Can't reproduce any more, we have pytest now anyway which should solve this.
