### ISSUE TITLE
function annotations got a PEP

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#887]
we should think about trying to follow that standard more closely: https://www.python.org/dev/peps/pep-0484/#abstract

**Comment by Makman2** [comment]
you mean type annotations etc.?
yeah this is cool makes code more strict and static-typed, but I'm a bit irritated with the generic functions when looking over them^^ And what about typed tuples?

**Comment by sils1297** [comment]
Time's short, we have bigger fish to fry than to rethink our function annotation concept which actually works very well. Accepting "patches" of course if someone really wants to look into this.
