### ISSUE TITLE
Cancelation approaches

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#890]
This is a software design issue to track gists that show which approaches work to make arbitrary code cancellable. The overall goal is to:

1. Start a subprocess, preferrably via multiprocessing for easy data synchronization. The process may contain prepared code around a long running unprepared code fragment which is intended to be cancelled.
2. Interrupt that process: The interrupt should throw an exception in the "long running unprepared code fragment" i.e. execute finally clauses and be catchable.

**Comment by Makman2** [comment]
Even this list should be bigger, but I found the solution...
https://gist.github.com/Makman2/f6024138108d801a8ce6

**Comment by Makman2** [comment]
I think can be closed in favor of #915.
