### ISSUE TITLE
Linter Bears

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#897]
So, Ive been looking at a lot of linter plugins in sublime, atom and also gnome-code-assistance.
One thing they have in common is that they make a **Linter** class which is used to run multiple linters.

The linter class basically runs an executable with some args and parses the output using a predefined regex pattern.

So, the inputs to the LinterBear are `executable`, `args`, `regex` - thats it !

With this, we can easily make any linter's bear in a matter of minutes.

Some references:

 - `__init__.py` files in https://github.com/GNOME/gnome-code-assistance/tree/master/backends/
 - atom's linter - https://atom.io/packages/linter
 - sublime-linter - http://www.sublimelinter.com/en/latest/

Linters:
 - [x] - JSON : using python's `json` module
 - [ ] - JSON Schema validation: https://people.collabora.com/~pwith/walbottle/ ?
 - [x] - Python - PyLint
 - [x] - Javascript - JSHint
 - [x] - C/CPP - cpplint, clang
 - [x] - PHP - using `php -l`
 - [x] - Ruby - using `ruby -wc`
 - [ ] - Ruby (Bakeman)
 - [ ] - Java - using `java -Xlint`
 - [x] - Java - checkstyle
 - [x] - CSS - csslint
 - [ ] - reStructuredText - rst
 - [ ] - Markdown - mdast-lint or markdownlint
 - [x] - Natural Language: Alex, proselint
 - [x] - C# - using mono's `mcs`
 - [x] - Dockerfile - dockerfile_lint
 - [ ] - Bash : shellcheck
 - [ ] - HTML : HTML-lint or HTML tidy
 - [ ] - CSV : 
 - [ ] - TEX : chktex
 - [ ] - Matlab : Matlab's mlint
 - [ ] - R : lintr
 - [ ] - XML : xmllint
 - [ ] - XML schema validation
 - [ ] - YAML : yaml-js
 - [ ] - CoffeScript - coffeelint
 - [ ] - Haskell : hlint
 - [ ] - Bootstrap - bootlint
 - [ ] - Gettext - Dennis
 - [ ] - Go : golint
 - [ ] - SQL - sqlint

Auto fixers:
 - [ ] - Python : autopep8
 - [ ] - JS : fixmyjs
 - [ ] - PHP : Php code sniffer

**Comment by sils1297** [comment]
Cool, let's design that first!

**Comment by sils1297** [comment]
usage example:

```python
from coalint import linter
from ... import RESULT_SEVERITY

@bear
linter(binary="coala",
       arguments="--find-config",
       severity_translation=
           {"trace": RESULT_SEVERITY.DEBUG,
            "info": RESULT_SEVERITY.INFO,
            "warning": RESULT_SEVERITY.WARNING,
            "error": RESULT_SEVERITY.ERROR},
       parse_format="R-{line_nr}-{severity}-{origin}:{message}")
```

**Comment by AbdealiJK** [comment]
I tried implementing a Linter. I then decided I'd peek at the sublime linter code and found it to be much better tested and robust than what I wrote. So, I'm hoping the maintainer of SublimeLinter would like to make an abstract library for linters which will help anyone handle various types of linters

Heres the request : https://github.com/SublimeLinter/SublimeLinter3/issues/311

**Comment by sils1297** [comment]
@AbdealiJK still on it? This is strategically very important, making us able to integrate lots of analytics very fast.

**Comment by sils1297** [comment]
@AbdealiJK ping?

**Comment by AbdealiJK** [comment]
I have no completed it yet. I'll do it soon.
Seems like SublimeLinter doesnt wish to do it :'( .

**Comment by sils1297** [comment]
@AbdealiJK thanks, let me know if you need anything, I think this will really help us.

**Comment by AbdealiJK** [comment]
http://pastebin.com/MD6rr2vm

So, the implementation I was working on involved making a LinterMeta which checks which type of linter the class is, compiles all the regex which will be used to get the results and handles basic things like that. Majority of this was taken from SublimeLInter
The linter class is a base class which actually saves which syntax the linter handles. The class in pastebin is extremely documented, so not much to say ...

 - I removed abilities which allowed the linter to check for languages inside another language - like python inside markdown, or JS inside HTML. This made the whole thing too complicated. Also, it became complicated because the bears would have to register that they can parse a specific language and multiple bears being enabled for the same language becomes complicated, etc, etc
 - I removed lots of sublime specific code and sublime settings related stuff - but only for some functions. Some functions are still left.
 - I removed the parts where the linter uses `stdin` as an input method.

A lot more clean up is needed ... if anyone's free, please continue this.

**Comment by sils1297** [comment]
see also https://github.com/sk-/git-lint/blob/master/gitlint/linters.py

**Comment by sils1297** [comment]
https://github.com/sk-/git-lint/blob/master/gitlint/configs/config.yaml

**Comment by AbdealiJK** [comment]
Has anything been done in this ? Or can I continue it ?
Have you spoken to sk- ? I notice emails were exchanged.

**Comment by sils1297** [comment]
@AbdealiJK nothing in there that would help here. The important part is that he seems to have found a nice format to write down linter specs, maybe we can do something similar/the same.

**Comment by AbdealiJK** [comment]
I spent majority of my night planing and designing a wonder class which could handle all the linters and I finally decided I was going crazy.
So, I decided to keep it simple. I'm going to go at the linters one by one and all features to out abstracted Linter class as and when new features are needed.

https://github.com/coala-analyzer/coala/pull/1109 is my attempt to abstract the Pylint, I'll add pep8 and a few more soon so that if necessary, it gets more features.
Let me know if you see something you don't like in it

**Comment by sils1297** [comment]
@AbdealiJK for mdast/alex there's already a WIP commit: https://github.com/coala-analyzer/coala/pull/1080 , the problem is that I'm not good at JS and installing that stuff globally is hard because there e.g. is already an alex binary on our CI systems, so we may want to pull them down during setup or so?

**Comment by sils1297** [comment]
@AbdealiJK about the auto fixers: we could take Autopep8 or so, run only one correction at a time and then we get the issue descriptions to the fixes. (We talked about this but never wrote that down)

**Comment by sils1297** [comment]
@AbdealiJK just a note, all the linters should obey the `max_line_length` and the `tab_width` (/indentation) setting. I've just added that for the PEP8Bear

**Comment by AbdealiJK** [comment]
@sils1297 We should maybe close this ? As it's way too huge a task. And anyway we have multiple smaller issues for each bear.

You could document this in Wiki - as prospective Bears ?

**Comment by sils1297** [comment]
@AbdealiJK sure, can you move it to the wiki page and close it?

**Comment by AbdealiJK** [comment]
Moved to wiki page - https://github.com/coala-analyzer/coala/wiki/Bears
