### ISSUE TITLE
Get text data from stdin and parse

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#901]

**Comment by AbdealiJK** [comment]
Need the file path also somehow - so that `--find-config` doesnt break

**Comment by sils1297** [comment]
@AbdealiJK could you elaborate? This a feature request?

**Comment by AbdealiJK** [comment]
It is a feature reqeust.
This is a method of using coala without having a physical file - i.e. The textual data is given to coala using stdin.
This is one of the ways that linters get data which is not in actual files.

**Comment by sils1297** [comment]
IMO not important, accepting patches.
