### ISSUE TITLE
Make coala-bears

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#903]
It makes sense to move most (if not all) bears out into a new repo named `coala-bears`

**Comment by Makman2** [comment]
you sure? I think (nearly) no one wants to use coala without bears^^ Especially we write helpers for some bears, shall we part them too?
I'm not in favor of this^^

**Comment by sils1297** [comment]
@AbdealiJK ?

**Comment by sils1297** [comment]
I agree closing this would be good.

**Comment by AbdealiJK** [comment]
I seem to have missed @Makman2 's comment on this

@Makman2 : Lets say we write 10 bears. And each bear depends on things like pylint, clang, language-check etc ...
We'd soon get a HUGE dependency list ... which is not nice. It makes sense to provide it in batches or separately

**Comment by sils1297** [comment]
@AbdealiJK you think we should setup infrastructure for this like... now? I mean sooner or later, we'll need that and then we'll probably want to go for groups of bears that make sense into one package.

**Comment by AbdealiJK** [comment]
Not sure if it should be done. RIght now, it doesnt matter (as we dont have
many bears).
I added the issue so that it remains a reminder that eventually (or now) it
needs to be done. i.e. Decoupling the bears from the coala package.

**Comment by Makman2** [comment]
Highly depends on the bears. If it's something super-advanced, yes then part, but if it's generic and universal keep it in coala imo

**Comment by sils1297** [comment]
Closing this for now, we'll probably open another bug for this when it becomes an issue (even if this issue existed :))
