### ISSUE TITLE
Integrate coala into existing build systems as a build step

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#904]
I.e. we implement macros for CMake for easy coala use.
So a check-list of build systems we want support:

- [ ] Setuptools
- [ ] automake
- [ ] CMake

**Comment by sils1297** [comment]
Setuptools should be easy, we'd just provide a setup command in the coalib people can import. The other stuff is a bit optional/wontfix for me because its lots of work and we don't have time right now.

**Comment by Makman2** [comment]
We can move it to 0.5 maybe^^

**Comment by sils1297** [comment]
@Makman2 any progress? You wanted it in cmake right?

**Comment by Makman2** [comment]
It's possible to add custom targets the CMakeLists.txt writer can use however he wants. But I haven't anything done for this issue^^

**Comment by sils1297** [comment]
essentially you'd want to pass the clang flags to coala there I guess?

**Comment by Makman2** [comment]
should be possible, at least that functionality should be encapsulated inside another CMake-function, one for plain coala usage, and one for C/C++ checks generated from workspace automatically^^

**Comment by Makman2** [comment]
Created a new repository for CMake stuff: https://github.com/coala-analyzer/coala-cmake

**Comment by Makman2** [comment]
Alright, we have a repo for CMake scripts, setuptools should get another issue. And automake, I don't like it that much, so `wontfix/accepting-patches` for it since there's plenty of other things that need to get done.

--> Setuptools issue: #1754
