### ISSUE TITLE
ClangCloneDetectionBear: Better status messages

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#906]
The percentage messages are a bit confusing since you might think the whole clone detection is meant (which is definitely wrong).

**Comment by sils1297** [comment]
notabug... though an easy issue to fix. Just change debug messages so this gets clearer for now.

**Comment by sils1297** [comment]
Also the bear probably should rather use `info` than `debug`

**Comment by abit2** [comment]
@sils1297 @Makman2 ,should it be self.info("Creating results...") instead of self.debug("Creating results...") and  instead of "difference of these two occurrences is " will it be right to write "difference of these two occurrences(in percentage) is "

**Comment by sils1297** [comment]
@abit2 hey, welcome! I think instead of `(in percentage)` I'd rather append a simple `%` to the number.

Actually I'm not that convinced of that info use rather than debug, @Makman2 what were we thinking?

**Comment by Makman2** [comment]
the messages are currently quite verbose, I would keep them 'debug'. If we shorten them and make them more "efficient" we could switch to 'info', because then it's valuable user information.

**Comment by sils1297** [comment]
Yeah, I think the same. Messaging can be improved but debug level is good.

2016-02-02 14:11 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by abit2** [comment]
@sils1297 
"difference of these two occurrences is "
"{difference} %.").format( 
something like this??

**Comment by sils1297** [comment]
I wouldn't do a space before %, looks good otherwise

2016-02-02 14:15 GMT+01:00 ankit <notifications@github.com>:

**Comment by abit2** [comment]
got it

**Comment by NalinG** [comment]
Hello, 
Is this issue open and if it is, can I send a PR.

**Comment by sils1297** [comment]
@NalinG hey, probably best if you drop in at https://gitter.im/coala-analyzer/coala so we can speak there. Feel free to work on this. I've sent you an invitation to the org so we can assign you, please ping back when you accepted the invitation so we can do that.

@abit2 I assume you aren't working on this since you have not expressed explicit intent to do so.

**Comment by NalinG** [comment]
Hi, I accepted the invitation and ready to start working :)

**Comment by NalinG** [comment]
Please do check if this is correct.

**Comment by NalinG** [comment]
I rebased the PR
