### ISSUE TITLE
Make rultor not push if there are more bugs than features

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#907]
We could use the github api along with the the labels `bug` and `feature` to check this

**Comment by sils1297** [comment]
actually that may be a thing they want to do upstream.

2015-08-10 14:23 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
filed upstream: https://github.com/yegor256/rultor/issues/916
