### ISSUE TITLE
Handle KeyboardInterrupt

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#915]
The usage of multiprocessing.Process is problematic, because KeyboardInterrupt are also delegated to them. The best solution is to let the coala main thread handle it and propagate it down to the spawned subprocesses. There are two approaches (I have in mind):

1. **The cool approach, but more complicated one (if it anyway works):**
   There's a possibility to send asynchronously an exception from one thread to another thread (not subprocess to subprocess). The script for python2 can be found here: https://gist.github.com/liuw/2407154.
   So what we need to do: We must be able to send a message to the subprocess that causes it to create a new asynchrone thread for it. Hopefully it works with sockets. If this happens, the created thread only needs to invoke the async-exception-raiser and the running bear can be KeyboardInterrupted directly.
   The super nice advantage of this approach: The user does not have to bother of checking any cancellation status, he just needs to program save with try-catch-finally statements.

2. **The simpler but not so superior approach (that loads off some work to the user):**
   We offer manual cancellation status polling. If we request a bear to quit, the implementer of the bear is responsible to check the cancellation status here and there in computation-intensive algorithms. Easier and definitely working, but the user must know how to tweak the cancelability of a bear. Even we can't interrupt after each statement (it is possible by checking the cancellation status everytime, but this is overhead and reduces execution speed significantly, not talking about that the code looks just like crap with every second line with the check).

**Comment by Makman2** [comment]
For approach one:
This is a bit more imperformant, but should work safely:
1. Create a new multiprocessing.Process class
2. The multiprocessing.Process class spawns a Thread (yes, a threading.Thread)
3. The thread polls for a cancellation event we passed to the process/it waits for the event (via `Event.wait`).
4. The bear gets executed normally in another thread
5. If the poll thread recognizes the event raise, it throws asynchronously an exception with the hacky way.

**Comment by sils1297** [comment]
@Makman2 clearing release, this is your task, please reschedule it as it fits your schedule. I'd love to see this getting done somewhen especially since it should probably be needed for the GUI, right?

**Comment by Makman2** [comment]
I was working on a prototype for interruptable threads/multiprocessing-processes here:
https://gist.github.com/Makman2/88ac3f8ce5bfcc5237a5
It's not ready yet, but the direction is right I think^^

**Comment by Makman2** [comment]
It seems to work quite well in the moment, https://github.com/coala-analyzer/coala/issues/933 will even improve the behaviour when using `multiprocessing.Pool`.
