### ISSUE TITLE
Move constants out of class

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#917]

**Comment by AbdealiJK** [comment]
Could you elaborate ? which classes have you seen with constants that can be moved out ?
Should they be in Constants.py or just outside the class ?
Or will they be members in the class with capitals ?

**Comment by sils1297** [comment]
Currently we have the `Constants` class which holds the constants as static members, I think that's pretty useless. We can simply declare the constants at module level, in `Constants.py` directly.

**Comment by kaushikmit** [comment]
I would like to take care of this bug. Can you assign this to me ?
