### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#918]
`sudo ./setup.py install` -> `coala-format` Works

`sudo pip install . --upgrade` -> `coala-format` Import error

**Comment by sils1297** [comment]
could someone try to reproduce?

**Comment by AbdealiJK** [comment]
Both work for me - maybe you had some weird code in your branch ?

**Comment by Makman2** [comment]
confirmed :+1:

**Comment by sils1297** [comment]
I just reproduced it on fedora, there's something weird going on!

**Comment by AbdealiJK** [comment]
Just covering all bases here.
 - This ImportError was saying that a coala module was not found ?
 - The `pip` mentioned above was for python v3 right ? (i.e. you didnt make a mistake on pip and pip3)

**Comment by sils1297** [comment]
unable to reproduce. Thanks for pinging.
