### ISSUE TITLE
Documentation comments

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#919]
Our current doc comments are not very nicely formatted.
If you need to add a new parameter, the formatting of all the other params may need to change.
Also, if you have a large name, the doc string will spill into many many lines of code for all parameters.

Also, the combination of the left indent condition of the param and the 80 char limit together mean lots of unnecessary time wasted on formatting

It'd be better to think of something better for this.

**Comment by sils1297** [comment]
Agreed. We *could* try to make a bear that automatically formats the stuff
so you just write it and run it over it to get the same nice look... or
remove the indentation. Not sure. Latter is easier for sure.

2015-08-11 11:12 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by Makman2** [comment]
Agreeing too.

**Comment by Makman2** [comment]
Maybe this pattern?
```
My main description.

Sub descriptions.

:param x:
    4 spaces after docs.
:param x2:
    another text. for test like it would like with more than one line: 
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
    tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero
    eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
    takimata sanctus est Lorem ipsum dolor sit amet.
:raises OMG.SUPERLONG.Exceptions.EXTREME_Exception:
    Now this is not ugly any more.
:return:
    Haha no return!
```

**Comment by sils1297** [comment]
@Makman2 I like that pattern. Can you make a bear for that? Though keep in mind that we'll want to add more patterns to this bear over time, try keeping it generic. Assigning you.

**Comment by Makman2** [comment]
@sils1297 What do you think about a simple bear the user provides regexes for? This would be the easiest^^

**Comment by sils1297** [comment]
@Makman2 could you make a concrete example?

**Comment by Makman2** [comment]
```python
class DocumentationFormatBear:
    def __init__(self):
        self.regex = ""
        self.flags = 0 # Passed to the re module regex processor.


# Usage:
bear = DocumentationFormatBear
# For example to force a detailed doc:
bear.flags = 0
bear.regex = ".+\n\n.+"

```

**Comment by sils1297** [comment]
@Makman2 how's it going? Are we getting this within a week or so? Otherwise I'd reschedule it for the next release I guess.

**Comment by Makman2** [comment]
@sils1297 it's difficult like before, progressing a bit slowly. Would be best to move this issue to the next release^^

**Comment by sils1297** [comment]
closing in favour of https://github.com/coala-analyzer/coala/issues/1140
