### ISSUE TITLE
Case insensitive bear names in config files

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#923]
It would be better to allow case insensitive bear names in config files.

We'd need to throw an error if there are 2 bears with names like `ABC` and `Abc` - because this would cause a confusion to the codebase.

**Comment by sils1297** [comment]
@fneu could you look into that? That's really important for usability.

**Comment by fneu** [comment]
@sils1297 I summon you and your opinion on this. @AbdealiJK also.

Personally I'm actually rather convinced of our current approach, supporting case sensitivity where the file system does it. This way we support all kinds and combinations of names a user might come up with.

And it is more in line with virtually all common linux command line tools. 

Something like (auto)correct might be a better approach if we want to ease the typing of bear names. 

Also I'm not sure how this might interact with future reworked bears. Citing #933:

> Make bear class a decorator or even an undecorated function.
> I think we really want bears to be specified like module.bear 
> e.g. spacing.check_space_consistency or so.

There we would have the problem again with the case of functions. Matching them case insensitive strikes me as even more odd.

SO, what do you guys think?

**Comment by sils1297** [comment]
Basically I agree, the most important thing is that the user get's some feedback if there's no bear found and *ideally* a proposal for something he might use with like minor differences or so

**Comment by Makman2** [comment]
@fneu The auto-correction is definitely the better approach like you said. And in conjunction with bear name proposals the user shouldn't have a problem any more^^

**Comment by fneu** [comment]
Closing this then

**Comment by meetmangukiya** [comment]
No new issue for autocorrection? I was about to create an issue for this feature. Can we re-open this? 

/cc @Makman2

**Comment by Makman2** [comment]
I think we agreed on not supporting case insensitive bear names. Autocorrection would be a different issue (which we forgot to file actually...) @meetmangukiya
