### ISSUE TITLE
Suggest bears based on existing bear names

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#924]
Take the bear name given if its not found - and tries to find the closest match to it based on word distance

**Comment by sils1297** [comment]
related : https://github.com/coala-analyzer/coala/issues/934

**Comment by sils1297** [comment]
Accepting patches for this one, however it's a rather big feature and we need to focus right now, so wontfix. FWIW I'd love to see this but there's just some really way more important stuff out there.
