### ISSUE TITLE
SpaceConsistencyBear: logic cleanup

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#930]
I think logic can be cleaned up a bit, effectively what this bear does is chaining replacements and checking functions. Should be possible to generalize that^^

**Comment by sils1297** [comment]
Not milestone relevant. If you disagree, ping me on gitter for discussion.

**Comment by sils1297** [comment]
@Makman2 you still on this? SpaceConsistencyBear works pretty well currently, if you don't want to do this soonish I'd rather close this as wontfix as it doesn't affect *anything*.

**Comment by sils1297** [comment]
reopen if you're working on this
