### ISSUE TITLE
Invoking coala externally from python should be simpler

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#936]
For example the gedit plugin needs to invoke `gather_configuration` and other functions to invoke coala. Imo I just want to do:
```python
coala(args)
```
or
```python
coala(section)
```
and just get a list of results.

**Comment by sils1297** [comment]
Indeed, this'll also solve the duplication we have in our "binaries". It
should be a function that takes only optional arguments and gets args from
CLI if none are given. If more sophisticated behaviour is needed, we'll
want to have keyword arguments, e.g. for asynchronous result processing for
the GUI or so.

Important issue. Can you please set milestone to 0.3?

2015-08-19 20:03 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Yeah or easy helper method we summarize in a single module and document them well.
