### ISSUE TITLE
ClangPrintASTBear jumbles up output when run on multiple files.

### ISSUE THREAD

**Issue by Udayan12167** [coala-analyzer/coala#944]
I think running that bear in parallel on many files causes the problem.

**Comment by sils1297** [comment]
Fix is easy but probably cumbersome: it needs to be transformed into a local bear (easy and fast) and the tests need to be adjusted accordingly (easy but may take some time).

**Comment by NalinG** [comment]
Hi, I would like to work on it.
Can hyou please give me some starting pointers.

**Comment by sils1297** [comment]
@NalinG  Hey I've assigned you to another bug (simply because I saw that comment first), talk to me on gitter if you want another or if we totally confused you ;)

**Comment by Makman2** [comment]
Hi  @NalinG ;)
If you want to get started, please read https://github.com/coala-analyzer/coala/wiki/Getting-Started-to-Contribute .
There's some useful Information how things work here^^

You should join our gitter channel where you can ask questions and where we organize such stuff.

To work on this issue you need to get an invitation to our org so we can assign you this issue. @sils1297 will send you one.

**Comment by AbdealiJK** [comment]
@sils1297 It already seems to be a local bear

**Comment by sils1297** [comment]
I meant global bear. Sorry :/
