### ISSUE TITLE
No mention of how to get the debug stream from coala in the documentation.

### ISSUE THREAD

**Issue by Udayan12167** [coala-analyzer/coala#945]

**Comment by Makman2** [comment]
I think we already mention it now inside README and docs.

> You can get the latest prerelease version directly from our master branch:
>
> `pip install coala --pre`

**Comment by sils1297** [comment]
This is about -L DEBUG

**Comment by sils1297** [comment]
This is about -L DEBUG

**Comment by Makman2** [comment]
oh sorry

**Comment by sils1297** [comment]
actually we have this doc covered in the writing bears tutorial because that's where it matters, right? Plus there's the help.
