### ISSUE TITLE
Add serial number in coala-format

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#950]
There should be a provision to print the serial number (to number the output) in coala-format

**Comment by sils1297** [comment]
@AbdealiJK sorry but what's the usecase? Don't see it yet...

**Comment by AbdealiJK** [comment]
It's good to have serial numbers :P
Helps in referring to specific warnings when multiple people look at the output
Makes it look more organized and nice outputs like
```
 1 | 20:3 | WARN | Message 1
 2 | 34:7 | ERR  | Message 2
```
can be got easily.

I thought it'd be a nice feature if someone wants to show all warnings easily at a glance. Not at all high priority

**Comment by sils1297** [comment]
Closing as wontfix, accepting patches because of lack of priority, we need to focus a bit.
