### ISSUE TITLE
ShowPatchAction: Pull out show_diff function

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#967]
This function isn't tied to that action and should exist outside of it and be applicable to any Diff object or unified diff or two files or something like that.

**Comment by sils1297** [comment]
Ok that means there's a function `show_diff` which shows the diff which is used by the ShowPatchAction - not that there's no such action anymore :) I think this is well defined and doable for a newcomer.

**Comment by AbdealiJK** [comment]
Closing this as I cannot find the show_diff functions anymore =>`git grep show_diff` gave me nothing
I found a `print_beautified_diff` which seems to be a revamped version of it.

Reopen if I am mistaken about this.
