### ISSUE TITLE
more compact view for diffs

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#969]
```
|OLD|   | filename
|   |NEW| filename
```

or

```
|---|   | filename
|   |+++| filename
```

**Comment by fneu** [comment]
I find myself in favor of the second version. In the first one, the capital letters attract too much attention, away from the filename. Or the diff itself.

**Comment by sils1297** [comment]
yeah, the second is charming. @fneu assigning you, this *really* is a five minute job :)

**Comment by Makman2** [comment]
where shall the code be placed? can't find the class that is responsible for outputting this :O

**Comment by sils1297** [comment]
ShowPatchAction
