### ISSUE TITLE
Use built-in function `vars(object)` instead of using `__dict__` directly

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#971]
Imo this is cleaner^^

**Comment by cw1** [comment]
According to this http://pythondoeswhat.blogspot.de/2012/01/dict-and-vars.html, the use of `vars(object)` is much slower than `__dict__`. Shall we ignore this performance penalty?

**Comment by sils1297** [comment]
@cw1 thanks for digging that up, that'll convince @Makman2 for sure to leave this as it is and maybe even go towards using `.__len__()` instead of `len()`

**Comment by Makman2** [comment]
To be honest I dont believe that. Ill test that soon locally with a venchmark^^

**Comment by sils1297** [comment]
@Makman2 why? It makes totally sense. vars will first have a few
conditions, then access dict, while accessing it directly will avoid all
that unneeded checking.

2015-10-27 14:26 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
My benchmark:
```
With vars():
2.172344666005436
Directly via __dict__:
1.4370877611060155
With len():
4.380952825268093
Directly via __len__:
3.092824838883348
```
so about 50% slower.
I added another case where I just check for method delegation, and this is the bottleneck (method delegation is 100% slower), not the if-conditions or else inside `vars()` or `len()`.

**Comment by sils1297** [comment]
so what do we want to do?

2015-10-27 16:19 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
I'm in favor of using built-in methods still, since they are built-in and so have a meaning to be and we use the standard interface from python.
Also `vars` is not critically used in our code, just here and there, so it wouldn't have a performance impact.

**Comment by cw1** [comment]
The usage of `vars` instead of `__dict__` and `len()` instead of `.__len__()` is more consistently i think. So may we should integrate it to our code guidelines, if we ignore the performance impact.

**Comment by sils1297** [comment]
why not use the faster version everywhere consistently? It has the same meaning.

**Comment by Makman2** [comment]
since there're default functions for, also it makes code for newcomers more hard to read^^

**Comment by sils1297** [comment]
You think so? __len__ is pretty obvious IMO...

2016-01-08 18:15 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
since it's not that obvious to find in documentation I don't like using `__len__`^^

**Comment by fneu** [comment]
+1 for builtins from me. I guess I will just take care of this and then we can talk about this in the PR

**Comment by Makman2** [comment]
@fneu :+1:

**Comment by sils1297** [comment]
done
