### ISSUE TITLE
Get rid of to_string_dict methods

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#982]
They essentially do a very similar thing to our json export which works out of the box, could we use DBus based on that? Would be cleaner IMO.

@AbdealiJK could you do that maybe? You're the most into it and this shouldn't take that long. (Okay whenever I write that sentence that doesn't work out...) Still, want to give it a try?

**Comment by sils1297** [comment]
This is important for the ongoing result refactoring.

**Comment by sudheesh001** [comment]
@sils1297 What is the exact requirement here ? How should DBus be used ? There are log messages
`self.uut.to_string_dict()`, How should they be replaced once the `to_string_dict` method is removed ?

**Comment by sils1297** [comment]
So basically we have this JSON conversion routines (JSONEncoder or so) somewhere which take any object and make a neat JSON object out of it without you having to specify what goes in because it just takes public members and properties. Maybe we could do something similar for the DBus stuff since this `to_string_dict` has to be implemented multiple times for all objects while the encoder works for everything.

**Comment by AbdealiJK** [comment]
I don't see how this will be possible .
Source ranges will be encoded to arrays and diffs will be jsons. Even if we use the jsonencoder wev would have to put if conditions to filter out and change these .
It seems simpler and more logical as it is now to me

**Comment by sils1297** [comment]
ok it hasn't disturbed me for a while so we can close this indeed I guess.
