### ISSUE TITLE
@generate_eq for easy `__eq__` creation

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#995]
Since implemnting `__eq__` is everytime the same stupid task, this should be hand over to a decorator.
Especially writing tests is boilerplate and often you miss details like inheritance, passing `None` etc.

I think it can work basically like `@generate_repr` which takes members or works in "auto" mode.

So this issue involves:
- Implementing `@generate_eq` (or chose another name) that generates `__eq__` and works basically like `@generate_repr`
- Use it everywhere where appropriate
- Delete equality tests for those classes where `@generate_eq` will be used.

**Comment by Makman2** [comment]
Maybe it's then also worth to implement `__ne__`, maybe we find a more performant solution than letting python automatically invoke `not __eq__()`

**Comment by sils1297** [comment]
merged
